### ISSUE TITLE
Vastly different lighthouse performance score in pagespeed insight and webpagetest

### ISSUE THREAD

**Issue by sauravvarma** [GoogleChrome/lighthouse#10007]
Steps to reproduce:
1. Run LH on https://www.1mg.com/otc/accu-chek-active-test-strip-otc139543

#### What is the current behavior?

The current performance score seems to be very different from what WebPageTest gives us upon running a lighthouse audit (within devtools or page speed insights)

WebPageTest: https://ibb.co/xf211bJ (https://www.webpagetest.org/result/191119_TG_57eeedf96b58e4db4c2089e747f06f8d/)
Lighthouse: https://ibb.co/94Kwgsr

#### What is the expected behavior?

Both the lighthouse scores to be identical (one presented via webpagetest and the other from devtools/pagespeed insight)

#### Environment Information
* Affected Channels: DevTools, PageSpeed Insight
* Lighthouse version: 5.2.0
* Chrome version: 78.0.3904.87
* Node.js version: 10.15.3
* Operating System: MacOS 10.15.1

I have the JSON and CSV from both as well the trace in case that would help debugging it.

Thank you!

**Comment by exterkamp** [comment]
> Both the lighthouse scores to be identical (one presented via webpagetest and the other from devtools/pagespeed insight)

Unfortunately at this time this is an unrealistic expectation, since they are totally different runtime environments, we cannot make them perform the same and get the same exact scores. There are some great [docs on cross-environmental inconsistency and variance](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) that go into more detail, but the TL;DR is that since Lighthouse is measuring real performance the runtime environment matters and therefore different runtime environments can affect performance scores.

This site actually performs similarly in PSI and DevTools:
![image](https://user-images.githubusercontent.com/6392995/69451247-be82bc00-0d13-11ea-83d9-479a0c707a7d.png)
WPT w/3G (Moto4 @ Dulles) scored a little worse:
![image](https://user-images.githubusercontent.com/6392995/69452137-dc512080-0d15-11ea-8720-86ab3a1b4a78.png)

**Comment by sauravvarma** [comment]
> Edit: I also thought that maybe locality was an issue, I ran this site a few times in APAC and EMEA, got 70 and 68 score respectively. So I am moderately confident that isn't an issue either.

That's what I thought when you first posted the screenshots. However, this brings up a concern where WebPageTest (upon selecting Mumbai and emulating Nexus 5 on 3G Fast which is automatically set when selecting the 'Capture Lighthouse Report' option) shows a very different result. The network waterfall makes it seem like the webpage is performing well (if you could take a look at the link of the result I shared in the original post).

I came here since Mariko Kosaka and Jake Archibald suggested there might be issues with how Lighthouse is analysing the webpage and said I should file an issue here. It would be of great help if you could explain why that might be the case or look into it?

Thank you for your time @exterkamp !

**Comment by paulirish** [comment]
Hey Saurav.. its true that LH under LH is different than LH under PSI.  
They are different runtime environments so we can't guarantee similar results.  The doc Shane linked has more details on that.

Thanks for getting in touch
