### ISSUE TITLE
Warn about late, or missing, <meta charset>

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChrome/lighthouse#10023]
If present, `<meta charset=...>` must occur within the first 1024 bytes of the HTML document per the HTML Standard: https://html.spec.whatwg.org/multipage/semantics.html#charset

Ideally, `<meta charset>` is the very first element within the `<head>`. This has been a best practice for a long time, e.g. recommended by HTML5 Boilerplate: https://github.com/h5bp/html5-boilerplate/blob/master/dist/doc/html.md#the-order-of-the-title-and-meta-tags

To guide developers towards adopting this best practice, Lighthouse could show a warning when `<meta charset>` is not the first element within `<head>` (`document.head.firstElementChild`).

Relevant links:

- Twitter thread: https://twitter.com/hsivonen/status/1198618391042560000
- Chromium DevTools issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1028041

**Comment by connorjclark** [comment]
I saw this too! Thanks for opening.

There is also the BOM byte marker and the HTTP headers to consider - if either are set appropriately than the meta element is not needed.

Because of the 3 ways this can occur, I would prefer a signal via the CDP over us determining ourselves.

**Comment by mathiasbynens** [comment]
> There is also the BOM byte marker and the HTTP headers to consider - if either are set appropriately than the meta element is not needed.

I'd still argue that even with those three options, the `<meta charset=utf-8>` is the best practice. It's the most explicit and self-contained way of declaring the charset at the document level. Relying _only_ on a BOM character is brittle since a teammate opening and saving the file with different editor settings might remove the BOM, and relying _only_ on the server-side header gets problematic when the file is saved to disk or rehosted elsewhere without also copying the server config.

**Comment by connorjclark** [comment]
Would like to see experimental evidence that this is actually a performance improvement.

**Comment by mathiasbynens** [comment]
@connorjclark The links in OP provide some more context. Here's something I wrote elsewhere:

> The HTML document can include `<meta charset="utf-8">`. This is the most explicit and self-contained approach. However, there's still a gotcha: for optimal cross-browser performance, the `<meta>` must occur within the document's first 1024 bytes. In Chrome, not following this advice can result in [delayed subresource loads](https://twitter.com/hsivonen/status/1198884600728236033). In Firefox, not following this advice can result in the page being parsed using a legacy encoding, then [reloaded (!) and re-parsed](https://twitter.com/hsivonen/status/1198884600728236033) once the `<meta>` is found.

What kind of experimental evidence are you looking for exactly? cc @zcorpan

**Comment by connorjclark** [comment]
I meant I'd like to see data of how this optimization affects metrics. The main concern is that we don't want to suggest low-wattage changes, and I'd like to be able to point towards something that says "this can increase first paint by x ms in these conditions". Maybe I missed something like that in the links provided (on mobile, cant check right now).

Also, if we want this to be in the performance category as an opportunity, we need to understand the performance implications in order to simulate / come up with an estimated savings. Otherwise it'd have to be a diagnostic (no estimation given).

**Comment by mathiasbynens** [comment]
@hsivonen, any insights as to how we could get metrics on the cost of Firefox's reloading and re-parsing in the late `<meta charset>` case?

Test pages:

- [late `<meta charset>`](https://mathiasbynens.be/demo/late-meta-charset)
- [missing `<meta charset>`](https://mathiasbynens.be/demo/missing-meta-charset)

**Comment by hsivonen** [comment]
Above the HTTP layer, it is as though the user pressed the reload button mid-way of the page. All work done until then is lost: The parser stops, the DOM and layout are torn down and things start over. I don't know if or how the interaction with the HTTP cache differs from the case of the user pressing the reload button.

Starting over is so self-evidently a performance problem that I haven't measured how bad it is exactly. 

A realistic case to measure would be taking a product page for a [Lego set](https://www.lego.com/en-fi/product/bookshop-10270) on lego.com and measuring loading it in Firefox via a proxy as-is (as of today triggering a realistic late-`<meta charset>` reload) and then having the proxy add `charset=utf-8` to the `Content-Type` header of the root resource (easier than making the proxy actually move the `<meta charset>`) and measuring again (without the reload).

For completeness, Firefox (as of 73) has three kinds of character encoding-related reloads that are implicitly triggered on non-`file:` URLs by non-conforming content (as opposed to user action):

1. There is no HTTP-layer `charset`, there is no BOM, but there is a `<meta charset>` beyond the first 1024 bytes. The reload triggers once the HTML5 tree builder algorithm that processed the `<meta charset> on the parser thread.
2. We're on a .jp domain, there is no HTTP-layer `charset`, there is no BOM, and there either isn't a `<meta charset>` or before one there is either an ISO-2022-JP escape sequence or a pair of bytes that is invalid in Shift_JIS or decodes as half-width katakana in Shift_JIS and there hasn't been prior bytes that would be invalid as EUC-JP or that would decode to half-width katakana in EUC-JP. The reload is triggered when the deciding byte is processed by the parser thread prior to tokenization.
3. We're on any TLD other than .jp, .in, or .lk, there's no HTTP-layer `charset`, there is no BOM, there is no `<meta charset>` and at EOF the encoding guess made by looking at the TLD and the whole byte stream differs from the encoding guess made by looking at the TLD and the first 1024 bytes. The reload is triggered when the parser thread encounters the EOF from network. (Note that if UTF--8 is detected, the TLD-affiliated encoding is used instead for intentional misdecoding for the same reason why Chrome doesn't detect UTF-8: To avoid Web authors starting to depend on this stuff. Hence, https://mathiasbynens.be/demo/missing-meta-charset decodes as windows-1252, since .be is a windows-1252-affiliated TLD.)

Which is to say that pages really should be specifying their encoding and do so within the first 1024 bytes.

**Comment by hsivonen** [comment]
> There is also the BOM byte marker and the HTTP headers to consider - if either are set appropriately than the meta element is not needed.

Indeed. To avoid training Web developers to ignore warnings by showing ones that aren't strictly necessary, I wouldn't emit a warning about the lack of `<meta charset>` if HTTP-level `charset` or a BOM is present.

**Comment by connorjclark** [comment]
Thanks for sharing your expertise here @hsivonen.

Realizing that simulating how the parser behaves here is something our simulation doesn't support, so we must consider this as a performance diagnostic (or a best-practices audit).

@Beytoven

Useful artifacts for this will be `MainDocumentContent` and `MetaElements`. It's important for the audit to fail only if the meta element is after the first 1024 bytes _and_ there isn't an appropriate HTTP header / BOM.

Would be nice to get some numbers (on a complex page like the Lego one above). I believe the affect will only occur when real throttling is used (`--throttling-method=devtools`)

**Comment by paulirish** [comment]
My expectation is we'll put this in the best-practice category.

Also it's worth calling out webhint's similar audit: [docs](https://webhint.io/docs/user-guide/hints/hint-meta-charset-utf-8/) and [source](https://github.com/webhintio/hint/blob/master/packages/hint-meta-charset-utf-8/src/hint.ts).

**Comment by zcorpan** [comment]
Reparsing at EOF (case 3 in @hsivonen's list) could be a huge perf cost even on a fast network (especially for larger documents where it takes several seconds to reach EOF), but of course more so on a slow network. I think cases 1 and 2 are also non-trivial but measuring would give a clearer picture.

**Comment by hsivonen** [comment]
> My expectation is we'll put this in the best-practice category. I think the perf benefits aren't a huge deal, but it's an important practice nonetheless.

This seems an odd categorization considering that 1) both a late meta and the lack of encoding declaration altogether are unambiguously errors per spec and 2) these errors have performance effects, i.e. they are more serious than some authoring conformance errors related to element nesting and such.
