### ISSUE TITLE
Tiny HTML code makes lighthouse crash

### ISSUE THREAD

**Issue by bb560** [GoogleChrome/lighthouse#10032]
My code to test here: https://www.billi-bolli.de/test.php

tested on https://web.dev/measure/ causes:

> Error: Error: Lighthouse returned error: generic::internal: APP::1: Abnormal renderer termination, status = crashed exit_code = 1

Why is that? It seems to be the combination of some parts (I could not figure out which exactly) that seem to cause the crash. If I delete e.g. EITHER the text between `<a></a>` or the text before it, the crash does not happen.

**Comment by connorjclark** [comment]
this is fascinating

**Comment by connorjclark** [comment]
minimal repro:

```
u<a>&shy;üuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu“</a>
```

**Comment by connorjclark** [comment]
issue was fixed in this chromium cl: https://chromium.googlesource.com/chromium/src/+log/8765e7e3095a9d9456359058a49d21c86659396b..e8d2bfd50a6db2296e068c8cb958367aa4c460b9?pretty=full (`&shy;` soft hyphens are considered [generated text](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/layout/ng/inline/ng_inline_layout_algorithm.cc?l=430&rcl=079c6c8155bfec9247ad334399a24ae4e1637d16), and I guess some code here causes the renderer process to crash when it receives trash bytes)

LR is using a slightly older chromium. we will update soon to fix this.

**Comment by connorjclark** [comment]
@bb560 For now, just set an encoding.

```
<meta charset="utf-8"/>
```

**Comment by ChaosCoder** [comment]
We got the same crash on https://ticeapp.com but we already set `<meta charset="utf-8">`. Do you know any other workaround or is any update on the fix available?

**Comment by exterkamp** [comment]
@ChaosCoder Entirely my fault 😓

>  we will update soon to fix this.

I made Connor a liar. LR is still running an older Chromium. We will update this soon.

**Comment by exterkamp** [comment]
Should be g2g. lmk if you still have problems!
