### ISSUE TITLE
Inconsistency in PSI Scoring and Lighthouse Scoring

### ISSUE THREAD

**Issue by murali-krishnamoorthy** [GoogleChrome/lighthouse#10068]
Hi i have been running test on PSI . When i take the 5 key metics ( FCP , FMP , First CPU Idle , TTI and Speed index  )  and plug it into lighthouse version 5 , i see a very different score. . 

Also when i run the same test in webpagetest ( using 3G connection ) , i get a different score , but the score on WPT seems to align with lighthouse and timing also seems to align with how the site will work for the 3G connection. 

So wanted to understand the variance. Based on the PSI Docs i am assuming they are running of WPT equivalent of 3G Fast ( https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md )

Steps to reproduce.
1. URL : https://www.thermofisher.com/us/en/home.html
<img width="1649" alt="Screen Shot 2019-12-04 at 12 43 45 PM" src="https://user-images.githubusercontent.com/56832545/70167119-0c90ab80-1694-11ea-8689-b3fb9af1c773.png">

2. Corresponding value substituted in lighthouse v5
<img width="1004" alt="Screen Shot 2019-12-04 at 12 48 10 PM" src="https://user-images.githubusercontent.com/56832545/70167284-63968080-1694-11ea-9cac-5b6bb661de75.png">

3. webpagetest 
<img width="1540" alt="Screen Shot 2019-12-04 at 12 49 12 PM" src="https://user-images.githubusercontent.com/56832545/70167354-89bc2080-1694-11ea-9e52-ae27b5fdaf07.png">
https://www.webpagetest.org/lighthouse.php?test=191204_8T_b385975c8368133693593d48fb542b9b&run=1

**Comment by ChromeCAB** [comment]
Typically when we see this cross-environment inconsistency, it is because of runtime environment. PageSpeed Insights is running on Google servers, whereas Lighthouse will be running locally (if you're running it through DevTools). Because of the differences in runtime conditions, even though the core logic is the same you can see different scores.

@patrickhulce to help provide additional context if he thinks the variance is attributed to something else. :)

**Comment by patrickhulce** [comment]
@murali-krishnamoorthy you've screenshoted the "Desktop" values in PSI which does not use Fast 3G. When I run a mobile audit in PSI I get very similar numbers to the WPT ones you've posted (subject to typical environmental [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md))

**Comment by murali-krishnamoorthy** [comment]
Hi @patrickhulce  would you be able to provide us the connection speed for the desktop version , i am not able to find it anywhere.

**Comment by murali-krishnamoorthy** [comment]
Also @patrickhulce  - if it take the metric values from PSI (screenshot 1 ) and plug those numbers in lighthouse v5 ( as per my screenshot 2 ) .  the numbers dont match . Should they have not resulted in the same score . in this case lighthouse shows 95 and PSI Show 71

**Comment by patrickhulce** [comment]
Yes the desktop scoring curve and connection speeds are different because, understandably, the user experience and expectations are very different on desktop vs. mobile. Both are set in the lr-desktop-config

https://github.com/GoogleChrome/lighthouse/blob/d13d092e0076e0fb130c9ebf82ae42cf5998db44/lighthouse-core/config/lr-desktop-config.js#L9-L25

**Comment by murali-krishnamoorthy** [comment]
@patrickhulce  Thanks

**Comment by murali-krishnamoorthy** [comment]
thanks closing this issue
