### ISSUE TITLE
Input have name & associated label still showing accessibility Issue 

### ISSUE THREAD

**Issue by chetanbane** [GoogleChrome/lighthouse#10087]
Please check below URL for Ref:
http://124.30.44.228:8201/express-painting/getintouch-july2019?utm_source=google-SEM

**Comment by mikolaj6r** [comment]
Also having same issue, see SS.
![lighthouse_audit](https://user-images.githubusercontent.com/35143306/70522583-ab5c5280-1b41-11ea-8d41-2d42ae497b9e.PNG)
![lighthouse_dom](https://user-images.githubusercontent.com/35143306/70522585-abf4e900-1b41-11ea-91fb-c9abdf773c18.PNG)

**Comment by mikolaj6r** [comment]
I belive, the issue is because Your label doesn't mean anything in Accessibility subject. As MDN describes `The HTML <label> element represents a caption for an item in a user interface.` [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label). However, yours `label` is empty - I mean text, not contained input. As so you could either apply some text to describe your input or add `aria-label` attribute to inputs.

**Comment by jazyan** [comment]
Thanks @mikolaj6r!
