### ISSUE TITLE
Unable to find console-time

### ISSUE THREAD

**Issue by sravanthi97** [GoogleChrome/lighthouse#10104]
**Summary**

We are able to see console-time information in the documentation but were unable to get related information in lighthouse results.

**Comment by patrickhulce** [comment]
That's because Lighthouse doesn't report timings from `console.time`. If you'd like your times to be captured by other tooling, we'd recommend using the [User Timing API](https://www.html5rocks.com/en/tutorials/webperformance/usertiming/) which is specifically designed for this purpose. Then you'll get those times in the `user-timings` audit in Lighthouse.

If there's somewhere in the documentation where we say otherwise, please let us know so we can fix it!

**Comment by sravanthi97** [comment]
oversized-images, cache-contains-start_url, date-now, mutation-events, old-flexbox, manifest-short_name-is-not-truncated this are the elements we are unable to get the related information.

**Comment by patrickhulce** [comment]
Those are all audits that have been renamed or removed in the latest Lighthouse version. The documentation is still there to preserve links from old audits but should not be linked to or referenced from a latest report.

**Comment by ashwin31** [comment]
@patrickhulce where do we see there renaming or removed audits? or can you point us to the latest documents reflecting these changes?

**Comment by connorjclark** [comment]
Check out release notes for major releases to see such breaking changes. https://github.com/GoogleChrome/lighthouse/releases
