### ISSUE TITLE
Has lighthouse been upgraded?

### ISSUE THREAD

**Issue by omo-y** [GoogleChrome/lighthouse#10126]
I checked the lighthouse icon of the crom extension suddenly changed to a red lighthouse, but there is no information about version upgrades. ([Announcing Lighthouse 3.0](https://developers.google.com/web/updates/2018/05/lighthouse3) is the latest?)
Unlike previous lighthouse, sometimes hungup and results are not displayed.
Has lighthouse been updated recently? Is there a similar problem with the lighthouse trouble information?
(The image on the left is the icon until now. The icon has changed suddenly. The menu on the left is the menu when the icon that has been changed suddenly is clicked.)
![lighthouse](https://user-images.githubusercontent.com/46962034/71081827-54a2e880-21d3-11ea-92fd-437d3f073432.png)
![lighthouse1](https://user-images.githubusercontent.com/46962034/71081839-58366f80-21d3-11ea-8756-8c016c148720.png)
![lighthouse3](https://user-images.githubusercontent.com/46962034/71081848-5b316000-21d3-11ea-83c6-51cbe0e87978.png)

**Comment by rockeynebhwani** [comment]
Lighthouse latest version is 5.6.0. You can see here - https://github.com/GoogleChrome/lighthouse/releases

It was released on 17th Oct

**Comment by exterkamp** [comment]
Yes the Chrome extension has been updated. The new extension relies on the PSI API to run Lighthouse, its [docs have been updated](https://developers.google.com/web/tools/lighthouse/#extension) as well as the UI itself to indicate this. 

The new extension will not work on private or auth'd pages. To audit those we recommend using Lighthouse with [Chrome DevTools](https://developers.google.com/web/tools/lighthouse/#devtools).

If your page does not run in Chrome DevTools, or it _does_ run in PSI and _not_ the extension, then this might be a problem, otherwise this change is expected with the new version of the extension. 

Hope that clears this up 😄

**Comment by omo-y** [comment]
Thank you for your quick reply
