### ISSUE TITLE
Unable to view the generated html inside Jenkins

### ISSUE THREAD

**Issue by vinodhinisekar** [GoogleChrome/lighthouse#10139]
The report is generated but couldn’t able to view the report from Jenkins. Getting this message "Lighthouse report requires JavaScript. Please enable."

**Comment by patrickhulce** [comment]
Have you tried enabling JavaScript? Lighthouse report requires JavaScript ;)

If you're trying to embed the HTML of the report inside another view that doesn't allow JavaScript, you might be better off linking to the report as a standalone file instead.

**Comment by stayshungry83** [comment]
Seriously,,,, I don't know why you duudes even email me...

**Comment by cybersonic** [comment]
Not sure why this is closed, looks like an issue with the HTML, I am running into this too and yes, JavaScript is enabled. 
The error in the console says:

`Blocked script execution in '<URL>' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.`

This happens in Jenkins. I am still looking for a solution and will post if I find it.

**Comment by cybersonic** [comment]
It looks like we have to reduce the security settings in Jenkins, see https://www.jenkins.io/doc/book/security/configuring-content-security-policy/
