### ISSUE TITLE
FCP differs in Lighthouse from Browser Performance API 

### ISSUE THREAD

**Issue by voronianski** [GoogleChrome/lighthouse#10211]
**Summary**

I'm trying to understand why values for First Contentful Paint (FCP) in Browser Performance API (https://developer.mozilla.org/en-US/docs/Web/API/PerformancePaintTiming) differ from Google Lighthouse.

For example, I've built a simple demo server that has query param to control speed of response.

When I make request to this server with 5s delay like https://test-metrics-swujgrqwro.now.sh/index/?delay=5000, after page is loaded I can see the value of FCP in browser console :

![image](https://user-images.githubusercontent.com/974035/72156094-f1147100-33b4-11ea-8fad-901211daa762.png)

And here I can see that 5s delay was included in `first-contentful-paint` metric.

However Lighthouse audit shows only 1.9s for First Contentful Paint...
![image](https://user-images.githubusercontent.com/974035/72155870-5f0c6880-33b4-11ea-9c22-2f4121ca085b.png)

**Am I missing something or FCP in Google Lighthouse is calculated differently?**

Here's the demo app that I used to test the behavior -
- with delay 5000ms e.g. `https://test-metrics-swujgrqwro.now.sh/index/?delay=5000`
- source code - `https://zeit.co/voronianski/test-metrics/swujgrqwro/source`
- all tests were done in Chrome Version `79.0.3945.79 (Official Build) (64-bit)`, incognito mode, cache cleared and macOS Version `10.14.4 (18E226)`

### Update
The most confusing is actually if I go to trace view of Lighthouse Audit, FCP will be the same as in Browser Performance API
![image](https://user-images.githubusercontent.com/974035/72157070-4f425380-33b7-11ea-9b40-c8415f6d728a.png)

**So why report is showing the different value? Is it a value without network requests time?**

**Comment by voronianski** [comment]
the most confusing is actually if I go to trace view of Lighthouse Audit FCP will be the same as in Browser Performance API
![image](https://user-images.githubusercontent.com/974035/72157070-4f425380-33b7-11ea-9b40-c8415f6d728a.png)

So why report is showing the different value? Is it a value without network requests time?

**Comment by patrickhulce** [comment]
This is due to the use of simulated throttling, if you use `--throttling-method=provided` or `--throttling-method=devtools` the trace and metric will align with the observed values.

Simulated throttling's goals are to:

1. Provide estimates for alternate network and CPU conditions that differ from the host device
2. Mitigate variance

Variable server response times are one of the largest contributing factors to FCP variance, so when simulated throttling sees abnormally long server response times, it throws them away as outliers. You can control this behavior explicitly by providing `--precomputed-lantern-data` with a map of origin to desired server response time.

If you don't need either of those goals than feel free to use more advanced throttling techniques described [in our docs](https://github.com/GoogleChrome/lighthouse/blob/9931d2438fe0d0c4cbb477bf9cec2dd52a3bad61/docs/throttling.md).

**Comment by voronianski** [comment]
@patrickhulce thanks for explanation! Do you if the way to change this Lighthouse flags in Chrome devtools is via throttling settings?
![image](https://user-images.githubusercontent.com/974035/72171315-05676680-33d3-11ea-9078-87a6df4adb39.png)

**Comment by patrickhulce** [comment]
Simulated === 'simulate'
Applied === 'devtools'
No throttling === 'provided'
