### ISSUE TITLE
Lighthouse occured error from specific page

### ISSUE THREAD

**Issue by aidenjaylee** [GoogleChrome/lighthouse#10233]
Please take a look following screenshot;
![image](https://user-images.githubusercontent.com/43595871/72486476-59989d80-384e-11ea-81ba-a556cdc2edd7.png)

We'd like to know the issue was caused by our application or from lighthouse code.

You will want to get test url same as mine.
https://academy.elice.io/

Thanks in advance.

**Comment by RakeshUP** [comment]
The site https://academy.elice.io/ is very slow, that's why a timeout error happened in @aidenjaylee's device. But I was able to run lighthouse on that website. 
cc: @paulirish 
Here is the screenshot:
![screencapture-file-Users-rakesh-Documents-lighthouse-academy-elice-io-2020-02-05-21-06-35-report-html-2020-02-05-21_10_05](https://user-images.githubusercontent.com/20946466/73856911-3022ce80-485c-11ea-851a-18ea86096c36.png)

**Comment by patrickhulce** [comment]
@RakeshUP hit the nail on the head. Also see the advice in #6512 for duplicate :)
