### ISSUE TITLE
Extension Error: The extensions gallery cannot be scripted

### ISSUE THREAD

**Issue by umeshphirke** [GoogleChrome/lighthouse#1023]
**Lighthouse Version**: 1.2.0
**Chrome Version**: 54.0.2840.99
**Error Message**: The extensions gallery cannot be scripted.
**Stack Trace**:
 ```undefined```

**Comment by brendankenny** [comment]
This is happening because the Chrome extension debugger API [isn't allowed to script the Chrome webstore](https://chromium.googlesource.com/chromium/src/+/5d1f214db0f7996f3c17cd87093d439ce4c7f8f1/chrome/common/extensions/chrome_extensions_client.cc#232) (I assume this is trying out Lighthouse immediately after installing the extension).

We should do better with the error message to indicate this.
