### ISSUE TITLE
Please run Lighthouse again. (NO_FCP)

### ISSUE THREAD

**Issue by Magnithor** [GoogleChrome/lighthouse#10347]
There were issues affecting this run of Lighthouse:
Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP)

https://magni.strumpur.net/Map/indexMain.html

running in chrome webgl map homepage...

#### Environment Information
* Affected Channels:   DevTools 
* Lighthouse version:
* Chrome version: Version 80.0.3987.106 (Official Build) (64-bit)
* Node.js version:
* Operating System: Windows 10 Pro 1909

**Comment by exterkamp** [comment]
I'm not seeing anything painted on this page...
![image](https://user-images.githubusercontent.com/6392995/74702718-a231d680-51bf-11ea-9985-5b318cfb0f4f.png)

Seems like requests are being cancelled for mixed content. Lighthouse can't get a first contentful paint because nothing is being painted, just a blank canvas.

**Comment by zleight1** [comment]
I'm seeing this as well since bumping to 80 (current is 80.0.3987.116).

However, in Canary 82.0.4062.6  it seems to be working.

Node v10.18.1
OS Name	Microsoft Windows 10 Pro
Version	10.0.18363 Build 18363

**Comment by exterkamp** [comment]
In Canary on `v82.0.4064.0` I am still seeing `NO_FCP` and the site content is still blocked by mixed-content. 😕

**Comment by zleight1** [comment]
> In Canary on `v82.0.4064.0` I am still seeing `NO_FCP` and the site content is still blocked by mixed-content. 😕

What settings are you using for the new simulated throttling? I get results when I enable it, but with it unchecked that's when I get the NO_FCP. This is with cache enabled/disabled and also clear storage checked/unchecked.

This started happening after 80, so the change with throttling seems to be suspect here.

**Comment by paulirish** [comment]
@Magnithor your page is blank due to mixed content errors: 
![image](https://user-images.githubusercontent.com/39191/75285811-2beb3080-57cc-11ea-81bf-e91be3812e96.png)


@zleight1 FCP is a common issue but if your case is reproducible we're interested.  Are you keeping the tab in the foreground while the audit completes? (It needs to be.)

**Comment by arthurborgesdev** [comment]
I submitted for testing a blank page. After adding a simple `<h1>Hello World</h1>` inside body, Lighthouse completed the report!

**Comment by Anvi98** [comment]
> I submitted for testing a blank page. After adding a simple `<h1>Hello World</h1>` inside body, Lighthouse completed the report!

This really helped me. Thank you Arthur
