### ISSUE TITLE
Serve images in next-gen formats even though, they are.

### ISSUE THREAD

**Issue by ThomasWT** [GoogleChrome/lighthouse#10379]
**Describe the bug**
The tools says images needs to be delivered in next-gen format, even though, they are.

**To Reproduce**

**Expected behavior**
Expecting it to not tell me to deliver webp images when the images are webp

**Screenshots**
![image](https://user-images.githubusercontent.com/1246641/74827221-4f663500-530d-11ea-9726-57090d2b94fe.png)

**Comment by patrickhulce** [comment]
Could you please provide a URL for these to reproduce the issue?

Just because a file has a `.webp` extension doesn't mean it's been encoded with WebP. We only suggest images that were served with a mime type of png/jpeg/bitmap, so my assumption is that this was a JPEG that just renamed to a WebP file.

**Comment by ThomasWT** [comment]
> Could you please provide a URL for these to reproduce the issue?
> 
> Just because a file has a `.webp` extension doesn't mean it's been encoded with WebP. We only suggest images that were served with a mime type of png/jpeg/bitmap, so my assumption is that this was a JPEG that just renamed to a WebP file.

https://www.metadata2go.com/result/df3a2c11-3d81-4182-9852-f185e9ef8ba4

https://www.pharmanord.dk/static/CKFinderJava/userfiles/images/2019/DK/xkosttilskud-er-gode.jpg.pagespeed.ic.huzd5rcPKq.webp

**Comment by patrickhulce** [comment]
Thanks @ThomasWT! I meant the page URL for us to audit :) this is a good start though I think I found it (https://www.pharmanord.dk/nyheder ?)

That file you sent in this issue is indeed a WebP image, but that's not what I see the page serving when I visit it. The file that the page is serving to me (and to Lighthouse) is ~10x bigger and is a JPEG.

In fact lots of images the page is serving have a `.webp` extension but aren't WebP images.

![image](https://user-images.githubusercontent.com/2301202/75284410-5b089e80-57da-11ea-9f50-e5274bb93e65.png)

**Comment by ThomasWT** [comment]
> Thanks @ThomasWT! I meant the page URL for us to audit :) this is a good start though I think I found it (https://www.pharmanord.dk/nyheder ?)
> 
> That file you sent in this issue is indeed a WebP image, but that's not what I see the page serving when I visit it. The file that the page is serving to me (and to Lighthouse) is ~10x bigger and is a JPEG.
> 
> In fact lots of images the page is serving have a `.webp` extension but aren't WebP images.
> 
> ![image](https://user-images.githubusercontent.com/2301202/75284410-5b089e80-57da-11ea-9f50-e5274bb93e65.png)

It's the frontpage. https://www.pharmanord.dk

Here's the gist from lighthouse :)
https://gist.github.com/ThomasWT/1d236a889da7bd692bfb23ebac397f64

**Comment by patrickhulce** [comment]
Thanks, yes, I believe the result you see in the report! What I'm saying though is that Lighthouse is correctly flagging those images because they are not being served as WebP. 

Do you see the screenshot of the network panel? That server is sporadically serving JPEGs and PNGs with a `.webp` extension. The images being served on that domain seem to have a random chance of being served with the incorrect mime type/encoding. **This appears to be a server issue** and Lighthouse is just correctly flagging what's going on.

**Comment by ThomasWT** [comment]
Hey Patrick.

I see the mime type and what you are talking about! Thanks for the help! Sorry for the inconvenience! :)
