### ISSUE TITLE
PageSpeed Insights page not working 

### ISSUE THREAD

**Issue by qdb** [GoogleChrome/lighthouse#10414]
Hi, 

Please check URL below, looks like some data is missing in response from backend or there is bug in the front-end code, which generates the report.

https://developers.google.com/speed/pagespeed/insights/?url=google.com

`lightsights-en.js:344 TypeError: Cannot read property 'length' of undefined
    at DetailsRenderer._renderTable (labreport_js.js:77)
    at DetailsRenderer.render (labreport_js.js:71)
    at PerformanceCategoryRenderer.populateAuditValues (labreport_js.js:87)
    at PerformanceCategoryRenderer.renderAudit (labreport_js.js:85)
    at Array.map (<anonymous>)
    at PerformanceCategoryRenderer.renderClump (labreport_js.js:93)
    at PerformanceCategoryRenderer.render (labreport_js.js:126)
    at prepareLabData (labreport_js.js:148)
    at In (lightsights-en.js:332)
    at Hn.f.b (lightsights-en.js:328)`

**Comment by exterkamp** [comment]
We're looking into this.

**Comment by exterkamp** [comment]
We are rolling out a fix, should be rolled out within a few hours.

**Comment by jazyan** [comment]
@qdb Thank you for reporting! Fix is rolled out and PSI frontend should now be working. More details coming soon.

**Comment by jazyan** [comment]
# Post Mortem: PSI Frontend Outage

On March 2, 2020 from 12:26 - 22:51 PST, the PSI frontend would fail on all sites as pictured below. 
![image](https://user-images.githubusercontent.com/3894375/76344783-64583780-62bf-11ea-9bde-deb6da1b53cb.png)
This resulted in about 10 hours of downtime for https://developers.google.com/speed/pagespeed/insights/. While the frontend was down, the API continued to process requests as normal.

## What happened?
On January 30, there was a change in one of our upstream dependencies that updated the behavior of an internal flag. This internal flag now suppressed empty arrays in the JSON response during proto-to-JSON serialization.

| Before                                            | After           |
| -------------                                 |-------------|
| {<br>&nbsp;&nbsp;&nbsp;&nbsp;"details": {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"items": [],<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...<br>&nbsp;&nbsp;&nbsp;&nbsp;},<br>&nbsp;&nbsp;&nbsp;&nbsp;...<br>} | {<br>&nbsp;&nbsp;&nbsp;&nbsp;"details": {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...<br>&nbsp;&nbsp;&nbsp;&nbsp;},<br>&nbsp;&nbsp;&nbsp;&nbsp;...<br>} |

We upgraded PSI on March 2, which included the above change. Since the Lighthouse renderer relied on empty arrays being preserved, it would crash and fail to render any results. This behavior presented in the Pagespeed frontend, but also affected anyone who relied on empty arrays being preserved in the API JSON responses. Upon noticing the frontend outage, we immediately rolled back to the previous working PSI version. 

## Moving forward
We removed the internal flag. We also updated our end-to-end tests and release documentation to enable catching similar failures in the future earlier.

Major thanks to @qdb for reporting this issue!
