### ISSUE TITLE
Moving script from head to top of the body (right after <body>) can trick lighthouse

### ISSUE THREAD

**Issue by dehghani-mehdi** [GoogleChrome/lighthouse#10422]
In one of my projects I could not put JS at the end of page (before `</body>`). I remove all `script` tags from `head` and put them at the beginning of the `body` tag (after `<body>`) and lighthouse gets happy. this could improve your render blocking score, but we all know it is not good idea and basically nothing changes, still user have to download script first (based of my knowledge)

Before:
```
<head>
    <script src='/path/to/bundle1.js'></script>
    <script src='/path/to/bundle2.js'></script>
</head>
<body>
    <h1>:)<h1>
</body>
```

After:
```
<head>
</head>
<body>
    <script src='/path/to/bundle1.js'></script>
    <script src='/path/to/bundle2.js'></script>
    <h1>:)<h1>
</body>
```

**Comment by ximbong91023** [comment]
![image](https://user-images.githubusercontent.com/23175345/75875050-a1ce4800-5e1b-11ea-9cab-bf9eea3c090d.png)

Script tags in `<head>` will block rendering, while having them at the end of `<body>` won't.

It's quite similar to `<script defer>` in my opinion, while I believe `<script defer>` do start the download earlier than `<script>` locates at the end of `<body>`

**Comment by patrickhulce** [comment]
Thanks very much for filing @dehghani-mehdi! I think I know what you're getting at but would you mind clarifying how we're being tricked? (specific audits, different metrics, etc)

We're aware of the fact that the render blocking resources opportunity (and to a certain extent the simulated FCP metric) can be "fooled" by this (because we have to rely on heuristics like browser priority to avoid loading every possible permutation of the page with certain resources blocked) but these early metrics in general can also be "fooled" by other more innocuous decisions like putting a loading spinner early instead of your actual content. And that's an intentional design property of the metric itself! 

That's why we have a suite of performance metrics that work together. Individually they can be gamed but you'll usually be punished elsewhere for trying to trick a particular metric. If you think you've found a situation where you can get away with instant improvement across all the metrics in both simulated and applied throttling methods without user experience improvements we would love to hear about it to close the gap :)

**Comment by dehghani-mehdi** [comment]
@patrickhulce Thank you for lighthouse. it is really helpful.

I'll do anything and provide information as much as I can to help making lighthouse even better. I have a question tho.

Please forget about the lighthouse and answer this question, putting `script` at the beginning of `body` tag (before anything else) will improvements user experience?

**Comment by paulirish** [comment]
> Please forget about the lighthouse and answer this question, putting `script` at the beginning of `body` tag (before anything else) will improvements user experience?


I looked into this a little.

First started with https://addyosmani.com/blog/script-priorities/ as it has updated details regarding late body scripts.. but it doesn't say what happens to scripts in the body that aren't "late".

Turns out that's defined here: 

https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/loader/fetch/resource_fetcher.cc?l=433-445&rcl=2ddf2643dbbb537501f9f9865859385ed4feeffc

If it's after the first image, it's late. Otherwise.. it's early.  I can see how that affects the network priority.
@patrickhulce i dont immediately see how earlybody or latebody scripts are handled wrt blocking render.  LH has always ignored body scripts. we feel confident in that?

**Comment by patrickhulce** [comment]
> putting script at the beginning of body tag (before anything else) will improvements user experience?

Compared to putting it in the head, yes it marginally will. Compare https://melodic-class.glitch.me/script-head.html vs https://melodic-class.glitch.me/script-body.html with "Slow 3G" throttling turned on. Notice that the background color is able to render after only 2s when in the body compared with 4s when in the head. While there's going to be virtually no difference for the content, it does marginally improve the UX + speed index.

> LH has always ignored body scripts. we feel confident in that?

For the opportunity? Yes, I feel confident about that. If it's not in the head, it's not render-blocking. If we wanted to capture "important content blocking" then we can rename the audit and change its impl :)

For lantern, we don't ignore them. If they're early in the body they'll be issued with `High` priority and be swept up into FCP graph.

https://github.com/GoogleChrome/lighthouse/blob/a5ff4f51abf430950cde2a53e9cee085d908c6de/lighthouse-core/lib/dependency-graph/network-node.js#L81-L88

**Comment by patrickhulce** [comment]
Addressed this in the last few comments, but this behavior is intentional. If anyone has a different example of metrics being incorrect, feel free to file a new issue :)
