### ISSUE TITLE
uses-responsive-images only cares about savings not about correct use of responsive images

### ISSUE THREAD

**Issue by sk-** [GoogleChrome/lighthouse#10434]
The `uses-responsive-images` check only checks whether a too large image is used. This means that it only catches cases in which the used image is way bigger than the actual display size. This typically happens when developers just shove a @2x or larger version of the image without using a `srcset`.

The part that is missing is when the image is too small compared to the display size. I.e, no @2x version is in use.

Basically I'm suggesting to add something along the lines:

```js
const DPR = artifacts.ViewportDimensions.devicePixelRatio;
const TOLERANCE = 0.9; // This is to not produce that many violations, I'd like it to be set to 1.
const bigEnough = image.displayedHeight <= image.naturalHeight / (DPR * TOLERANCE) && image.displayedWidth <= image.naturalWidth / (DPR * TOLERANCE);
```

I understand, that doing in that way may change the scope of the audit, as it is currently part of the byte efficiency category. So feel free to recategorize this as a feature request.

**Comment by patrickhulce** [comment]
Thanks for filing @sk-! Yeah we definitely wouldn't want to put something in the performance category that tells folks to serve *larger* images ;) so I think we'd consider this a good candidate for a "Best Practices" new audit. 

Anyone passionate here care to fill out the new audit proposal questionnaire?  :)

**Comment by sk-** [comment]
@patrickhulce below is the new audit proposal questionnaire, let me know if you need something else.

#### Provide a basic description of the audit
The audit, called for now `ImagesHaveRightSize`, will enforce that source images in a website are at least larger to how they are displayed. This is necessary to ensure that images look crisp to the user.

Note that for technical reasons, similar to the ones given in the audit `UsesResponsiveImages`, the audit will not consider css images.

#### How would the audit appear in the report? 
The audit would appear in the `Best Practices` category.

For a failing test the results would be similar to those of `UsesResponsiveImages`.

It would be a tabular data showing the offending images, with a thumbnail, the image's original size and the dispalyed size.

#### How is this audit different from existing ones?
This is a complement to `UsesResponsiveImages`, which only checks whether the images are small enough.  This check will also enforce that the images are not too small. Effectively requiring the users to use responsive images to pass the audit. This also complements the audit `ImeageAspectRatio`.

#### What % of developers/pages will this impact?
I'd say that more than 90% of sites will be impacted by ths audit. I executed the POC (shown at the end), and all of the top 10 Alexa sites were affected, although some use techniques to replace the images with a higher density version after scrolling them into view.

Tht number is also supported by some work I did while at Google, in which I developed an extension to detect incorrectly sized images. From what I remember at the time, all the Google sites I tried were affected by it. Note though, that that check was considering css images as well.

#### How is the new audit making a better web for end users?
This would make a better web for users as nowadays most devices have a high density display, the so called Retina displays. For example on Android, more than 90% of the devices have a pixel density greater than one. See https://developer.android.com/about/dashboards. On iOS and MacOs, all of their devices have a high density. Even Chromebooks have retina displays. And now with the adoption of 4k or even 8k monitors, more and more users have access to a high resolution display. This audit would also prevent

> "the rendered image may look distorted, possibly creating an unpleasant user experience"
(Source: https://web.dev/image-aspect-ratio/)

#### What is the resourcing situation? 
The audit is quite similar to `UsesResponsiveImages`, so I could volunteer an initial PR with the change.
Regarding the documentation, it probably should be a merge between the articles https://web.dev/image-aspect-ratio/ and  https://web.dev/uses-responsive-images/, but I have no idea how to edit or contribute to that site.
Regarding the audit's maintainance, I'd imagin thate someone from the Lighthouse team needs to champion it. 

#### Any other links or documentation that we should check out?
A proof of concept that can be used to test a website via the JS console is attached.

```js
const DPR = window.devicePixelRatio;
const TOLERANCE = 0.7;
function isValidImage(img) {
  if (img.srcset !== '' || img.width <= 1 || img.height <= 1 || img.naturalWidth === 0 || img.naturalHeight === 0 || img.src.endsWith('.svg') || img.src.startsWith('data:image/svg')) {
    return true;
  }
  const widthRatio = img.naturalWidth / img.width;
  const heightRatio = img.naturalHeight / img.height;
  if (img.height <= 64 && img.width <= 64) {
    return widthRatio >= DPR && heightRatio >= DPR;
  }
  return widthRatio >= DPR * TOLERANCE && heightRatio >= DPR * TOLERANCE;
}
Array.from(document.querySelectorAll('img')).filter(img => !isValidImage(img));
```

**Comment by patrickhulce** [comment]
Thanks very much @sk- ! Excellent plan 👍 

> although some use techniques to replace the images with a higher density version after scrolling them into view.

This is a great point. We'll probably want to limit to above the fold images since offscreen image lazy loading libraries tend to use these techniques with placeholder content. Unfortunate that our net will be smaller but better IMO than to falsely flag and discourage lazy loading of images.

> it probably should be a merge between the articles https://web.dev/image-aspect-ratio/ and https://web.dev/uses-responsive-images/, but I have no idea how to edit or contribute to that site.

There's a [separate repo](https://github.com/GoogleChrome/web.dev), but it doesn't necessarily need to be a launch blocker since the action item is so similar to our guidance for regular responsive images when it's too large.

If all that sounds good I'm happy to be the reviewer and support from the LH side of things here.

**Comment by sk-** [comment]
Great! I do have a working version already. Need to add unit tests and do some more empirical tests, before sending the PR. I expect to submit it by next week.

**Comment by hugues-koolsol** [comment]
Hello,
On my site, https://www.koolsol.com/
there is a warning because a button containing an image is not displayed with a good size on a Moto G4 which has a pixel ratio of 3. Instead of 41 pixel, lighthouse suggests 123 pixels.

1 °) To have the explanation, I clicked on the link "learn more" which leads to this page:
https://web.dev/image-size-responsive/?utm_source=lighthouse&utm_medium=devtools
which displays a 404.

2 °) If the image is small (which is the case with this button), isn't this test too harsh?
I understand that a "beautiful" jpg image must have an optimized size depending on the device but for an optimized gif or png image contained in a button, is it really necessary in all cases?

I suggest adding a test to return "true" in case the displayed size of the image is less than 100px and it is a png or a gif. After all if the png / gif image display satisfies my client on a device with a pixel ratio of 3, why lighthouse imposes a larger image.

PS: I could have used an svg image for this button, as for the other buttons but on some "old" devices/browsers, the svg works badly and I wanted to display at least the "new game" button for sure.

Hugues
![image](https://user-images.githubusercontent.com/26767344/82122270-cedf9500-9792-11ea-974c-d586bdd67378.png)


Runtime Settings
URL : https://www.koolsol.com/
Fetch Time May 16, 2020, 3:37 PM GMT+2
Device Emulated Moto G4
Network throttling 150 ms TCP RTT, 1,638.4 Kbps throughput (Simulated)
CPU throttling 4x slowdown (Simulated)
Channel devtools
User agent (host) Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4148.0 Safari/537.36
User agent (network) Mozilla/5.0 (Linux; Android 6.0.1; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3963.0 Mobile Safari/537.36 Chrome-Lighthouse
CPU/Memory Power 1268
Lighthouse 6.0.0

**Comment by patrickhulce** [comment]
@hugues-koolsol you're describing the exact case the audit is trying to catch. It's just a best practice, not a performance audit. That being said, our DPR of 2.625 is going to make the strict 1:1 mapping of this audit, *extremely* annoying. I don't know of anyone alive that will create specific `2.625x` versions of their tiny icons.

IMO, we should loosen the smaller icons to the large image factor of 0.75.

**Comment by sk-** [comment]
@hugues-koolsol That icon does look bad on my MacBook pro, and is smaller icons the ones that usually need a higher density.

@patrickhulce we could apply the floor to the used DPR, so instead of using 2.625 we use a factor of 2 instead. 

With respect to treat small images the same as larger ones, my rationale was that the smaller ones are the most visible when they have an underpar density. I'm open to lower the threshold, however in this particular case, it would not fix the problem as the website has the image at a 1x density, and with a factor of 0.75 it would require a density of at least 2.15x.

@patrickhulce Given that math, we could also discretize the required density after applying the factor.

Maybe we should use something like the following:

```
if (requiredDensity >  2) {
  requiredDensity = Math.floor(requiredDensity)
}  else if (requiredDensity >= 1.5) {
  requiredDensity = 1.5
} else {
  requiredDensity = 1;
}
```

WDYT? Let me know and I can prepare a PR.

**Comment by patrickhulce** [comment]
Oh definitely agreed that the audit should still flag this image in its current state, just noting that requiring exactly 2.625 is going to be really rough.

My other concern is that DPR is not the only factor in play as fluid images with variable sizing will need both some tolerance for the specific breakpoint selected *and* the 2.625 DPR. 

I think if we effectively treat 2.625 as 2 for both large and small images (using your proposed snippet) and then allow 75% coverage as passing for large images we'll be covered here 👍

**Comment by hugues-koolsol** [comment]
Thank you very much for your comments, I must admit that I am a little overwhelmed by your technical knowledge. But if I could bring my little stone to the construction of lighthouse, I am delighted.
Anyway, whatever your choice, I will adapt my page.
Thank you.

**Comment by hugues-koolsol** [comment]
Page adapted :-)
I have put an svg image instead of the png image, I feel better now !
I hope the image will look better on your mac book pro. As it is a pwa you may have to load 2 new games before seeing the change.

There is only the "learn more" link to fix.
![image](https://user-images.githubusercontent.com/26767344/82147896-39efa100-9851-11ea-8674-84a4e6add5ba.png)

Thank you for your work and your help.
