### ISSUE TITLE
Question: Auth - How do you auth with Puppeteer w/o caching the page?

### ISSUE THREAD

**Issue by rozenmd** [GoogleChrome/lighthouse#10442]
I'm building a tool that runs Lighthouse in AWS Lambda (http://perfbeacon.com/) to monitor pages both regularly and ad-hoc, and it seems like I'm hitting a wall with Auth.

I've seen [this comment](https://github.com/GoogleChrome/lighthouse/issues/1418#issuecomment-459080398) and it basically describes what I'm seeing:
- Enabling `--disable-storage-reset` results in inflated perf scores, as Puppeteer has already logged into the page, and caches the assets (even if you add `await page.setCacheEnabled(false)`).
- Not enabling `--disable-storage-reset` results in somewhat accurate perf scores, though some pages will revert to an unauthenticated view as you've cleared localStorage.

I guess what I'm asking is: Is there a way to get Lighthouse to run the storage reset without blowing away localStorage/cookies etc?

Edit:
With a bit of experimentation, it looks like enabling `--disable-storage-reset` in conjunction with using

```js
const client = await page.target().createCDPSession();
await client.send('Network.clearBrowserCache');
```

at the end of my Puppeteer login snippet seems to clear the cache as expected before Puppeteer runs, without blowing away localStorage or cookies.

**Comment by patrickhulce** [comment]
> With a bit of experimentation, it looks like enabling --disable-storage-reset in conjunction with using

Yep that's pretty much what we'd recommend :)

Here are the two places Lighthouse clears caches if you'd like to more completely reproduce the behavior, though it might not affect your site.

https://github.com/GoogleChrome/lighthouse/blob/ea9d226606c5b534d4259253baac5f709a9e3d7c/lighthouse-core/gather/driver.js#L1402-L1416

https://github.com/GoogleChrome/lighthouse/blob/ea9d226606c5b534d4259253baac5f709a9e3d7c/lighthouse-core/gather/driver.js#L1431-L1468


Unrelated but worth noting since you mentioned it, we've had a really poor experience with getting reliable performance metrics out of AWS lambda due to the underlying hardware variability (along with any of the "burstable" instance types). If you care about the performance metrics, I'd suggest trying to use a dedicated instance to run Lighthouse.

**Comment by rozenmd** [comment]
Exactly what I was looking for, thanks @patrickhulce!
