### ISSUE TITLE
Generate Report Error

### ISSUE THREAD

**Issue by dennisjosephquinto** [GoogleChrome/lighthouse#10474]
PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://localhost:44369/
Chrome Version: 80.0.3987.132
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (devtools://devtools/remote/serve_file/@fcea73228632975e052eb90fcf6cd1752d3b42b4/audits_worker/audits_worker_module.js:1268:229)
```

**Comment by dennisjosephquinto** [comment]
Just to add, when PWA is ticked off, the report is generated seamlessly.

**Comment by MickeyKay** [comment]
That said. . . even with throttling enabled, Lighthouse numbers don't seem to match the linked trace. For example. . . 

Here's my Lighthouse TTI metric:
![image](https://user-images.githubusercontent.com/3189678/77270839-48af4280-6c6a-11ea-8f60-67ca734611f6.png)

However when I click the `View Trace` link, my entire trace is only ~15s long:
![image](https://user-images.githubusercontent.com/3189678/77270907-77c5b400-6c6a-11ea-824c-0953ee1b0532.png)

Is there a better way to ensure the LH #'s match up with Chrome dev tools' trace so that I can do some more granular analysis of what's pushing key metrics out?
