### ISSUE TITLE
Use installabilityErrors for PWA Installable criteria

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#10515]
EDIT: this issue now tracks using installabilityErrors entirely to power the installable section of Lighthouse PWA. more details here: https://github.com/GoogleChrome/lighthouse/issues/10515#issuecomment-693013839

original OP comment below;

----------

https://code.nasa.gov/

Maybe related to how the page causes a PROTOCOL_TIMEOUT?

From https://bugs.chromium.org/p/chromium/issues/detail?id=951684

**Comment by brendankenny** [comment]
As noted in that crbug, devtools says `Page does not work offline`. Looks like that's the "does the SW have a fetch handler" check: https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/installable/installable_manager.cc;l=689-691;drc=34ad93361f96ad875bf350ced27e15b7aa126113

Lighthouse does not do this check. IIRC, the idea was that Chrome would do the basic check (is it possible for this SW to respond offline at all, aka has an event handler for fetch, not if it *actually* responds when offline), while Lighthouse would do the real offline-load check.

However, we didn't put the real offline-load check in the `Installable` group, we put it in the `Fast and reliable` group:

<img width="595" alt="Lighthouse PWA report" src="https://user-images.githubusercontent.com/316891/77777240-aa362f00-7025-11ea-9bae-9cc1ab658310.png">

https://googlechrome.github.io/lighthouse/viewer/?gist=c47b34872c967c1cbc4d92ab80bdc656

I would think this would have come up in the review of what to put in the `Installable` group, but it was long enough ago I don't remember if there were any nuances.

If our goal is still `Installable` badge ⊃ installable as a PWA in Chrome, seems like we have two choices:

- Follow the letter of the law and add a SW fetch handler audit to the `Installable` group. This is a dumb test and it would feel bad to include in LH.
- Follow the spirit of the law ("Page works offline", which includes the Chrome fetch-handler check) and move the offline audits to the `Installable` group. Seems like it would be great for `Installable` (would need to include in 6.0 as a breaking change). Downside is `Fast and reliable` would then only contain a single audit, which is a bit silly.

**Comment by brendankenny** [comment]
> If our goal is still `Installable` badge ⊃ installable as a PWA in Chrome

though I guess many on the team have also gradually shifted to thinking more `Installable` badge === installable as a PWA in Chrome, and our audits should only match what is really required.

The first option may be preferable to those folks (maybe folding it into the "Registers a service worker that controls page and start_url" audit would make it more palatable) and our mandate to do a real offline check becomes part of the above-and-beyond part of the other two PWA badges. May be worth discussing in the next team meeting.

**Comment by patrickhulce** [comment]
While it is definitely a pretty useless check that feels bad to write, I agree that the only point of having the "Installable" category at all is if it actually maps to installability. Otherwise we might as well abandon this and go back to our old structure. Option 1 makes the most sense to me.

**Comment by paulirish** [comment]
Yup agreed with @patrickhulce. let's look for a fetch handler. (`artifacts.InstallabilityErrors` should actually have this, so it should be straightforward)

**Comment by brendankenny** [comment]
> I agree that the only point of having the "Installable" category at all is if it actually maps to installability. Otherwise we might as well abandon this and go back to our old structure. Option 1 makes the most sense to me.

*grumble grumble*

...yeah.

**Comment by paulirish** [comment]
Chrome's has the has-fetch-handler check, but is working on an improved one: [965802 - Implement more accurate service worker&apos;s offline capability detection - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=965802#c30)

I tested this out and it works and even provides this signal to `Page.getInstallabilityErrors`:

```sh
chrome-debug --enable-features=CheckOfflineCapability
```


![image](https://user-images.githubusercontent.com/39191/93270828-bbefc800-f766-11ea-921a-8c1655d9398d.png)


so backing up... a sw with this (non-handler):

```js
/// COMMENTED OUT! NO HANDLER! this.addEventListener('fetch', .........
```

and we'll see a `not-offline-capable` in Chrome today.

but if its... 

```js

this.addEventListener('fetch', function(e) {
  console.log('nothing happening...')
});
```

we won't have that error signal... unless the `--enable-features=CheckOfflineCapability` flag is flipped. wooo!

we can work on this at will, though it'd be nice to start using this signal once the experiment lands so that chrome doesn't change Lighthouse's installability signal unexpectedly.  :)

star [crbug.com/965802](https://crbug.com/965802) to watch it.

**Comment by rictic** [comment]
As a point of reference, I'm hacking on a little multiplayer social game right now, which would benefit from being installable, but doesn't have a coherent offline experience (except maybe eventually a tutorial). I spent a lot of time ticking the check boxes for installability (TLS in rust server, manifest, icons, etc etc), got the lighthouse audit passing and then felt stuck and frustrated because Chrome wasn't giving the option to add to home screen.

**Comment by paulirish** [comment]
> (e.g. by moving the existing audit that the start URL gives a 200 OK while offline).

@rictic you mean "removing" instead of "moving", right?

in general that sounds good and i agree aligning with chrome's impl is better. annoying to not have them match.

**Comment by rictic** [comment]
I mean moving. Currently there is an audit for whether the start URL gives a 200 OK while offline, but it isn't listed under the PWA installability audit. IMO it would be an improvement if it was listed as an installability audit, because while that's not 1:1 with Chrome's requirement, it's a superset of it (assuming that the only way to get a 200 OK while offline is via a service worker fetch handler)

**Comment by paulirish** [comment]
@rictic Hmmm gotcha! We are thinking of removing those offline/200OK checks entirely and relying instead on Chrome's heuristics (which include the fetch handler). This means there's no full function offline check, but it means LH's messaging totally consistent with the Chrome experience. Does that seem decent to you?
