### ISSUE TITLE
incorrectly reporting third-party code on Netlify app

### ISSUE THREAD

**Issue by BernardA** [GoogleChrome/lighthouse#10521]
#### Provide the steps to reproduce
1. Run LH on <https://musing-davinci-538143.netlify.com/>
  

#### What is the current behavior?

It is reporting own app code as third-party  code, from Netlify specifically. The app is hosted by Netlify, but as you can see in the below discussion, Netlify does not add any code to it.

![Screenshot 2020-03-28 at 11 54 57](https://user-images.githubusercontent.com/9449665/77821549-86d5b780-70eb-11ea-8bcb-9f987306719d.png)

#### What is the expected behavior?

Should not show as third-party code

#### Environment Information
* Affected Channels: 
* Lighthouse version:5.7.0
* Chrome version: Version 80.0.3987.149 (Official Build) (64-bit)
* Node.js version:
* Operating System: Mac OS Catalina 10.15.4

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @BernardA! I think this is primarily a mistake in messaging. The third-party summary section is meant to highlight resources that came from another entity whether you have control over their content or not. The lines are blurred for CDN providers because *sometimes* it's your code just distributed through the CDN and other times it's *someone elses* code distributed through the CDN (or even the CDN provider's! though not in Netlify's case). 

I think there are two action items:

1. Ignore any "third-party" content that matches the eTLD+1 of the audited page.
2. Tweak the description and docs to make it clearer that these were *served* by a third-party even if it's possible its still your code.

**Comment by patrickhulce** [comment]
Oh wait, turns out we already fixed this issue in November (https://github.com/GoogleChrome/lighthouse/pull/10006) but it just hasn't been deployed to PSI yet. Just up to the docs then.

**Comment by exterkamp** [comment]
Pending changes: 
> Tweak the description and docs to make it clearer that these were served by a third-party even if it's possible its still your code.

Other than that, just waiting on PSI 😄

**Comment by connorjclark** [comment]
@exterkamp I guess this it done ya?

**Comment by exterkamp** [comment]
Should be! Doesn't appear anymore for that URL.
