### ISSUE TITLE
Repeated performance score of 0 for https://www.lendopolis.com/

### ISSUE THREAD

**Issue by alkidel** [GoogleChrome/lighthouse#10539]
#### Provide the steps to reproduce
1. Run LH on https://www.lendopolis.com/
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System: 

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @alkidel! This is expected behavior for a site that does not render any content for 10s on a typical mobile connection. If you're the owner of this site, try to follow the suggested optimizations to improve the performance metrics and the score.

![image](https://user-images.githubusercontent.com/2301202/78270301-42be2a80-74d0-11ea-866c-ca8c328ac63d.png)
