### ISSUE TITLE
Audit is much slower when "clear storage" and "simulate throttling" are unchecked

### ISSUE THREAD

**Issue by hugues-koolsol** [GoogleChrome/lighthouse#10543]
1. Run LH on https://sudoku.koolsol.app/
2. See how fast the result comes => it takes 5 seconds 👍 , the result is 💯  for all scores
3. Uncheck clear storage and simulate throttling
4. Re-run lighthouse => it takes more than 30 seconds even if the result is also 💯 for all scores

#### What is the current behavior?
The second audit is much slower than the first one.
#### What is the expected behavior?
The second audit should be much faster than the first one.

#### Environment Information
* Lighthouse version : 5.7.1
* Chrome version : Google Chrome 83.0.4103.0 (Build officiel) canary (64 bits) (cohort: Clang-64)
* Node.js version : v10.16.3
* Operating System : Windows 10 OS Version 1903 (Build 18362.720)
* Tested from : Paris, France

**Comment by patrickhulce** [comment]
Thanks for filing @hugues-koolsol! This is expected behavior. 

"Simulated throttling" is the fast version that loads the page very quickly without applying any observed throttling, i.e. it's simulated. Unchecking "simulate throttling" will fallback to "applied throttling" which will dramatically slowdown the page's network and CPU as well as require a 5s quiet window after everything has loaded before anything can be computed.

**Comment by hugues-koolsol** [comment]
Thanks for your reply and sorry for having understood the contrary.
