### ISSUE TITLE
Delete 'mixed-content' preset

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#10593]
I think this was disabled b/c of some issue with Chromium that has since been resolved. https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-cli/bin.js#L73

Removing a preset is a breaking change, so we should do this soon.

I don't want to move the existing `mixed-content` to the default config, because we will be replacing it entirely with data from the new issues protocol. I'd prefer going from no `mixed-content` in default config -> data from CDP; than no `mixed-content` -> our `mixed-content` logic -> data from CDP. There may be enough differences to consider it a breaking change? Or we may decide to present the data differently than what the current audit does, to align with Issues panel. Seems simpler to just toss what we currently have.

**Comment by brendankenny** [comment]
I'm all in favor of deleting because it's a totally separate type of LH pass that AFAIK no one runs or pays attention to (#5498 was my "if we have to keep, fine, at least let's make CI run it" :), but it is different than what the Issues Panel will highlight.

`mixed-content` actually does a separate load of the `http` version of the test page to see if there's a mixed content issue on that version of the page, while the Issues panel will only have what was actually loaded to work with.
