### ISSUE TITLE
Expose constants more easily

### ISSUE THREAD

**Issue by mehulkar** [GoogleChrome/lighthouse#10600]
It would be nice to be able to do `require('lighthouse').constants` or `require('lighthouse/constants')`. I could be missing something, but right now I have to do `require('lighthouse/lighthouse-core/config/constants.js')`

**Comment by patrickhulce** [comment]
Thanks for filing @mehulkar! We don't really consider the constants part of our public API at the moment, so that's why they're difficult to get. It might be a good idea to re-examine what files would be nice to expose for plugins though, and I could see constants making the cut :)

Plug: Team if we did want to commit to this, wdyt about using [generate-export aliases](https://www.npmjs.com/package/generate-export-aliases)? :)

**Comment by paulirish** [comment]
Yah for now we're gonna make it a lil hard for you. We're not ready yet to consider those part of the public API (and commit to non-breaking changes, etc)

honestly they dont change all that much, so you should be good. :) 

excited for what you're doing with them!
