### ISSUE TITLE
Performance incorrectly reported on HTML/JS site

### ISSUE THREAD

**Issue by ac00perw** [GoogleChrome/lighthouse#10629]
I have a local VueJS site that when compiled for development loads and is usable in ~580ms that gets reported as 19s 'time to interactive' and all other metrics report as 11.5s. It's also reporting that adding text compression will shave 16.6s off. 

When compiling for production it reports as 4.4s/7.3s which is faster but still wildly inaccurate.

**Comment by patrickhulce** [comment]
Thanks for filing! 

This is working as intended. Lighthouse reports the performance metrics as they would be experienced by a typical mobile user on a 4G connection and a mid-tier ~$200 phone.

The performance score is not going to be very helpful on a development build served over localhost without compression. As you've discovered, if you were to actually do that to serve your users it would have awful performance and isn't at all realistic of what happens when you deploy your site. You want to run Lighthouse on production assets served with text compression for realistic performance metrics.

> When compiling for production it reports as 4.4s/7.3s which is faster but still wildly inaccurate.

I'm not sure if this also adds compression or not, but the remaining delta is almost certainly the disconnect with [default throttling](https://github.com/GoogleChrome/lighthouse#how-does-lighthouse-use-network-throttling-and-how-can-i-make-it-better). It is virtually impossible to serve a site over a realistic mobile network in 580ms, so that sounds like your localhost/desktop experience.

**Comment by ac00perw** [comment]
Ah thanks. Not sure how I missed that. I was under the impression it was giving me results based on my browser/experience. All said and done I pushed the site to a server and got 1.5s to first contextual paint and a score of ~95 which is what I would expect. 

Thanks for the link and your time.

**Comment by patrickhulce** [comment]
Sure, glad you got it sorted out :)
