### ISSUE TITLE
Specify axe-core version in report

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#10640]
Either in the category description or the report footer.

**Comment by paulirish** [comment]
> in the category description 

so like this?
![image](https://user-images.githubusercontent.com/39191/80533302-42d80b80-8952-11ea-8a74-980bb45aceb9.png)

> or the report footer.

tossing into the runtime settings block seems peachy.

**Comment by connorjclark** [comment]
I feel like we were leaning towards the image, not the runtime settings, when we discussed this in eng sync.

**Comment by paulirish** [comment]
Heh I recall myself and Shane, at least, favoring RS. Brendan too? (And he brought up other credits we _could_ expose)

**Comment by connorjclark** [comment]
I thought Shane explicitly said he didn't like the settings. blegh. we need to record these meetings or sumthin.

**Comment by connorjclark** [comment]
i really don't care where it goes tho

**Comment by brendankenny** [comment]
Yeah, I'm not a fan of increasing `default-config.js` complexity to do string replacement with the version number and would rather it be in runtime settings as a result. It should be a little cleaner that way, too, because we won't have to mess with package.json or deps or anything...it's on `axeResult.testEngine.version` and so could be added to the a11y artifact.

**Comment by patrickhulce** [comment]
I also favor runtime settings if we're keeping score :)
