### ISSUE TITLE
The CLI --output csv option should include the requestedUrl in the output.

### ISSUE THREAD

**Issue by liamvictor** [GoogleChrome/lighthouse#10654]
[batch.txt](https://github.com/GoogleChrome/lighthouse/files/4547869/batch.txt)

[reports.zip](https://github.com/GoogleChrome/lighthouse/files/4547874/reports.zip)

I frequently batch up a number of pages using the CLI, using a command such as:

`lighthouse $page --quiet --output html --output csv --output json --only-categories performance --chrome-flags="--headless"`

This will produce a results with filenames such as www.example.com_2020-04-27_18-34-16.report,csv .json and .html

The reports all just have the domain as the filename. Within the html and json files, I can see what the page I tested was. However with the CSV file the total fields outputted for performance are related to the weightings and don't include the page tested.

There you can see from the attached that the page that was tested is not listed in the CSV, and as the filename doesn't include the page - only the domain - I have to jump through further hoops to compile the data together.

The json output includes, (like the HTML), the actual values rather than a weighting. If all of that could be included in the csv output it would be wonderful - but the page tested fields ("requestedUrl" and "finalUrl") would make the csv much easier to work with at a stroke.

**Comment by connorjclark** [comment]
Looks like @patrickhulce is ready with a PR already :)

FYI, as you've discovered the CSV report is not something we prioritize, since the JSON is so much more useful. You've already got some programmatic glue in your workflow–if you need more than what the CSV report can provide, I suggest looking into converting the JSON to whatever CSV you want so you can customize your sheets.

Apparently jq can do this on the command line (although a node script may be easier): https://www.freecodecamp.org/news/how-to-transform-json-to-csv-using-jq-in-the-command-line-4fa7939558bf/

**Comment by liamvictor** [comment]
I don't know if it's the done thing to say thank you here, but thank you for taking a look and suggesting an alternative workflow.
