### ISSUE TITLE
Natural-Language Quality Evaluation

### ISSUE THREAD

**Issue by anasram** [GoogleChrome/lighthouse#10691]
Hi all!

I used to use [web.dev](https://web.dev/measure) to evaluate my website from time to time.

I've been wondering recently if it's a good idea to add a spell —& maybe grammar— evaluation to [web.dev](https://web.dev/measure)?

In theory, doesn't natural-language quality considered as an accessibility issue in a web page?

**Comment by patrickhulce** [comment]
Thanks for filing @anasram! This is something outside the scope of Lighthouse as the complexity of text nodes and intentional spelling liberties is not something that can be universally suggested.

While we're unlikely to implement such a feature in core, feel free to create a [plugin](https://github.com/GoogleChrome/lighthouse/blob/master/docs/plugins.md) and add it to our README for others to use :)
