### ISSUE TITLE
bytes smoke test is flaky

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#10734]
https://travis-ci.org/github/GoogleChrome/lighthouse/builds/684851812#L1770

devtools node path is flaky.

**Comment by patrickhulce** [comment]
@brendankenny are you still of the belief that those assertions in the smokes are necessary? 

could I see you on `\d+` to replace all those numbers? :)

**Comment by brendankenny** [comment]
> @brendankenny are you still of the belief that those assertions in the smokes are necessary?

Haha, I think I just suggested we have [*some* smoke test coverage](https://github.com/GoogleChrome/lighthouse/pull/9713#pullrequestreview-291882323) :P

I'd probably be ok with `\d+` for those since it's just a slightly different node ordering and not central to what's being tested (we could get conservative and do `143\d` if we're feeling confident in the "slightly" part of "slightly different), but independent of the specific test, do we feel reasonably satisfied we know what the root flakiness is?

Are nodes being added to the page dynamically and so depending on relative execution times a node might be slightly earlier or later in its parent? Or is the cause unknown?

**Comment by brendankenny** [comment]
ha, apparently it was [flipping between 1438 and 1437](https://github.com/GoogleChrome/lighthouse/pull/9713#discussion_r327224841) in #9713, now it's between 1438 and 1439

**Comment by connorjclark** [comment]
> Are nodes being added to the page dynamically and so depending on relative execution times a node might be slightly earlier or later in its parent? Or is the cause unknown?



yes, i made it less flaky: https://github.com/GoogleChrome/lighthouse/pull/9713#discussion_r327224841

timer code: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-cli/test/fixtures/byte-efficiency/tester.html#L45

`\d+` sgtm

**Comment by connorjclark** [comment]
lol I said `fixess`
