### ISSUE TITLE
Make the 3P row in 'Keep request counts low and transfer sizes small' more accurate

### ISSUE THREAD

**Issue by danieltxok** [GoogleChrome/lighthouse#10851]
Context: https://web.dev/resource-summary/

This is a request to consider same-site requests as 1P. Currently, if we audit www.example.com, anything that has a different origin is considered 3P. For example, many sites serve images under cdn.example.com (same-site but cross-origin) and these requests are currently counted as 3P. I think that removing them from the 3P classification will give a better overview of the real 3P assets a page is loading.

Thanks

**Comment by connorjclark** [comment]
@patrickhulce more third-party-web? :)

**Comment by patrickhulce** [comment]
I would certainly like to for our own summary but it might have weird inconsistency with budgets since they share the same breakdown :/

Unfortunately budgets was the one place I think we decided we didn't want to base on third-party-web since it can change as we update the list of third parties.

`firstPartyHostnames` was the [budgets option](https://github.com/GoogleChrome/lighthouse/blob/fed2b62f230cffc90939c76a77608ee0ccde8b46/docs/performance-budgets.md#budgetjson) introduced to combat this problem there.

> For example, many sites serve images under cdn.example.com (same-site but cross-origin) and these requests are currently counted as 3P

This shouldn't be happening @danieltxok. Do you have a specific webpage as an example? We should be counting the entire TLD+1 as first party by default, so `cdn.example.com` should count as first party, but `cdn-example.amazonaws.com` will still be third party.

**Comment by danieltxok** [comment]
My bad guys. Missed that I was running from another country: page in _www.example.de_ but images served from _cdn.example.com_. I guess this is how it should be, thanks!
