### ISSUE TITLE
LCP strange behavoir and Unused js for AMP site

### ISSUE THREAD

**Issue by trademinister** [GoogleChrome/lighthouse#10888]
#### Provide the steps to reproduce
1. Run LH on <moussonatelier-ru.myshopify.com>
#### What is the current behavior?
Use AMP. 
1. There is message about unused javascript v0.js
2. LCP time calculation for image is 4,6 sec
#### What is the expected behavior?
1. Without v0.js impossible to run site with amp-img and other tags
2. LCP time is wrong, Even if I use only text tags there is 4 sec time for it.

#### Environment Information
* Lighthouse version: 6
![lcp](https://user-images.githubusercontent.com/23034301/83356852-6f2be100-a371-11ea-9f6a-89ac27d9f317.png)
![network](https://user-images.githubusercontent.com/23034301/83356859-7a7f0c80-a371-11ea-87ff-97492424889a.png)

**Comment by patrickhulce** [comment]
Thanks for filing @trademinister!

1. It's not saying the entire file is unused. It's saying a significant percentage of the files are unused. If it's coming from a third-party (like AMP) there might be nothing you can do about it other than reaching out to the vendor to see if there's a slimmer version you can use that has the smaller feature set that you actually need.
2. See the [FAQ on Lighthouse throttling](https://github.com/GoogleChrome/lighthouse/#why-is-the-performance-score-so-low-it-looks-fine-to-me).

**Comment by trademinister** [comment]
Hello,

Thanks for such a quick response.
Read the FAQ.
But how is it possible to render LCP for 4 sec if it only contains text for
h1 tag (I threw all images from the homepage moussonatelier-ru.myshopify.com
)?
Please see attached.


вс, 31 мая 2020 г. в 19:17, Patrick Hulce <notifications@github.com>:

**Comment by patrickhulce** [comment]
I don't see any attachments in your latest comment, but when I audit that site I see you've removed the image.

Accordingly, I also see the LCP has improved to around ~3.5s. It's still sitting there because this page requires a couple JS tasks to complete and fetching the AMP JS takes a while.

![image](https://user-images.githubusercontent.com/2301202/83357833-81d3f500-a334-11ea-9102-392f8e7c8f83.png)

There is some amount of [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) here but nothing that I see is wrong with the LCP calculation. Running on [a real device with real throttling](https://webpagetest.org/lighthouse.php?test=200531_FG_9972a24ed7c27777f10c74636f069a54&run=1) returns very similar numbers as Lighthouse.

**Comment by trademinister** [comment]
Thanks Patrick for the help.
I understand the problem.
