### ISSUE TITLE
Add repo website

### ISSUE THREAD

**Issue by dandv** [GoogleChrome/lighthouse#1093]
https://developers.google.com/web/progressive-web-apps/#lighthouse would be good

Also, the repo description could start with a capital letter.

**Comment by brendankenny** [comment]
> Add repo website

do you mean add to the readme?

**Comment by dandv** [comment]
I mean in the repo's website field:

[![image](https://cloud.githubusercontent.com/assets/33569/4949884/c2b69bde-6651-11e4-88eb-8fdf8e8c9f0a.png)](https://github.com/dandv/meteor-jquery-rateit)

![image](https://cloud.githubusercontent.com/assets/33569/20818628/c0ec419c-b7e3-11e6-932c-ed4e6c642b19.png)

**Comment by paulirish** [comment]
I'd be into linking to https://developers.google.com/web/tools/lighthouse/ as the homepage.
There are two changes I'd like to see first though.

1. Remove (or move to the bottom) the author attribution of @kaycebasques. It doesn't look like a homepage for a project because the attribution is so up front. 
2. The https://developers.google.com/web/progressive-web-apps/images/pwa-lighthouse.png image is pretty cute and I'd be happy to see it on the /lighthouse/ page. 

hows that sound?

**Comment by ebidel** [comment]
3. link to icanbeyourlighthouse.firebaseapp.com 😆

**Comment by kaycebasques** [comment]
SGTM

I have some plans to rework that page into a proper Overview. Overviews just cover what the product is, what it's used for, maybe some stats on other people that are using LH and how it's helping. The installation instructions would be moved to a Get Started doc. We can link to the Get Started doc at the top and bottom of the Overview

**Comment by ebidel** [comment]
Made these updates in https://github.com/google/WebFundamentals/pull/4059. That should be merged in and available next week.
