### ISSUE TITLE
Align load-fast-enough-for-pwa with Core Web Vitals?

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#10943]
**Summary**

"Fast enough" is determined by TTI: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/load-fast-enough-for-pwa.js#L22

Seems like this should be based off of CWV thresholds?

**Comment by paulirish** [comment]
We could also align with the TWA criteria of perf score 80: https://blog.chromium.org/2019/02/introducing-trusted-web-activity-for.html

**Comment by paulirish** [comment]
Options:

1. Leave it on TTI
1. Drop hard perf criteria entirely
1. Move from metrics to non-variable numbers (count of renderblocking bytes or w/e)
1. Use some combo of LCP/CLS/TBT with thresholds
1. Use perf score threshold

**Comment by cheneytsai** [comment]
Couple of thoughts but agree to raise with larger group:
1. Leave it on TTI - (Not preferable) - It's not the highest weighted metric in the Speed Score, so it seems unaligned
2. Drop hard perf criteria - This seems cleaner and simpler to me (if you keep reliability around offline out). It keeps PWA about capabilities. Any system that wants to gate on LH score can just have 2 requirements: Speed > XX and has PWA badge instead of double counting speed. 
3. Move to non-variable numbers - Unclear if we have a good suggestion here, and it's one step removed from reflecting user experience
4/5. Combo with CWV or Perf Score threshold - Makes sense to me for better alignment though I think what thresholds are important. 80/100 LH would be a bit high for even being considered a PWA

**Comment by demianrenzulli** [comment]
Just wanted to add to Cheney's thoughts, that after working with several partners on PWAs, the bullet that they keep failing all the time is the performance one (TTI).

I think the problem with keeping that metric is that: (1) it has more variance than others, which can make the test show as pass/failed alternatively even during the same day (2) it's harder to improve than others, which makes it less actionable.

As a result companies end  up staying in a non-PWA state endlessly (specially those which business models that depend heavily on things  like ads / 3rd party scripts).

**Comment by paulirish** [comment]
We're steering towards removing the perf audit from the PWA category. Next action was on @b1tr0t.

On the Lighthouse side we'll have to figure out what we'll do with the "fast and reliable" group.
