### ISSUE TITLE
document.write() audit may be too strict

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#1098]
The Chrome intervention against `document.write()` is specifically against dynamically-injected, render-blocking scripts. But the Lighthouse audit calls out all uses of `document.write()`.

**Comment by ebidel** [comment]
I'd have to look at the message chrome shows, but I suspect these may be one and the same.

`document.write('<script>...</script>');` is "dynamically injected" and rendering blocking. That's what the audit cover.

**Comment by ebidel** [comment]
@kaycebasques I think we can close this. Right now, LH is specifically warning on all uses of `document.write` because we want to discourage using that API. It's ok if Chrome's intervention is slightly different. In the future, we'll have an audit that shows intervention warnings sent to the console (similar to the new deprecations audit.)
