### ISSUE TITLE
Lighthouse for use with other chrome extensions

### ISSUE THREAD

**Issue by sauren-khosla** [GoogleChrome/lighthouse#11030]
**Feature request summary**
From what I've gathered, Lighthouse is restricted from performing audits on other Google Chrome extensions -- it'd be incredibly useful if this was not the case! This would obviously not be a trivial change, but monitoring the performance of other Chrome extensions I think would be useful to developers (easier to find out inefficiencies) and users (access to more efficient extensions) alike. 

**What is the motivation or use case for changing this?**
Most extensions, and, in particular, the top extensions (Grammarly, AdBlocker, Honey, OneTab, etc.) are always looking to increase performance, similar to all other forms of web development. It'd be great to be able to use Lighthouse during the development and performance-enhancement of those extensions & more.

**How is this beneficial to Lighthouse?**
Expand the user base & open up opportunities to work alongside other chrome extension groups!

If I'm incorrect (Lighthouse is already capable of chrome extension audits), if you could point me towards some documentation that would be great. Thank you!

**Comment by patrickhulce** [comment]
Thanks for filing @sauren-khosla! You can already measure the impact of a Chrome extension's content scripts by running Lighthouse in DevTools on a page where they'll be injected.

This is so commonly done accidentally we even put a warning into the report if we noticed lots of Chrome extension activity :) 

The other place I'm assuming you might want to audit is the popup page. A lot of Lighthouse advice won't be as relevant to the popup since it's likely hosted locally without any network trips, but it can be audited for the other category advice if it's hosted on a regular http URL during development.

**Comment by sauren-khosla** [comment]
Amazing, @patrickhulce -- thank you for the quick response!
