### ISSUE TITLE
CLS and web fonts: a missing exception to accommodate intent?

### ISSUE THREAD

**Issue by andy-feldman** [GoogleChrome/lighthouse#11054]
It goes without saying that no single metric can be over-generalized to ubiquitously work well in every single UI/UX experience and their elements.  In this particular circumstance, it seems like the fundamental nature in the use of web fonts may be needlessly increasing CLS.

Let's assume you have a large `<div>` containing a phrase in large size font.  Does Lighthouse 6.0 go by the Layout Shift Regions highlighting algorithm when adding up the CLS?  The reason I'm asking is because I noticed that during throttled network and CPU, while following the recommendation of displaying a substitute font until the web font loads, the text line-height itself for the entire phrase gets highlighted as a layout shift when the web font loads in its place.  The end result does not affect layout shift for the page as a whole much at all -- (or if at all), and the intent of the `<div>` remains the same: to either simply display text or have some hyperlinked text (or the entire element may be clickable/"tappable").

If text shifts around ever so slightly due to a web font loading in its place, while the clickable/"tappable" zones remain more or less the same, then it would be a disservice to rack up a high CLS score.  The only recourse to avoid CLS in this circumstance could be one of the following:

1.  Avoid using web fonts and stick to system fonts only -- wait, what?!
2.  Avoid using display swap for web font loading and go against this widely-encouraged principle.
3.  Start throwing up placeholders everywhere until web fonts have loaded, à la Google's web font loader from the olden days.
4.  Modify how Lighthouse treats layout shift with fonts based on containing elements and shifting of any user-interactive zones?

For instance, if the width of the phrase "How are you doing today?" becomes 10 pixels wider once a web font loads, while the rest of the page remains static and nothing affects any possible user interaction within that phrase or its containing element (if any are in place), then an exception should be in place to ignore this type of layout shift.

**Comment by patrickhulce** [comment]
Thanks for filing @andy-feldman! Since this is about how layout instability events are emitted by the browser rather than a specific Lighthouse issue with them, you might find more success in the https://github.com/WICG/layout-instability issue tracker. 

Lighthouse will end up observing whatever decision is reached by browser vendors with respect to when layout shift events are issued. 

As for the impact of this and what to do about it, CLS takes into consideration the amount of movement, so the goal for both optimal user experience and minimal CLS is to find a font that shifts the content as little as possible.

https://meowni.ca/font-style-matcher/ is super helpful here and https://www.zachleat.com/web/comprehensive-webfonts/ is a great article (if a bit dated) on some tradeoffs of other strategies to prevent the FOUT.
