### ISSUE TITLE
Score computation is off

### ISSUE THREAD

**Issue by amedina** [GoogleChrome/lighthouse#1110]
Two lighthouse runs: one on Google-A, the other on GIN-3G; both yield the same score. In the attached snapshots you can see the metrics that vary across both runs and the score given to each run. 

![lh-gin3g](https://cloud.githubusercontent.com/assets/506089/20897645/08efb400-bad8-11e6-9090-ff257f1f1b99.png)
![lh-googlea](https://cloud.githubusercontent.com/assets/506089/20897646/08f3736a-bad8-11e6-905d-978d898987d8.png)

**Comment by patrickhulce** [comment]
so for this the score computation itself is functioning as expected (since the first run actually got a 99 for Input Latency the averages are pretty close), but I think this highlights the more important point that average probably isn't the best metric to use and something more aggressive with some weighting might make more sense.

**Comment by brendankenny** [comment]
closing because it looks like the numbers are actually (if counterintuitively) correct.

#746 is probably our master "fix scoring" issue for those that want to follow and/or contribute
