### ISSUE TITLE
Make full-page-screenshot resistant to layout shifts

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#11118]
ref https://github.com/GoogleChrome/lighthouse/pull/10716#issuecomment-657904592

Possible fixes:

* somehow iterate all the elements we gathered w/ bounding rects and do a last-call on their position
* there's more in that comment but I don't think they are a full solution

wip branch: `resolve-nodes`

**Comment by paulirish** [comment]
> Possible fixes:
> [...]
> there's more in that comment but I don't think they are a full solution

hah yeah from the comment I mentioned the 3 below items

1. disabling JS
   - we've since looked into this. it almost seems to work. we do a `await driver.sendCommand('Emulation.setScriptExecutionDisabled', {value: true});` on either side of `GatherRunner.afterPass`.. Setting this means the page cannot run JS however our `evaluateAsync` is immune to that.. However a setTimeout within evaluateAsync will be a problem and unfortunately axe has some (though they're only for splitting up long tasks. lol).  
   - we could work around that. but would we still have perfect positions? it's not guaranteed, though mostly edge cases.
1. keeping the full-size screenshot viewport applied while the elem dimensions are being collected. 
   - this is what connor is currently investigating.  
1. The ["pause page activity" effort](https://bugs.chromium.org/p/chromium/issues/detail?id=1076633) from dgozman is also relevant.
   - relevant but on hold. no news there.
