### ISSUE TITLE
Add choice of emulation device with ranging capabilities

### ISSUE THREAD

**Issue by IanLunn** [GoogleChrome/lighthouse#11112]
With the release of Lighthouse 6.1, the TBT metric greatly penalizes use of JavaScript for mobile tests. It seems many websites using a moderate amount of JS, such as a Gatsby website, will potentially get 0 points for TBT. Given that TBT accounts for 25 points, the best possible score in mobile testing is 75. 

The above maybe deserves its own discussion (is TBT given too much weight for example?) however, that's not my intention in this issue. I instead give this example as one scenario that is difficult to explain to bosses and clients. It's not immediately clear that the mobile testing is only carried out on a mid-tier device. It's true that TBT may be 2000ms on a mid-tier device but does that device represent the userbase for a given website?

My suggestion is that Lighthouse have the ability to emulate a range of devices at different tiers of ability and make this information far clearer in the report. If I tell a client their website scores 75 on a Moto G4, there next question may be what does it score on the latest iPhone? As far as I am aware, we can't yet answer this.

**Comment by patrickhulce** [comment]
Thanks for filing @IanLunn! We've tossed around this idea in the past of presenting multiple performance profiles in a single report, though often about heading the *opposite* direction ;)

> but does that device represent the userbase for a given website

Part of the point of improving performance is making the site accessible to users who can't use your site right now because of how slow it is on their device. Showing how fast a site could be when loading on the fastest ideal network and fastest ideal device doesn't really have much value when everything will be pretty fast. Surfacing what happens when we deviate just *a little* from the happiest path is where things get interesting.

> It seems many websites using a moderate amount of JS, such as a Gatsby website, will potentially get 0 points for TBT

I think it's worth noting that it's not as if all sites using JS automatically get a 0 score for TBT and that the metric is a direct reflection of how well the site manages their JS execution. A site could spend 20s executing JavaScript and still get 0ms TBT if the work were broken up into smaller chunks. Some frameworks make this difficult today but features like [concurrent mode](https://reactjs.org/docs/concurrent-mode-intro.html) in React promise to make this far more accessible. Tracking TBT in this way helps measure the true user impact of excellent perf improvements like concurrent mode (and the sad state of *current* affairs for many sites) :)

**Comment by devdpontes** [comment]
I have the same probably at my company. 99.9% of our user base is on high end devices, all iPhones and Samsungs. How realistic is the simulated slow 3G network in real life in the UK? It's actually a pointless test for us, but what worries me more is the potential impact that has with search results, when it's not relevant to our users.

It does feel like, regardless of how optimised your code is, if it relies on JavaScript, you're going to be penalised from the get go. Suddenly, a test that had a consistent score above 90 is now always lower than 70. This is factoring a Total Blocking Time of 110ms and Cumulative Layout Shift of 0. It doesn't look like a fair test, imo.
 
> Part of the point of improving performance is making the site accessible to users who can't use your site right now because of how slow it is on their device
I get this point, but we do know how many people access our website in those conditions, +-0.1%. The amount of resources or technical challenges to account for those 0.1% are simply not worth it for us as a business.

I don't know the weight of these scores on search results rankings, but trying to create silver bullet rules for every product out there looks like a slippery slope. Should we also be penalised if we don't offer support for older browser versions? Some people out there still use them.

**Comment by connorjclark** [comment]
> I have the same probably at my company. 99.9% of our user base is on high end devices, all iPhones and Samsungs. How realistic is the simulated slow 3G network in real life in the UK?

I have many points to share on this:

* As Patrick noted, there are potentially people that aren't in your user base _because_ the site is not performant enough on their lower class device or network. It's not a fair conclusion to only look at your current user base to determine if performance is worth the effort: this is something that by-and-large improves the UX of and retainment of people _not already in your userbase_
* Most relevant to you: Lighthouse is just a tool, you can configure your own network or CPU throttling. You could also use the desktop configuration for a default closer to a home office setup. How you run Lighthouse is the only thing that matters. We just provide opinionated defaults.
* We (Lighthouse) purposefully choose a slower device preset as the default because it reflects our ideals for the web (caveat: this is just my take): Sites should be accessible no matter the fanciness of a user's device or the amount of money spent on an internet package. Even ignoring the privilege that comes with being able to afford those things, the web should still be usable and enjoyable when you're on-the-go and don't have access to all the bells and whistles of gigabit connection speeds. Using the highest performing device as the benchmark doesn't enable these things. But progress can be made when you lower the capabilities of your benchmark device. This helps identify choke points in performance, allowing developers to make more impactful changes, and opens up the web to more people–and to the same people in more environments.
* I'm in a big city in the US, probably with similar internet speeds as your main userbase in the UK. For the past couple weeks I've been forced to mainly use my phone's data hotspot for all my web activity. It's pretty clear to me which sites don't take performance seriously. There's at least one web store I gave up on due to this, even though I had the exact URL of the product I wished to purchase.

> It's actually a pointless test for us, but what worries me more is the potential impact that has with search results, when it's not relevant to our users.

Lighthouse is a lab tool made for developers. Do you have a source that says Lighthouse scores impact search ranking? :)

> It does feel like, regardless of how optimised your code is, if it relies on JavaScript, you're going to be penalised from the get go. 

As Patrick explain, this isn't true. Lots of JS can be on the page without impacting TBT, as long as it is scheduled in small chunks. Optimized code _does_ result in better TBT. The problem is relying on tons of JS to be executed in one big swath: that's when user input becomes a secondary concern to the browser, UX suffers on slower device profiles. This is what TBT captures.

**Comment by patrickhulce** [comment]
In addition to @connorjclark 's great points, I just want to add that the number of people experiencing conditions like Lighthouse's is far greater than 0.1%. Last data that was public from Chromium, I believe roughly 50% of users *that had fast devices and connections* still experienced 85th percentile conditions (like Lighthouse's) on a weekly basis and ~20% on a *daily* basis. Think of all the times your phone is moving between cell towers, on low battery so the CPU is being throttled by the OS, getting off the subway, etc. Just because your current user base has fast devices and networks doesn't mean they always get the full advantages of a stationary target with full battery. 

Also, unlike browser compat (where fixing old IE issues doesn't also make your site better on newer browsers), improving performance on a lower end device improves performance *for everyone*, people with the latest iPhone included ;)

**Comment by devdpontes** [comment]
> Lighthouse is a lab tool made for developers. Do you have a source that says Lighthouse scores impact search ranking? :)
I'm not saying it does, but there are lot of articles saying it does. Also, https://webmasters.googleblog.com/2018/01/using-page-speed-in-mobile-search.html

What a slow page means is hard to know from that article. But if it doesn't have any impact, why is this included in audit tools like Google Search Console or PageSpeed Insights in a way that highlights to stakeholders poor performance based on the same metrics? It's a bit misleading, imo. Like I wrote before, I'm unaware of the actual impact, if any, on discoverability. the signals are mixed across the web.

The 0.1% is applicable to our experience. As you know, and please correct me if I'm wrong, GA will run regardless of the amount of JavaScript or anything else on the page, or how long users wait for the page to load, so we know who's hitting it.

In terms of browser compat, I could argue that supporting all browsers could make my site accessible to everyone, and not just people on newer devices with Chrome latest versions. It's the difference between it works but it's slow, and it doesn't work at all.

I completely understand your arguments from a global perspective, but if our business is focused on UK users, we're being told that we have to account for the rest of the world.

Anyway, thanks for your replies, I still appreciate your hard work on this tool.

**Comment by patrickhulce** [comment]
> The 0.1% is applicable to our experience. As you know, and please correct me if I'm wrong, GA will run regardless of the amount of JavaScript or anything else on the page, or how long users wait for the page to load, so we know who's hitting it.

Not 100% true, but let's set that aside for a second because it's missing the point behind my statement. GA can only report facts that are accessible via JS web APIs, which are super coarse (phone model, super generic and practically useless network classification). Chromium obviously has much deeper access to network-level statistics and phone *in the moment* performance. The figures I was reporting to you was Chromium data that for a user that visits your site on a fancy brand new iPhone and "4G" connection type, the actual observed performance statistics are much worse. It is not possible to observe what I was referring to in GA.

Returning to not 100%, GA will only report data for loads that make it so far as to download the GA script, execute its payload, and fire its tracking pixels. For a site that's built without performance in mind, that can easily be ~10-20s in on some connections long after abandonment has already set in. Those users are invisible to Google Analytics. Abandonment is a common pitfall of RUM where sites that are *so bad* that users give up actually appear to be faster than sites that are extremely fast.

> In terms of browser compat, I could argue that supporting all browsers could make my site accessible to everyone, and not just people on newer devices with Chrome latest versions. It's the difference between it works but it's slow, and it doesn't work at all.

I certainly don't mean to advocate for abandoning web compat :) I'm just explaining why performance is applicable to a much larger percentage of potential users, no matter how niche the site, than the 0.1% GA has misled some to believe.

**Comment by connorjclark** [comment]
Addressing the initial ask here: via our CLI we have all the knobs a user might want to turn. More advanced users that for some reason don't want to use the CLI can instead use a tool like Webpage Test (which, incidentally also has network packet shaping which is far better than DevTool's observed throttling mechanism). Point is, lots of ability to fine tune to other standards.

For the reasons described above, we want to stick to the mid-tier device being "the mobile device" in our various channels (devtools, PSI, `--preset=mobile`, etc.)

> what does it score on the latest iPhone? As far as I am aware, we can't yet answer this.

Gotta go to Crux for this specific query anyway, until the day iOS allows Chrome rendering engine...
