### ISSUE TITLE
Lighthouse is taunting me.  Click here to learn more.

### ISSUE THREAD

**Issue by Sarke** [GoogleChrome/lighthouse#11203]
**Summary**

Lighthouse is taunting me.

![Learn More](https://user-images.githubusercontent.com/2719310/89113374-25b94a00-d425-11ea-8b8d-9de9bc248d78.png)

**Comment by patrickhulce** [comment]
![image](https://user-images.githubusercontent.com/2301202/89114894-c4a26e00-d446-11ea-9ebc-a86b902bbb89.png)

😉 

Per https://github.com/GoogleChrome/lighthouse/issues/5349#issuecomment-505668026 if you have specific suggestions for how to improve the a11y experience here, we'd welcome comments over there, but otherwise we're fine with the SEO implications of something not intended to be indexed at all :)


Ref #5349 https://github.com/GoogleChrome/lighthouse/issues/4494#issuecomment-388097162

**Comment by BogdanCerovac** [comment]
@patrickhulce  - I think this is actually an accessibility issue for the Lighthouse report (ref. to https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-refs.html (link text that identifies the purpose of the link without needing additional context)).

I believe we must also make Lighthouse reports accessible, so that the reports will be assistive technology users friendly too (links are an frequently used navigation option for a screen-reader for example, so hearing "Read more" for all helping resources in the report is not very useful.)

My suggestion is that each and every "read more" (throughout Lighthouse reports) is replaced with a text that has a meaning (also outside context). I am not a native English speaker, so maybe it is better that somebody who is make the corrections, but I would for example write : "Learn more about how descriptive links help search engines to understand your content" (or maybe something a bit shorter).

**Comment by patrickhulce** [comment]
@BogdanCerovac we agree.

> Per #5349 (comment) if you have specific suggestions for how to improve the a11y experience here, we'd welcome comments over there

This is exactly what was meant to encourage suggestions to improve the text for *a11y* reasons. We just don't care about it from an SEO perspective. 

Either way we're going to try to coalesce conversation in one place not in new duplicate issues. Even if the original is currently closed.
