### ISSUE TITLE
a11y: off-screen contrast ratio report

### ISSUE THREAD

**Issue by peterpeterparker** [GoogleChrome/lighthouse#11280]
#### Provide the steps to reproduce
1. Run LH on https://deckdeckgo.com
  
#### What is the current behavior?

LH is reporting contrast ratio issues for text finding place off-screen but having a valid contrast ratio according the Chrome debugger.

#### What is the expected behavior?

Not contrast ratio error on such elements.

#### Environment Information
* Affected Channels: Both CLI (v6.2.0) as in Chrome v84

#### Screenshots

<img width="1186" alt="Capture d’écran 2020-08-17 à 21 45 09" src="https://user-images.githubusercontent.com/16886711/90437811-40511b80-e0d3-11ea-9cfa-cb39fd5ad669.png">
<img width="1186" alt="Capture d’écran 2020-08-17 à 21 45 17" src="https://user-images.githubusercontent.com/16886711/90437820-45ae6600-e0d3-11ea-8bad-fa9c3e62f9b1.png">
<img width="1186" alt="Capture d’écran 2020-08-17 à 21 45 28" src="https://user-images.githubusercontent.com/16886711/90437822-4646fc80-e0d3-11ea-95a9-3eaf9180f75d.png">

**Comment by patrickhulce** [comment]
Thanks for filing @peterpeterparker! I can reproduce this with Lighthouse but not axe-core alone so it's something we'll need to look into.

**Comment by peterpeterparker** [comment]
Thank you for the feedback @patrickhulce. Let me know if you need more information.

**Comment by adamraine** [comment]
@patrickhulce What method did you use to test the page with just axe-core. The axe chrome extension results back up the results in the Lighthouse report even though devtools reports contrast as good.

<img width="1784" alt="Screen Shot 2020-09-18 at 11 41 19 AM" src="https://user-images.githubusercontent.com/6752989/93617608-30fc1100-f9a4-11ea-9085-7872f7271c0a.png">

**Comment by peterpeterparker** [comment]
Can confirm I still notice it with Chrome v85.0.4183.102

Fresh screenshot:

<img width="1128" alt="Capture d’écran 2020-09-18 à 19 08 17" src="https://user-images.githubusercontent.com/16886711/93625537-67f11780-f9e2-11ea-8c5e-843208cc77f2.png">

**Comment by adamraine** [comment]
@peterpeterparker are you running Lighthouse on the mobile or desktop site?

On the mobile site, it appears some of the text elements are getting dimmed when they are out of view which might be causing axe to throw a contrast violation:

When brought into view normally vs being focused using devtools:
<img width="369" alt="Screen Shot 2020-09-18 at 1 10 52 PM" src="https://user-images.githubusercontent.com/6752989/93626581-9efb0500-f9b1-11ea-973a-ee2b8cd062d9.png"><img width="369" alt="Screen Shot 2020-09-18 at 1 10 39 PM" src="https://user-images.githubusercontent.com/6752989/93626588-a4584f80-f9b1-11ea-9617-23bce9b04ca4.png">

**Comment by peterpeterparker** [comment]
Indeed I run lighthouse on desktop.

Note that the fact that the elements are dimmed outside view on mobile is also correct (these are dimmed when outside view /  window to apply a fade effect on transition from a slide to another).

**Comment by adamraine** [comment]
When you say you are running on desktop, do you mean you are testing from a desktop computer or you have set Lighthouse to test the desktop site instead of the mobile site?

Lighthouse will test the mobile site by default and to test the desktop site you need to select the "Desktop" radio button before running Lighthouse. It looks like you have Lighthouse set to test the mobile site in one of your screenshots (third picture in first comment):
<img width="419" alt="Screen Shot 2020-09-18 at 3 51 55 PM" src="https://user-images.githubusercontent.com/6752989/93639372-e344d000-f9c6-11ea-9cf7-831c2c594319.png">


I just want to confirm since I am unable to replicate this for the desktop site but I can replicate it for the mobile site.

**Comment by peterpeterparker** [comment]
you  are right, sorry @adamraine for mixing the information or not being precise enough

I run lighthouse in Chrome v85 on Mac desktop with the default settings aka "test the device mode"

<img width="1128" alt="Capture d’écran 2020-09-18 à 22 12 28" src="https://user-images.githubusercontent.com/16886711/93641214-35541880-f9fc-11ea-962e-7ec36d9f5212.png">

**Comment by peterpeterparker** [comment]
note: if that would ease the debugging, I can set up our website to behaves the same way on desktop as on mobile, that would be a quick setting

**Comment by adamraine** [comment]
> you are right, sorry @adamraine for mixing the information or not being precise enough

It's no problem, I should have clarified the question better the first time :)

> I can set up our website to behaves the same way on desktop as on mobile

Changing the deployed website shouldn't be necessary. You can just pull up a test build of the site with the fade transition disabled, then run Lighthouse on that. The results for the color contrast audit on the mobile site should now match the desktop site results.

Regardless, I'm pretty sure I understand the issue. Axe is flagging off screen text because of the dimming effect even though the dimming is removed when the text is in view.

You could file this as an issue under [axe-core](https://github.com/dequelabs/axe-core), but accounting for this specific case might be complicated. Either way, I don't think this is an issue with Lighthouse.

**Comment by peterpeterparker** [comment]
Giving the fact that it is probably not a lighthouse issue and also probably too complicated, or not worth, to be fixed, as it is kind of an edge and marginal case, I will try to find a solution on my side aka not use these dimming effects for mobile website and apply another style. I can, and probably our users too, live with that.

Therefore, I close this issue.

Thank you a lot for all your time and help @adamraine and @patrickhulce !
