### ISSUE TITLE
Seeing lot of variance in lighthouse metrics while using through node modules

### ISSUE THREAD

**Issue by alapoojitha** [GoogleChrome/lighthouse#11360]
#### Provide the steps to reproduce

1. Run LH on <https://www.lowes.com/>
2. **Config:**
- chromeFlags: ["--headless"],
- onlyCategories: ["performance", "pwa"],
- emulatedFormFactor: 'desktop',
- throttlingMethod: 'simulate'

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/43389439/91866333-6680ca80-ec40-11ea-92f3-e533c99f441b.png)

#### What is the expected behavior?
I would expect the metrics to be more consistent. In the snapshot I uploaded above, we can see there is a difference of 2-3 seconds in TTI between the runs and similar behavior with other metrics too which is not acceptable.

#### Environment Information. 
* Lighthouse version: 6.3.0
* Chrome version: 0.12.0
* Node.js version: 12.18.3
* Operating System: MacOS 10.14.6: Mojave

**Related issues**

**Comment by patrickhulce** [comment]
I hate to be the bearer of bad news but this is definitely well within the expectation for variance, *especially* on live production sites. If you consider this level of variability unacceptable, have you taken every mitigation in the [variability guide](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md)? Even then 2-3+s on TTI is still going to happen due to the nature of its implementation (a 1ms task difference can result in a 20s difference in the metric).
