### ISSUE TITLE
More neutral helpText for "Best Practices"

### ISSUE THREAD

**Issue by seejamescode** [GoogleChrome/lighthouse#1140]
After receiving the red X icon for using `Date.now()`, I spent five minutes trying to find more documentation on how to replace my use case with `performance.now()`. In the end, I found #1017 assuring me that I had a proper use case for `Date.now()`.

The text was also the following:
```
Consider using performance.now(), which has better precision than Date.now() and always increases at a constant rate, independent of the system clock.
```

Has there been a relevant issue about creating a neutral icon and more "questioning if you need Date.now()" text? The current messaging seems confident that it knows your use case is valid for `performance.now()`.

**Comment by ebidel** [comment]
It's a fair point. As you've discovered, we've started to move some of these "best practices" to a new section called "Fancier stuff":

<img width="1162" alt="screen shot 2016-12-10 at 9 42 07 pm" src="https://cloud.githubusercontent.com/assets/238208/21078375/8f147f1e-bf21-11e6-8bff-b292986c5244.png">

Hopefully, that will make things more obvious that these are not well established  BPs (yet), but more suggestions.

I think finding another icon might be a good idea. It's also worth noting that the best practices and fancier section don't contribute to a score....so it's less of a bad thing if you see more red x's down there :)

**Comment by seejamescode** [comment]
For sure. I am thinking of wordage that would convey that the warning is not an absolute. Perhaps:

`
If you are measuring time elapsed since the start of navigation, consider using performance.now(). This has better precision than Date.now() and always increases at a constant rate, independent of the system clock.
`

The [warning icon](https://material.io/icons/#ic_warning) from Material would also be great for it.

Let me know if you are comfortable with a PR for this. Otherwise, I understand closing it.

**Comment by ebidel** [comment]
cc @kaycebasques  for the wording. `performance.now()` is also useful for cases where you just want a timestamp to compare against, which is why we're suggesting it instead of `Date.now()`. I think what the description needs to capture is that `performance.now()` gives you better precision, should be used if you need to diff two timestamps (e.g. record a start and stop time for metrics), always increases at a constant rate (independent of the system clock).

For icons, I've opened https://github.com/GoogleChrome/lighthouse/issues/1146 discuss / PR against.

**Comment by ebidel** [comment]
We've removed this audit from the default run. Closing old issues.
