### ISSUE TITLE
Does not provide a valid apple-touch-icon

### ISSUE THREAD

**Issue by GlenKPeterson** [GoogleChrome/lighthouse#11458]
The Apple documentation says:

> "To specify an icon for the entire website (every page on the website), place an icon file in PNG format in the root document folder called apple-touch-icon.png"
> https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

Why do I then also have to add `<link rel="apple-touch-icon" href="/apple-touch-icon.png">` to my home screen?

I like that Apple follows the "convention-over-configuration" rule here.  Also, I'm always looking for ways to specify less in my HTML, JSON, and JS files for speed.

Thank you very much for Lighthouse!  I love tools that let me pass tests to ensure compatibility!  Lighthouse, mail-tester, ssl-labs.  These are all great tools!

**Comment by connorjclark** [comment]
Hi @GlenKPeterson, I suggest filing this as a discussion/bug in https://bugs.webkit.org/ 

ref https://github.com/GoogleChrome/lighthouse/issues/7890

**Comment by jespertheend** [comment]
From what I understand you are not required to add `<link rel="apple-touch-icon" href="/apple-touch-icon.png">`. This is only useful if you want an icon for a specific page. If you don't add it to your html, iOS will happily take the `apple-touch-icon.png` from your root.

In my opinion lighthouse should not show a warning/error if your page contains an icon in the root.

**Comment by GlenKPeterson** [comment]
Oh, I get it now @connorjclark, You're saying that Apple's IOS doesn't follow Apple's own spec.  That until it does, you're reporting this issue to PWA developers.  That wasn't clear to me from the info given around this error message.  Maybe updating that info is the only change that needs to be made here?

**Comment by GlenKPeterson** [comment]
Ahh, so @jespertheend is saying that Apple has fixed this bug?  So that Lighthouse can remove reliance on the meta tag if the apple-touch-icon is in the right place?  I bet it would be really useful to know which versions of iOS have this apple bug and which ones have it fixed!

**Comment by jespertheend** [comment]
I'm not aware of any bug in iOS. As far as I know iOS has always looked for an `apple-touch-icon.png` in the root dir of a server when no tag was specified.

**Comment by connorjclark** [comment]
Thanks @GlenKPeterson & @jespertheend for explaining, I didn't fully understand the issue before.

We need to discuss if we think it worth it to make an additional request for every run for this resource (or; the resource as defined in the HTML, if the page doesn't want to use the default) just for ios PWA. We may otherwise decide to move this audit to "manual", which means we do nothing but list it as a thing that exists.

**Comment by jespertheend** [comment]
Manual sounds good enough for me, an extra request would be nice to have though.
It felt weird to see an error for something that I was pretty sure I had done correctly.

**Comment by paulirish** [comment]
For correctness, I think we do have to end up making the request. People who do it this way are saving some HTML bytes and that's nice.

**Comment by keganlance** [comment]
We only have to make the request when it's not listed as meta tag in the head.

Keep in mind the apple-touch-icon meta tag can also be injected using JS and apple will pick it up and use it.

In any case, doing this request is very welcome as to provide the best experience on each device, there are 20 icons to include, which would otherwise have to all be defined in the html, since apple prefers the meta tag over files it finds with requests. This is the full list:
apple-touch-icon.png
apple-touch-icon-57x57-precomposed.png
apple-touch-icon-57x57.png
apple-touch-icon-60x60-precomposed.png
apple-touch-icon-60x60.png
apple-touch-icon-72x72-precomposed.png
apple-touch-icon-72x72.png
apple-touch-icon-76x76-precomposed.png
apple-touch-icon-76x76.png
apple-touch-icon-114x114-precomposed.png
apple-touch-icon-114x114.png
apple-touch-icon-120x120-precomposed.png
apple-touch-icon-120x120.png
apple-touch-icon-144x144-precomposed.png
apple-touch-icon-144x144.png
apple-touch-icon-152x152-precomposed.png
apple-touch-icon-152x152.png
apple-touch-icon-180x180-precomposed.png
apple-touch-icon-180x180.png
apple-touch-icon-precomposed.png

So yeah, by doing this we can save 20 metatags.

**Comment by Seirdy** [comment]
Might be worth updating this audit to instead not impact the score, since [Safari 15.4 supports Web App Manifest icons](https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/).

Once older versions of Safari dwindle, the audit can be removed; this will become a proprietary non-essential feature.

**Comment by connorjclark** [comment]
Thanks for sharing the news! Let's go ahead and delete this audit for 10.0, we don't need to waste people's times with this since the compatibility problem will disappear soon.

**Comment by Seirdy** [comment]
On Mon, Mar 21, 2022 at 07:51:35PM -0700, Connor Clark wrote:
>Thanks for sharing the news! Let's go ahead and delete this audit for 10.0, we don't need to waste people's times with this since the compatibility problem will disappear soon.

@connorjclark 10.0 is coming up soon; is this still on track for removal by then? Issue #14064 is about the removal of this audit, but it doesn't seem to have the 10.0 label.
(I'm only asking so I can plan accordingly, not to be pushy)

-- 
Seirdy
