### ISSUE TITLE
SVG icon "is not configured for a custom splash screen"

### ISSUE THREAD

**Issue by GlenKPeterson** [GoogleChrome/lighthouse#11456]
I have a nice SVG icon less than 26KB in size.  The 16x16 PNG looks very slightly better, but it's hard to tell the difference.  The SVG looks at least as good as the PNG at any other size (including arbitrarily large) and never gets fuzzy/jagged when resized by the browser.

I expected this page to explain why I still have to make a 512x512 PNG icon?
https://web.dev/splash-screen/?utm_source=lighthouse&utm_medium=devtools

**Comment by connorjclark** [comment]
I believe Android does not support SVG splash screens. We should confirm and then update the docs with why SVG doesn't suffice.

also found this, kinda related: https://stackoverflow.com/questions/62825490/svg-icon-in-pwa-manifest-json-how-to-set-it-for-all-sizes

**Comment by phoglenix** [comment]
Android does now support SVG splash screens. I suspect it may not have until SVG icons were supported in web apps in early 2020: https://bugs.chromium.org/p/chromium/issues/detail?id=578122
You can check it with the test site listed there: https://fir-skirt.glitch.me/

I think the error message in Lighthouse should be updated to mention SVG in addition to PNG?

**Comment by phoglenix** [comment]
Sorry, I was mistaken: Android does support SVGs for splash screens and "add to homescreen" shortcut app icons, but still does not support SVGs for webAPKs (the generated "real android app" that shows up in your app drawer).
Supporting it in the webAPK generator is an open bug b/145513773 (Googlers only, sorry).

So the warning here / on web.dev is wrong (splash screens work fine), but the advice is still unfortunately correct: you should avoid having only SVG icons because your site won't install properly to the app drawer on Android.

**Comment by adrianaixba** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse will be deprecating the PWA category in the next upcoming release. For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/). Marking this as closed!
