### ISSUE TITLE
site definition option in chrome

### ISSUE THREAD

**Issue by arcarvalho-isq** [GoogleChrome/lighthouse#11541]
**Feature request summary**

site definition option in chrome

Sure

**What is the motivation or use case for changing this?**
Some virtual addresses present 404 response. You have to define the original URL not the presented virtual one.

**How is this beneficial to Lighthouse?**
It expands the evaluation universe for Lighthouse in Chrome.

**Comment by patrickhulce** [comment]
Thanks for filing @arcarvalho-isq! I'm not sure what this is asking.

If you're saying that Chrome DevTools Lighthouse integration should audit a URL other than what you're currently looking at because refreshing the page causes a 404, we would consider that a major bug of the page that a user refresh triggers a 404. 

Nonetheless, #11313 will bring some of this capability in the far off future.

**Comment by arcarvalho-isq** [comment]
Dear all,

Thank you for your swift reply.

Angular URL may redirect the original URL to a virtual one, so it could be interesting to evaluate the original URL not the virtual one.
I can do it by CL but not in the GUI.

Best

**Comment by patrickhulce** [comment]
Got it, thanks! We don't intend on doing anything special to allow this in DevTools outside of #11313. CLI and PSI serve this use case quite well (and even then we warn you that you're auditing the wrong URL...).
