### ISSUE TITLE
Anchors without any children are flagged as uncrawlable (AMP)

### ISSUE THREAD

**Issue by Frenchomatic** [GoogleChrome/lighthouse#11549]
Simple scroll to top button on an amp page. Uses these libraries 

  <script async custom-element="amp-position-observer" src="https://cdn.ampproject.org/v0/amp-position-observer-0.1.js"></script>
  <script async custom-element="amp-animation" src="https://cdn.ampproject.org/v0/amp-animation-0.1.js"></script>

Lighthouse reports a significant SEO error. A 7 point drop saying the link is uncrawlable. Whilst that may be the case, this isn't really a crawlable link in the bad sense but something which enhances usability. I see no reason why it would have any bad effect on SEO.

**Comment by patrickhulce** [comment]
Thanks for filing @Frenchomatic! I can't reproduce this issue you're referring to though. Would you mind providing a public URL that has this problem?

**Comment by Frenchomatic** [comment]
Hi, I removed the offending code. Basically if you have  href="#" you get the drop in SEO score. So on a scroll to top button using amp animation you lose 7 points.

**Comment by patrickhulce** [comment]
This audit won't flag any buttons @Frenchomatic, just anchors. Is this the [AMP scroll to top](https://melodic-class.glitch.me/amp-seo.html) example you're talking about?

If so,  I cannot reproduce. The *anchor where the page scrolls to and **not** the scroll to top button* will be flagged if there's no href and no name though. It's definitely a bit odd to me that AMP would force the use of *id* anchors rather than *named* anchors which are obviously commonplace and allowed under the audit.

Perhaps Lighthouse should skip any anchors which have a name or ID *and* don't have any content or children? There's nothing that could possibly be clicked in that case.

**Comment by paulirish** [comment]
Sounds legit, but we'll wait until there's a real case we can test against and repro.
