### ISSUE TITLE
Remove unused JavaScript - /v0.js(cdn.ampproject.org)

### ISSUE THREAD

**Issue by Frenchomatic** [GoogleChrome/lighthouse#11550]
This is a mandatory bundle as far as I am aware. There is  no choice to unbundle it. In my case I am seeing these errors  / opportunities. I think it is worth talking with the people over in AMP about how to improve Lighthouse support when testing AMP pages. 

…src/service/url-replacements-impl.js | 2.6 KiB | 3 KiB
-- | -- | --
…src/service/history-impl.js | 2.1 KiB | 1.8 KiB
…src/service/resources-impl.js | 4 KiB | 1.7 KiB
…src/custom-element.js | 4 KiB | 1.7 KiB
…src/service/viewport/viewport-impl.js

There are also issues regarding 

Eliminate render-blocking resources

There is no way to avoid this with AMP pages using external fonts. Any <link> to fonts.googleapis.com even using preconnect and display swap still means a considerable drop in the performance score which doesn't really follow real load times. In fact this is almost forcing people to consider using websafe fonts everywhere which will make web design very bland. 

I accept you may have a different opinion here on "reality".

**Comment by patrickhulce** [comment]
Thanks for filing @Frenchomatic! There are many comments in this issue, and I'm not really sure what your expectations are. 

What are the **specific behavioral changes** you'd like to see in Lighthouse?

A few general principles that will probably prevent any action on most of what you're talking about:

1. Lighthouse does not hide audit results just because they come from a specific stack, framework, or entity, regardless of a potential connection with a Google-sponsored project.
2. Performance is reported with [a mobile default](https://github.com/GoogleChrome/lighthouse#why-is-the-performance-score-so-low-it-looks-fine-to-me) that will always reflect the less than ideal conditions of the time.

**Comment by westonruter** [comment]
cf. https://github.com/ampproject/amphtml/issues/28638

**Comment by brendankenny** [comment]
> cf. ampproject/amphtml#28638

From the upstream amp issue it seems like this has been a priority and bundle size has been reduced and will be reduced further in the future.

In addition to what @patrickhulce wrote above, note that the Lighthouse/PSI performance score is _not_ based on recommendations like "remove unused JavaScript" and "eliminate render-blocking resources", they're based only on the metrics listed in the report. The opportunities and diagnostics are suggestions from Lighthouse as to what to look into to improve on those metrics.

It's possible that not everyone will be able to act on all the recommendations, depending on their tech stack, but as Patrick noted, Lighthouse tries to be agnostic and gives advice regardless of what stack is being used.
