### ISSUE TITLE
New audit idea: avoid linking to index.html

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#11607]
**Feature request summary**

@jakearchibald brought to my attention in https://github.com/GoogleChrome/web.dev/pull/4133 that preconnecting to `index.html` is less preferable than `/directory/` (for example). I'm not sure of the scale of this problem. But it's definitely actionable.

Perhaps there's a way to formulate it more generically? I.e. perhaps there are other costs to linking to `index.html`?

**Comment by patrickhulce** [comment]
Thanks for filing @kaycebasques :)

My initial impression is that this is relatively site-dependent and while it's a good fix given our knowledge of web.dev's structure and as a *typical* example, I'm not sure we'd want to extend it as generic "always do this" advice to Lighthouse users. As Jake mentions "there's nothing that requires /foo/ and /foo/index.html to be the same content" and if that's the case we would be telling someone to break prefetch in the process.

Maybe the root behind this is a site-wide suggestion for "clean" URLs rather than `.html`/`.php`/`.urfavoriteext` links? But that feels a little more opinionated than I would expect Lighthouse to be.

We can certainly discuss in our next eng sync though :)

**Comment by paulirish** [comment]
It's gonna be hard to make this generalizable and guarantee it wont break.

I'm really happy with Jake's change to the docs and think that modeling good behavior is the best solution here.
