### ISSUE TITLE
Performance is worse when I add image width & height as per LH recommendations. 

### ISSUE THREAD

**Issue by Th0masP4ttz** [GoogleChrome/lighthouse#11646]
#### Provide the steps to reproduce
1. Run LH on <https://www.legargantua.com/courses/bread_baking_course> 
  

#### What is the current behavior?
Worse performance score

#### What is the expected behavior?
Better performance score

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @Th0masP4ttz !

I'm not able to reproduce this, are you able to provide a before/after set of minimal examples? The only images that have `width`/`height` on that page are lazily loaded offscreen (and don't match the actual dimensions of their source either). The only way we're aware of that adding this can possibly make the score worse is if the attributes were incorrectly applied. 

Correctly used dimension attributes will improve CLS a bit, but the poor CLS value on this page is caused by the flash of unstyled content. I would fix that first before focusing on the unsized images.

**Comment by Th0masP4ttz** [comment]
Brilliant, Thank you.
