### ISSUE TITLE
New redirect warning appeared for bbc.co.uk

### ISSUE THREAD

**Issue by JayneTosh** [GoogleChrome/lighthouse#11681]
We've noticed a new warning appear in the Github lighthouse page when running tests to try and identify our performance issues.

Link to report: https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fwww.bbc.co.uk%2Fnews%2Fhealth-54886286&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext

We recently have been seeing a warning stating:

```
There were issues affecting this run of Lighthouse:

The page may not be loading as expected because your test URL (https://www.bbc.co.uk/news/health-54886286) was redirected to https://www.bbc.com/news/health-54886286. Try testing the second URL directly.
```

that we didn't used to see on the same test page, wondering if something has changed or if it's because the page is hosted internationally (which I imagine is the case)

Querying because it's a new thing we've seen. - We used to have scores in the 40-50 range on this test page.

**Comment by patrickhulce** [comment]
Thanks for filing @JayneTosh!

Lighthouse was in fact recently updated to add the redirect warning to *client-side redirects* so if this page does that, it's expected behavior. Note though, that this did not impact scores in any way, it's just notifying you why scores might be unexpectedly low.

As for the geo part, since it's redirecting from .co.uk to .com I expect this warning will only appear when accessing the site from geos outside of the UK (and wherever the `.com` TLD is preferred).

**Comment by JayneTosh** [comment]
Thanks for the info @patrickhulce ! Will close the issue now.
