### ISSUE TITLE
update-report-fixtures.js shouldn't use a random port

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#11776]
see https://github.com/GoogleChrome/lighthouse/pull/11733#discussion_r537744905

**Comment by brendankenny** [comment]
#11841 is one place where this wasn't just code churn on updating the artifacts, it actually removed valid audit results from `sample_v2.json`. Different ports between the `TagsBlockingFirstPaint` urls and the existing devtoolsLogs meant that no urls matched between the artifact and network records, so suddenly nothing was blocking first paint :)

The fix was to manually change the URLs back to `:10200` and the audit worked again, but it would be nice if it just did that for me :)
