### ISSUE TITLE
Support for User-Agent based rendered apps

### ISSUE THREAD

**Issue by boopathi** [GoogleChrome/lighthouse#118]
Problem with apps that send different responses based on User-Agent.

+ Looks like DevTools and lighthouse(extension) debugger cannot be open at the same time - https://bugs.chromium.org/p/chromium/issues/detail?id=129539 . So device mode emulation with lighthouse extension seems not possible
+ lighthouse uses sendCommand to emulate device mode when opening a url. So you can use lighthouse extension after opening url from a lighthouse cli. But the `app/manifest.json` isn't called with device mode on as it is called in the scope of the extension without device mode on. So user agent check kicks in sends no manifest for desktop. And this fails all the checks depending on manifest.
+ And opening chrome with device mode "on" is also not an option - https://bugs.chromium.org/p/chromium/issues/detail?id=373169&thanks=373169&ts=1400050662 

Any ideas ?

**Comment by brendankenny** [comment]
Hi Boopathi!

Right now lighthouse uses the debugging protocol to always enter device mode emulation when testing. The code for this is in [emulation.js](https://github.com/GoogleChrome/lighthouse/blob/8ada139e574d5e93e352f3af00a66343ef50ac67/helpers/emulation.js) and [called from the driver](https://github.com/GoogleChrome/lighthouse/blob/8ada139e574d5e93e352f3af00a66343ef50ac67/helpers/browser/driver.js#L271). This exact device parameters are hard coded right now, but this could eventually be configurable. @paulirish has probably already been thinking about what we're going to do here.

The manifest fetching issue is going to be fixed by having the page itself fetch the manifest and swiping it from the network traffic. This is tracked in #83

**Comment by paulirish** [comment]
> Looks like DevTools and lighthouse(extension) debugger cannot be open at the same time 

yup that's true.

> So device mode emulation with lighthouse extension seems not possible

it's very possible. so possible that we're already doing it, as brendan pointed out. :) 

really the only problem right now is that the manifest is not fetched by the browser while under emulation. That's a bug in lighthouse, and one that we gotta fix asap. 

As such, I think this issue mostly gets duped into #83.

**Comment by boopathi** [comment]
Thanks.

Correct me if I'm wrong.

The device mode emulation is done when you invoke the extension. So we'd have to reload the app  after device mode is turned on - i.e. when the lighthouse extension is invoked - right ?

Or you'd have to open dev tools, enable device mode emulation, reload/load the app. Close devtools. Use extension.

**Comment by paulirish** [comment]
Ah! good call yeah.

If the content is dependent on the UA, then yeah a reload will be neccessary. Right now extension can't reload the page but that's what's happening in #52.  Take a look on that issue and see if the user flow that makes sense to you.
