### ISSUE TITLE
Images served to web.dev are not always webp but are on browsers to our website

### ISSUE THREAD

**Issue by jamiemil** [GoogleChrome/lighthouse#11817]
Images served in the web browser show webp but seems when on web.dev they are now, so affects our scoring.

<img width="491" alt="Screen Shot 2020-12-10 at 17 54 30" src="https://user-images.githubusercontent.com/30082417/101810672-f91ee880-3b10-11eb-9688-5f41f1e5e5c1.png">

<img width="915" alt="Screen Shot 2020-12-10 at 17 54 40" src="https://user-images.githubusercontent.com/30082417/101810696-fe7c3300-3b10-11eb-8fc6-41cf20fc9ea9.png">

We need to understand why the browser sees images as webp but web.dev does not.

**Comment by robdodson** [comment]
I think this may be a lighthouse issue (which web.dev is using under the hood)

**Comment by patrickhulce** [comment]
Can you share the URL or a minified repro @jamiemil? 

Usually this is because of a user agent sniffing problem where the page is intentionally (but perhaps unknown to the developer 😉 ) serving different content to Lighthouse. Does webp get served when requesting with the Lighthouse UA?

https://github.com/GoogleChrome/lighthouse/blob/5b4b47c9b04c54e9687c2b70251121b072272628/lighthouse-core/lib/emulation.js#L44

**Comment by brendankenny** [comment]
Going to close since there hasn't been any movement on this issue. Please comment if you think there's still a problem here and we can reopen.
