### ISSUE TITLE
gather-runner: can we reduce to just one pass?

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#11822]
Over in https://github.com/GoogleChrome/lighthouse/pull/11806 I'm removing the need for our offlinePass. And we've also removed the `w/o javascript` gatherer.

So in https://github.com/GoogleChrome/lighthouse/pull/11806#discussion_r540339519 @brendankenny proposed we drop down to just 1 pass:

> should `service-worker` move to `redirectPass` and only have two passes? `service-worker` would fail if the site doesn't redirect, but should `http-redirect` move to use `driver.fetcher` anyways?

> and actually, with the new DevTools offline check, which is doing a real request, that means the ServiceWorker has to be activated and controlling the page. Presumably that means `getServiceWorkerVersions`/`getServiceWorkerRegistrations` will return the info, so do we even need a second pass anymore?

We'd move the `'service-worker'` and `'http-redirect'` gatherers to defaultPass and then we're good.

----

Patrick asked "can you request an insecure iframe on a secure page? I assume that would be blocked by mixed content" and noted: "no reason the offline pass needs to exist though"

**Comment by paulirish** [comment]
Adam proposed that `service-worker` audit is removed as the instability errors surfaced in `installable-manifest` audit cover all the data we provide.  Connor, Adam and I looked and it appears we might lose out on being definitive that the starturl isn't within SW scope. But there should still be an error. So we think its fine, given that it's not really LH's role to help you debug all SW things.

**Comment by connorjclark** [comment]
We think we can remove `service-worker` audit and gatherer because `installable-manifest` seems to cover all the same cases well enough. With that, we could then be down to a single pass.

Removing that audit would require waiting for 10.0, but we could still remove the pass sooner if we changed the `service-worker` implementation to use InstallableManifest and try to recreate the audit result.

#11329 added some data which we might have trouble accurately recreating, and may mean we can't outright remove the `service-worker` audit.

**Comment by connorjclark** [comment]
With #13711 turns out we don't need to delete the audit at all, so this is def. not a breaking change.

**Comment by adamraine** [comment]
Passes still exist but only in legacy navigation mode, so this is probably shuffling deck chairs on the titanic at this point.

**Comment by connorjclark** [comment]
Days are numbered for legacy, so let's not waste time on this!
