### ISSUE TITLE
Why is an image that never comes on the viewport reported as LCP?

### ISSUE THREAD

**Issue by AnchalGupta3** [GoogleChrome/lighthouse#11849]
1. Run LH on https://www.oyorooms.com/us/

<img width="1440" alt="Screenshot 2020-12-17 at 5 40 30 PM" src="https://user-images.githubusercontent.com/70004243/102486678-68f01e80-408f-11eb-9516-3c6fec04791c.png">
<img width="1440" alt="Screenshot 2020-12-17 at 5 46 01 PM" src="https://user-images.githubusercontent.com/70004243/102486903-c1272080-408f-11eb-87ad-786f12a9b975.png">
<img width="1440" alt="Screenshot 2020-12-17 at 5 44 02 PM" src="https://user-images.githubusercontent.com/70004243/102486729-7ad1c180-408f-11eb-9d72-69b11c4f51f8.png">

Issues: 
1. The image that is getting reported as LCP, doesn't even come on the viewport. 
2. If the image is getting loaded in 3s, then why is LCP reported at 7.4s

Expected behaviour: 
The search bar should be considered as LCP

**Comment by patrickhulce** [comment]
Thanks for filing @AnchalGupta3!

This is a funny case where the image is in the browser's viewport but not in the site's self-created viewport.

![image](https://user-images.githubusercontent.com/2301202/102504101-07579200-4046-11eb-8d6e-ebbd7006ebba.png)

The search button would likely never be considered for this because LCP defines the size of text nodes as the size of the text itself and not of their container. While it's unfortunate that LCP doesn't flag a more interesting element here (I filed an [upstream issue against the spec](https://github.com/WICG/largest-contentful-paint/issues/70)), Lighthouse is marking LCP correctly.

For your second concern, see the [FAQs](https://github.com/GoogleChrome/lighthouse#why-is-the-performance-score-so-low-it-looks-fine-to-me).
