### ISSUE TITLE
Lighthouse Chrome plugin emulates desktop in mobile tests

### ISSUE THREAD

**Issue by SerialTickler** [GoogleChrome/lighthouse#11873]
This started on Dec, 20. Even though I select "mobile" in devices, it says "Emulated Desktop" in the report. The user agent is:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/85.0.4183.140 Safari/537.36

If I test the same page in Dev tools it the Lighthouse works as intended and emulates Moto G4 with the following UA:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Comment by connorjclark** [comment]
any reason you're stuck on Chrome 85? I think there's nothing for us to do, except encourage you to update Chrome (current stable version is 88, so 85 is ~4.5 months old).

**Comment by connorjclark** [comment]
ok I see PSI is currently on 85 (heh, I'll see about us updating that), is that where you're running into an issue?

**Comment by connorjclark** [comment]
Nevermind, I easily reproduced this with the extension and example.com. Thanks for alerting us!

**Comment by connorjclark** [comment]
[example.com run](https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fwww.example.com%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext)

The config is right:

![image](https://user-images.githubusercontent.com/4071474/102934393-a4149800-4469-11eb-8339-e74fbcdd385c.png)

I suppose this is an artifact of the new v7 renderer not being able to map the old `emulatedFormFactor` (it is now `formFactor`) to the correct UI string. 

https://github.com/GoogleChrome/lighthouse/blob/2bdf6cb4ef9a3a44570af49a13d6667cb72980a9/lighthouse-core/report/html/renderer/util.js#L428

We should add some back-compat here.

@SerialTickler This means that the bug is simply the report showing the wrong text here. The test is still being run as a mobile report.
