### ISSUE TITLE
How can I get just the scores from each category?

### ISSUE THREAD

**Issue by alejomoreno07** [GoogleChrome/lighthouse#11885]
Greetings to the team, 

I'm working with the api, and unfortunately, it takes too long to respond. Is it possible just to get the scores? if so how could I do that?

**Comment by connorjclark** [comment]
no, all the work is needed to get the score...

you can try disabling categories you don't care about, but unless it is the performance/pwa category it won't help

**Comment by alejomoreno07** [comment]
I still wonder if we could decrease the size of the json, if the interest remains in just the scores though. 

For instance, I tried using the five categories and it produced a json with about 11k lines which slows down the time of each response. 

I feel that if it were possible to decrease its size it could boost the api itself, in terms of performance, because now it takes around 30 up to 40 seconds in order to get a response.

**Comment by connorjclark** [comment]
It seems it would have negligible effect on response time. What's the math?

**Comment by paulirish** [comment]
@alejomoreno07 we need all the results of every audit in order to generate the scores. so.. if all you want is the scores.. unfortunately we need to run all audits (and their gatherers). 

yes the JSON is big, but generating it is trivial.

waiting for pageload and gathering take the most time by far. the best way to reduce the lighthouse run time is to use `onlyCategories` or `onlyAudits` to get a subset of things.
