### ISSUE TITLE
Bad evaluation LCP and Best Practices on picture tag

### ISSUE THREAD

**Issue by aladeuil** [GoogleChrome/lighthouse#11895]
On this page (https://www.kortic.com/photographie/skateboard-volant.html) , Lighthouse matches only the src tag and ignores the source tags. So LCP is wrong. It says : 
```
Largest Contentful Paint element 1 element found

Skateboard (volant) <img decoding="async" loading="lazy" src="/images/card/950/643c16e4/skateboard-volant-2.jpg" alt="Skateboard (volant)" aria-labelledby="imgContentInfo" itemprop="contentUrl">
```
Additionnaly, the evaluation of best practice "Serves images with low resolution" is wrong too on the same element : 
Displayed size | Actual size | Expected size
360 x 360 | 420 x 420 | 945 x 945

However, only the "/images/card/420/643c16e4/skateboard-volant-2.jpg" is loaded on mobile.

The original source is : 
```
<picture>
<source media="(max-width: 29.9375rem)" srcset="/images/card/420/643c16e4/skateboard-volant-2.jpg">
<source media="(min-width: 30rem) and (max-width: 63.9375rem)" srcset="/images/card/500/643c16e4/skateboard-volant-2.jpg">
<img decoding="async" loading="lazy" src="/images/card/950/643c16e4/skateboard-volant-2.jpg" alt="Skateboard (volant)" aria-labelledby="imgContentInfo" itemprop="contentUrl">
</picture>
```

**Comment by noyearzero** [comment]
I think I may be having the same or similar issue.  However I think the issue is ultimately a Chrome bug.  I was running some tests trying to optimize images with the picture tag.  I was using px units in my min/max widths so the issue seems more clear.  If you look at the network tab while you hard refresh the page you should still see the issue.  When you try to view desktop chrome like mobile, you can either shrink the window which has a minimum size (for me around 483px), or you can use the mobile view tool in dev tools.  However when you do the mobile tool, it seems like the picture tag media attributes are evaluating based off of the actual window size rather than the fake mobile viewport.  I'm guessing lighthouse taps into this same fake mobile view causing the incorrect images to be pulled.

**Comment by aladeuil** [comment]
Hi @noyearzero 
Thank you for comment, but this issue is related to the online test at this tool [here](https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fwww.kortic.com%2Fphotographie%2Fskateboard-volant.html&strategy=mobile). I prefer it to the console tools, because I don't use Chrome ;-)

**Comment by noyearzero** [comment]
As far as I know, Lighthouse always runs within Chrome ultimately (in this case a version of Chrome on the server for googlechrome.github.io), so whatever bugs are in chrome, will also show up in any LH report.  I could be wrong, so I hope someone can correct me if this isn't the case.  But I believe it's that way because the point of LH testing is to get as close to real-world results as possible.  Also to have someone try and build a browser emulator is probably close to the same amount of work as actually building a browser.

**Comment by aladeuil** [comment]
For my part, I have seen big differences between LightHouse in the console and the online version. In the browser, any extensions disrupt the raw performance of all the sites consulted. Except to test in private browsing and without active extensions. On the other hand, it would be good for Google to change the version of the simulated terminal. A Motorola G4 is not very representative of the current market. :-)

**Comment by noyearzero** [comment]
I see big differences between audits on the same system with the exact same code.   So there are variances based on factors out of the control of web developers.  One of those is network congestion from the server to the client.  So you probably want to ask yourself is the path from www.kortic.com to googlechrome.github.io quite similar to the network path actual users of the site will experience?  Also is the hardware on the googlechrome.github.io service similar to the hardware your real users will be using?  It's possible your real users will be using extensions.  So you might get more consistent scores using the service, but that doesn't necessarily mean they are accurate scores.  The results in the example you showed don't show any network or CPU throttling being done, which can make the results even more unrealistic.  Overall it seems like the test that was done isn't very close to what Googlebot would be judging the site on.... if that matters for this case.  

If you do want more control, I'd recommend setting up the nodejs library for lighthouse.  I bit the bullet and finally did it.  It's nice because you have more control over the environment and audit settings.  You can also automate and standardize a lot of things.  And as long as the server/PC you set it up on is in the same geographic region as your target audience, you should get very close to real-world results.  

On a different note, I did look into the bug I thought might be part of your issue.  I found it only applies to items preloaded with media tags, so I don't think it would affect you in this case.  https://bugs.chromium.org/p/chromium/issues/detail?id=1162287

**Comment by connorjclark** [comment]
I made a minimal repro here: https://misc-hoten.surge.sh/lh-11895-picture-lcp/

> The LCP is wrong ...

The `picture` element actually [_does not work_](https://www.w3schools.com/tags/tag_picture.asp#main:~:text=one%20%3Cimg%3E%20tag.) without an accompanying `img` element. Try removing the `media` attributes + removing the `img` element: you'd expect the first `source` image to be used, but nothing is drawn, because there's to `img`. The `img` element is the container used to draw a `picture`.

Since the LCP element should be the element where the largest content is drawn, identifying the `img` inside `picture` seems to be working as intended. I'll reach out to folks on the Chrome metrics team and confirm if this behavior is intentional.

Some things Lighthouse team should check:

* Should we special-case how we show what the LCP element is for `img` inside `picture`? At least delete the `src` in the snippet, or just point to the `picture` instead?
* Do we directly use the specific node identified as the LCP for further analysis as an `img` element? I see we do in at least one place ([preload-lcp-image](https://github.com/GoogleChrome/lighthouse/blob/0d25b6b34baea44198b588297ccd92216d03e69a/lighthouse-core/audits/preload-lcp-image.js#L98))–is there also something in Lantern?

> Additionnaly, the evaluation of best practice "Serves images with low resolution" is wrong ...

This audit doesn't check if an image element has an associated [network resource](https://github.com/GoogleChrome/lighthouse/blob/0d25b6b34baea44198b588297ccd92216d03e69a/lighthouse-core/audits/image-size-responsive.js#L237). We just assume any image element is fair game to analyze. There is a filter for "is this image in the initial viewport", so I think we can argue that we should also filter out "invisible" img elements (I mean–verify that an image element actually has a network request for its `src`).

Lighthouse team: it seems we want to do a normalization pass when using `artifacts.ImageElements`, to take in account the `picture` behavior. Are there places other than `image-size-responsive` we need to apply this?

**Comment by connorjclark** [comment]
> Should we special-case how we show what the LCP element is for img inside picture? At least delete the src in the snippet, or just point to the picture instead?

We could replace `src` with `el.currentSrc` in the snippet ...

> Do we directly use the specific node identified as the LCP for further analysis as an img element? I see we do in at least one place (preload-lcp-image)–is there also something in Lantern?

We actually use `.currentSrc` when collecting `ImageElements`, so this is not an issue.

---

Looking closer at this:

> Additionnaly, the evaluation of best practice "Serves images with low resolution" ...

Actually, two of these images are loaded when emulating a Moto G4 viewport (which is what LH does). And given what I learned above (we use `.currentSrc`, not `.src`, when analyzing image elements), I don't see an issue here.

![image](https://user-images.githubusercontent.com/4071474/104240370-94152600-5421-11eb-861c-787d14311119.png)

**Comment by connorjclark** [comment]
FWIW, the `url` property in PO.entry.url refers to an img.currentSrc.

**Comment by patrickhulce** [comment]
We have two options here that we can think of:

- Rewrite the snippet to show `picture` instead with some sort of nesting of the img
    - We don't love this because it won't match PO/RUM data anymore
- Rewrite the src attribute of the snippet to use `currentSrc`
    - Downside: snippet won't match the original HTML 
    - But it matches what the actual src is and what developers expect.

We're gonna go with the 2nd one.

**Comment by craigs100** [comment]
Do these changes fix the issue where the Picture element isn't correctly  parsed?
We've just changed all our img tags to picture tags, added srcset nodes of webp images with a fallback img node of a jpg image (for iOS). Lighthouse just sees the img node and marks us down for not providing images in webp format which we do. Very frustrating considering that clients are using Lighthouse to rate their developers.
Is there an estimated time frame when this might be fixed?
Thank you

**Comment by connorjclark** [comment]
If the page is requesting webp for this image, I'd expect Lighthouse to report that correctly (by not saying anything...) in the "use optimized image formats" audit. At least, that seems to be what the code is doing after giving it a quick look. Can you provide an example page where the problem occurs?

**Comment by craigs100** [comment]
Sure: https://www.myerscough.ac.uk/news/

Each picture tag has a webp srcset node, an auto srcset (the native file) node and an img node which is also the native file.  The huge querystrings just drive the image processor for responsive sizing. That's where the format=webp or format=auto live.

Thanks.

**Comment by connorjclark** [comment]
I'm not able to repro:

![image](https://user-images.githubusercontent.com/4071474/106766217-44c8ac80-65ff-11eb-80a5-bf73b92576f1.png)

Initially I thought it might be due to `.png` even though it's webp, but the Content-Type headers are set correctly so the network record mimeType (which is what we check in this audit..) is set as expected.

Chrome 88.0.4324.96
LH 6.4.0
![image](https://user-images.githubusercontent.com/4071474/106766355-6b86e300-65ff-11eb-817d-7504c43b560b.png)

Are you running LH differently?

**Comment by craigs100** [comment]
I'm running it from the chrome Lighthouse extension v100.0.0.0 installed in Brave (Version 1.19.88 Chromium: 88.0.4324.96 (Official Build) (64-bit)) on both Windows 10 and Linux Mint 20.1. The extension says it uses the PSI API (?).

**Comment by aladeuil** [comment]
> > Should we special-case how we show what the LCP element is for img inside picture? At least delete the src in the snippet, or just point to the picture instead?
> 
> We could replace `src` with `el.currentSrc` in the snippet ...
> 
> > Do we directly use the specific node identified as the LCP for further analysis as an img element? I see we do in at least one place (preload-lcp-image)–is there also something in Lantern?
> 
> We actually use `.currentSrc` when collecting `ImageElements`, so this is not an issue.
> 
> Looking closer at this:
> 
> > Additionnaly, the evaluation of best practice "Serves images with low resolution" ...
> 
> Actually, two of these images are loaded when emulating a Moto G4 viewport (which is what LH does). And given what I learned above (we use `.currentSrc`, not `.src`, when analyzing image elements), I don't see an issue here.
> 
> ![image](https://user-images.githubusercontent.com/4071474/104240370-94152600-5421-11eb-861c-787d14311119.png)

They are not the same images :-)
The error I reported only concerns the main image on the page (square image on white background).

**Comment by connorjclark** [comment]
> I'm running it from the chrome Lighthouse extension v100.0.0.0 installed in Brave (Version 1.19.88 Chromium: 88.0.4324.96 (Official Build) (64-bit)) on both Windows 10 and Linux Mint 20.1. The extension says it uses the PSI API (?).

That would be https://developers.google.com/speed/pagespeed/insights/ . In any case, it seems to be a separate issue than this thread, can you file a new issue with the same details?

> If I run it from Chrome Dev Tools I get this, so I never bother:-

Can you try in Incognito? (perhaps a chrome extension is messing up the Lighthouse run)

> They are not the same images :-)

The same conclusions throughout this issue should still apply.

**Comment by craigs100** [comment]
Thanks, wasn't sure if it was this issue or not. Will raise another.

Thanks
