### ISSUE TITLE
First Contentful Paint (FCP) and Largest Contentful Paint (LCP) incorrect values when tested with mobile device

### ISSUE THREAD

**Issue by thanhtoan1196** [GoogleChrome/lighthouse#11909]
#### Provide the steps to reproduce
1. Run LH on https://ngontinh24.com (Mobile Device)
2. Check result
3. Click `View Original Trace` to show `Timings`
  

#### What is the current behavior?

`First Contentful Paint (FCP)` and `Largest Contentful Paint (LCP)` have a big difference between the result and `Original Trace`

![image](https://user-images.githubusercontent.com/16433547/103450059-78a07180-4ce3-11eb-8434-229c016fec69.png)

![image](https://user-images.githubusercontent.com/16433547/103450064-85bd6080-4ce3-11eb-86e3-e0a95e92035c.png)

#### What is the expected behavior?

`First Contentful Paint` and `Largest Contentful Paint` have the similarity between the result and `Original Trace`

#### Environment Information
* Affected Channels: DevTools
* Chrome version: 87.0.4280.88 (Official Build) (x86_64)
* Operating System: MacOS 11.0.1

**Comment by alexd-3d** [comment]
Hi, I', not just a regular Lighthouse user but not long ago was also curious about this. And found out that there's hint you can see when hover over View Trace button. Similar question was already raised and answered on some of the thread.
![image](https://user-images.githubusercontent.com/29104318/103484588-990e2000-4df8-11eb-949d-568f4f772931.png)

BUT. Your site does have an issue with too long LCP and I had the same one. My advice for you - change the logic of tile generation on BE-side to deliver non-lazy-loaded picture\img tag markup for every 1st tile. And that solved my issue too. The problem is that lazy-loading comes into play only after all client JS is loaded, it replaces all src attributes, browser downloads it and only then user sees the image in viewport. And the Largest Content Paint, in fact, is you Image tile in every viewport. Other solution as a workaround (if you have no access\skills for Back-End) - set some non-lazy-loaded banner that is at least 5% bigger (just calculate Width x Height in pixels) than your img tile in viewport. That will draw "LCP's attention" to that banner that will be regular picture tag that is loaded almost instantly without lazy-loading. 
Good luck!

**Comment by patrickhulce** [comment]
Thanks for filing @thanhtoan1196! 

@alexd-3d is exactly right. The difference is in simulated throttling and [covered in this FAQ](https://github.com/GoogleChrome/lighthouse#why-is-the-performance-score-so-low-it-looks-fine-to-me).
