### ISSUE TITLE
Inconsistent LCP across LH and performance timeline

### ISSUE THREAD

**Issue by mgechev** [GoogleChrome/lighthouse#11918]
#### Provide the steps to reproduce

1. Open DevTools on crunchbase.com
2. Set the page width to ~377px
3. Run performance profiling with LH
4. View original trace
5. Compare the LCP value in the performance timeline with the value in LH

#### What is the current behavior?

LCP in LH is ~3x higher compared to FCP (see screenshot).

<img width="726" alt="Screen Shot 2020-12-24 at 3 02 54 AM" src="https://user-images.githubusercontent.com/455023/103685290-d500cc80-4f41-11eb-8076-b437afbdae18.png">

LCP in the performance timeline is equal to FCP (see screenshot).

<img width="440" alt="Screen Shot 2020-12-24 at 3 03 11 AM" src="https://user-images.githubusercontent.com/455023/103685262-c87c7400-4f41-11eb-905d-721529d0d957.png">

#### What is the expected behavior?

LCP should have consistent value across performance timeline and LH.

#### Environment Information
* Affected Channels: DevTools, LH
* Lighthouse version: 7.0.0
* Chrome version: 89.0.4379.0 (Official Build) canary (x86_64)
* Node.js version: v12.0.0
* Operating System: macOS

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @mgechev! This is expected due to use of simulated throttling by default (Canary should have a tooltip explaining this before clicking the view trace button, but admittedly it isn't instantaneous enough to help swift clickers). To get a matching trace, you [can use *applied* throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md#devtools-audits-panel-throttling) by unchecking the "Simulated throttling" checkbox.

**Comment by mgechev** [comment]
Thanks for the quick response!
