### ISSUE TITLE
audit for "Preload key requests" generates spurious warnings

### ISSUE THREAD

**Issue by shubhie** [GoogleChrome/lighthouse#11933]
1. Run LH on nextjs.org
  
#### What is the current behavior?

In passed audits, "Preload key requests" generates warnings":

Warnings:
A preload `<link>` was found for "https://nextjs.org/_next/static/chunks/7aff9340358677c20ddd5af98fbc6e919793498d-9590371a0b1a54e61c0b.js" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
A preload `<link>` was found for "https://nextjs.org/_next/static/chunks/984c6d06633e962ee57399a6e4796c41646d99ae-3160b6c275faa707ebbf.js" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.

#### What is the expected behavior?

the warnings should not be generated.
preload + async are used for signal boosting self bundled javascript.
It is not "not used by the browser".

#### Environment Information
* Lighthouse version: 6.4.0
* Chrome version: latest stable

**Comment by patrickhulce** [comment]
Thanks @shubhie! 

For future implementors, preliminary investigation from earlier showed that Chrome's behavior here seems to have shifted since the audit's impl to issue a 2nd request that ends up serving from the "prefetch cache" instead of simply reusing the existing request. This behavior actually makes way more sense, so we can remove our workarounds :)


![image](https://user-images.githubusercontent.com/2301202/104069631-27085300-51cb-11eb-8d54-0e3c4f4899f8.png)

**Comment by patrickhulce** [comment]
PR is up in #12122
