### ISSUE TITLE
Image with an area of 0 results in a recommendation of being deferred but it already is

### ISSUE THREAD

**Issue by gregwhitworth** [GoogleChrome/lighthouse#12026]
#### Provide the steps to reproduce
1. Run LH on https://karenwhitworth.com/collections/hawaiian-landscapes/products/hawaiian-cottage-and-jungle-waterfall-canvas-art-by-karen-whitworth
2. Notice the images at the top are in a scroller

#### What is the current behavior?

The images in the scroller get the recommendation of "Defer offscreen images"

![image](https://user-images.githubusercontent.com/865244/106368653-25c8d280-6300-11eb-8b02-1a11f4baf3ab.png)

#### What is the expected behavior?

All of these images are deferred. Looking at the [offscreen-images](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/byte-efficiency/offscreen-images.js) code it treats an image with an area of 0 as something that should be deferred. All of these images are set to be lazyloaded so I'm not sure what else can be done to defer them.

You'll noted that the images go from lazyload to lazyloaded as they are brought in.

In testing the reasoning it's due to the images in the carasouel being set to `display: none` and thus an area of 0 when getting the images clientRect.

Not sure if there is a clear solution to this but possibly a hint in the UI that technically it is within the position of the viewport but is not currently visible. Looking at the code it doesn't seem to take into account animations or other reasons why in the first few tasks it may not be visible.

**Comment by patrickhulce** [comment]
Thanks for filing @gregwhitworth!

> All of these images are deferred.

I'm not seeing this behavior. When I load the page on mobile without Lighthouse involved, all of these images are requested immediately and before at least a dozen scripts despite not being visible (and several of them being *very* far down the viewport).

![image](https://user-images.githubusercontent.com/2301202/106401671-0195f000-63eb-11eb-83e5-414b709c39f6.png)

> All of these images are set to be lazyloaded so I'm not sure what else can be done to defer them.

This lazy loader that is being used does not prioritize for main thread quiescence. That might be the right tradeoff to make for this site, I don't know, but it doesn't change the fact that lazily loading these images would in fact improve TTI like Lighthouse says. We're exploring ways to deemphasize this savings (#11279)  because it doesn't tend to improve the user experience as much as the big red bar suggests it will, but the savings is accurate in this case.
