### ISSUE TITLE
The install page for the Lighthouse extension in Chrome Web Store has wrong version

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/lighthouse#12033]
Unless there's something I'm not aware of, I don't think Lighthouse is up to version 100.

![image](https://user-images.githubusercontent.com/8204171/106514029-97338d00-6488-11eb-9619-888729a4f8e1.png)

**Comment by connorjclark** [comment]
The extension version is separate from the LH version. It used to be the same, but we now the extension just calls the PSI api (instead of a bundled version of Lighthouse that could run as an extension), which is usually the latest (minus 1) version of LH. So we decided to shoot the extension version to 100.
