### ISSUE TITLE
“Simulated throttling” checkbox is misleading

### ISSUE THREAD

**Issue by chrisjshull** [GoogleChrome/lighthouse#12080]
I think the “Simulated throttling” checkbox is misleading. Regardless of whether it’s enabled or not, throttling does happen - just different methodologies (and I’m not sure “simulated” couldn’t describe either). A dropdown like the Network inspector would be clearer.

#### Environment Information
* Affected Channels: Extension
* Lighthouse version: 6.4.0
* Chrome version: 88.0.4324.150

**Comment by patrickhulce** [comment]
Thanks for filing @chrisjshull! I'm assuming you're talking about the checkbox Lighthouse panel in Chrome DevTools?

I agree "Simulated throttling" alone is not self-descriptive of what it does which is why we have the tooltip and "Learn More" links on there to try to help with this problem. 

Is the suggestion here that this is replaced with a dropdown that has "Simulated throttling" and "Applied throttling" options? The freeform throttling of the Network panel is not an option for Lighthouse which has very specific profiles paired with scoring curves derived from real-world data from those profiles.

**Comment by chrisjshull** [comment]
> Thanks for filing @chrisjshull! I'm assuming you're talking about the checkbox Lighthouse panel in Chrome DevTools?

yeah

> Is the suggestion here that this is replaced with a dropdown that has "Simulated throttling" and "Applied throttling" options? 

Love it! I think that's is a lot clearer than a "learn more", which is nice, but I can't "learn more" on every unchecked checkbox just as I'm starting to use a tool. To me unchecked means it's not happening, so I don't need to know what it does (yet).

**Comment by patrickhulce** [comment]
Thanks for the clarification! Just for our knowledge, are tooltips also too hidden and/or too burdensome to learn about a control's implications?

> To me unchecked means it's not happening, so I don't need to know what it does (yet).

This is quite concerning for patterns throughout DevTools where checked is the default and unchecking is a significant and important change in behavior. Anyone out there watching this, do you also have an expectation that unchecking everything is the state you want to get to if you don't know how the tool works yet? Let us know either way :)

The honest answer here is that we don't really want people who don't know what it does to mess with it and instead use the defaults. If everyone has the instinct of unchecking pre-checked boxes though, we're defeating that goal.

**Comment by connorjclark** [comment]
Let's make a dropdown, and use this text for the options:

- Simulated throttling (Default)
- Applied throttling (Advanced)

**Comment by adamraine** [comment]
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3665057
