### ISSUE TITLE
How does Lighthouse interact with the Network tab?

### ISSUE THREAD

**Issue by chrisjshull** [GoogleChrome/lighthouse#12081]
It’s not clear whether Lighthouse clears caches itself, or is dependent on the Network tab cache setting (as well as what happens if I throttle in the network tab, what happens to lighthouse?). 

Does "clear storage" include caches?

Can the UI make this more clear?

#### Environment Information
* Affected Channels: Extension
* Lighthouse version: 6.4.0
* Chrome version: 88.0.4324.150

**Comment by paulirish** [comment]
First up, there's the existing tooltip which I fairly clear.

<img width=600 src="https://user-images.githubusercontent.com/39191/108891765-f128fd80-75c3-11eb-8844-0d21ee727426.png">


-----------

> It’s not clear whether Lighthouse clears caches itself, or is dependent on the Network tab cache setting (as well as what happens if I throttle in the network tab, what happens to lighthouse?).

I'll be exhaustive in this answer since there's a lot of details at play..

**Cache**: Lighthouse will clear the entire disk cache itself. That behavior is not configurable and it'll always do it. It also clears the memory cache (which isn't guaranteed in devtools unless you know the special invocation (uncheck & check "Disable Cache") :)

**Storage**: "storage" refers to non disk-cache storage mechanisms, such [as these](https://chromedevtools.github.io/devtools-protocol/tot/Storage/#type-StorageType). If _Clear storage_ is checked, Lighthouse will clear these 5 types prior to loading the page: 'appcache', 'file_systems', 'shader_cache', 'service_workers', 'cache_storage'.  If not, they stay there. Note that cookies, localstorage, sessionstorage, indexeddb and websql are not cleared (though we do issue a warning if we detect usage).


**Preserve log**: does preserve the log while LH does it's thing. and will include network requests that happened during the LH run. (Otherwise, the log will be cleared because LH Panel reloads the page once LH is done to reset the page state)

**network throttling**: Anything set in devtools is ignored for the Lighthouse run. 

**cpu throttling**: if set in devtools, it WILL apply during the LH run if "simulated throttling" is on. 🤔 And if that's unchecked, ([thus](https://github.com/GoogleChrome/lighthouse/issues/12080) applied throttling), then LH will override any existing cpu throttling with its own.

**Local Overrides**: If set in devtools, it'll apply during LH run.

**network request blocking**: if set in devtools, it'll apply during LH run.

**device emulation**: this will be applied according to the mobile/desktop choice. Any existing emulation applied prior won't be used, but it should be restored after things are done.

--------

i think that's it.... any questions past that? We can add the above to our documentation to help folks understand this.

**Comment by chrisjshull** [comment]
I think a lot can fall under the "etc" in that hover text (technically a cache is a form of storage). 
Also, when I talk to UX people they don't tend to think that hover text is discoverable.

And woof, that's a complicated mix of interdependency/overriding. A linked out help page (maybe with a table of the options and how they play out?) would be super helpful. Even better if I don't even need to go to a help page by embedding more of that in the lighthouse UI, ready to see.

> Storage: ... Note that cookies, localstorage, sessionstorage, indexeddb and websql are not cleared (though we do issue a warning if we detect usage).

Doesn't this contradict the hover text which says that localstorage *is* cleared?

**Comment by adamraine** [comment]
> Doesn't this contradict the hover text which says that localstorage is cleared?

This is a bug, we don't clear localstorage, indexeddb, or websql anymore. We should update the tooltip to use different examples, or exhaustively list everything Lighthouse clears.

**Comment by adamraine** [comment]
Resolved in M92: https://chromiumdash.appspot.com/commit/77ee43824306bad7bdf65d525760d9540c92098a
