### ISSUE TITLE
SVG and Pictures, triggering the Image elements do not have explicit width and height opportunity

### ISSUE THREAD

**Issue by peixotorms** [GoogleChrome/lighthouse#12116]
On pagespeed insights, SVG images without width and height attribute are triggering the "Image elements do not have explicit width and height" opportunity.

Since SVG images are essentially scalable and don't usually have a fixed dimension, shouldn't perhaps this opportunity metric exclude these images?

Also images inside the picture html element are also triggering this, even if the source has a media attribute.

In my opinion, pagespeed insights should not trigger the opportunity for these cases, but someone please let me know if I am wrong about this.

Thank you

**Comment by j-mendez** [comment]
> On pagespeed insights, SVG images without width and height attribute are, triggering the Image elements do not have explicit width and height opportunity.
> 
> Since SVG images are essentially scalable and don't usually have a fixed dimension, shouldn't perhaps this opportunity metric exclude these images?
> 
> Also images inside the picture html element are also triggering this, eve if the source attribute has a media attribute.
> 
> In my opinion, pagespeed insights should not trigger the opportunity for these cases, but someone please let me know if I am wrong about this.
> 
> Thank you

I agree, we should exempt svg images since this does not affect cls.

**Comment by j-mendez** [comment]
@peixotorms the issue is gone, I think lighthouse caches the page, try to see if it still occurs on your end.

**Comment by peixotorms** [comment]
@j-mendez it appears to be fixed now, thanks.

However, now I see base64 data images instead, which were previously not showing up.
That being said, it makes sense on the case below, so this is helpful.
Will this apply only for images above the fold, or for all images on the page?

`<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" alt="something" data-lazy-src="https://domain.com/example.jpg">`

**Comment by peixotorms** [comment]
@j-mendez  this is actually back again (earlier looked fine).
https://i.imgur.com/pbJG4qO.png

**Comment by j-mendez** [comment]
@peixotorms np, I just checked and it seems fine still on my end. Try to clear the cache on the page, maybe.

**Comment by peixotorms** [comment]
@j-mendezthere is no cache to clear, as I am talking about pagespeed insights.
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwholesomeyumfoods.fastvelocity.com%2F

**Comment by j-mendez** [comment]
@peixotorms yeah, I am talking about the browser cache, I was thinking if you open the dev menu and click shift to do clear cache and force reload. On my end I had issues appearing for svg ims without width, heights, I then put pushed a fixed and it took several hours for lighthouse to tell me that I fixed the issue. My img's are not base64, which maybe could be the difference. I hope you it gets fixed soon on your end sorry!

**Comment by connorjclark** [comment]
If we're talking about pagespeed insights, please note that Lighthouse runs on Google servers, not your machine, so your browser cache plays no role.

**Comment by patrickhulce** [comment]
> Since SVG images are essentially scalable and don't usually have a fixed dimension, shouldn't perhaps this opportunity metric exclude these images?

> In my opinion, pagespeed insights should not trigger the opportunity for these cases, but someone please let me know if I am wrong about this.

> Also images inside the picture html element are also triggering this, even if the source has a media attribute.

I think there's a misunderstanding here about why images should have fixed dimensions.  It is unrelated to how scalable they are. 

The unsized images audit is to help prevent CLS increases. If the browser has to parse/decode/download an image in order to compute its displayed size there will be a delay in sizing it appropriately. This delay is what causes layout shifts. 

If you were only referring to inline SVGs, that's tracked by https://github.com/GoogleChrome/lighthouse/issues/11631 and we intend to fix it.

**Comment by peixotorms** [comment]
Thanks for clarification. I was wondering about the inlined svg too.

**Comment by rgpublic** [comment]
@patrickhulce : What I don't understand and what I think needs clarification is this:

Let's take e.g. an SVG with `<svg width="120" height="100">....` in the file. The browser needs to load that file first to find out the width is 120 and height is 100. We want to avoid that an dthe corresponding layout shift that might occur due to this, so we add width="120" height="100" in the img tag: `<img src="test.svg" width="120" height="100">`

Now, the browser knows just from the img tag what the size is before even loading the SVG file. No sudden layout shift after that SVG file is actually loaded. Wonderful. Lighthouse is correctly complaining if these attributes aren't there because in that case, the layout shift might occur.

But: Let's take an SVG file without those width / height attributes. I've found out that those files just scale up to fit their container (if not influenced by CSS). How can I tell the browser in advance that the SVG file is going to be such a file?

`<img src="test.svg" width="" height="">`

Would that have any effect? It looks strange for sure. Will Lighthouse stop complaining in this case (didn't try)? I think this case is valid. We tell the browser in advance that the SVG won't have width / height attributes. So it knows that fact in advance. No layout shift. .... Right?
