### ISSUE TITLE
Lighthouse flags valid canonical URLs as invalid

### ISSUE THREAD

**Issue by dd-pardal** [GoogleChrome/lighthouse#12149]
**Summary:** Lighthouse flags relative URLs and URLs for different domains as invalid for `<link rel="canonical">`

I don't think this is a bug, but [RFC 6596](https://tools.ietf.org/html/rfc6596#section-3) explicitly states that:

> The target (canonical) IRI MAY:
>
> * Specify a relative IRI (see [[RFC 3986]](https://tools.ietf.org/html/rfc3986#section-4.2), Section 4.2).
> * Be self-referential (context IRI identical to target IRI).
> * Exist on a different hostname or domain.

I prefer to use path-absolute relative URLs (`/like/this`) whenever possible because they work well even if the origin is different. This is useful for testing and it's one less thing to worry about when transferring the website to another domain name. (Maybe this audit exists because people sometimes forget to put the first `/`?)

Also some websites may have mirrors in different domains, so it would make sense to link to a canonical version in a different domain, in that case, although that's a very specific use case.

**Comment by brendankenny** [comment]
I'm not a subject-matter expert here, but looking at the original requirements for the implementation (https://github.com/GoogleChrome/lighthouse/issues/3178)

> `href` value of canonical link is absolute

was there from the start, and so relative URLs were always planned to be a failure case. The [docs linked from that issue](https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls#expandable-5) (and linked in the [lighthouse docs for the audit](https://web.dev/canonical/)) explicitly says to "use absolute paths rather than relative paths".

I assume this is practical advice for what crawlers support vs what the RFC allows? e.g. that RFC quote also says it MAY exist on a different hostname or domain but that will also fail the audit (the docs state ["Yahoo and Bing don't allow this"](https://web.dev/canonical/#general-guidelines)).

cc @AVGP (and @rviscomi for ancient implementation background) for any additional insight they might have.

**Comment by connorjclark** [comment]
Closing b/c we are sticking to documented recommendations.
