### ISSUE TITLE
Chrome is not launching on desktop Environment Xfce

### ISSUE THREAD

**Issue by Rudloff** [GoogleChrome/lighthouse#1223]
When I run `lighthouse --verbose https://airhorner.com/` (with Node 6.2.2), it only outputs this then it exits:
```
  [3undefined;1mLighthouse CLI:verbose Using supplied port 9222 [3undefinedm+0ms
  [3undefined;1mLighthouse CLI Launching Chrome... [3undefinedm+5ms
  [3undefined;1mChromeLauncher:verbose created /tmp/lighthouse.wkYF6V1 [3undefinedm+4ms
```

**Comment by wardpeet** [comment]
Are you using latest master?
Are you running on windows? (seems like it)

**Comment by brendankenny** [comment]
The next line should be `ChromeLauncher:verbose Chrome running with pid xxxxx on port 9222`, so looks like Chrome is somehow never launching? We don't explicitly cover errors coming from the spawned process there, but the following lines should fail in that case.

(don't know if it would help diagnose the problem here, but we probably should have a `chrome.on('error', err => reject('whatever'));` there)

**Comment by Rudloff** [comment]
I'm using Debian 8.6.
I can reproduce with lightouse 1.3.0 and master.

**Comment by wardpeet** [comment]
which type of UI are you using? (gnome? KDE?)
Which chrome do you have installed? (chrome-stable? or chromium?)

**Comment by Rudloff** [comment]
I am using Xfce 4.10 and Chromium 55.0.2883.75.

**Comment by Rudloff** [comment]
I can also reproduce on Ubuntu 16.10 with Xfce 4.12, Node 4.2.6 and Chromium 55.0.2883.87.

**Comment by wardpeet** [comment]
will have to check Xfce to look into this issue :)
you can set the following env enviroment LIGHTHOUSE_CHROMIUM_PATH and see if chrome starts spinning.
see https://github.com/GoogleChrome/lighthouse/blob/master/.travis.yml#L23

**Comment by Rudloff** [comment]
I tried setting LIGHTHOUSE_CHROMIUM_PATH but I get the same result.

**Comment by nobol** [comment]
I have a similar error, so I thought I would comment here instead of opening a new issue:

OS: arch-linux
Browser: Google Chrome Beta 56.0.2924.28 beta (64-bit)

1. I installed the lighthouse-cli via npm
2. Tried to run `lighthouse niklaszantner.de`, lighthouse exits with the following error:
```
 [3undefined;1mLighthouse CLI Launching Chrome... [3undefinedm+0ms
which: no google-chrome-stable in (/home/nik/.npm-global/bin:/home/nik/.npm-global/bin:/home/nik/.npm-global/bin:/usr/local/bin:/usr/local/sbin:/usr/bin)
(node:15382) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'kill' of undefined
(node:15382) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
``` 
3. Looks like Google Chrome cannot be found, as I am using the chrome beta, so I added 
```
export LIGHTHOUSE_CHROMIUM_PATH=/usr/bin/google-chrome-beta  
``` 
to my .bashrc used `source ~/.bashrc` to source it and executed `$LIGHTHOUSE_CHROMIUM_PATH` in my terminal. Chrome indeed opened. 

Rerunning `lighthouse niklaszantner.de` sadly produced the same error I already encountered. Also, reinstalling lighthouse did not help.

4. So I created a symbolic link for google-chrome-stable:

```
sudo ln -s /usr/bin/google-chrome-beta /usr/bin/google-chrome-stable
```

and as failed with `no google-chrome`
```
[3undefined;1mLighthouse CLI Launching Chrome... [3undefinedm+0ms
which: no google-chrome in (/home/nik/.npm-global/bin:/home/nik/.npm-global/bin:/home/nik/.npm-global/bin:/usr/local/bin:/usr/local/sbin:/usr/bin)
(node:16400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'kill' of undefined
(node:16400) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I also created a symbolic link for google-chrome:

```
sudo ln -s /usr/bin/google-chrome-beta /usr/bin/google-chrome
```

5. Yeah, at least the error message changed after rerunning `lighthouse niklaszantner.de`:

```
  [3undefined;1mLighthouse CLI Launching Chrome... [3undefinedm+0ms
  [3undefined;1mChromeLauncher Waiting for browser. [3undefinedm+46ms
  [3undefined;1mChromeLauncher Waiting for browser... [3undefinedm+2ms
  [3undefined;1mChromeLauncher Waiting for browser..... [3undefinedm+505ms
  [3undefined;1mChromeLauncher Waiting for browser....... [3undefinedm+502ms
  [3undefined;1mChromeLauncher Waiting for browser......... [3undefinedm+501ms
  [3undefined;1mChromeLauncher Waiting for browser........... [3undefinedm+502ms
  [3undefined;1mChromeLauncher Waiting for browser............. [3undefinedm+501ms
  [3undefined;1mChromeLauncher Waiting for browser............... [3undefinedm+501ms
  [3undefined;1mChromeLauncher Waiting for browser................. [3undefinedm+502ms
  [3undefined;1mChromeLauncher Waiting for browser................... [3undefinedm+501ms
  [3undefined;1mChromeLauncher Waiting for browser..................... [3undefinedm+502ms
  [3undefined;1mChromeLauncher Waiting for browser....................... [3undefinedm+501ms
(node:16548) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'kill' of undefined
(node:16548) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

6. So I installed google-chrome-stable and tried the same, running into the same errors.

I am slightly ouf of ideas what I can do. If I can help you with any more informations, please let me know.

**Comment by khrome83** [comment]
I see something similar @nobol as well.

But my results are in a CI #1645

**Comment by wardpeet** [comment]
Closing as this is old and plenty of updates on headless & docker
