### ISSUE TITLE
Add support for testing using the version to be released with Chrome 93 [change in PWA identification]

### ISSUE THREAD

**Issue by humble-barnacle001** [GoogleChrome/lighthouse#12248]
**Feature request summary**

Add support for lighthouse testing with the version to be released with Chrome 93 [change in PWA identification]

No

**What is the motivation or use case for changing this?**
- Identify breaking of PWA installability
- New features

**How is this beneficial to Lighthouse?**
It would help the developers to identify if their application is not working offline and the specific pages where it is not working correctly

**Comment by brendankenny** [comment]
Chrome 93 doesn't exist yet, so there's no way to test with it :)

That said, the warning in the `installable-manifest` audit ("Page does not work offline. The page will not be regarded as installable after Chrome 93, stable release August 2021") is triggered when the current version of the check _planned_ for Chrome 93 fails for a page, so that's the best way to tell if a web page will fail that installability check starting in ~August.

We believe the offline check is basically what will ship in Chrome 93, but it's possible that some details may change between now and then. It's also possible there are some remaining bugs in the check; if you encounter a site you believe is incorrectly triggering that warning, be sure to file an issue on https://bugs.chromium.org/p/chromium/issues/list.

**Comment by humble-barnacle001** [comment]
Hey thanks!
