### ISSUE TITLE
Update to latest version of `jsonld` to avoid pulling in vulnerable version of `xmldom`

### ISSUE THREAD

**Issue by G-Rath** [GoogleChrome/lighthouse#12244]
[An advisory has been open against `xmldom`](https://www.npmjs.com/advisories/1650), which is pulled in by `lighthouse` via `jsonld` - while the advisory has been patched via `xmldom@0.5.0`, all versions of `jsonld` until v4 are fixed to use v0.1.19 of `xmldom`, and the versions in-between have some breaking changes like dropping support for node versions (among others) that means it's unlikely a version of `jsonld` will be released that uses a patched version of `xmldom`.

This is doubly unlikely given that [`jsonld` no longer uses `xmldom` in v4](https://github.com/digitalbazaar/jsonld.js/blob/master/CHANGELOG.md#removed) (this could be its own trouble as it seems the functionality it was powering has been moved to its own package, which needs patching - hopefully `lighthouse` doesn't need this feature).

`lighthouse` is currently using v1 of `jsonld` - the breaking changes between that version and v4 seem like they should be acceptable to take on in a minor/patch release.

They are:
  * v2: [removes callbacks in favor of promises, and removes a few deprecated methods](https://github.com/digitalbazaar/jsonld.js/blob/master/CHANGELOG.md#notes-1)
  * v3: [changes the framing omitGraph default to match the JSON-LD 1.1 Framing spec.](https://github.com/digitalbazaar/jsonld.js/blob/master/CHANGELOG.md#notes)
  * v4: [moves the RDFa parser to jsonld-rdfa package](https://github.com/digitalbazaar/jsonld.js/blob/master/CHANGELOG.md#removed)

**Comment by davidlehn** [comment]
Hi, upstream jsonld.js maintainer here.  There were many things in jsonld.js that were ancient.  We are slowly modernizing and doing various updates as we have time.  A v5 will be out soon too.  Feedback is welcome if these changes are causing trouble.  We recognize various projects are still using old versions.  If there are smaller minor/patch updates to old versions that would help keep them running, please file an issue and we'll try to help.

I think there was some issue updating xmldom in particular, which is why it had been locked at an old version for a long time.  I'm forgetting the details.  That lib dependency moved out of jsonld.js and over to jsonld-rdfa.  That package is a work in progress.  If lighthouse needs it, let us know and we'll try to get it fixed up and released.  We'll try to make sure it uses a modern xmldom (or other lib as needed).

**Comment by brendankenny** [comment]
Thanks! Fix is up in #12257. The migration was pretty easy as promised, though we only use a single call into `expand()`, so there wasn't much to migrate :)

**Comment by G-Rath** [comment]
If I'm not mistaken, it also looks like it'll be a non-breaking change too, so should be shippable in a patch release 🥳
