### ISSUE TITLE
Lighthouse ignores webp image url generated with query params.

### ISSUE THREAD

**Issue by arekkoperek** [GoogleChrome/lighthouse#12373]
#### What is the current behavior?
On our page  we generate images with some server optimizer that crops and converts them for webp. Our source srcset looks like this: 
'./media/tdkdytyi/couple-computer-online-information-adobestock_309014939.jpeg?anchor=center&mode=crop&width=800&height=448&rnd=132591051074830000&format=webp&quality=80 1x, /media/tdkdytyi/couple-computer-online-information-adobestock_309014939.jpeg?anchor=center&mode=crop&width=1600&height=896&rnd=132591051074830000&format=webp&quality=80 2x'

In the chrome lighthouse extension report it returns: Serve images in next-gen formats depite the img response from server is webp. This seems not to be an issue for dev tools reports. 

#### Environment Information
* Affected Channels: Extension
* Lighthouse version:
* Chrome version:  90.0.4430.72
* Node.js version: 12.16.3
* Operating System: Win 10

**Related issues**

**Comment by brendankenny** [comment]
Are you able to share a URL for testing? It's much easier to check why they might differ with a live example.

**Comment by arekkoperek** [comment]
> Are you able to share a URL for testing? It's much easier to check why they might differ with a live example.

unfortunately not....project is in pre-live state. I can send you the link privately.

**Comment by walder** [comment]
We are having the same Issue here. I presume Lighthouse is stripping get parameters, which in our case leads to the image being to large in the Lighthouse test.

Unfortunately the URL ist on a Testserver, I can send it to you @brendankenny via DM if you want. Just don't want it publicly available due to indexing, thats something your employer is really god at :-).

This seems to have happened previously, see:
https://github.com/GoogleChrome/lighthouse/issues/4100

This is the code of the section:
``
<picture><source media="(min-width: 1600px)" data-srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=1600&amp;ar=1.5%3A1&amp;fm=webp" type="image/webp" srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=1600&amp;ar=1.5%3A1&amp;fm=webp"><source media="(min-width: 1600px)" data-srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=1600&amp;ar=1.5%3A1&amp;fm=png" type="image/png" srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=1600&amp;ar=1.5%3A1&amp;fm=png"><source media="(min-width: 1200px)" data-srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=1600&amp;ar=1.5%3A1&amp;fm=webp" type="image/webp" srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=1600&amp;ar=1.5%3A1&amp;fm=webp"><source media="(min-width: 1200px)" data-srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=1600&amp;ar=1.5%3A1&amp;fm=png" type="image/png" srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=1600&amp;ar=1.5%3A1&amp;fm=png"><source media="(min-width: 800px)" data-srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=1200&amp;ar=1%3A1.3&amp;fm=webp" type="image/webp" srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=1200&amp;ar=1%3A1.3&amp;fm=webp"><source media="(min-width: 800px)" data-srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=1200&amp;ar=1%3A1.3&amp;fm=png" type="image/png" srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=1200&amp;ar=1%3A1.3&amp;fm=png"><source media="(min-width: 480px)" data-srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=800&amp;ar=2%3A1&amp;fm=webp" type="image/webp" srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=800&amp;ar=2%3A1&amp;fm=webp"><source media="(min-width: 480px)" data-srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=800&amp;ar=2%3A1&amp;fm=png" type="image/png" srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=800&amp;ar=2%3A1&amp;fm=png"><source media="(min-width: 320px)" data-srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=480&amp;ar=1%3A1&amp;fm=webp" type="image/webp" srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=480&amp;ar=1%3A1&amp;fm=webp"><source media="(min-width: 320px)" data-srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=480&amp;ar=1%3A1&amp;fm=png" type="image/png" srcset="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=480&amp;ar=1%3A1&amp;fm=png"><img alt="Lagerverkauf günstige Frauenkleider Chicorée" data-src="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=320&amp;ar=1%3A1&amp;fm=webp" src="https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&amp;crop=edges&amp;width=320&amp;ar=1%3A1&amp;fm=webp"></picture>
``

The image URL reported in Lighthouse is:
https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&crop=edges

![Issue Lighthouse](http://transfer.allink.ch/chicoree/light-house-report-issue-github.jpg)

**Comment by walder** [comment]
At least in our case we were able to resolve the issue it turned out that in one version of the image the width and height params were not passed.

**Comment by arekkoperek** [comment]
> At least in our case we were able to resolve the issue it turned out that in one version of the image the width and height params were not passed.

@walder thanks for the tip. How do you handle width and height for responsive images eg in <picture> tag?

**Comment by walder** [comment]
@arekkoperek I am not quite sure what you mean.

**Comment by Soonz** [comment]
Hello,

I think this might be related, I ran the Lighthouse test on my website ( [Dealwithit](https://www.dealwithit.fr) ) on which every images are ( at least believe ) converted in Webp but I still get the warning **Serve images in next-gen formats**.

I believe Lighthouse doesn't actually check the "real" file type but only the extension of the ressources.

**Comment by adamraine** [comment]
Lighthouse looks at the `content-type` response header to determine the image format for this audit.

The `content-type` header of https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&crop=edges is `image/jpeg`.

The `content-type` headers of images on https://www.dealwithit.fr/ are all `image/jpeg`, `image/gif` or `image/png`.

@arekkoperek can you check the value of the `content-type` response header for the images on your site?

**Comment by arekkoperek** [comment]
@adamraine thanks for response. content-type response is image/webp but running the report from chrome extension still shows as if this was jpeg. Check the example screenshots

![Screenshot_43](https://user-images.githubusercontent.com/6543804/147154975-6258718a-a00b-4090-ad5b-20c0767b9b35.jpg)



![Screenshot_44](https://user-images.githubusercontent.com/6543804/147154957-6637f878-48a1-42bb-ae2f-22d6fef94021.jpg)



> Lighthouse looks at the `content-type` response header to determine the image format for this audit.
> 
> The `content-type` header of https://chicoree-test-cms.imgix.net/media/original_images/Lagerverkauf_halle_02.jpg?fit=crop&crop=edges is `image/jpeg`.
> 
> The `content-type` headers of images on https://www.dealwithit.fr/ are all `image/jpeg`, `image/gif` or `image/png`.
> 
> @arekkoperek can you check the value of the `content-type` response header for the images on your site?

**Comment by connorjclark** [comment]
This seems like your server may be sending different results to google IPs. The chrome extension just runs the PSI api, which runs on google infra. DM me a url https://twitter.com/cjamcl and I can look closer.

**Comment by arekkoperek** [comment]
@connorjclark message sent. Let me know if you need more details

**Comment by adamraine** [comment]
@arekkoperek it looks like the site you sent us is indeed delivering different image types depending on the form factor. The webp versions are not served for the dimensions which Lighthouse uses.

If you go into DevTools and change your dimensions to "Galaxy Fold", you should get the jpeg/png versions of the images delivered after a refresh.

**Comment by arekkoperek** [comment]
@adamraine thank you for response. I still do not understand why there is a different output for the lightouse report run in dev tools and the one from extension. One is shouting about wrong image formats and another one not

**Comment by adamraine** [comment]
The Lighthouse chrome extension will test the site on one of our servers, while the Lighthouse in DevTools will run on your local machine. The difference in results can be attributed to the different testing environments, because the site is liable to deliver different image formats depending on the environment.
