### ISSUE TITLE
Report: expand violation details on print

### ISSUE THREAD

**Issue by enjikaka** [GoogleChrome/lighthouse#1240]
`<details>` not expanded in printed version, rendering it very less unusable since papers and PDF files are not that interactive, so you can't open them.

Should be expanded in print CSS.

**Comment by wardpeet** [comment]
@ebidel ? ^^

**Comment by enjikaka** [comment]
Should maybe explain my use case too;

- I generate report with chrome extension
- I print it to share with my collegues

And in here they don't see which selectors has wrong aria stuff etc because it's hidden in those non-expanded <details> :)

**Comment by ebidel** [comment]
Expanding all the help and url lists (all those `<details>`) would create a huge printed report. The current state is not ideal to see all the details, but I'm not sure the right answer. The latter could be too much :\ WDYT?

**Comment by ebidel** [comment]
```
const details = [].slice.call(document.querySelectorAll('details'));

// FF and IE implement these.
if ('onbeforeprint' in window) {
  window.addEventListener('beforeprint', e => {
    details.map(detail => detail.open = true);
  });
  window.addEventListener('afterprint', e => {
    details.map(detail => detail.open = false);
  });
} else {
  // Note: while FF has media listeners, it doesn't fire the event on a print.
  window.matchMedia('print').addListener(mql => {
    details.map(detail => detail.open = mql.matches);
  });
}
```

**Comment by AdrianoCahete** [comment]
Creating a print.css don't fix the issue and prevent to online report be a massive wall of text?

**Comment by enjikaka** [comment]
Maybe an HTML export could be an option?

**Comment by ebidel** [comment]
@AdrianoCahete we already have a print stylesheet. The issue is that a lot of the useful violation details are hidden behind `<details>`. Even a print stylesheet can't open them :\ https://github.com/GoogleChrome/lighthouse/issues/1240#issuecomment-268863499 would work.

@enjikaka 
I'm not sure if HTML export solves the printing issues.

But it's worth noting we have a couple of export options on http://googlechrome.github.io/lighthouse/viewer/.  https://github.com/GoogleChrome/lighthouse/issues/1166 tracks moving that functionality into the reports produced by the CRX and CLI.

**Comment by AdrianoCahete** [comment]
> Even a print stylesheet can't open them

On print stylesheet:
```
..subitem__help-toggle {
  display: none;
}
.subitem__help-toggle + .subitem__help {
  display:block;
}
```

**Comment by ebidel** [comment]
That's the help text, which we already display by default when an audit is violated. Both print and in the normal report. 

This issue is talking about the `<details>` elements on the page. For example, a list of URLs:

<img width="685" alt="screen shot 2017-01-06 at 1 04 26 pm" src="https://cloud.githubusercontent.com/assets/238208/21732912/bab3edea-d410-11e6-9435-e4de49299872.png">

**Comment by AdrianoCahete** [comment]
> This issue is talking about the <details> elements on the page. For example, a list of URLs:

Yeah, it's true. Sorry :(

**Comment by enjikaka** [comment]
I see here - https://developers.google.com/web/updates/2017/12/lighthouse - that there are quite a few print/save options now. Good job, and thanks! 🥇
