### ISSUE TITLE
Wrong FCP and LCP for slow sites 🐢

### ISSUE THREAD

**Issue by Gus657** [GoogleChrome/lighthouse#12403]
#### Provide the steps to reproduce
1. Set up LH for mobile 📱 - Optional step but we usually do it 🤟🏽
2. Run LH on https://torre.co/es/search/people 🔍
2. Wait for the Audit results :) 
3. Check the results, usually are under 4s for FCP and LCP 🕓
  
#### What is the current behavior?
The site audit always shows very good results, most of the time at 2.5 seconds for both FCP and LCP. 

These numbers are not correct 😢 as the site is perceived to be noticeably slow 🐢, much slower than 2.5 seconds 🐇. We are not able to know the real results of the site audit 🚥.
#### What is the expected behavior?

We know that the site is quite slow 🐢, in fact, we don't know how slow 🐢🐢, but we think it should generate results like:

- FCP: 🔺🔻7s 
- LCP: 🔺🔻11s

It is difficult to say what the expected results would be 🙇🏽‍♂️

#### Environment Information

👨🏽‍💻 Normally we use LH in DevTools, but we also try it with node on different versions, 🤡 same results. 👩🏽‍💻
* Affected Channels: DevTools
* Chrome version: Version 90.0.4430.85
* Operating System: Windows 

**Related issues**
- None known 🕵🏽‍♂️

**Comment by paulirish** [comment]
The LCP element audit shows that the element with the LCP was the `.search-skeleton__search-box img`:

![image](https://user-images.githubusercontent.com/39191/116456431-2269b800-a817-11eb-9181-42ce2c81223f.png)

As you know that shows up very early. That image also satisfies the FCP.
So basically the skeleton UI trick worked on both FCP and LCP, and so those metrics are quite fast.

I agree the site feels kinda slow, and there's definitely a LOT of time between the skeleton image coming up and the page being loaded.


So for this page, the problem isn't getting early stuff painted. 

The problem is finishing. That's better tracked by Speed Index and TTI. (Which i'm seeing at ~5s and ~17s). 
So focusing on those metrics will probably be a better optimization target.
