### ISSUE TITLE
Bug with defining LCP

### ISSUE THREAD

**Issue by Andrii256** [GoogleChrome/lighthouse#12429]
![image](https://user-images.githubusercontent.com/41700032/116791702-29e4c780-aa8a-11eb-92e8-94f8e23e374e.png)
![image](https://user-images.githubusercontent.com/41700032/116791713-39641080-aa8a-11eb-88a5-46c71c326643.png)

Hello
As you see on screenshots, by LC element paints almost immediately, and your analyzer shows it in screenshots panel.
But it counts LCP as 7s. This is bug

https://andrii256-denysvarenik.github.io/grocceries-front/build/

**Comment by patrickhulce** [comment]
Thanks for filing @Andrii256 ! 

You might find the [FAQ](https://github.com/GoogleChrome/lighthouse#why-is-the-performance-score-so-low-it-looks-fine-to-me) and [throttling docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md) on this subject helpful. While LCP is ever so slightly overreported in this case with [simulated throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md#types-of-network-throttling) (see [ground truth](https://www.webpagetest.org/result/210501_BiDc79_29d22e93f560bee51d9f71ed9649d271/) of what Lighthouse is trying to emulate), the other metrics are significantly underreported so the overall Performance score estimate isn't overly harsh here, if anything it's being a bit generous.

**Comment by Andrii256** [comment]
@patrickhulce , Hello! Thanks for your answer.

I will deep in docs that you left and maybe then will understand.

But now I took a quick look in those docs and I still not understand.

I have simulator of loading data in those LC place (internet quality doesn't impact for speed of loading number in main screen. Rest api still not ready. I created simulator. It loads automatically after Promise resolved after setTimeout fired. You can check source code, there are src/store/API/simulators/cheaperFetch.ts. So I cant understand why internet throtling impacts for loading speed of my kinda Api)

**Comment by patrickhulce** [comment]
Great! The page isn't slowed down by an API request though, it looks like it's being slowed down by two JS resources, the subsequent execution, and a webfont. You can take a look at the [WebPageTest waterfall on a real device](https://www.webpagetest.org/result/210501_BiDc79_29d22e93f560bee51d9f71ed9649d271/1/details/#waterfall_view_step1) for better debugging.

![image](https://user-images.githubusercontent.com/2301202/116815225-33217300-ab22-11eb-9b85-a8228f74ed85.png)

**Comment by pahan35** [comment]
@patrickhulce, I have a similar question, so I ask it here instead of creating a new ticket.

All page content is rendered from the server-side. Because of it, I suppose that LCP should be triggered simultaneously as FCP is triggered.

However, occasionally, LCP is triggered after initializing the analytics.js

Link to the page with problem https://www.lawinsider.com/dictionary/objective-criteria

Recorded screencast https://recordit.co/c4VOSbcAQ2

#### Settings to reproduce the problem.
CPU throttling: 6x.
Web vitals: checked.
Mobile view.
Moto G4 device.

When I remove the analytics script from the page, the LCP metric looks fine: triggered simultaneously as FCP as it is supposed to be.

A bit more context available here https://stackoverflow.com/questions/67241872/how-to-figure-out-what-caused-lcp-retriggering.

Do you have any idea what delays LCP metric triggering and how to fix it?

Thanks in advance!

**Comment by connorjclark** [comment]
> Because of it, I suppose that LCP should be triggered simultaneously as FCP is triggered.

This is not true in general.

> Do you have any idea what delays LCP metric triggering and how to fix it?

What did the Lighthouse report say? :)

Please file a new issue in the future, this isn't particularly related except that it deals with LCP.
