### ISSUE TITLE
Low image quality for --element-screenshot-url 

### ISSUE THREAD

**Issue by alexyz41** [GoogleChrome/lighthouse#12449]
#### Provide the steps to reproduce
1. Run LH on https://musculo365.com
  

#### What is the current behavior?
When I use --element-screenshot-url as a background-image in my custom lighthouse report, screenshot looks pixeled, have a look here http://prntscr.com/12l2osy

#### What is the expected behavior?
Clean high-quality screenshot

**Comment by patrickhulce** [comment]
Thanks for filing @alexyz41! This is intentional behavior. Element screenshots are meant for giving a general sense of where the element is on the page, not hidef materials :)

If you want to build custom lighthouse reports with high quality full page screenshots you can add a custom gatherer to deliver this functionality.

**Comment by connorjclark** [comment]
fyi
https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gatherers/full-page-screenshot.js#L16-L18

**Comment by alexyz41** [comment]
@connorjclark you are the boss. thanks I did not know that option. Now the pictures are high quality. Thanks
