### ISSUE TITLE
SEO - Document doesn't have a valid hreflang

### ISSUE THREAD

**Issue by Vadorequest** [GoogleChrome/lighthouse#12458]
#### Provide the steps to reproduce
1. Go to https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fnrn-v2-mst-aptd-at-lcz-sty-c1-mgu1yndpx-unly-oss.vercel.app%2Fen%3FnoAutoPreviewMode%3Dtrue
  

#### What is the current behavior?

SEO error with `Document doesn't have a valid hreflang` but there are only 3 and all seem to follow the spec.

![image](https://user-images.githubusercontent.com/3807458/117588199-3fa95b00-b122-11eb-96c7-e2f5a77ad8c7.png)

#### What is the expected behavior?

I checked several times and even read https://hreflang.org/what-is-a-valid-hreflang/ and can't figure out what's wrong. The error is too wide to be actionable.

**Comment by connorjclark** [comment]
The error is below each item: "Relative href value". You need to use absolute URLs.

Why do we check that in this audit? I'm not sure. Does anyone know?

Our docs don't mention it either. https://web.dev/hreflang/

The string could be better.

**Comment by Vadorequest** [comment]
Relative values are valid hreflang. See https://stackoverflow.com/a/29789422/2391795

**Comment by patrickhulce** [comment]
The SEO category is not just for what *can* work according to HTML spec, but about SEO best practices. I find that Stack Overflow answer rather misleading as the source article is specifically calling out the use of relative href as a common source of mistakes, not saying it should be used.

The [official search documentation on this subject](https://developers.google.com/search/docs/advanced/crawling/localized-versions?hl=en&visit_id=637562569436549367-1667439553&rd=1) specifically recommends use of absolute URLs for all `hreflang` alternates. 

> Alternate URLs must be fully-qualified, including the transport method (http/https), so:
https://example.com/foo, not //example.com/foo or /foo

Until told otherwise by search, that's what the audit will respect.

**Comment by Vadorequest** [comment]
Although [the doc](https://developers.google.com/search/blog/2013/04/5-common-mistakes-with-relcanonical) does mention `The <link> tag, like many HTML tags, accepts both relative and absolute URLs.` 


![image](https://user-images.githubusercontent.com/3807458/117716333-bf463100-b1d9-11eb-9863-f246e33fcde4.png)

Regardless, specs probably have changed since then, and alternate url specs is different from standard `<link>` (non-alternate) `url`.
