### ISSUE TITLE
Insufficient Real World Speed Data | PageSpeed

### ISSUE THREAD

**Issue by neha-sha** [GoogleChrome/lighthouse#12532]
I am getting this message on PageSpeed tool after optimising the website:

**_The Chrome User Experience Report does not have sufficient real-world speed data for this page._**

The domain isn't new and also have good traffic. Earlier this data used to appear but after optimisation it started showing the above message. 

Any help would be much appreciated.  Thanks in advance!

**Comment by adamraine** [comment]
Are you able to share a URL for this site?

**Comment by brendankenny** [comment]
@neha-sha since this question is really about CrUX data and not Lighthouse, you'll likely get better help over in the public [CrUX Google Group](https://groups.google.com/a/chromium.org/forum/#!forum/chrome-ux-report). It's pretty active so you should get a response, but there may also be helpful advice in previous questions answered there.

**Comment by neha-sha** [comment]
> Are you able to share a URL for this site?

Hi Adam, the website URL is dreamcast.in

**Comment by neha-sha** [comment]
> @neha-sha since this question is really about CrUX data and not Lighthouse, you'll likely get better help over in the public [CrUX Google Group](https://groups.google.com/a/chromium.org/forum/#!forum/chrome-ux-report). It's pretty active so you should get a response, but there may also be helpful advice in previous questions answered there.

Thank you so much for the help. I've posted the same on the suggested group and other groups too. Awaiting for a concrete solution to the issue.
