### ISSUE TITLE
Clarification on how you calculated the image

### ISSUE THREAD

**Issue by learning101010** [GoogleChrome/lighthouse#12559]
**Summary**

So we have this Image when we use this tools its give us warning about the size of images it already 50kb need to optimize then use other technology like jpeg2000 but when we implement still same need to optimize again the image to lower the size of the picture.
(Images already optimize from 50 to 30kb)

We use google-chrome.

**Comment by patrickhulce** [comment]
Thanks for filing @learning101010! Could you please fill out the details from the [bug report template](https://github.com/GoogleChrome/lighthouse/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)? Specifically the example URL, expected result, and actual result. I'm not sure I understand what the issue is here.
