### ISSUE TITLE
Incosistent Runtime parameters during the multiple runs

### ISSUE THREAD

**Issue by ddbhagat** [GoogleChrome/lighthouse#12560]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### What is the current behavior?
We are seeing incosistent Runtime Setting parameters during the executions. And this looks like its afftecting the results as well.
These parameters are
- Network throttling - In may reports we recieve it as Unknown and under few report we do some values for this
- CPU throttling - In may reports we recieve it as Unknown and under few report we do some values for this
- CPU/Memory Power - These values varry from 100 to 1500 or so. And we can clearly see that if the values are low, TBT, TIT are increased.

#### What is the expected behavior?
We would like to have consistent runtime settings so that the reports are more comparable.

![image](https://user-images.githubusercontent.com/40200572/119635688-8fca3200-be31-11eb-840f-5f51cfafee80.png)
![image](https://user-images.githubusercontent.com/40200572/119635788-a40e2f00-be31-11eb-89aa-a2b7f814c45c.png)

#### Environment Information
* Affected Channels: We mostly fetch the reports through the 3rd party sites.
* Lighthouse version: Lighthouse 7.3.0
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
> We would like to have consistent runtime settings so that the reports are more comparable.

Then you need to run in a consistent environment. Runtime settings just describe the environment in which Lighthouse was used so that you can be *aware* of what led to the differences. If you use Lighthouse in different environments, it is **expected** that the runtime settings will change. 

See the [variability docs](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) for more information.
