### ISSUE TITLE
Protocol error (Tracing.end): Tracing failed

### ISSUE THREAD

**Issue by barotrahulh123** [GoogleChrome/lighthouse#12669]
**Summary**

Hi

using lighthouse npm for genrate multiple website report through our site but after sometime genrate  5-6 website rport facing below error

2021-06-16T05:26:30.573Z	7d893044-5b73-438c-8d5a-8c584960fa3c	INFO	Error: Protocol error (Tracing.end): Tracing failed
    at Function.fromProtocolMessage (/var/task/node_modules/lighthouse/lighthouse-core/lib/lh-error.js:146:19)
    at /var/task/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:141:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  protocolMethod: 'Tracing.end',
  protocolError: 'Tracing failed'
}

i am using aws lambda function. can't find reason why its happen

**Comment by patrickhulce** [comment]
Thanks for filing @barotrahulh123!

Unfortunately, we can't actually support running Lambda due to its narrow restrictions (see [docs on adequate hardware](https://github.com/GoogleChrome/lighthouse/blob/bfa5351639f81ea8a034bed6fb752864ff71f580/docs/variability.md#run-on-adequate-hardware)). If you're able to reproduce the issue outside of lambda with a particular URL and environment that is supported you can share, I'd be happy to take a look!

**Comment by barotrahulh123** [comment]
> Thanks for filing @barotrahulh123!
> 
> Unfortunately, we can't actually support running Lambda due to its narrow restrictions (see [docs on adequate hardware](https://github.com/GoogleChrome/lighthouse/blob/bfa5351639f81ea8a034bed6fb752864ff71f580/docs/variability.md#run-on-adequate-hardware)). If you're able to reproduce the issue outside of lambda with a particular URL and environment that is supported you can share, I'd be happy to take a look!

any way to run multiple url in lighthouse for genrate html
