### ISSUE TITLE
Lighthouse doesn't tell which image doesn't have alt attribute

### ISSUE THREAD

**Issue by ravikiran-srini** [GoogleChrome/lighthouse#12668]
**Summary**

Hi,

I ran Lighthouse from Chrome dev tools on this page.
https://ravikirans.com/az-204-azure-exam-study-guide/

Under SEO, Lighthouse suggests that "**Image elements do not have [alt] attributes**"
But, it doesn't point out which image element doesn't have the alt attribute.

I manually checked each image and I see all the images have the alt attribute. Please let me know how do I find out which image Lighthouse is referring to.

Thanks,

**Comment by ravikiran-srini** [comment]
I'm sorry missed your notification. Thanks for the reply.

In my case, the audit fails, it lists the failing element, but I am unable to find out which element on the webpage it refers to.
I checked each URL, and they have the alt attribute. So, I am confused about which element it is referring to. 

![Lighthouse](https://user-images.githubusercontent.com/39718717/122697973-09ecab80-d264-11eb-9005-288699d795fd.PNG)

This is the page I am referring to

https://ravikirans.com/az-204-azure-exam-study-guide/

Note: I am able to see this audit only sometimes. Other times it doesn't appear, which makes me skeptical about this audit.

**Comment by patrickhulce** [comment]
1. This appears to be the loading spinner for your comments. `div > div#llc-comments-loader > img`
2. Hovering over the element provides a tooltip of this selector.


Lighthouse core team, should we revisit the node display to consider adding the selector back in again if nodeLabel is just the tagName? `nodeLabel` is worthless in the case where the audit is flagging an element *because it doesn't have a nodeLabel* 😉

**Comment by patrickhulce** [comment]
Options:

1. Fallback to `selector` in nodeLabel generation instead of `tagName`.
2. Do not fallback to tagName in nodeLabel generation (which would force consumers to fallback to something else).
3. In the renderer, when we detect the nodeLabel isn't very informative, also show the selector.

@connorjclark and @brendankenny are partial to option 1. We're OK with the others too I guess 🤷‍♂️

**Comment by amulagrawal02** [comment]
Is this issuse is still alive? I am intrested to resolve this issue.

**Comment by tannerdolby** [comment]
I used `git grep -n "nodeLabel("` to find where exactly the `nodeLabel` generation was happening, 

```
tannerdolby:lighthouse TannerDolby$ git grep -n "getNodeLabel("
lighthouse-core/lib/page-functions.js:385:function getNodeLabel(element) {
```

and within `page-function-js` the [`getNodeLabel()`](https://github.com/tannerdolby/lighthouse/blob/master/lighthouse-core/lib/page-functions.js#L385-L419) function is where I think this fix is going to implemented from what I gathered in the above conversation.

> nodeLabel is worthless in the case where the audit is flagging an element because it doesn't have a nodeLabel
 
I replaced `tagName` with `selector` so the `getNodeLabel()` function falls back to `selector` instead of `tagName` like @patrickhulce mentioned.

**Comment by connorjclark** [comment]
> Is this issuse is still alive? I am intrested to resolve this issue.

We had just posted an update hours before your comment, you could have taken the issue :)

Thanks for the PR @tannerdolby !
