### ISSUE TITLE
SEO score vs Performance score.

### ISSUE THREAD

**Issue by vimal-mozanta** [GoogleChrome/lighthouse#12768]
**Summary**

My website has got a good SEO score for mobile
![image](https://user-images.githubusercontent.com/81166195/125087366-0d988300-e0ea-11eb-8c62-c550999b0918.png)

But the performance score is very bad.
![image](https://user-images.githubusercontent.com/81166195/125087664-4a647a00-e0ea-11eb-8363-42197b7a6af9.png)

Question: As the SEO score is good, can I assume that my website's search engine ranking will be good, regardless of the bad performance score?

The SEO report says

> These checks ensure that your page is optimized for search engine results ranking

**Comment by patrickhulce** [comment]
> As the SEO score is good, can I assume that my website's search engine ranking will be good, regardless of the bad performance score?

No, this is not a safe assumption. The SEO category score represents how many common SEO *mistakes* were avoided and is not a comprehensive assessment.

Your misunderstanding raises a valid point though! 

Lighthouse team, WDYT about a CWV-style audit that has a high SEO weight and represents whether LCP/CLS/TBT are passing? Wording would need to be carefully chosen to avoid confusion with actual CWV metric thresholds, but something to capture the spirit of CWV in SEO would be nice instead of easily getting 100s.

**Comment by connorjclark** [comment]
Assigning any weight to a performance part of a SEO score is going to be seen as too authoritative. We have no idea what the weighting really is in Search.

**Comment by patrickhulce** [comment]
This concern sounds like an argument against us having an SEO category score at all :) (which, to be fair, could be a possible outcome here)

If we *are* going to have an SEO category though, one that is almost always ~90+ and is missing major components of the score that we know to be considered seems rather misleading. IMO, we either try to capture the aspects of SEO we know about and can automatically check, or we punt it to plugin land.

**Comment by evolve2k** [comment]
Drawing on peoples concerns above, that it would be a real shame to loose the SEO score as it provides an important baseline to ensure that essentials are covered.

**In light of the above I'm suggesting the 'SEO' section be renamed 'SEO Essentials'.**
And the copy beneath just making clear that this is not everything but common details to get right.

Lighthouse improves overall website quality across the web and I suggest it keeps that focus.

**Comment by benschwarz** [comment]
> This concern sounds like an argument against us having an SEO category score at all :) (which, to be fair, could be a possible outcome here)

I believe removing the SEO category score (actually, all category scores 🤪) would be a _positive_ improvement. The technical SEO audits are helpful, but are in no way an exhaustive list that ensure a high listing. Having a score muddies that information.

**Comment by patrickhulce** [comment]
We're going to be updating the category description to indicate more strongly that there are *many* aspects of SEO that are not captured in the SEO category, including performance.

**Comment by vimal-mozanta** [comment]
@patrickhulce Thanks for the update. 
Now understood that - If the SEO score is above 90, we cannot safely assume that the search engine rankings will also be good.

Do we have a calculation already or a weight-age in terms of search engine ranking for both LH's performance & SEO scores?
For example, if the performance score **is above 90** and SEO score **is below 10,** what will be the level of impact in terms of search engine ranking? Will it be more critical than the use case I shared in [my first comment?](https://github.com/GoogleChrome/lighthouse/issues/12768#issue-940796557)

**Comment by patrickhulce** [comment]
> For example, if the performance score is above 90 and SEO score is below 10, what will be the level of impact in terms of search engine ranking?

No mapping of Lighthouse score to search ranking impact exists. Lighthouse is a tool to help debug and monitor signals for improvements, not the canonical explanation of all search ranking issues.

To that point, I'm not aware of any tool or document that explains the *exact* impact of all search ranking issues (nor do I think it would be a good idea for one to exist due to exploitation), but you should be able to take a look at [Search Console](https://search.google.com/search-console/about) and the *field data* section of [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/) for search's explanations.

**Comment by vimal-mozanta** [comment]
@patrickhulce - Sure, thanks for the inputs.
