### ISSUE TITLE
Unique ids with hypens reported as not unique

### ISSUE THREAD

**Issue by chrisabnorm** [GoogleChrome/lighthouse#12908]
**Describe the bug**
The lighthouse report offers as an accessability opportunity fixing IDs that are not unique in the navigation section.
But the failing elements shown have unique IDs. Even checking the source code of the website, there is no duplicate ID. As the IDs are containing hypens with another digit following, my guess is that lightouse ignores the part of the ID starting with a hypen.
The exact IDs are:
slide0-2
slide0-0

Lighthouse's output:
Failing Elements
--
a
&lt;a  href="/" id="slide0-2" class="swiper-slide  slide-white swiper-slide-duplicate swiper-slide-duplicate-next"  data-swiper-slide-index="2" style="width: 360px;">
a
&lt;a  href="/" id="slide0-0" class="swiper-slide  slide-white swiper-slide-prev" data-swiper-slide-index="0" style="width:  360px;">

**To Reproduce**
Start a test using the home page of our website (URL via private message) or set up an example page using two ids that differ just in ther suffix after a hypen.

**Expected behavior**
Reporting the unique ID check as passed.

**Comment by robdodson** [comment]
@MichaelSolati for questions about LH I usually reassign to the LH team.

In this case it sounds like it might be an axe bug.

**Comment by brendankenny** [comment]
Without a URL to test I can't confirm with complete certainty, but this looks like the audit is correct but the way Lighthouse reports it is confusing. Lighthouse shows a single element for every duplicated ID, so it's trying to say "`'slide0-2'` and `'slide0-0'` are duplicate IDs, and here's a _single example per ID_ of how they're used".

This has caused confusion, though, because for many people it looks like it's saying "here are _all_ the elements that have duplicate IDs".

Clearing that up is tracked in #10396, so I'll close in favor of that one.
