### ISSUE TITLE
Regarding Total Block Time

### ISSUE THREAD

**Issue by cantacell** [GoogleChrome/lighthouse#12904]
Misuring the total block time is not entirely correct when loading a site, because when building the page a lot of things must be done in less time as possible (tipycal a topbar, a bottom bar,  and a content). If during the load of a (fast) site, like 3-4 seconds on a low budget smartphone, an user CAN'T notice if the page is blocked for 500ms - 1 second, and not even the fastest user in the world would close the site for this. It's the same when loading a videogame. It's important to have a smooth experience during the game (so during the navigation of a site) and NOT during the loading. 
When using a framework for build SPA (like Angular and others) is impossible to reduce the TBT to 0 (when using Lighthouse >= 8.0). When using a SSR (server side rendering),  the CSR (client side rendering) HTML must be the same, so we don't introduce setTimeout else we have a bad CLS and/or LCP.
Moreover, if a page require a task of 500ms, and we split it to 10 tasks, each of 50ms, and introduce a setTimeout after each task, we will increment the TTI because the time required will be around > 600ms.
So I suggest to eliminate the TBT in the Lighthouse report or reduce it to 5% or start counting AFTER 500ms/1sec.
I repeat, in my opinion, it's important to have fast tasks DURING the navigation of a site, NOT during loading of a site.
Please argue my reasoning instead of hastily closing without even reading carefully what I reported as happened in the bug [#12882 ](https://github.com/GoogleChrome/lighthouse/issues/12882)

**Comment by patrickhulce** [comment]
> Please argue my reasoning

Will do 👍 

> If during the load of a (fast) site, like 3-4 seconds on a low budget smartphone, an user CAN'T notice if the page is blocked for 500ms - 1 second

This isn't true. 1s delays in interaction are [material contributors to abandonment](https://wpostats.com/).

> When using a framework for build SPA (like Angular and others) is impossible to reduce the TBT to 0 (when using Lighthouse >= 8.0). When using a SSR (server side rendering), the CSR (client side rendering) HTML must be the same, so we don't introduce setTimeout else we have a bad CLS and/or LCP.

Your point about typical SSR configurations with massive client-side hydrations leading to poor experiences is exactly right. Except the conclusion in our opinion should be "let's find a better way" instead of "let's lower the bar for success" 😉

PS - This sort of blocking problem is precisely why React is investing in [Concurrent mode](https://reactjs.org/docs/concurrent-mode-intro.html).

> Moreover, if a page require a task of 500ms, and we split it to 10 tasks, each of 50ms, and introduce a setTimeout after each task, we will increment the TTI because the time required will be around > 600ms.

This is a *good* tradeoff (even ignoring the fact that if you keep them to <50ms, TTI isn't affected at all), and one that would be encouraged by the scoring weights today. Keeping the main-thread completely available in exchange for 100ms later completion is great (unless of course your SSR-rendered experience is useless until that point, in which case as we covered that's a bad experience, period).

> in my opinion, it's important to have fast tasks DURING the navigation of a site, NOT during loading of a site.

Unfortunately, users don't really care about this distinction, so neither does Lighthouse. Once the page looks like it has something they want to interact with, they *will* start interacting with it, TBT helps capture this case and Lighthouse will not be diminishing its weight in the score because some development patterns make it difficult to perform well.

**Comment by cantacell** [comment]
> Your point about typical SSR configurations with massive client-side hydrations leading to poor experiences is exactly right. Except the conclusion in our opinion should be "let's find a better way" instead of "let's lower the bar for success" 
> 
> PS - This sort of blocking problem is precisely why React is investing in [Concurrent mode](https://reactjs.org/docs/concurrent-mode-intro.html).
> 
> > Moreover, if a page require a task of 500ms, and we split it to 10 tasks, each of 50ms, and introduce a setTimeout after each task, we will increment the TTI because the time required will be around > 600ms.
> 
> This is a _good_ tradeoff (even ignoring the fact that if you keep them to <50ms, TTI isn't affected at all), and one that would be encouraged by the scoring weights today. Keeping the main-thread completely available in exchange for 100ms later completion is great (unless of course your SSR-rendered experience is useless until that point, in which case as we covered that's a bad experience, period).

So a page should be loaded in pieces, like PWA with App shell strategy... Wait! PWA is not SEO friendly. But Lighthouse is used for increment ranking in SEO...

> 
> > in my opinion, it's important to have fast tasks DURING the navigation of a site, NOT during loading of a site.
> 
> Unfortunately, users don't really care about this distinction, so neither does Lighthouse. Once the page looks like it has something they want to interact with, they _will_ start interacting with it, TBT helps capture this case and Lighthouse will not be diminishing its weight in the score because some development patterns make it difficult to perform well.

Then explain this to me (see screenshoots): why a fast site loading (4s of TTI) is worse than (7s of TTI)?
A user see principally how much time the site is loading and ready to interact. In my opinion, a rigorous uptime of 50ms for a task is excessive when loading the site.
> Except the conclusion in our opinion should be "let's find a better way" instead of "let's lower the bar for success"

I mean to put a "right bar", a "real bar" (weight as a 5% - 10%, or start counting after 300ms for example).
![googlechrome github io_lighthouse_scorecalc_ (1)](https://user-images.githubusercontent.com/15688388/129076824-4900a3f4-7184-4b5f-8664-1fe747f522b2.png)
![googlechrome github io_lighthouse_scorecalc_](https://user-images.githubusercontent.com/15688388/129076831-f65b8dc8-c71b-401e-9de6-3ab6289c489f.png)

**Comment by patrickhulce** [comment]
Your responses continue to indicate that you don't believe input delay during page load is a problem. This isn't what the data demonstrates nor what Lighthouse is going to encourage, so I'm not sure further discussion is worthwhile here.

We've shared why input delay is an issue, and how TBT captures potential opportunities for input delay after load. This is why TBT is given substantial weight in the score. Even in a hypothetical future where TBT weight is reduced, it will only be because *other* metrics that capture input delay *even better* are replacing it. 

The goal of the score is not to be easy to achieve.

**Comment by cantacell** [comment]
> We've shared why input delay is an issue, and how TBT captures potential opportunities for input delay **after** load. This is why TBT is given substantial weight in the score. Even in a hypothetical future where TBT weight is reduced, it will only be because _other_ metrics that capture input delay _even better_ are replacing it.

Notice '**after**'.
> The goal of the score is not to be easy to achieve.

Never said or thought this.
> This isn't true. 1s delays in interaction are material contributors to abandonment.

You are right, but not in 1 second full loading site. It depends in which context: slow loading site or fast loading site. It is obvious that a slow and blocking site is predisposed to abandonment. I haven't seen any data showing that a fast loading site with a (ridicoulus) 500ms TBT has a lot of dropouts... If you find one please give me the link.

You don't explain my last comment:
> Or why a site that loading all in 1 second has the same score that a site that load in 7 seconds.

Is it better to have a 7 second site with a smoth scroll and semi-blank page than a fully rendered, fully ready 1 second (blocked) site? I do not believe.

> ...so I'm not sure further discussion is worthwhile here. 

Yes, I know that I'm nobody and you are a Google developer... (closing the issue!)

**Comment by leopris** [comment]
@cantacell  has reasons for reporting scoring anomalies on fast sites with some TBT. Furthermore, browsing the link I also did not find any data that confirms that the input delay on a fast loading site causes the abandonment.
Finally I believe that closing the issue with the phrase "... so I'm not sure further discussion is worthwhile here." exhibits unprofessional and constructive behavior.

**Comment by jorgellose** [comment]
"The goal of the score is not to be easy to achieve.", i believe you, the problem is when things change constantly and what is recommended one month next month is not recommended, for me PageSpeed without some kind of stability is just useless.
I remember the day i improved SSR load from 1.2s to 0.2s (if not cached) and sudenly, we lost pagespeed score becouse now fonts were blocking (http push), its like a bad joke
