### ISSUE TITLE
lighthouse-logger does not run with node 16

### ISSUE THREAD

**Issue by KnisterPeter** [GoogleChrome/lighthouse#12938]
**Summary**

[marky](https://github.com/nolanlawson/marky) used by `lighthouse-logger` does not work with node 16 currently.

Upstream issue: https://github.com/nolanlawson/marky/issues/26

**Comment by brendankenny** [comment]
Sorry this change caught you! I commented in the upstream issue too, but you'll need to update to the latest `marky` to get the fix (at least `1.2.2`).

`lighthouse-logger` has explicitly specified `marky@^1.2.2` for about a month now, but has been on `marky@^1.2.0` for nearly three years before that—since `marky` was added as a dependency—so there won't be any version conflict. If you're using a lockfile, you may have to manually trigger the update, though.

**Comment by KnisterPeter** [comment]
Thanks for the explanation. I'll update our lockfile and close this issue.
