### ISSUE TITLE
Are there artifacts for visible text ?

### ISSUE THREAD

**Issue by bacloud14** [GoogleChrome/lighthouse#13015]
I would like to code an audit for language quality (detect gibberish...). For this I came across a [tutorial ](https://www.debugbear.com/blog/custom-lighthouse-audits) showing a custom audit acting on some meta tags.

My case would be on "text elements" like value of `<h>, <p>, <blockquote>` and so.

I found 

https://github.com/GoogleChrome/lighthouse/blob/77cf83e6d61ea643c557dc843bb97d906250f145/types/artifacts.d.ts#L144

Which represents text in input elements only.

Thanks !

**Comment by paulirish** [comment]
There's not a dedicated gatherer for it nah.  

It's a little tricky because you can just have plain text nodes without a parent element. but then a line of text can also span multiple text nodes, so you wouldnt want to report just the atomic text nodes.

document.body.innerText is probably the fastest decent result..  I fear that trying to do a generalized "TextFragments"-ish collection would not work because dom/textnode structure is too unpredictable.

**Comment by bacloud14** [comment]
Ok thanks 👍
