### ISSUE TITLE
Audit: Report the SI-optimal order of resource loading and the corresponding optimal SI value

### ISSUE THREAD

**Issue by SipLoader** [GoogleChrome/lighthouse#13363]
**Feature request summary**

Using the information such as network transmission time and CPU time of each resource gathered during a test page load, Lighthouse can in fact calculate the best order of resource loading and task execution towards the (nearly) optimal Speed Index (SI) value for the web page. I am willing to develop this feature myself.

**What is the motivation or use case for changing this?**

The page load performance metric, Speed Index, reflects how quickly web page contents are populated onto the screen during the entire page load, which is more sensible compared with some other simple metrics based on a specific time instant.

Given a web page, if we know its SI-optimal loading order as well as the corresponding SI lower bound, we can decide whether we should change the priorities of resources or reduce the page complexity. In this way, we can provide users with a better visual experience during page loading.

**How is this beneficial to Lighthouse?**

Although Lighthouse reports the SI of a page load, currently it seems to provide limited suggestions on how to optimize the page for a better SI. It would be helpful to provide more informative content about SI in the report.

**Comment by paulirish** [comment]
Curious... why the focus on speed index instead of other metrics? I'm fine with it, but just curious. :)

Also.. it sounds like you're with a research group. UW? Stonybrook? Just curious.

The idea sounds interesting. 

We have some internal work that sketches out the ideal loading sequence. Here's the gist of it:

> 1. small inline 1P scripts
> 1. inlined critical CSS [preload if external]
> 1. inlined font CSS [preconnect if external]
> 1. LCP image [preconnect]
> 1. fonts (triggered from inlined font-css no. 3 above) [preconnect]
> 1. non-critical (async) CSS
> 1. first-party JS for interactivity
> 1. above-the-fold images [preconnect]
> 1. below-the-fold images
> 1. lazy loaded JS chunks


We think currently our opportunities basically hint the user to make loading order changes one-by-one, whereas this would be a larger more holistic perspective. I'm a tad worried it'd be too high level to be actionable, but still it seems there may be something valuable.

We'd be eager to see how things develop. :)

**Comment by SipLoader** [comment]
Hi Paul @paulirish, thanks for your response. Yeah, we are in a research group. :)

Indeed, the loading sequence listed above is quite reasonable, while we think it can be further improved. Specifically, we assume that the above suggestions are a bit coarse-grained -- it is not so clear what is the ideal loading sequence of the objects that fall in the same criterion. An intuitive example is that, for pages having a number of above-the-fold images, it would be better (from the web user's perspective) to load visually larger ones first. In practice, we observe that in some cases, reorganizing the loading sequence of objects in the same criterion can yield noticeable performance improvement of page loading.

In contrast, we seek to offer more detailed (at the web page object level), customized suggestions on the loading sequence of certain web pages. To be more specific, we want to provide the ideal loading sequence even for objects that belong to the same criterion. Fortunately, we find that Speed Index, as a user-oriented metric, contains fine-grained insights on how each web page object could impact the visual progress during page loading, which greatly facilitates us to generate a fine-grained loading sequence. Currently we are working on this and looking forward to integrating this small patch into Lighthouse (if possible) once we have accomplished it.

**Comment by paulirish** [comment]
Very cool! We're excited about this research. 

I'd say it's too early to commit to landing this functionality within Lighthouse, but we'd be interested in taking things for a spin.

Please feel free to keep us in the loop with your developments. :)

I'll close the issue.. not because we're not interested.. Just because it isn't an open item requiring work from our team.   Cheers!

**Comment by paulirish** [comment]
Looks like your paper was published a bit ago... congrats!!

http://www.greenorbs.org/people/lzh/papers/%5BSIGMetrics'22%5D%20Speed%20Index.pdf

@SipLoader would you think there's strong potential for Lighthouse to make a recommendation following the logic of your SipLoader work?
