### ISSUE TITLE
LayoutShifts are incorrectly marked with had_recent_input false

### ISSUE THREAD

**Issue by EdwinVanVliet** [GoogleChrome/lighthouse#13480]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.vanharen.be/nl-be/dames

### What happened?

LayoutShift which occur just after navigation are marked with had_recent_input = false, while creating a trace using Chrome F12 Application Tab results in the LayoutShifts at the start having had_recent_input = true. As Lighthouse starts the navigation to the page itself, it doesn't seem to register it as input. This causes the CumulativeLayoutShift value to to overreported. 

### What did you expect?

I expect Lighthouse to mark the LayoutShifts are had_recent_input = true to mimick a real user navigating to the page.

### What have you tried?

[Profile-20211209T171919.txt](https://github.com/GoogleChrome/lighthouse/files/7691761/Profile-20211209T171919.txt)
[Profile-20211210T101502.txt](https://github.com/GoogleChrome/lighthouse/files/7691762/Profile-20211210T101502.txt)

Trace Profile-20211209T171919.txt is made using LightHouse. All LayoutShift elements have had_recent_input = false. The second one is made using Chrome F12 Performance Tab, the LayoutShift elements are marked with had_recent_input = true here.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

8.5.0

### Chrome Version

96

### OS

Windows

**Comment by brendankenny** [comment]
This seems like it may be a Chrome bug to file in crbug.com, though maybe I'm misunderstanding the problem you're reporting.

Lighthouse doesn't control the `had_recent_input` property in trace events, so there's nothing we can do about that in this repo.

There is a subtlety, though: when Lighthouse turns on its default mobile emulation, the window size change _does_ get counted as user input by Chrome, so some LayoutShift events at the beginning of a Lighthouse trace may be unexpectedly marked with `had_recent_input: true`.  When Lighthouse calculates CLS this is dealt with automatically: https://github.com/GoogleChrome/lighthouse/blob/4bda0ed0ee6e1fecfa4ea44b1464ac59f5b28775/lighthouse-core/computed/metrics/cumulative-layout-shift.js#L26-L31

That could be part of the discrepancy you see, but Lighthouse can't do anything to change it. It's the most correct choice for Chrome to make for marking as `had_recent_input` or not, which is why Lighthouse just works around it.

See https://bugs.chromium.org/p/chromium/issues/detail?id=1094974 for more discussion.
