### ISSUE TITLE
Not able to run Lighthouse on Brave Browser

### ISSUE THREAD

**Issue by akashkoco** [GoogleChrome/lighthouse#13535]
**Summary**

Its impossible to run Lighthouse from dev tools in Brave Browser even after closing the Brave Protection.

Link: 
https://www.loom.com/share/3aff3cb19ad74804b36f0a2541414a87

**Comment by brendankenny** [comment]
I'm going to close this issue because we don't have any control over the Brave integration of DevTools/Lighthouse, so it's better to file an issue over in https://github.com/brave/brave-browser/issues (though we're happy to coordinate if they need something specific on the Lighthouse side of things).

That said, this is probably #13396, so should be fixed in the next Brave update (assuming it picks up Chromium 97) or possibly already is fixed in the Brave Beta/Dev/Nightly versions.
