### ISSUE TITLE
Background and foreground colors do not have a sufficient contrast ratio is incorrect

### ISSUE THREAD

**Issue by jwpgroup** [GoogleChrome/lighthouse#13628]
**Describe the bug**
Bright Red text on a pure white background is reported as not having sufficient contrast

**To Reproduce**
https://www.jwp.co.uk/sailing-timer.html
https://www.jwp.co.uk/reaction-timing-game.html

**Expected behavior**
No complaint re contrast

**Screenshots**
See links

**Comment by adamraine** [comment]
> If you change the colour from #FF0000 to #EE0000 it works fine. So less red is acceptable. Go figure. ;-)

This makes sense to me. Darker colors will stand out more on a bright background.

In any case Lighthouse uses https://github.com/dequelabs/axe-core for all our accessibility audits, so I would suggest moving the discussion there if you have a problem with the contrast rules.

From the Lighthouse perspective, this is WAI because axe-core and DevTools indicate `#FF0000` does not have high enough contrast.
