### ISSUE TITLE
Use an isolated execution context by default

### ISSUE THREAD

**Issue by SchmelFerenc** [GoogleChrome/lighthouse#13646]

**Comment by adamraine** [comment]
@SchmelFerenc does your page change the prototype for `Array.map`? It looks like `Array.map` called on an empty list returns undefined which is not what that function normally does.

This is causing errors in some Lighthouse gatherers. Luckily we have a solution for this, our page functions can be run in isolation. The changes in https://github.com/GoogleChrome/lighthouse/compare/increase-isolation-usage are enough to eliminate all the errors on this page.

What worries me is if gatherers are returning incorrect results instead of failing because of changes like this. It's easy to plug the holes as they pop up, but should isolated execution contexts be the default?

**Comment by connorjclark** [comment]
Adam will test if useIsolation could work. Need to verify if we can even notice event cbs assigned in the main isolated from an isolated one (is this global state or isolate-specific state??)

**Comment by adamraine** [comment]
In addition to breaking the passwords gatherer, this also breaks the `TagsBlockingFirstPaint` gatherer. Unfortunately an isolated context isn't possible here because we install our media listener on a new document which doesn't have the `useIsolation` option.
https://github.com/GoogleChrome/lighthouse/blob/586d4a2db6d6d98b8ca97c226651866b55728709/lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js#L215
 I think we can create an isolated world for each call to [Page.addScriptToEvaluateOnNewDocument](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-addScriptToEvaluateOnNewDocument), but I don't know if we can share it for when the media listener is accessed later on.

It's still possible that making isolation the default will prevent *some* issues like this, so we can keep this issue to track that part.

**Comment by brendankenny** [comment]
See #14003, if it's not clear
