### ISSUE TITLE
Lighthouse VS Funding Choices CMP

### ISSUE THREAD

**Issue by nunoperalta** [GoogleChrome/lighthouse#13666]
I am running Lighthouse through this: https://web.dev/measure/

I see that the Funding Choices CMP (cookie consent) is taking over the whole screen on the audit.
I assume this is because Lighthouse is running on a server in EU.

To get more accurate results on this report, is it possible to run Lighthouse on a server out of GDPR scope?

Some errors are due to the Funding Choices CMP.

![sshot-2022-02-15-04-29-47-1](https://user-images.githubusercontent.com/487079/153993124-ec0b84a2-39c4-472b-be81-cf8bf124059c.jpg)

![sshot-2022-02-15-04-30-10-1](https://user-images.githubusercontent.com/487079/153993129-68f9ee14-133d-4cbd-816c-9f5bbf03abde.jpg)

**Comment by connorjclark** [comment]
Presumably you control the site, can't you disable this prompt with a query parameter for testing?

**Comment by connorjclark** [comment]
The PSI/web.dev APIs will select a server based on where the request comes from. You can influence this process by using a VPN. Other than that, there isn't a way.

I suggest using a query parameter to suppress this feature, and also to _force_ it, and monitor both versions' Lighthouse reports. Because real users are hitting this and the issue the report shows is still relevant, even if this is just for the initial visit.

**Comment by nunoperalta** [comment]
Thanks, and I understand.
About the low-res issue reported, I provided a 200x200 image, but it's Google FC that reduced it to be low-res :-)

Many/most issues I get usually come from Analytics, AdManager or Ads.
No much we can do! (but I'm glad they're reported in Lighthouse, at least)

Kind regards.
