### ISSUE TITLE
Performance numbers with custom audit are very high

### ISSUE THREAD

**Issue by johnpmitsch** [GoogleChrome/lighthouse#13726]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

forum.minervaproject.com

### What happened?

Including a custom audit results in very high performance values, see screenshot below:

![Screen Shot 2022-03-08 at 9 29 20 AM](https://user-images.githubusercontent.com/5964462/157258579-35f2c4e2-dc4c-46a2-9c90-7afc89969343.png)

Here is my LH config:

```js
const lhDesktopConfig = require('lighthouse/lighthouse-core/config/lr-desktop-config.js')

module.exports = {
	// 1. Run your custom tests along with all the default Lighthouse tests.
	extends: 'lighthouse:default',

	// 2. Add gatherer to the default Lighthouse load ('pass') of the page.
	passes: [{
		passName: 'defaultPass',
		useThrottling: false,
		gatherers: [
			'./performance/gatherers/dashboard-gatherer',
			'./performance/gatherers/breakout-gatherer',
		],
	}],

	// 3. Add custom audit to the list of audits 'lighthouse:default' will run.
	audits: [
		'./performance/audits/dashboard-audit',
		'./performance/audits/breakout-audit',
	],

	// 4. Create a new 'My site metrics' section in the default report for our results.
	categories: {
		Forum: {
			title: 'Forum Metrics',
			description: 'Custom metrics for Forum',
			auditRefs: [
				// When we add more custom audits, `weight` controls how they're averaged together.
				{id: 'dashboard-audit', weight: 1},
				{id: 'breakout-audit', weight: 1},
			],
		},
	},
	settings: {
		formFactor: "desktop", // tells lighthouse to evaluate as desktop
		screenEmulation: { disabled: true }, // don't emulate mobile or resized screen
		// The performance scores are really long when custom 'Forum' audit is included, not sure why
		onlyCategories: ['Forum', 'performance'], // can add more categories like 'accessibility' here
		emulatedUserAgent: lhDesktopConfig.settings.emulatedUserAgent,
	}
};
```

If I change `onlyCategories: ['Forum', 'performance'],` to `onlyCategories: ['performance'],`, I get the numbers I would expect to see:
![Screen Shot 2022-03-08 at 9 37 44 AM](https://user-images.githubusercontent.com/5964462/157259767-294677dd-a55b-4beb-9040-16be3eb5fae2.png)

### What did you expect?

A custom audit would not affect the performance category

### How were you running Lighthouse?

node

### Lighthouse Version

lighthouse@9.3.0

### Chrome Version

94.0.4585.0

### Node Version

14.17.1

### OS

Mac

**Comment by connorjclark** [comment]
Can you try not setting `useThrottling: false` in your pass override config?

**Comment by johnpmitsch** [comment]
No luck unfortunately, numbers still look the same

![Screen Shot 2022-03-08 at 3 34 35 PM](https://user-images.githubusercontent.com/5964462/157320338-bca6fe51-b29c-4abf-92ba-fe63afdd8f1e.png)

Current settings:
```js
// This is the basic desktop settings that we can use for screen size and some basic throttling
const lhDesktopConfig = require('lighthouse/lighthouse-core/config/lr-desktop-config.js')

module.exports = {
	// 1. Run your custom tests along with all the default Lighthouse tests.
	extends: 'lighthouse:default',

	// 2. Add gatherer to the default Lighthouse load ('pass') of the page.
	passes: [{
		passName: 'defaultPass',
		useThrottling: false,
		gatherers: [
			'./performance/gatherers/dashboard-gatherer',
			'./performance/gatherers/breakout-gatherer',
		],
	}],

	// 3. Add custom audit to the list of audits 'lighthouse:default' will run.
	audits: [
		'./performance/audits/dashboard-audit',
		'./performance/audits/breakout-audit',
	],

	// 4. Create a new 'My site metrics' section in the default report for our results.
	categories: {
		Forum: {
			title: 'Forum Metrics',
			description: 'Custom metrics for Forum',
			auditRefs: [
				// When we add more custom audits, `weight` controls how they're averaged together.
				{id: 'dashboard-audit', weight: 1},
				{id: 'breakout-audit', weight: 1},
			],
		},
	},
	settings: {
		formFactor: "desktop", // tells lighthouse to evaluate as desktop
		screenEmulation: { disabled: true }, // don't emulate mobile or resized screen
		// The performance scores are really long when custom 'Forum' audit is included, not sure why
		onlyCategories: ['Forum', 'performance'], // can add more categories like 'accessibility' here
		emulatedUserAgent: lhDesktopConfig.settings.emulatedUserAgent,
	}
};```

**Comment by johnpmitsch** [comment]
Numbers still look the same without that unfortunately:

```js
// This is the basic desktop settings that we can use for screen size and some basic throttling
const lhDesktopConfig = require('lighthouse/lighthouse-core/config/lr-desktop-config.js')

module.exports = {
	// 1. Run your custom tests along with all the default Lighthouse tests.
	extends: 'lighthouse:default',

	// 2. Add gatherer to the default Lighthouse load ('pass') of the page.
	passes: [{
		passName: 'defaultPass',
		gatherers: [
			'./performance/gatherers/dashboard-gatherer',
			'./performance/gatherers/breakout-gatherer',
		],
	}],

	// 3. Add custom audit to the list of audits 'lighthouse:default' will run.
	audits: [
		'./performance/audits/dashboard-audit',
		'./performance/audits/breakout-audit',
	],

	// 4. Create a new 'My site metrics' section in the default report for our results.
	categories: {
		Forum: {
			title: 'Forum Metrics',
			description: 'Custom metrics for Forum',
			auditRefs: [
				// When we add more custom audits, `weight` controls how they're averaged together.
				{id: 'dashboard-audit', weight: 1},
				{id: 'breakout-audit', weight: 1},
			],
		},
	},
	settings: {
		formFactor: "desktop", // tells lighthouse to evaluate as desktop
		screenEmulation: { disabled: true }, // don't emulate mobile or resized screen
		// The performance scores are really long when custom 'Forum' audit is included, not sure why
		onlyCategories: ['Forum', 'performance'], // can add more categories like 'accessibility' here
		emulatedUserAgent: lhDesktopConfig.settings.emulatedUserAgent,
		}
	}
```
![Screen Shot 2022-03-08 at 3 42 07 PM](https://user-images.githubusercontent.com/5964462/157321508-373bbe3b-bb5a-470b-8aea-1b1c27841192.png)

**Comment by connorjclark** [comment]
Shoot, was hoping it'd be that simple!

Can you share

1) the report you are screenshotting (click upper right menu for share options)
2) the custom audit code (probably not relevant... auditing phase shouldn't affect metrics like this)

**Comment by johnpmitsch** [comment]
> Shoot, was hoping it'd be that simple!

I was too! :) 

I set up a reproducer and some example reports here https://github.com/johnpmitsch/lighthouse_repro/tree/main

I'm using news.ycombinator.com, so it's a much more subtle difference, but I'm consistently seeing different performance metrics if I remove the custom audit. The difference seems to correspond with how long the custom audit is taking too. Let me know if you need any more info or examples!

**Comment by connorjclark** [comment]
OK, so since you have a custom gatherer, this all make sense. The operations you are doing:

1) creating a pupeteer page object, wrapping the existing target Lighthouse opened. Seems OK, certainly unusual though wrt how our gathering is meant to work. Are you aware that you can just use the driver directly? (of and FYI, that param is called _context_ not _options_, small nit https://github.com/GoogleChrome/lighthouse/blob/048847f4ff66f69f9b4cf77e7680718fbb574ee1/lighthouse-core/fraggle-rock/gather/base-gatherer.js#L86 

2) reloading the page. 100%, you shouldn't do this. The assumption is that gatherers just read the page state, not navigate it. We have an entire lifecycle that handles navigation that gets messed with when you reload the page in a gatherer. This is the reason you get wonky metrics

I think your intention with this gatherer is to get how long this element takes to paint–although, as it is, you are really getting _how long until it exists in the DOM_. is that correct? If so, you should probably use the [Element Timing API](https://developer.mozilla.org/en-US/docs/Web/API/Element_timing_API). I assume you own this page: you will need to add `elementtiming` attribute to the element you want to track.

As it stands, you'd still need a custom gatherer for this, and have to setup the DOM observer yourself. You shouldn't need to refresh the page, just  But this use case seems pretty useful in general, Lighthouse should itself collect all the element timings on the page and display it next to the metrics. We'll have to discuss this.

Note: for the observer you probably want to pass the `buffered: true` option, which may be needed if the element of interest has already been rendered by the time you install the observer. that, or use `driver.executionContext.evaluateOnNewDocument` in the gatherer `beforePass`.

**Comment by johnpmitsch** [comment]
> reloading the page. 100%, you shouldn't do this. The assumption is that gatherers just read the page state, not navigate it. We have an entire lifecycle that handles/monitors navigation (to know when to stop measuring the metrics) that gets messed with when you reload the page in a gatherer. This is the reason you get wonky metrics

Thanks for the help, that is interesting. I was hoping to use Lighthouse to measure the speed of user interactions, like [user flows](https://www.debugbear.com/blog/lighthouse-user-flows), but it sounds like this isn't supported in a custom audit? Is there any way to test this kind of navigations with LH?

**Comment by connorjclark** [comment]
Can you explain why you are using a custom audit for this? The article you linked to and our guide [here](https://github.com/GoogleChrome/lighthouse/blob/master/docs/user-flows.md) show a new feature in Lighthouse for scripting user interaction, but it isn't done via custom audits.

**Comment by johnpmitsch** [comment]
I was hoping to have a large amount of flows tested but have the results in one report, so we would also have an overall score for the custom flows, like the overall score you would get for a group of custom audits. Basically have everything summarized in one report. 

It seems like each flow will have it's own report/dataset? Zooming out, we basically want to track how long common user actions take and graph that over time. It would be great to do something like this with lighthouse and lighthouse-ci.

IIUC the limitations, I think the flows as described in the guide will be a good fit for us though, especially if we can grab the data from them and do our own storage and analysis of that data. So we'll probably use lighthouse for the out-of-the-box performance metrics and do a more custom data analysis on the flows. I'm open to suggestions though :)

**Comment by connorjclark** [comment]
> It seems like each flow will have it's own report/dataset?

There is an overview page for the user flow report ([example](https://ivy-cloudy-blackcurrant.glitch.me/)). Is this what you have in mind? In your case, if the interaction of interest is just the navigation then you'll just do a `flow.navigate` and each call to that will be its own row in this summary page. If you have a custom category that will show too.

As long as you do everything in a single script, you'll get it all in one summary report. That could get really big though depending on your scale. The data format is pretty [straightforward](https://github.com/GoogleChrome/lighthouse/blob/048847f4ff66f69f9b4cf77e7680718fbb574ee1/lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json#L2) too, so you could even do it in multiple "scripts" and just combine the resulting flow LHRs/steps.

> Zooming out, we basically want to track how long common user actions take and graph that over time.

Lighthouse CI solves this use case, although it hasn't been updated to work with user flows yet. So for now you'll either have to do something custom or instead track (in LHCI) each page separately (again, no flow/interaction support yet, so this is limited to navigations).

Note: when relevant, make sure your navigation in the user flow script is actually simulating a user interaction (as opposed to just refreshing the page, like the custom gatherer you have does): otherwise you miss out on potential issues related to JS/click handlers. ex:

```
// Navigate with a callback function
  await flow.navigate(async () => {
    await page.click('a.link');
  });
```

**Comment by johnpmitsch** [comment]
@connorjclark Thanks, this is super helpful! I'll give the multiple flows a shot and we'll do something custom to track this info to start.

Thanks again for clarifying everything 🙏🏻
