### ISSUE TITLE
Various canonical url protocols should be allowed

### ISSUE THREAD

**Issue by g-u-r-k-a-n** [GoogleChrome/lighthouse#13786]
I am using .NET Core View's razor engine for the project and if you are using the same protocol, the output format is coming as "//". That's why I get the warning that it's not best practice. 

![image](https://user-images.githubusercontent.com/55924924/160297014-e6643bfb-f990-4fe0-bc83-46b540549ce4.png)

![image](https://user-images.githubusercontent.com/55924924/160296816-d24fd174-e578-4886-9109-f3129ca194bb.png)

Actually, the html code contains the protocol but is not rendered in the output. 

**_Layout.cshtml**
`<link rel="canonical" href="https://gurkantuna.com" />`

I tried many ways to get it as `https://` but no matter what i do i can't change the protocol in the html output. I'm thinking you should allow various protocols for html output. If not, how can I pass the warning?

**Comment by connorjclark** [comment]
Read https://web.dev/canonical/ carefully. This value needs to be an absolute URL for search engine optimization. This sounds like a failure with the framework you are using, I suggest you file a bug there.

The way you have it, there is no canonical url for the page, because "//..." means the url changes based on if the user is on http or https.
