### ISSUE TITLE
Make gather errors use a super class function

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/lighthouse#138]
There's a probability a bunch of gathers will fail. At the moment we have a class-level method in the manifest gatherer to capture its failure: https://github.com/GoogleChrome/lighthouse/blob/master/gatherers/manifest.js#L47-L55

This should get moved to the Gather parent class. I'll do it, but we have a lot of PRs open, so I'll wait till they are merged or rejected before proceeding.

**Comment by samccone** [comment]
using flat objects + Object.assign(...) would also make this easy :goat:

**Comment by paullewis** [comment]
@samccone Look at you all ES5in'. :snowman:

**Comment by brendankenny** [comment]
So I added that function because the manifest-parser was already using `debugString` on that object to indicate top level errors, like the manifest being invalid JSON, so I just hitched the fetching errors to that. Not sure if it will be a generally useful model.

I'd like to see where #81 is going, as that will likely end up with a major refactoring of the gatherers, and it starts showing the spectrum of error states we'll need to be able to express (artifact not collected because the extension doesn't refresh the page by default, artifact not collected because the CRI blew up and you need to try again, started collection but invalid for these particular reasons so the gather can't continue to its end,  collected but we hit a situation we don't handle yet, etc etc)
