### ISSUE TITLE
no element screenshots in timespans

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#13983]
It appears that it has been this way since at least 9.0 (e.g. see the "Avoid large layout shifts" audit in [this report from the user-flows article](https://abaft-burnt-title.glitch.me/#index=1)), even in simple timespans with no navigations and no dynamic DOM or changing styles.

`lhr.audits['full-page-screenshot'].details.nodes` is always empty, so detals-renderer assumes the element wasn't in the DOM at the time of the screenshot and you always get just the outerHTML and snippet:

https://github.com/GoogleChrome/lighthouse/blob/62bd5783a14fbf87dd98a1bd3d3e0eea90994098/report/renderer/details-renderer.js#L515-L516

I haven't dug too far into this, but from a quick debug it looks like `__lighthouseNodesDontTouchOrAllVarianceGoesAway` is always `undefined` (both with and without isolation) when the `full-page-screenshot` gatherer goes looking for it:

https://github.com/GoogleChrome/lighthouse/blob/62bd5783a14fbf87dd98a1bd3d3e0eea90994098/lighthouse-core/gather/gatherers/full-page-screenshot.js#L148

Is this expected? I couldn't find any discussion of this before, and I can't think of anything fundamental about timespans that would prevent this from working

**Comment by brendankenny** [comment]
Interestingly, the sample flow report does have element screenshots, so maybe I'm wrong that it's always true for timespans, but for all my timespan scripts and some random tests with timespans in DevTools all have missing `nodes`

**Comment by adamraine** [comment]
I think the root cause is https://github.com/GoogleChrome/lighthouse/pull/13881#discussion_r854394936. Most but not all element collecting gatherers run after the FPS. I'll make a PR to fix this.

Honestly we could consider disabling FPS for timespans. The gatherer is pretty disruptive as is and theoretically there isn't anything special about the end of a timespan. Unfortunately, this opens a whole can of worms about gatherers only looking for elements at the end of a run.
