### ISSUE TITLE
token store in sessionStorage

### ISSUE THREAD

**Issue by Fangtzu1024** [GoogleChrome/lighthouse#14065]
I have a web app, which is built by react. the page is protected by a login page
after login, a token is stored in sessionStorage, then jump to home page

I want to use puppeteer to login first, in a seprate tab, and at some point when lighthouse begin to load the url(another tab, would not inherit the tokens),  and in the targetchange listener inject the token to sessionStorage. but failed with "Provide URL did not match initial navigation URL", How to make lighthouse wait for inject the token, or lighthouse does not open new tab?please help. Thanks

![pic](https://user-images.githubusercontent.com/106508004/170936979-0b3bedde-5dc3-42cb-be7b-c1db198e2381.PNG)

**Comment by Fangtzu1024** [comment]
> Have you checked out https://github.com/GoogleChrome/lighthouse/blob/master/docs/authenticated-pages.md?

Yes, I use option1 Script the login with Puppeteer. use puppeteer login and token store in sessionStorage，when run lighthouse always at login page because lighthouse open another tab and can not inherit the tokens.

Have any other solutions? please help, thanks.

**Comment by Fangtzu1024** [comment]
Please help~~~

**Comment by adamraine** [comment]
> Yes, I use option1 Script the login with Puppeteer. after use puppeteer to login and token stores in sessionStorage, and then run lighthouse always at login page because lighthouse open another tab and can not inherit the tokens.

I see, the login status is not shared between tabs because you are using `sessionStorage`. You have a couple options here which are currently experimental features.
- Test the login interaction using a [user flow](https://github.com/GoogleChrome/lighthouse/blob/master/docs/user-flows.md)
- LH 10.0 will change how the standard `lighthouse()` API to accept a puppeteer page directly. You will either have to wait for 10.0 to be released or clone the master branch from this repo.
