### ISSUE TITLE
`yarn smoke` should always take into account our current known test failures

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#14127]
We often disable tests that are not working by one of two ways:

1) Comment out the assertion in the expectation file
2) Skip the smoke test in CI / .yml

The second approach has the unfortunate result that using `yarn smoke` locally will also run known-failing tests, muddying the results.

Example: `yarn smoke --runner devtools` will fail for any fixtures that redirect because the browser will follow that redirect _before_ Lighthouse panel even starts. So we disable those tests in CI https://github.com/GoogleChrome/lighthouse/blob/e776c8620dc6774b6bf90a0769aa6f5de273b789/.github/workflows/devtools.yml#L180 . meaning all those tests still fail locally.

Instead, we should add an `exclude` property to the test expectation interface:

<img width="266" alt="image" src="https://user-images.githubusercontent.com/4071474/173681887-7f9f9142-783e-4dc7-8a6c-d7fe9937a2b5.png">

The smoke test runner should skip this test if the exclude array contains the runner.

Can also take into account wholesale exclusion from every runner if `exclude` is `true`.

May want to provide a flag in smoke test runner to ignore this exclusion (for purposes of testing/fixing broken smokes).

**Comment by brendankenny** [comment]
In an ideal world all the runners would run all the smoke tests, and the exclusions should be as noisy as possible to motivate getting us to that goal. Having exclusions diffused across smoke tests makes that easy to miss and hard to survey where we need work.

What about a central list of exclusions (literally `runner-exclusions.js` or whatever with arrays for each runner)? That would keep them in one place (can even see cross-runner support, unlike in the current yml files) and allow an easy place for comments explaining exclusions, etc.

- For removing from all runners, that happens so rarely that commenting out of `core-tests` seems fine, rather than adding an additional level of exclusion.

- `--ignore-exclusions` also seems like overkill for now. The only time you'd need this is if you're testing an excluded smoke test, and in that situation you're likely focused on a test or group of tests, not _all_ the excluded tests (e.g. if you did `yarn smoke --runner devtools --ignore-exclusions` today, you're going to have a really bad time when you hit `errors-expired-ssl`). It seems like if you include a requested test by name (`yarn smoke --runner devtools oopif-scripts`) it should ignore the exclusion list in that case, basically only do the exclusions in this branch:
-
