### ISSUE TITLE
NO_FCP for unknown reason

### ISSUE THREAD

**Issue by nstringham** [GoogleChrome/lighthouse#14129]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://othello-rust.web.app/

### What happened?

I get a NO_FCP error

### What did you expect?

Lighthouse should give me a report

### What have you tried?

I have tried running lighthouse from PageSpeed Insights and from Chrome dev tools on mobile and in desktop modes

### How were you running Lighthouse?

PageSpeed Insights, Chrome DevTools, web.dev

### Lighthouse Version

9.5.0

### Chrome Version

102.0.5005.115

### OS

Windows 11

### Relevant log output

I don't how to get logs

**Comment by adamraine** [comment]
No elements qualify as the FCP:
https://web.dev/first-contentful-paint/#what-fcp-measures
https://web.dev/fcp/#what-is-fcp

You don't have an LCP either so, please have a look at:
https://web.dev/lcp/#what-elements-are-considered

**Comment by rayjenn** [comment]
Why does the mpg and hmep not line up? Sent from Mail for Windows From: Adam RaineSent: Wednesday, June 15, 2022 12:45 PMTo: GoogleChrome/lighthouseCc: SubscribedSubject: Re: [GoogleChrome/lighthouse] NO_FCP for unknown reason (Issue #14129) No elements qualify as the FCP:https://web.dev/first-contentful-paint/#what-fcp-measureshttps://web.dev/fcp/#what-is-fcpYou don't have an LCP either so, please have a look at:https://web.dev/lcp/#what-elements-are-considered—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> 



	
		
			
				
			
		
		
			
				This email has been checked for viruses by Avast antivirus software.
				www.avast.com
