### ISSUE TITLE
Align TTFB audit with CrUX TTFB threshold

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#14255]
https://web.dev/time-to-first-byte/ describes the TTFB audit as using a threshold of 600 ms.
https://web.dev/ttfb/ describes general TTFB best practices and recommends a threshold of 800 ms for good performance.

This discrepancy is causing a bit of [confusion](https://groups.google.com/a/chromium.org/g/chrome-ux-report/c/aKYRqmkl3LM/m/xc9lh2drAAAJ).

Lighthouse also seems to be measuring server response time (SRT) which is a subset of the total TTFB time. Should the name be changed to reflect that? Or if we continue to call it TTFB, should we align the thresholds to 800 ms?

As a general comment, it's also potentially confusing that the web.dev URL having the full metric name (`time-to-first-byte`) corresponds to the Lighthouse audit while the abbreviation (`ttfb`) corresponds to general best practices. It may be worth separating them more cleanly.

**Comment by brendankenny** [comment]
There's no `time-to-first-byte` audit since #10735, so this is probably a docs bug (the article needs to be renamed to `server-response-time` and the existing one redirected to it).

600ms is mostly a [consequence of DevTools throttling](https://github.com/GoogleChrome/lighthouse/blob/c31a92a2224b8d491f22a95278f1b7a4f87acdc3/core/audits/server-response-time.js#L25-L27), but even with simulated throttling it's not clear what the changed threshold should be. Redirects handling is very different across LH platforms (e.g. in DevTools you'll almost never get a redirect because you're almost always already on the redirected page), so the separately focused audits (`server-response-times` and `redirects`) has been the solution, even if it leaves Lighthouse without a direct TTFB lab audit.
