### ISSUE TITLE
Lighthouse score doesn't match

### ISSUE THREAD

**Issue by JamieSummers** [GoogleChrome/lighthouse#14290]
**Describe the bug**
Am getting a Performance score of 21/26 on Lighthouse, but it's showing we're in the Yellow (in Lighthouse, see snip attached), and Pagespeed Insights is giving us an 87 on mobile.  

**To Reproduce**
Run a Lighthouse report on https://www.mcobject.com/

**Expected behavior**
Clear page speed results.  Is the site failing? Or average?  Why does the color differ from the score?  And why is the score so very different from Pagespeed Insights? 

**Screenshots**
Attached
![Capture](https://user-images.githubusercontent.com/33559406/183763912-de79f961-632f-446b-8899-116c00bca20e.JPG)

**Comment by adamraine** [comment]
You are using Lighthouse in timespan mode which tells you how many audits passed instead of calculating a performance score. If you want to get a performance score, you need to run Lighthouse in navigation mode. Checkout https://github.com/GoogleChrome/lighthouse/blob/master/docs/user-flows.md for more info.
