### ISSUE TITLE
Show metrics to more precision please

### ISSUE THREAD

**Issue by muster-mark** [GoogleChrome/lighthouse#14339]
I wanted to test if adding a `<link rel="preload">` for my page background image made a difference to the LCP, and if so how much. I ran the lighthouse audit 5 times before making the change, and the LCP was 1.2s each time. I made the change then ran the lighthouse audit 5 more times. Again, it was 1.2s each time. I learnt nothing, though I suspect if the metric was shown to greater precision, I might have found there was a small difference. But I have no way of telling (or do I?). Anyway, it would be great if these metrics were shown to greater precision, if not by default then perhaps when hovering over them.

**Comment by brendankenny** [comment]
Metrics are available in higher precision in the underlying report JSON (either "Save as JSON" from the top-right menu or available as `window.__LIGHTHOUSE_JSON__` if you have an independent HTML report).

However: those numbers are subject to variance (e.g. what the server, network, device, browser, etc were doing at the same time the page was loaded) so if the difference is less than the 100ms displayed in the report, you're going to need more than a few measurements to see it clearly in the data available.

There's also the possibility there was no LCP difference between the two scenarios. For instance, if the browser can statically determine the background image from the initial HTML, or other load steps are required before the image is displayed but take longer than it does to find and download the background image, then it doesn't matter whether or not the LCP image was preloaded.

**Comment by muster-mark** [comment]
Thanks for pointing out about the JSON file.

I am not quite sure as you do not go far as to say so explicitly, but it seems to me as if you are suggesting that the figures are only shown to 1 decimal point to protect people from themselves who might otherwise just run the report once for each A/B scenario, see that there is a difference and belive they have a statistically significant result. While I can't be certain that the same could be said of the general population, I think that the vast majority of people who are in the business of running lighthouse audits would be familiar with the fact that page load times are subject to a certain amount of variance due to myriad factors, and numerate enough to realise that the only way of dealing with this is to take multiple measurements and average.

The irony is that by forcing users to access the JSON file to get the data they need, this makes this process take about twice the amount of time it would otherwise.

**Comment by connorjclark** [comment]
All the data is in the JSON, and the HTML report show just what we consider to be significant (which is codified in the LHR result too, FWIW, but the raw value is there for you).

**Comment by muster-mark** [comment]
So just to clarify, when you say you show just what you consider to be significant, you mean that you consider the 2nd decimal place to be insignificant? I had figured this was the case.

However, Let me show you some data that might convince you otherwise. I ran lighthouse on my homepage 10 times and the results were as follows (figures in ms).

- 1198
- 1180
- 1176
- 1201
- 1188
- 1168
- 1199
- 1169
- 1194
- 1185

That has a standard deviation of 12.3ms. So a granularity of 0.1s is therefore a little over 8 standard deviations. Clearly, in this instance, truncating to 1 decimal place therefore hides some significant information.

**Comment by brendankenny** [comment]
This conversation is focusing on precision when really the problem is precision _and_ accuracy, as well as magnitude of effect.

Lighthouse is a lab tool, allowing fast generation of very tight confidence intervals if need be, but the more precise you can be, the question of how accurately Lighthouse can simulate real visitors becomes much more pressing. Running Lighthouse a bunch of times gives a distribution of what Lighthouse sees while running the page, but you really need to sample from the full distribution of users to do a real statistical test. For example, what might be a small improvement on desktop might be a small penalty on mobile due to bandwidth or memory limitations

Requiring a change to more clearly be an improvement before it's presented (by rounding metric values) somewhat mitigates this problem.

But, again, the full value is in the JSON. Putting it there also has the benefit of aligning with the fact that anyone doing this kind of analysis won't generally be manually copy/pasting the value out of 30 Lighthouse reports at a time, instead reading it programmatically from the node module or CLI.
