### ISSUE TITLE
Improve detection of quirks mode

### ISSUE THREAD

**Issue by Thomas789s** [GoogleChrome/lighthouse#14570]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.example.com

### What happened?

This is the response Lighthouse issues for pages with valid legacy doctypes like HTML 4.01 and XHTML 1.0, but all browsers I tested issue 'CS11Compat' (i.e. Standards Mode) for those. So the Lighthouse response is clearly a bug.

### What did you expect?

Accept valid doctypes

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

Sorry, no version number given (latest website version)

**Comment by Thomas789s** [comment]
See for instance https://www.sheldonplc.co.uk/ . All browsers issue " CSS1Compat " for this, which is not Quirks mode as Lighthouse claims (this would be "BackCompat). Issuing an HTML5 doctype  <!DOCTYPE html> for this (as Lighthouse suggests in the link https://web.dev/doctype/?utm_source=lighthouse&utm_medium=lr ) does not validate in W3C (contrary to the present Doctype)

**Comment by adamraine** [comment]
Ah I see what you're saying now. The audit could probably use a non-empty `publicId` as a diagnostic rather than a failure condition, and then use `document.compatMode` to determine if we are in quirks mode.

The problem is that [Limited-quirks mode](https://en.wikipedia.org/wiki/Quirks_mode#:~:text=Limited%20quirks%20mode%5Bedit%5D) can be used even with `compatMode === 'CSS1Compat'`. I see a few options for how to handle this:
- Treat limited-quirks mode the same as no-quirks mode, just pass the audit
- Issue a warning about limited-quirks mode if `compatMode === 'CSS1Compat'` and either publicId or systemId is not empty
- Exhaustively implement [every publicId / systemId case](https://en.wikipedia.org/wiki/Quirks_mode#:~:text=Comparison%20of%20document%20types%5Bedit%5D)
