### ISSUE TITLE
Rule Weighting / Scoring Feels Wonky

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/lighthouse#1460]
Over the past week or so I've been spending some time using lighthouse as part of my integration tests for a new version of my site.

After getting the performance audits passing (i.e. request chain down, async loading CSS) the score was relatively low. For  a basic page, no service worker or any "PWA" features I get: 38/100

I added theme color meta tag and a manifest with the all the required fields and the score jumps to 73/100.

The weighting feels off here. Manifest is not a big ask but results in a large boost.

Couple of ideas:

1. Include top level scores for PWA-y-ness, Performance, and Best Practice.
    - This gives some notion that developers should tune their web apps for different aspects
1. Change weighting so that adding a manifest is not such a big score booster. I.e. Adding offline support is inherently more difficult than adding a manifest - does the scoring match that?

**Comment by MatthiasWinkelmann** [comment]
I believe there's a basic assumption that you are going for a PWA with lighthouse. So a site could be perfectly tuned for its use-case, yet score low. That would happen with anything that isn't trying to get on users' home screens, for example. I'd agree that it'd seem useful to me if the scope were expanded to better serve those use cases, but maybe I'm fundamentally mistaken and offline capabilities etc. are recommended for every site?

Regarding your (2) I believe the scoring should (and currently does) reflect user experience, because that's what it's trying to improve. The difficulty/cost/etc of implementing a features is irrelevant in that regard, so don't interpret it as your personal grade. If there are "easy wins" to be had and the score motivates people to go for them first then it's working as intended.

**Comment by paulirish** [comment]
We did both of the two suggestions. :)  Thanks for filing this one, Matt!
