### ISSUE TITLE
--Output=json not parseable

### ISSUE THREAD

**Issue by pedro93** [GoogleChrome/lighthouse#1475]
When using the flag --output=json the output of lighthouse is not a valid JSON.

Using:
```
lighthouse --perf https://github.com --output=json > log.txt
```

Data in log.txt:
```
Launching Chrome...
created /var/folders/3h/zr7yb38n7yvgx5vqrn5_3cz0f3z0zs/T/lighthouse.XXXXXXX.l0awwJI0
Chrome running with pid = 73742
Waiting for browser.....[32m✓[0m
{
  "lighthouseVersion": "1.1.6",
  "generatedTime": "2017-01-16T15:43:32.299Z",
  "initialUrl": "https://github.com",
  "url": "https://github.com/",
  "audits": {
    "first-meaningful-paint": {....
}
Killing all Chrome Instances
Removing /var/folders/3h/zr7yb38n7yvgx5vqrn5_3cz0f3z0zs/T/lighthouse.XXXXXXX.l0awwJI0
```

As you can see the first 4 lines are not JSON. Perhaps forgotten logs?
There are the lines that generate the logs:

https://github.com/GoogleChrome/lighthouse/blob/3e1ddb6d72f7890c6c34096f5c6a8e6f45610124/lighthouse-cli/bin.ts#L213
https://github.com/GoogleChrome/lighthouse/blob/2a0a8d0e40a1b186f3aea5842b100da4ec7ad25a/lighthouse-cli/chrome-launcher.ts#L119
https://github.com/GoogleChrome/lighthouse/blob/2a0a8d0e40a1b186f3aea5842b100da4ec7ad25a/lighthouse-cli/chrome-launcher.ts#L163
https://github.com/GoogleChrome/lighthouse/blob/2a0a8d0e40a1b186f3aea5842b100da4ec7ad25a/lighthouse-cli/chrome-launcher.ts#L211
https://github.com/GoogleChrome/lighthouse/blob/2a0a8d0e40a1b186f3aea5842b100da4ec7ad25a/lighthouse-cli/chrome-launcher.ts#L232
https://github.com/GoogleChrome/lighthouse/blob/2a0a8d0e40a1b186f3aea5842b100da4ec7ad25a/lighthouse-cli/chrome-launcher.ts#L253

**Comment by ebidel** [comment]
By default, lighthouse will pipe to stdout. `--output=json` will output the final results as json, but we also include logging information during the run. So directing to a file won't work as expected.

If you're trying to save the JSON file to a file, also use `--output-path`:

    lighthouse --perf https://github.com --output=json --output-path=results.json

**Comment by brendankenny** [comment]
> "lighthouseVersion": "1.1.6",

this is a pretty old version of Lighthouse (early October).

In #774 logging in those files was moved to using the [`log`](https://github.com/GoogleChrome/lighthouse/blob/97d48d31d61d9743ce27f1177ee08023de0cc97f/lighthouse-core/lib/log.js) class instead of `console.log`. `log` uses `stderr` for logging (via [debug](https://www.npmjs.com/package/debug)) so doesn't interfere with redirecting `stdout` to file.

`lighthouse --perf https://github.com --output=json > log.txt` works and is valid JSON in Lighthouse 1.1.7+.

(`--quiet` is also available and silences *all* logging as of 1.2.0, but you really should update to latest as we've [fixed a lot of things since then](https://github.com/GoogleChrome/lighthouse/releases) :)

**Comment by pedro93** [comment]
Thank you, somehow I forgot to check the version.

**Comment by ebidel** [comment]
Nice @brendankenny. It does work in later versions.

...now I feel silly for using `--output-path` for so long.
