### ISSUE TITLE
Consider adding Chrome stable to Travis matrix

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#1480]
Context: Recently CSS usage broke Lighthouse master on Chrome stable since the protocol method wasn't added until v56 (#1473). 

It would be great to have Travis automatically check against these types of errors. Not sure how we would want to handle the failures/tests though since we would still want to ensure the smoke tests for canary were run.

**Comment by brendankenny** [comment]
Simplest solution: smoke tests take a combined ~1.5 minutes on travis right now. We could easily download Chrome latest *and* Chrome stable and just double that up. Obviously that's a lot of duplication of work, though, and only going to get more painful as the smoke tests grow.

**Comment by patrickhulce** [comment]
Oh @brendankenny I took that as a given, I meant more how do we handle the failures that result because stable lacks the feature support. Example: the CSS usage gatherer will fail on stable as expected and set a debug string which won't pass the expectations file. Should we maintain separate expectations, mark as OK to fail, etc?

**Comment by wardpeet** [comment]
what do you guys think about 2 travis checks? I for code linting & 1 for smokehouse?

**Comment by brendankenny** [comment]
for these differences between stable and canary, I think we're just going to have to go back to being stricter about not landing new audits or driver commands until supported by Chrome stable, rather than having a different expectation for each version.

This will still be a bit hard with audit changes due to Chrome changes, e.g. new deprecation warnings coming in Canary (one of the errors in the log in https://github.com/GoogleChrome/lighthouse/issues/1573#issuecomment-276129392)

**Comment by patrickhulce** [comment]
fixed by #2547 ! 🎉  moving forward we'll probably want to stick to tests that only pass in stable

**Comment by XhmikosR** [comment]
Cool, I'll add it in my long to-do list to update AppVeyor soon-ish

On Jun 20, 2017 22:13, "Patrick Hulce" <notifications@github.com> wrote:

fixed by #2547 <https://github.com/GoogleChrome/lighthouse/pull/2547> ! 🎉
moving forward we'll probably want to stick to tests that only pass in
stable

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GoogleChrome/lighthouse/issues/1480#issuecomment-309859078>,
or mute the thread
