### ISSUE TITLE
PSI: Oops! Something went wrong. unicode truncation json parse problem

### ISSUE THREAD

**Issue by arpadkdweb** [GoogleChrome/lighthouse#14897]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.kissmyparcel.com/retail/

### What happened?

Simply tried checking page speed score, got "Oops something went wrong" message.

### What did you expect?

Get the score.

### How were you running Lighthouse?

web.dev

### Lighthouse Version

10.0.2

**Comment by adamraine** [comment]
cc @paulirish @jazyan

**Comment by jazyan** [comment]
Thanks for reporting! I can repro this in both the PageSpeed UI and API. Seems to be a PSI specific issue, since the page can be audited successfully via DevTools.

Were you able to successfully audit this page via PageSpeed at some point, whether through the UI at pagespeed.web.dev or the API (https://developers.google.com/speed/docs/insights/rest/v5/pagespeedapi/runpagespeed)? If so, would be very helpful to know when and the LH version if possible to help us debug.

**Comment by paulirish** [comment]
internal bug: http://b/274017739

**Comment by arpadkdweb** [comment]
> Thanks for reporting! I can repro this in both the PageSpeed UI and API. Seems to be a PSI specific issue, since the page can be audited successfully via DevTools.
> 
> Were you able to successfully audit this page via PageSpeed at some point, whether through the UI at pagespeed.web.dev or the API (https://developers.google.com/speed/docs/insights/rest/v5/pagespeedapi/runpagespeed)? If so, would be very helpful to know when and the LH version if possible to help us debug.

My team was able to use the old pagespeed insights at some point, but it was years ago, not sure which version of the API. I'm not sure if it helps at all. Since then, only WordPress core and plugins were updated. Extra bit of info, the site is on a LiteSpeed server.
