### ISSUE TITLE
LinkElements gatherer encountered an error: Expected attribute delimiter at offset 94

### ISSUE THREAD

**Issue by mattzeunert** [GoogleChrome/lighthouse#14934]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://calendly.com/matt-665/debugbear-demo?month=2023-03

### What happened?

Run `lighthouse --view https://calendly.com/matt-665/debugbear-demo\?month\=2023-03`

There's no SEO score:

![Screenshot 2023-03-28 at 10 31 32](https://user-images.githubusercontent.com/1303660/228193619-2033db53-ee91-4b75-9be4-05db6d436853.png)

### What did you expect?

An SEO score should be reported, it worked with Lighthouse 10.0.1.

Started seeing this error on bunch of pages when trying to upgrade to 10.1.0.

### How were you running Lighthouse?

CLI

### Lighthouse Version

10.1.0

### Chrome Version

114

**Comment by brendankenny** [comment]
Thanks @mattzeunert! Looks like this is due to updating `http-link-header` in 10.1.0.

From the example page, it's attempting to parse the header `<https://assets.calendly.com/assets/booking/css/booking-5e8a798d.css>; rel=preload; as=style; nopush` and throwing when it doesn't find a `'='` after `nopush`.

I haven't looked into why it got stricter on this. The error condition looks like it was in the old version as well, so something else must have gotten stricter/changed requirements and led back to that code path.

**Comment by adamraine** [comment]
https://github.com/jhermsmeier/node-http-link-header/issues/29

**Comment by nagumii** [comment]
I can confirm this is still happening:
https://pagespeed.web.dev/analysis/https-www-rustil-co-il/3jaf8imvmb?form_factor=mobile

**Comment by nagumii** [comment]
Thanks, appreciate the response!
