### ISSUE TITLE
"Lighthouse is warming up..." in Chrome M112+

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#15026]
Updated Jul 11 2023:

For those that are still seeing this issue, please attempt the following fixes in this order:
1. Restart Chrome. `chrome://restart` should reboot the browser and reopen all of your tabs and such.
2. Use a newer version of Chrome (e.g. [Canary](https://www.google.com/chrome/canary/)). We believe this issue has been fixed in M115 however the current [stable Chrome](https://chromiumdash.appspot.com/releases?platform=Mac) is still M114 as of writing this.
3. Enable "Legacy navigation" in the Lighthouse settings
	- **Warning**: *We are planning on [removing this feature in the near future](https://github.com/GoogleChrome/lighthouse/issues/15060).*

If step 2 does not fix the problem, please leave a comment with the following information:
- The url you are testing on
- Chrome version
- Weather or not enabling "Legacy navigation" (step 3) works as a fix

If none of the above fixes work for you, you can use one of our other clients in the meantime:
- [Lighthouse CLI](https://github.com/GoogleChrome/lighthouse#using-the-node-cli)
- https://pagespeed.web.dev/
- [Lighthouse extension](https://chromewebstore.google.com/detail/blipmdconlkpinefehnmjammfjpmpbjk?pli=1)

**Comment by adamraine** [comment]
I did some digging here, it looks like Puppeteer within the Lighthouse worker is trying to attach to the `devtools://...` lighthouse worker target for some reason. I think if we ignore `devtools://...` URLs in the target filter everything should work. Still not sure why this is only happening in stable though.

**Comment by adamraine** [comment]
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4490746

**Comment by constbeecoding** [comment]
Just came to also report this issue as well, thanks for raising it!

**Comment by danny-englander** [comment]
I can also confirm this issue is happening in Chrome Mac version 112.0.5615.137 for arm64. In Canary, Lighthouse is working fine in Version 115.0.5741.0 for Mac arm64

**Comment by brunodeangelis** [comment]
Chiming in just to say I'm also having this issue in Chrome 112.0.5615.137 (Official Build) (arm64), on macOS 13.1

**Comment by briantully** [comment]
Same issue happening for me in Chrome Version 112.0.5615.137 (Official Build) (arm64) on macOS 12.6.5

**Comment by adamraine** [comment]
Thanks to everyone for chiming in! It looks like rebooting Chrome one time has fixed this issue permanently for me, I haven't reproduced this issue since restarting my Chrome.

Please let us know if restarting Chrome *does not* fix this issue for you.

**Comment by ristomatti** [comment]
Same issue on Linux Mint and Chrome 112.0.5615.165 (Official Build) (64-bit). I have not yet tried restarting but just to note this is not macOS specific.

**Comment by JohnnyWalkerDigital** [comment]
I have restarted and I still have this issue (although it temporarily went away after the restart).

Chrome Version 113.0.5672.92
MacOS 12.5.1 (21G83)

**Comment by adamraine** [comment]
@JohnnyWalkerDigital I haven't reproduced in M113, the problem has gone away since the first time I restarted :/

Does this happen in Chrome Canary for you as well?

**Comment by aixegorri** [comment]
Same problem here from a couple of weeks ago on M1 Macbook with Ventura.
Chrome: 112.0.5615.137

**Comment by adamraine** [comment]
For those still experiencing this problem after restarting Chrome, can you provide:
- The URL you are testing on
- Weather or not you are experiencing this on the latest Chrome Canary (M115)

**Comment by adamraine** [comment]
Thanks @constbeecoding! Would you also be able to test on Chrome stable in an incognito tab?

**Comment by constbeecoding** [comment]
OPE! @adamraine the fixes applied in the commits appear to have worked! The Chrome update yesterday as applied here: https://chromereleases.googleblog.com/2023/05/stable-channel-update-for-desktop_16.html JUST became available to me, after updating, all appears golden:


![Screen Shot 2023-05-17 at 3 56 39 PM](https://github.com/GoogleChrome/lighthouse/assets/63125095/37ff9330-46d2-4e9f-bb3d-517ae95904a9)

**Comment by JohnnyWalkerDigital** [comment]
Crapped out for me on 113.0.5672.126 - MacOS 12.5.1 (21G83)

Please note for all who are testing: Restarting Chrome temporarily fixes this. If you've only run Lighthouse once after restarting, it's **expected** to work.

<img width="1119" alt="Screenshot 2023-05-18 at 11 38 59" src="https://github.com/GoogleChrome/lighthouse/assets/6763222/f98d788b-5e71-4969-9b29-fb825a852e7c">

**Comment by constbeecoding** [comment]
Good shout @JohnnyWalkerDigital . @adamraine  Retested this morning on incognito as well and still buggy.

Infinite warming up:
![Screen Shot 2023-05-18 at 8 33 25 AM](https://github.com/GoogleChrome/lighthouse/assets/63125095/4028b765-dfc7-4e50-b786-de643c0f3af8)

**Comment by luckylooke** [comment]
Just FYI, for those who end up here, you may temporary use alternative https://pagespeed.web.dev/ until fixed. Happy coding 👍 🙂

**Comment by randychilau** [comment]
Another FYI (but perhaps assumed by all, except me, as a temporary workflow workaround when you have 10+ tabs opened): 

[as mentioned here](https://www.chromium.org/getting-involved/dev-channel/) in Chrome Release Channels:
>All channels may be run in parallel -- they install into distinct directories and use dedicated User Data directories.

So if you are experiencing the issue of needing to restart Chrome to do repeated dev console lighthouse testing, but don't want to restart because you have 20+ tabs opened or something, you can:

- download/install one of the channels (I used the beta channel)
- run them as another instance of Chrome
- use that for dev console lighthouse testing
- quit/restart that instance each time you want to use lighthouse again

Doesn't really save time, but you don't have to experience any bad feels from restarting chrome with 30+ tabs.

Cheers!

**Comment by paulirish** [comment]
I got a repro (and a fix)

repro just happened and I tried not changing much, since this seems mysterious...

<img width="1154" alt="image" src="https://github.com/GoogleChrome/lighthouse/assets/39191/c396cac3-1d2e-4ba4-8c1e-ae8de565995c">

Auditing the pi tab but have a few other tabs open in this ToT chromium...

There's a promise hang in this `browser.pages()` call:
<img width="329" alt="image" src="https://github.com/GoogleChrome/lighthouse/assets/39191/3c71dd69-a853-4e3f-a0ff-25f84d2b3253">

I narrowed it down to  here:
https://github.com/puppeteer/puppeteer/blob/a9bde8e726b02dc54b33718cddfbff1edb6dcd78/packages/puppeteer-core/src/common/Target.ts#L173

I had two background tabs where this pagePromise never resolved. (And now an hour later, now its just 1 that doesn't resolve.. shrug)

Here's all allowlisted targets before that await:
<img width="960" alt="image" src="https://github.com/GoogleChrome/lighthouse/assets/39191/3623c5e3-f861-4065-b0b8-c4b5296fd7ad">

And all of them that made it through:
<img width="1015" alt="image" src="https://github.com/GoogleChrome/lighthouse/assets/39191/c60db14f-8d79-4d96-9b34-93276c38f8f3">

note that the CDP-Runtime docs page isn't in the final set.
I have no idea why.  

-----------

but......backing up...

 why do we care about a pptr/cdp conection to any of these pages anyway? 
we shouldn't. (I'm guessing something about the Tab target refactor affected this)

Cuz now we get targetInfos for all these background tabs right here: 

https://github.com/ChromeDevTools/devtools-frontend/blob/efdfd1c500fa3aab8d5e6634f2c4e4fdcd60c95c/front_end/panels/lighthouse/LighthouseProtocolService.ts#L114

Seems odd..

I put up a fix for it: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4606010

The CL  just matches what recorder panel's logic is:

https://github.com/ChromeDevTools/devtools-frontend/blob/efdfd1c500fa3aab8d5e6634f2c4e4fdcd60c95c/front_end/panels/recorder/models/RecordingPlayer.ts#L51-L52

**Comment by YourMark** [comment]
I have updated to Chrome 114, but unfortunately this is still an issue for me.

**Comment by connorjclark** [comment]
FYI you can go to `chrome://restart` to trigger a chrome restart (which will restore your tabs).

**Comment by KungoJung** [comment]
Using Chrome version M114, restarting Chrome at `chrome://restart` solved this for me. Thanks all.

**Comment by csalmeida** [comment]
I have the same issue as described at: https://github.com/GoogleChrome/lighthouse/issues/9484

The message looks like this:
![CleanShot 2023-06-20 at 14 38 17](https://github.com/GoogleChrome/lighthouse/assets/12223613/2aa4d03c-b30b-43c5-8227-176d6dc92dd9)

Running `chrome://restart` like @connorjclark suggested got it working again:

![CleanShot 2023-06-20 at 14 39 28](https://github.com/GoogleChrome/lighthouse/assets/12223613/10f300ff-1f7e-46f1-9e0c-9708306d87f0)

Thanks for the help all.

**Comment by victorhooi** [comment]
I'm still seeing this issue as well - this is on the latest Chrome Canary (117.0.5853.0) on arm64 (Macbook Pro M1).

I've tried this on a few different websites - and they all seem to hang at "Ligthouse is warming up":

<img width="848" alt="image" src="https://github.com/GoogleChrome/lighthouse/assets/243499/d47e9f52-05a5-4a37-9411-c3d4d908c642">

<img width="857" alt="image" src="https://github.com/GoogleChrome/lighthouse/assets/243499/68dcce2f-2fff-4bbe-a63d-3d8a2cd8d0b0">

I did try restarting Chrome Canary - even directly after a restart, the issue still persists.

Does anybody have any suggestions?

**Comment by yangwao** [comment]
> I did try restarting Chrome Canary - even directly after a restart, the issue still persists

Same here, I went download Canary as sometimes upstream fixes are there, doesn't work even executing `chrome://restart`

**Comment by adamraine** [comment]
I can no longer repro this in Chrome 117.0.5858.0 on https://www.smh.com.au/. @victorhooi can you repro with this Chrome build version (should be latest Canary)?

**Comment by jcubic** [comment]
I'm using 114.0.5735.198 official 64 for Fedora and still have the issue, `chrome://restart` doesn't help. Same happen in incognito mode.

**Comment by elialbert** [comment]
https://github.com/GoogleChrome/lighthouse/issues/9484#issuecomment-716146785 fixed it for me on mac and 114. also disabled all adblocking.

**Comment by JohnnyWalkerDigital** [comment]
> yes. restarting initially didn't fix it for me, and following the linked fix has allowed me to run it multiple times.

Interesting. I'm not seeing it at all on macOS Ventura 13.4, Chrome Version 114.0.5735.198 (Official Build) (arm64). I wonder if you undid those changes if it would come back for you?

**Comment by elialbert** [comment]
you're right lighthouse is now working fine regardless. Perhaps the bug is located in a setup phase that only needs to run once?

**Comment by tomkiss** [comment]
Using `Version 114.0.5735.198 (Official Build) (arm64)` on MacOS Ventura 13.4.1 and enabling "Legacy Navigation" finally fixed this issue I've been seeing for months, thank you! 🙌

**Comment by adamraine** [comment]
Hey folks, I've update this [issue description](https://github.com/GoogleChrome/lighthouse/issues/15026#issue-1688952309) to summarize the various workarounds. Please let us know using a newer Chrome version (M115+) *does not* fix this issue.

**Comment by JohnnyWalkerDigital** [comment]
> Using `Version 114.0.5735.198 (Official Build) (arm64)` on MacOS Ventura 13.4.1 and enabling "Legacy Navigation" finally fixed this issue I've been seeing for months, thank you! 🙌

And what happens if you disable "Legacy Navigation"?

**Comment by JohnnyWalkerDigital** [comment]
Very strange. I haven't altered that setting and our setups are identical.

**Comment by YourMark** [comment]
> I'm using 114.0.5735.198 official 64bit for Fedora and still have the issue, `chrome://restart` doesn't help. Same happen in incognito mode.

I can confirm this. Same thing is still happening unfortunately

**Comment by jcubic** [comment]
Beta version (115) works though.

**Comment by adamraine** [comment]
Hey folks, Chrome M115 has hit stable. I'm going to close this issue but we can reopen if anyone reports seeing this on Chrome M115 or later.

**Comment by spanishgringo** [comment]
@adamraine I have this problem still on Edge 115.0.1901.188 (Official build) (arm64)

I've enabled Legacy Navigation and done chrome://restart. None of that fixes the issue.

**Comment by adamraine** [comment]
We don't officially support edge, this appears to be an issue there:
https://github.com/MicrosoftEdge/DevTools/issues/169

**Comment by clshortfuse** [comment]
Can't get lighthouse to work on Chrome Stable, Canary, or Edge.

Are there are any logs? This is Chrome Canary with google.com:

**Comment by adamraine** [comment]
Recently introduced bug in Chrome Canary: https://bugs.chromium.org/p/chromium/issues/detail?id=1471265

**Comment by D-Chatzis** [comment]
This problem was fixed for me on Canary!
