### ISSUE TITLE
Filter out long tasks coming from worker thread in TBT opportunities

### ISSUE THREAD

**Issue by alonkochba** [GoogleChrome/lighthouse#15052]
**Feature request summary**
I opened this [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1443440) today, about differentiating between long tasks coming from the worker thread and ones coming from the main thread in devtools.

Only long tasks from the main thread contribute to TBT, but I believe that because of this bug, in Lighthouse we incorrectly show all long tasks, including ones from the worker, as a TBT opportunity.

It's a bit hard to show on Lighthouse/PageSpeed Insights due to long tasks attribution not being very clear so I may be wrong, but here is an example, where I believe these long tasks are hiding behind thunderbolt-commons bundle:

https://pagespeed.web.dev/analysis/https-www-alonkochba-com-blog/o19ri9tq9e?utm_source=psi&utm_medium=redirect&form_factor=mobile

(from www.alonkochba.com/blog)

**What is the motivation or use case for changing this?**
Improve clarity of opportunities to improve TBT, and clarity of which long tasks come from which thread.

**How is this beneficial to Lighthouse?**
Better granularity of long tasks explanation, easier to pinpoint TBT opportunities.

**Comment by DFWCowboys** [comment]
My computer is compromised because I found that bug either in the
lighthouse app or Linux app on my chrome notebook. I believe people have
stolen my identity cause my social security number is now on the Dark Web.
I this was purposely done to me. I'm recently divorced and believe my wife
is apart of this conspiracy to have me harmed and all of my electronics
devices have be compromised. I have tracking malware on my devices that
allows people to know my whereabouts at all times and monitoring my calls.
I've reported this to the FBI Cybersecurity Division.

**Comment by adamraine** [comment]
I saw one very long task attributed to thunderbolt-commons but it was on the main thread track, so seems like Lighthouse is accurately recording the task as blocking the main thread.

None of the long tasks on the worker thread show up in the Lighthouse main thread time breakdown.

**Comment by alonkochba** [comment]
Thanks, I may have misinterpreted the output, but wanted to confirm. 
I'll close and come back if I find a clearer example of this behavior.
