### ISSUE TITLE
npm prepublish deprecation

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#1516]
So, with node.js 7 which has npm v4 we get:

```
As of npm@5, `prepublish` scripts will run only for `npm publish`.
(In npm@4 and previous versions, it also runs for `npm install`.)
See the deprecation note in `npm help scripts` for more information.
```

So this should be changed to something else eventually.

**Comment by ebidel** [comment]
Ack. Thanks. We're aware of the deprecation but decided to add the `prepublish` step for now. Discussed in https://github.com/GoogleChrome/lighthouse/pull/1439.

**Comment by XhmikosR** [comment]
Better think before than be late :)

What's the alternative here? `install` / `postinstall`? I'm not aware of their pros and cons.

**Comment by ebidel** [comment]
Really just a manual `yarn build-cli` when users check out the code. And we'll need to make sure it's documented before we publish the extension (to prevent the missing typescript build step we've experienced before).

`install`/`postinstall` are not good options because all users that install LH via `npm install` will have to run that unnecessary build step.

**Comment by XhmikosR** [comment]
Isn't `postinstall` being run automatically like `prepublish`?
