### ISSUE TITLE
LCP Element is different between Version 9.6 and Version 10 impacting LCP Metric

### ISSUE THREAD

**Issue by adisheshaiah** [GoogleChrome/lighthouse#15204]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.bell.ca/Mobility/Smartphones_and_mobile_internet_devices

### What happened?

Hi

Ran Lighthouse with version 9.6 and version 10.1.1. on URL https://www.bell.ca/Mobility/Smartphones_and_mobile_internet_devices

In both versions LCP element identified is different impacting LCP metric.
[DeviceListing_V10.1.1.txt](https://github.com/GoogleChrome/lighthouse/files/11876998/DeviceListing_V10.1.1.txt)
[DeviceListing_V9.6.2.txt](https://github.com/GoogleChrome/lighthouse/files/11876999/DeviceListing_V9.6.2.txt)

### What did you expect?

Element to be same between versions having similar LCP value. Weightages can be different.

### What have you tried?

Ran lighthouse from command line with different versions post variance in gathered data.
Noticed LCP element changed between versions

### How were you running Lighthouse?

CLI, Chrome DevTools

### Lighthouse Version

10.1.1 vs 9.6.2

### Chrome Version

114

### Node Version

16.15.1

### OS

Windows 10

### Relevant log output

```shell
Already attached both json files
```

**Comment by Mayur9704** [comment]
Facing same issue.

**Comment by swap-patil1409** [comment]
Same issue for me as well.

**Comment by Mad35** [comment]
I am still facing the same issue.

**Comment by praveenjunagade** [comment]
facing same issue

**Comment by adamraine** [comment]
In Lighthouse v10 we updated the default viewport to be larger vertically than it was in v9. In the case of https://www.bell.ca/Mobility/Smartphones_and_mobile_internet_devices, the large text block identified as the LCP element in v10 is not visible when the page is rendered with the v9 viewport, therefore it doesn't count as the LCP in v9. This is expected behavior.

I'm going to close this as WAI. If anyone else has a different page that is not covered by the scenario I just mentioned feel free to share it.

**Comment by Naga341** [comment]
I am also facing the issue.

**Comment by connorjclark** [comment]
People, please stop doing "+1" comments on this and all GitHub issues.
