### ISSUE TITLE
Disregard lack of label on Honeypot field

### ISSUE THREAD

**Issue by BowFarmer** [GoogleChrome/lighthouse#15212]
Lighthouse complains about there not being a label on honeypot fields in a form. A form plugin I use on my WordPress site adds a honeypot field which looks like this:

<input type="text" name="2772-multi_line_text" style="position:absolute;left:-5000px;" tabindex="-1" autocomplete="off">

As you can see, it is way off the page, is not tabable, and is only there to trap bots which fill out the form. However LightHouse lowers the accessibility score because it sees a form field without a label.

I got around this by adding aria-label="namex" to the field, however this can interfere with disabled people who use the form because they may see the form when they should not.

When LightHouse sees a form field that is clearly not visible, for example like in the form above style="position:absolute;left:-5000px, and has a tabindex=1, it should mark it as a field that is meant not to be accessible and exclude it from accessibility analysis.

**Comment by adamraine** [comment]
This is an interesting case, however Lighthouse is reporting this failure correctly IMO.

> As you can see, it is way off the page, is not tabable, and is only there to trap bots which fill out the form. 

It is not visible in the viewport, but it is still accessible via a screen reader otherwise it wouldn't be able to trap bots.

[This stack exchange answer](https://ux.stackexchange.com/questions/15835/honeypot-captchas-and-accessibility) does a good job of explaining the problem here. Any sort of honeypot/captcha is going to influence what a human using a screen reader sees. The proposed solution is to use a label that tells any humans to ignore it like "If you are a human, do not fill in this field".

In any case, Lighthouse get's its accessibility insights from [axe-core](https://github.com/dequelabs/axe-core), so if you are interested in discussing it further I would suggest filing an issue there.

**Comment by BowFarmer** [comment]
And using something like aria-hidden="true" which passes LightHouse Accessibility tests would not work because bots using screen readers would not see it and not fill it in? Or do the screen readers which bots use pay any attention to aria settings?
