### ISSUE TITLE
Query regarding axe-core for Google Lighthouse Accessibility Checks

### ISSUE THREAD

**Issue by daphneyyt** [GoogleChrome/lighthouse#15215]
Hi Google Lighthouse team, I am looking at the difference between Google Lighthouse's accessibility scanner and AXE DevTool (for websites).

From this URL, I understand that Google Lighthouse is using axe-core as their rule engine:
https://www.deque.com/blog/google-selects-deques-axe-chrome-devtools/

We did a comparison table between the criteria that AXE can scan and what Google Lighthouse can scan (only for Level A and Level AA issues).

We would like to understand why is there a difference in the WCAG Success Criteria that AXE and Lighthouse can capture. Please take a look at the image below.

![AXE DevTools](https://github.com/GoogleChrome/lighthouse/assets/75086091/5eecafb6-c718-4454-b2ec-8d8a783a2dd4)

I retrieved Google Lighthouse's list from:
https://developer.chrome.com/docs/lighthouse/accessibility/scoring/

I retrieved the AXE DevTool's list from: 
https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md

I look forward to hearing from you. 

Thank you!
Daphne

**Comment by adamraine** [comment]
@jazyan are some of these rules what you are working on adding?

**Comment by jazyan** [comment]
Yes, I'm currently adding more aXe rules in Lighthouse -- for example, [`link-in-text-block`](https://dequeuniversity.com/rules/axe/4.7/link-in-text-block) is WCAG 1.4.1 and was recently added in https://github.com/GoogleChrome/lighthouse/pull/15159. 

However, note that there are some rules that aXe DevTools has (based on the diagram) we are not planning to add: for example, WCAG 2.2.2 rules [`marquee`](https://dequeuniversity.com/rules/axe/4.7/marquee) and [`blink`](https://dequeuniversity.com/rules/axe/4.7/blink). `marquee` because the marquee element is deprecated, and `blink` because in blink no longer blinks in the vast majority of browsers.

I'm not too familiar with aXe DevTools, so I can't speak too much about the differences between the two tools and rules included. On the Lighthouse-side, we have been going through the current list of aXe rules with the help of a11y experts to determine which to include in Lighthouse a11y category. Aiming by the next major release to have more rules included, as well as updated documentation on why or why not each aXe rule was included.

Hope this answers your question to some degree, @daphneyyt!
