### ISSUE TITLE
Extension Error: Cannot read property 'requestId' of undefined

### ISSUE THREAD

**Issue by bssatya** [GoogleChrome/lighthouse#1528]
**Lighthouse Version**: 1.4.1
**Chrome Version**: 55.0.2883.87
**URL**: http://172.19.10.248:6060/training/training-event-management/
**Error Message**: Cannot read property 'requestId' of undefined
**Stack Trace**:
 ```TypeError: Cannot read property 'requestId' of undefined
    at CriticalRequestChains.compute_ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:3732:46)
    at CriticalRequestChains.request (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:3617:33)
    at Function.audit (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:541:22)
    at Promise.resolve.then._ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11614:20)```

**Comment by brendankenny** [comment]
failure is on [this line](https://github.com/GoogleChrome/lighthouse/blob/8a41880f10e574dcb474656f315b9e6c5d4c12bc/lighthouse-core/gather/computed/critical-request-chains.js#L106).

It's an interesting bug...since *all* network records in the LH network record log are pushed into `requestIdToRequests`, the only way I can see this happening is if somehow we're missing some network requests in `network-recorder` that the devtools-frontend *is* aware of since it provided that request via `NetworkRequest.initiatorRequest()` in the `ancestorRequest` loop above.

**Comment by brendankenny** [comment]
unfortunately without a way to repo, this is going to be very difficult to track down.

side note: some weird things in this file. It changed a ton during the course of #321, so the comments are slightly off from what's actually happening. `requestIdToRequests` also seems pointless...`initiatorRequest()` gives the request, so why store its ID just to look up that request again by ID a moment later? `requestIdToRequests` looks like it was originally going to be only a critical request lookup, but then that changed to all requests in https://github.com/paullewis/lighthouse/pull/5 as a workaround for #326, but when that bug was fixed the workaround was only partially reverted, leaving `requestIdToRequests` still redundant.

**Comment by paulirish** [comment]
waiting for sentry to pick this back up. thanks for the report!
