### ISSUE TITLE
Can what modes an audit supports be derived solely from its required artifacts?

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#15364]
navigation/timespan/snapshot modes inform what stages are available for a Gatherer, and so a Gatherer declares what modes it supports based on that

audits declare what artifacts they need ... but they also declare what modes they support? seems odd. can we instead derive based on the necessary artifacts?

one reason we can't right now is that the `ProcessedNavigation` computed artifact requires a `Trace` artifact, which is present in a navigation and a timespan; but `ProcessedNavigation` is only relevant in navigation mode. We could declare its requirement on a navigation mode more explicitly by introducing a `NavigationTrace` artifact that only supports navigation mode.

`URL` differs on mode, and perhaps enough so to inform what modes an audit should support. That is more awkward to split up.

If an audit does not declare `supportedModes`, all modes will attempt to run the audit. Perhaps this state should instead inform our audit filtering logic to derive the supported modes from the artifacts - and then an audit can override this logic if they need to.

**Comment by adamraine** [comment]
I'm interested to explore adding `NavigationTrace` further, it would allow us to have confidence in our assumptions about the trace of we get it from `NavigationTrace` instead of `Trace`. That being said I have a few more thoughts:

- This work would overlap significantly with #15306, we may want to finish switching all our audits to using `Trace` before doing this.
- `supportedModes` is still important for deciding applicability. If an audit works in navigation and timespan mode but only supports navigation mode then I prefer using `supportedModes: ['navigation']` over switching `Trace` to `NavigationTrace` if we want to explicitly disable timespan support.
- Is this worth the effort? I can see how the current situation is a bit odd, but I'm afraid of a giant refactor just to make it less confusing.
