### ISSUE TITLE
Expose more type in index.d.cts

### ISSUE THREAD

**Issue by dardavar** [GoogleChrome/lighthouse#15386]
Currently, only the `lighthouse` function is available through `index.d.cts` so it is the only function one can easily use in a CommonJS module. 
I can fix it by myself!

**Comment by adamraine** [comment]
We have several functions in the CJS entrypoint: https://github.com/GoogleChrome/lighthouse/blob/main/core/index.cjs

That being said, they are missing in the `index.d.cts` file because they are defined as properties of the `lighthouse` function :/. Ideally tsc would generate the correct `d.cts` file automatically.
