### ISSUE TITLE
INP - Interaction to Next Paint not appearing in report

### ISSUE THREAD

**Issue by dgautsch** [GoogleChrome/lighthouse#15482]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.google.com

### What happened?

I read that Lighthouse 11 moved INP from experimental and was now available in the standard audits. When I ran the command `npx lighthouse https://www.google.com --output html` I did not see it listed in the report.

### What did you expect?

I expected to see INP in the report.

### What have you tried?

I have tried only auditing for INP with `npx lighthouse https://www.google.com --output html --only-audits interaction-to-next-paint`

I DO see it when I ran a puppeteer script with timespans and navigation steps.

### How were you running Lighthouse?

CLI, node

### Lighthouse Version

11.1.0

### Chrome Version

116.0.5845.187

### Node Version

18.17.1

### OS

Mac

**Comment by brendankenny** [comment]
> ### What have you tried?
> I have tried only auditing for INP with `npx lighthouse https://www.google.com --output html --only-audits interaction-to-next-paint`
> 
> I DO see it when I ran a puppeteer script with timespans and navigation steps.

This is the expected behavior. INP happens only when there is user interaction (it's the timing from an interaction to when a response to the interaction is painted), so unfortunately the only ways to get it are either through manual testing (e.g. Lighthouse timespan in DevTools and you click on a button while it runs) or scripting an interaction via a tool like puppeteer. The default Lighthouse navigation mode won't include INP because there's no interaction to measure.

**Comment by dgautsch** [comment]
Thanks @brendankenny makes sense. Appreciate the help.
