### ISSUE TITLE
Feature Request: add `maxTestTime` config

### ISSUE THREAD

**Issue by vegerot** [GoogleChrome/lighthouse#15502]
**Feature request summary**

API config called `maxTestTimeMs` that will always end the test at the latest `maxTestTimeMs` ms.

Example config:

```js
await lighthouse(
  "https://github.com/GoogleChrome/lighthouse",
  { port: 8081 },
  { maxTestTimeMs: 10*1000  },
 )
```
after that many ms, the LCP as of that time and all other available audits will be collected and reported.

I will contribute this feature if the maintainers will accept such a patch (after code review).

**What is the motivation or use case for changing this?**
I am trying to figure out whether changes to my website affect LCP.  On my website, I notice that LCP normally happens at about 1300ms, but the Lighthouse run takes 25 seconds to finish.  Since I normally do at least 20 runs to reduce noise, that's a _lot_ of time spent collecting audits I'm not going to use.

It'd be great if I had an option like `maxTestTimeMs` that would tell Lighthouse to get the LCP as of `maxTestTimeMs` and end the run.

**How is this beneficial to Lighthouse?**

⚡Faster Lighthouse => Faster development => Faster websites => more money for Google 📈

**Comment by benschwarz** [comment]
FYI @vegerot there's already `maxWaitForFcp` and `maxWaitForLoad`, which can be used to influence overall test duration.

**Comment by vegerot** [comment]
Thanks, Ben.

I'm aware of that option.  `maxWaitForFcp` will **cancel** the test if the FCP is more than `maxWaitForFcp` ms.  If the FCP happens before then, then the Lighthouse run will continue running for another 20 seconds.  I want something different.  I want to end the test no matter what after a certain time.

Sorry, I might not have made the post clear enough.

**Comment by benschwarz** [comment]
It may be worth reviewing the timings of audits (found in JSON report), to observe which audits are taking the longest. You can also reduce the audits run to be performance category only, or choose audits to omit. That way you'll also reduce lengthy audit processing.

**Comment by vegerot** [comment]
> It may be worth reviewing the timings of audits (found in JSON report), to observe which audits are taking the longest
Good idea

> You can also reduce the audits run to be performance category only, or choose audits to omit.
I'm already doing this

**Comment by adamraine** [comment]
As @benschwarz mentioned, what you are looking for is `maxWaitForLoad`. There are several conditions that Lighthouse will wait for during the navigation (network quiet, CPU idle, FCP, etc.). This param is the max time Lighthouse will wait for all of them to complete before moving on to computing the audit results.

This is just the time spent waiting for the navigation to finish, the overall Lighthouse run will certainly take longer. Unfortunately, we can't cancel the run when computing audit results *and* provide an LCP result because the extra time spent processing the navigation is necessary for determining the LCP (and other audits).

> Since I normally do at least 20 runs to reduce noise, that's a lot of time spent collecting audits I'm not going to use.

You can use the `skipAudits`, `onlyAudits`, and `onlyCategories` options to narrow the scope of your run. For example, a report that only displays LCP can be achieved with `onlyAudits: ['largest-contentful-paint']`

The option `disableFullPageScreenshot` can also speed up the run but will remove the visual indicators for DOM elements in the report.

**Comment by vegerot** [comment]
> You can use the `skipAudits`, `onlyAudits`, and `onlyCategories` options to narrow the scope of your run. For example, a report that only displays LCP can be achieved with `onlyAudits: ['largest-contentful-paint']`
> 
> The option `disableFullPageScreenshot` can also speed up the run but will remove the visual indicators for DOM elements in the report.

Those options are useful.  Particularly `disableFullPageScreenshot` cuts off a second per each run.  Unfortunately there's still 19 seconds of waiting for nothing.

> Unfortunately, we can't cancel the run when computing audit results _and_ provide an LCP result because the extra time spent processing the navigation is necessary for determining the LCP (and other audits).

Understood.  In the case of my website each run takes at least 25 seconds and the LCP element never changes after 2s.  That's why I want an option to override the heuristics Lighthouse uses to detect when to compute the audit results (network quiet, CPU idle, FCP, etc.) and just put a value like 5s.

**Comment by vegerot** [comment]
I don't know exactly what you mean but that sounds promising

**Comment by adamraine** [comment]
Lighthouse needs more time to compute the result for all of our audits, it isn't possible for us to cancel the run in the middle *and* produce a valid report. If you need more control over how much time is spent loading the page you can check out: https://github.com/GoogleChrome/web-vitals

Worth noting at this point that https://github.com/GoogleChrome/lighthouse/blob/main/docs/user-flows.md timespan mode will not surface the LCP in the report, so that may not be a valid solution to this problem
