### ISSUE TITLE
User flows doc example doesn't work because of `pptr-testing-library`

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#15607]
### Discussed in https://github.com/GoogleChrome/lighthouse/discussions/15606

Looks like [`pptr-testing-library`](https://www.npmjs.com/package/pptr-testing-library) hasn't been updated in 2 years and is probably not compatible with the latest version of puppeteer. If that's the case, we shouldn't recommend it to users in our docs.

**Comment by ChristopherPHolder** [comment]
As i mentioned in the discussion #15606 It is likely that people cannot reproduce the example in the docs not because the lib [pptr-testing-library](https://www.npmjs.com/package/pptr-testing-library) is not compatible. 
(Tho i have not tested the compatibility and agree that its not maintained and should not be in the docs)

It is likely they cannot because the user-flow is attempting to access a DOM element which is not present. 

It is likely most pages change and update their interface and details which can be an issue for the docs if they relay on DOM nodes being present. 

Would it not be a better to convert the docs to use only puppeteer and use https://coffee-cart.netlify.app/ as it is more likely it will stay the same for a longer period of time?

**Comment by adamraine** [comment]
> Would it not be a better to convert the docs to use only puppeteer and use https://coffee-cart.netlify.app/ as it is more likely it will stay the same for a longer period of time?

That's one possibility, but that app is a SPA and we want the example to leverage a hard navigation via user interaction at the end.

**Comment by ChristopherPHolder** [comment]
> That's one possibility, but that app is a SPA and we want the example to leverage a hard navigation via user interaction at the end.

But is you new example with web.dev also an SPA ?

**Comment by adamraine** [comment]
No web.dev is an MPA, but we can still test some generic interactions in timespan mode.
