### ISSUE TITLE
PROD Lighthouse test: Something went wrong. Error: ERRORED_DOCUMENT_REQUEST

### ISSUE THREAD

**Issue by kenshanta** [GoogleChrome/lighthouse#15629]
**Summary**

In my basic next.js [portfolio website ](https://kovlekjian.com) all reports return a score of 0/100 and printing out the error: **Something went wrong. Error: ERRORED_DOCUMENT_REQUEST
**

Tried reproducing the issue locally but to no avail. The tests pass even on an incognito tab.

Repo [Link](https://github.com/kenshanta/next-portfolio)

Any help is much appreciated!

<img width="1340" alt="Screenshot 2023-11-23 at 2 31 40 PM" src="https://github.com/GoogleChrome/lighthouse/assets/83559262/3e68eb86-3fd4-4c72-b7cb-a9bbcfb1f6af">

<img width="844" alt="Screenshot 2023-11-23 at 2 34 38 PM" src="https://github.com/GoogleChrome/lighthouse/assets/83559262/4d50c483-4ad6-4ca4-99f7-584c7ad53e6b">

**Comment by adamraine** [comment]
I can reproduce on PageSpeed insights: https://pagespeed.web.dev/analysis/https-kovlekjian-com/7dsfxvsh36?form_factor=mobile

And with Lighthouse CLI using headless Chrome: https://googlechrome.github.io/lighthouse/viewer/?gist=db700e67657846899e0af4ff0900a724

Lighthouse is accurately reporting that the server is issuing a 401 response when it tries to load the page. If I had to guess, I would say that the server is doing this because the user agent contains `HeadlessChrome` instead of `Chrome`. Regardless, this doesn't appear to be an issue in Lighthouse.

**Comment by kenshanta** [comment]
@adamraine I understand that the issue isn't from lighthouse on the basis that the error is handled, what i don't understand is closing this thread based on a guess. 

I've been trying to figure out the right steps for this, and opening an issue was my last hope.
What should i do? or where should this question be properly asked?

**Comment by adamraine** [comment]
I closed the issue because Lighthouse is working as expected regardless of if my guess about headless chrome was correct or not.

I was only trying to point you in the right direction based on the conditions that would reproduce this error. The issue probably lies somewhere in your server configuration so I would suggest starting there.
