### ISSUE TITLE
Is lighthouse updated for WCAG 2.2 changes?

### ISSUE THREAD

**Issue by neethumani** [GoogleChrome/lighthouse#15760]
Can someone please confirm whether lighthouse has updated for WCAG 2.2 changes or not?

**Comment by neethumani** [comment]
appreciate the quick reply, but https://github.com/GoogleChrome/lighthouse/discussions/15692 is about WCAG **2.1** but my query is about WCAG **2.2** which has been published in October 2023. It would be great if someone can confirm it

**Comment by adamraine** [comment]
The point I was trying to make in that post is still valid. We can't define an explicit relationship with WCAG 2.1/2.2 because some checks will always require manual verification.

That being said, we get our automated accessibility checks from [axe-core](https://github.com/dequelabs/axe-core) which has [implemented several WCAG 2.2 checks](https://www.deque.com/blog/axe-core-4-5-first-wcag-2-2-support-and-more/).

**Comment by neethumani** [comment]
Thank you for the clarification
