### ISSUE TITLE
NO FCP error on UAT

### ISSUE THREAD

**Issue by daphneyyt** [GoogleChrome/lighthouse#16083]
Hi Google Lighthouse team, we encountered a 'NO FCP' error when Lighthouse scans on our website (UAT environment). We are using Lighthouse built into Chrome to run the scans (on Incognito).

This is the error message received: Error! The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)

We also troubleshooted by referencing a similar issue raised by another user: [Google Lighthouse Error - No FCP](https://support.google.com/webmasters/thread/199138419/how-to-fix-google-lighthouse-error-no-fcp?hl=en). We've tried using [WebPageTest](https://www.webpagetest.org/lighthouse) as suggested in this thread but encountered similar errors.

Could you let us know:
1) what is the reason that NO FCP error is triggering?
2) what other solutions could resolve the issue?
3) additionally, could there be any security issues on the server that could be causing the trigger? If yes, what type of security settings could cause the issue?

Appreciate your advise. Please let us know if further information is needed. Thank you.

**Comment by adamraine** [comment]
> what is the reason that NO FCP error is triggering?

As the error message says, the page did not paint any content. This can happen for a variety of reasons but is pretty common if the page Lighthouse is testing is hidden.

> what other solutions could resolve the issue?

We need to know how to reproduce this issue in order to diagnose it. What page are you testing on?

> additionally, could there be any security issues on the server that could be causing the trigger? If yes, what type of security settings could cause the issue?

This is not likely to be a security issue. The browser is probably just having trouble rendering content for some reason.

**Comment by benschwarz** [comment]
You may be able to work around this issue by increasing max load wait time or max fcp wait time. In Calibre we have an automatic test retry that watches for `NO_FCP` errors and re-runs with extended timeouts. In the majority of cases that helps to capture a successful test. If not, there's likely an issue on your side @daphneyyt

**Comment by daphneyyt** [comment]
Hi @adamraine @benschwarz thank you very much for the response. We will try to increase the max load wait time / max fcp wait time.

@adamraine do you have an email address / contact that we could reach you at? The website is confidential and we would prefer not to share its details over GitHub. Thank you!

**Comment by adamraine** [comment]
Please send the link to my email found here: https://mailhide.io/e/oDc3THdp

**Comment by daphneyyt** [comment]
Hi @adamraine thank you. I've dropped you an email with the necessary details.

**Comment by adamraine** [comment]
Thank you for sharing the site, I am able to reproduce the NO_FCP error. The root cause is that there is no visible content in the main frame of the web page, all of the visible content is contained in an iframe. Lighthouse does not look for FCP within iframe elements, and since there was no FCP in the main frame Lighthouse throws an error.

One workaround would be to test the performance of the site in the iframe directly.

Closing because this is WAI.
