### ISSUE TITLE
why not all relevant audits are part of response ?.

### ISSUE THREAD

**Issue by kundan2403** [GoogleChrome/lighthouse#16097]
In the response, I can see there are four relevant audits for "cumulative-layout-shift," as shown in the first screenshot. 
![Screenshot 2024-07-01 at 10 02 08 AM](https://github.com/GoogleChrome/lighthouse/assets/159939765/aff3654b-d8d8-47d7-bcc0-fb450dd02fae)

However, only two of these audits are selected to be part of the response, as illustrated in the second screenshot(Page speed). Is there a specific reason for this selection? If so, on what criteria are we prioritizing these audits?

![Screenshot 2024-07-01 at 10 02 39 AM](https://github.com/GoogleChrome/lighthouse/assets/159939765/65e6c8ee-3ea3-4e58-9727-d121f627a3e0)

**Comment by adamraine** [comment]
First of all `relevantAudits` should be removed in 12.0 and beyond, instead we use the metric impact fields to determine metric relevance. In the version you are using, `layout-shift-elements` is intentionally hidden because the audit was deprecated at the time (removed in 12.0) and `non-composited-animations` is hidden likely because it is N/A.
