### ISSUE TITLE
NO_LCP for mobile, but same element scores correctly on Desktop

### ISSUE THREAD

**Issue by pwcreative** [GoogleChrome/lighthouse#16203]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://pwcreative.com/

### What happened?

No performance score for Mobile:

Largest Contentful Paint
Error!
NO_LCP

### What did you expect?

Mobile should have a performance score in line with Desktop, because it is the same element, styled in the same way for both contexts.

### What have you tried?

There are lots of bug posts online connected to this. The main suggestion was opacity, so I tried setting the starting opacity to greater than zero, which didn't help. I removed the opacity transition altogether, and this still didn't help, so it must be connected to the translate.

<img width="216" alt="Screenshot 2024-09-27 at 10 12 13" src="https://github.com/user-attachments/assets/545f8280-5344-4f60-bddd-b524ce9028f8">
<img width="213" alt="Screenshot 2024-09-27 at 10 11 43" src="https://github.com/user-attachments/assets/7ff5dd60-b455-4323-86c9-da880d8a2f0a">

The H1 element takes up almost 50% of the screen height and is always on screen but it has nested spans which transform the text content from the top left (offscreen) into position:

.text-3d span {
    display: inline-block;
    position: relative;
    will-change: transform;
    transform: translate(-450px, -450px);
    transition: transform 500ms ease-in-out 100ms;
}

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

LATEST

### Chrome Version

Version 129.0.6668.59 (Official Build) (x86_64)

### OS

Mac

**Comment by adamraine** [comment]
This looks very similar to #10869. The short summary is that elements that are animated offscreen can cause a NO_LCP error in Lighthouse and other Chrome tooling surfaces such as the DevTools performance panel.

In your case the LCP element is different on desktop & mobile:
- On desktop it's the "FLUFF" text which is has its position animated
- On mobile it would be the "We'll assume since..." paragraph which is animated using opacity

Opacity animations appear to be a more common cause of #10869 than position animations, so that might explain why you are still getting an LCP on desktop. The current workaround is to set the initial opacity to something like 0.001 instead of 0.

**Comment by pwcreative** [comment]
Strange that the P is considered the LCP, when it's smaller than the H1, but hey, I don't make the rules! I adjusted the opacity and that is now giving us a reading. Thanks!
