### ISSUE TITLE
All Categories still appears eventhough I specify only one cateory

### ISSUE THREAD

**Issue by yasserhussien** [GoogleChrome/lighthouse#16208]
const flow = await startFlow(page, {
      config: lighthouseConfig,
        onlyCategories: ["performance"],
        throttlingMethod: "provided" // Provided by environment
      }
    });
in the generated report in the summary I still see all categories, but If I click to see the details information I see only the performance category
![image](https://github.com/user-attachments/assets/081a7702-8ce3-45f2-adb7-2f59a1ec47ae)

**Comment by yasserhussien** [comment]
Hi  @adamraine 
does this a known issue for you?

**Comment by ChristopherPHolder** [comment]
Hi @yasserhussien 

I am not sure i understand what the issue is. What version of lighthouse are you using?

But it seems like there is a missmatch in our configs, I am using "^12.2.1" in this example:
```ts
const flow = await startFlow(page,{
    flags: {
        onlyCategories: ["performance"],
    }
});
```

As you can see the onlyCategories is inside of flags. 

And results are what you would expected: 

![image](https://github.com/user-attachments/assets/a2446ce8-7d8d-46ac-b5b4-395d9fd78de7)

And in the step details i only have the performance audit.

**Comment by yasserhussien** [comment]
Hi @ChristopherPHolder
I have the same code like you, and the same result like the image
I want to see only the performance category without the other categories ( without SEO, Best Practice)
and in your case if you want to see the detailed information not the summary you will see only performance category
![image](https://github.com/user-attachments/assets/57041c29-38c8-4afc-a264-47bd92c07380)

**Comment by adamraine** [comment]
Yeah Lighthouse just shows the category names in the table header, but doesn't actually run them. This is working as expected.
