### ISSUE TITLE
A SEO warning about a link with a string "Go" is false positive

### ISSUE THREAD

**Issue by hajimehoshi** [GoogleChrome/lighthouse#16263]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://hajimehoshi.com

### What happened?

I run the PSI Frontend test on hajimehoshi.com and got this warning:

![image](https://github.com/user-attachments/assets/8a0ab419-01d8-4848-9ed5-808264c7ef85)

The link text is "Go" about Google's programing language ["Go"](https://go.dev/), so this warning should be false positive.

### What did you expect?

The warning disappears

### What have you tried?

Running the PSI Frontend via the Chrome extension.

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

12.2.1

### Relevant log output

https://pagespeed.web.dev/analysis/https-hajimehoshi-com/5pzt6foiu1?form_factor=desktop&category=performance&category=accessibility&category=best-practices&category=seo&hl=en-US&utm_source=lh-chrome-ext

**Comment by kgjjd** [comment]
[https://pagespeed.web.dev/analogy/https-hajimehoshi-com/5pzt6foiu1?form_factor=desktop&category=performance&category=accessibility&category=best-practices&category=seo&hl=en-US&utm_source=lh-chrome-ext]

**Comment by kgjjd** [comment]
✅

**Comment by kgjjd** [comment]
#16267

**Comment by kgjjd** [comment]
#10500

**Comment by kgjjd** [comment]
#16264

**Comment by kgjjd** [comment]
#16267

**Comment by kgjjd** [comment]
#15868

**Comment by davidldennison** [comment]
Hi!

That is not what this issue is referring to. It's informing you that the anchor text "Go" is not descriptive enough for users and search engines.

### **Let's break it down:**

1. **For Users:**  
   Anchor text should give users clear and specific information about where the link will take them. The term "Go" is too generic and doesn't provide any meaningful context, which could confuse users or discourage clicks.

2. **For Search Engines:**  
   Anchor text plays a key role in helping search engines understand the relationship and contextual relevance between the linked pages. Descriptive anchor text allows search engine crawlers (like Google's) to interpret the purpose of the link better, improving semantic context and page ranking for the destination URL.

### **Suggestions for Improvement:**
- Replace the generic "Go" with more descriptive anchor text, such as "Go Lang Contributions by Hajime Hoshi"
- Do this for all the other links on the page to ensure the anchor text aligns with the content or purpose of the linked page.

This small change will make your site more user-friendly and SEO-friendly. Let me know if you need help! 🚀

**Comment by hajimehoshi** [comment]
I know "Go" might be a confusing word, but avoiding this confusion should not be web authors' work, as there is actually a programming language named "Go".

**Comment by adamraine** [comment]
This is definitely an interesting case, but Lighthouse is WAI in my opinion. It isn't obvious from *just the link text* that this is the Go language and not some generic word. In this case you could use 'Golang' or maybe 'Go ("Golang")'.
