### ISSUE TITLE
Invalid JSON format on toepoke.co.uk manifest.json

### ISSUE THREAD

**Issue by toepoke** [GoogleChrome/lighthouse#1702]
Hi,

When running the report I get the following error:

"ERROR: file isn't valid JSON: SyntaxError: Unexpected token ﻿ in JSON at position 0"

It's been driving me mental for weeks!  Turns out it's because the manifest.json was saved with a byte-order-mark (I'm on Windows).  Saved without the BOM and all works well.

May I suggest adding a warning to the documentation so others don't have a similar battle?

Many thanks,
Franz.

**Comment by XhmikosR** [comment]
As far as I can tell LH is using the standard `JSON.parse` method.

Might be worth looking into https://github.com/sindresorhus/strip-bom/blob/master/index.js

**Comment by brendankenny** [comment]
Not sure what the correct thing to do here is. A BOM *is* an invalid character in JSON, but in some cases clients will drop the BOM before attempting to parse.

At the very least we could warn that the first character is a BOM to give a better error message, though.

If I test a manifest saved with a BOM, the application panel in devtools lists no information for the manifest. Since IIUC devtools is exposing what Chrome has actually parsed from the manifest, this implies Chrome doesn't understand the manifest either (devtools does not report a JSON SyntaxError, though, or any error at all).

If the browser doesn't understand it, we should definitely mark it as an error, just with a better error message.

OTOH, (one of?) the native Chrome JSON parser(s) [explicitly skips BOMs when encountered](https://cs.chromium.org/chromium/src/base/json/json_parser.cc?type=cs&l=88). Not sure how that interacts with the manifest parser.

**Comment by toepoke** [comment]
HI @brendankenny,

To confirm when I was saving with BOM I didn't see the manifest parameters in DevTools.  They magically start appearing when saved without BOM - which is in line with what you're seeing.

If it's not feasible to raise an error, perhaps a warning that _always_ appears in the report would be sufficient?  I'm just conscious of others falling into the same issue.

If I can be of any assistance, please give me a shout.

**Comment by XhmikosR** [comment]
IMO, we shouldn't do something special. It's an error in the parser so Chrome will not load it as I understand it.

**Comment by paulirish** [comment]
@toepoke when you look at the manifest panel in devtools, do you see warnings or errors?
![image](https://cloud.githubusercontent.com/assets/39191/23564521/1da6a2a2-ffff-11e6-89ac-42c28e374f44.png)

also same question for @zigmandel, as it seems like a related issue.

**Comment by zmandel** [comment]
on devtools there are no warnings or errors. my wpa has been also working
fine (offline etc) with a "utf-8 with signature" manifest. only changed it
to non-signature because of this lighthouse issue.

**Comment by toepoke** [comment]
HI @paulirish ,

Nothing appears in the console.  The manifest is devtools is just blank when saved with BOM:

Hope this helps.

**Error state:**
![failure](https://cloud.githubusercontent.com/assets/956482/23587023/83a36e72-019a-11e7-9114-2a6873ab5ad5.png)

**Working state:**
![working](https://cloud.githubusercontent.com/assets/956482/23587021/81a15ad0-019a-11e7-84d6-977be6596817.png)

**Comment by wardpeet** [comment]
perhaps it's more like a chrome issue where it should tell that it's invalid.

**Comment by HolgerJeromin** [comment]
There is an [open issue for the dev tools](https://bugs.chromium.org/p/chromium/issues/detail?id=706926) where i added the comment that there should be an info text (would have saved us a few debug hours :-)

**Comment by wardpeet** [comment]
@HolgerJeromin thank you for reporting to devtools

**Comment by wardpeet** [comment]
Fixed on master
