### ISSUE TITLE
Uses 90% of its CSS rules > Lighthouse is very different to DevTools

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/lighthouse#1712]
The outpupt for the "Uses 90% of its CSS rules" isn't clear on what exactly is the problem (i.e. which parts of a rule are not needed).

I tried looking at DevTools Audit for CSS and got very different results,is this expected?

**Comment by patrickhulce** [comment]
Yes, this is expected. DevTools used selector matching to determine if rules *could* be used while Lighthouse uses the new protocol API to see which rules were actually applied. This has both pros and cons in that we're being more accurate with what's being used but miss out on all the `:hover` rules, media queries, etc that still make sense to send down. 

The threshold is also getting revamped a bit in #1635 to be more lenient here.

**Comment by ebidel** [comment]
It's also worth noting that the discrepancy will fix itself when the LH-powered Audits panel 2.0 lands in DevTools.

**Comment by gauntface** [comment]
Thanks @ebidel for walking me through this. Sounds like most problems will be solved in #1635 - thanks @patrickhulce.

The only thing that may remain is that the information provided doesn't really help identify the unused rules. Line and column number would be super useful to direct the developers attention.

![http://i.imgur.com/hy9Mqgy.png](http://i.imgur.com/hy9Mqgy.png)

![http://i.imgur.com/4xqXBqX.png](http://i.imgur.com/4xqXBqX.png)

**Comment by patrickhulce** [comment]
@gauntface yeah we went through a number of iterations here and decided against displaying the rules since it's just information overload (in fact after the upcoming change only stylesheets with 100s or 1000s of unused rules will show up at all). The rationale being that hunting down individual rules is better served by other tools that will properly take into account everything we lack such as the aforementioned media queries, pseudo selectors, etc.

**Comment by patrickhulce** [comment]
Since #1635 has been merged and actual unused rules can be viewed in existing audits 1.0 panel for now until live CSS usage UI lands, closing this for now.

**Comment by gauntface** [comment]
Looks great - thanks @patrickhulce
