### ISSUE TITLE
Audit for iOS add-to-homescreen meta tags

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1808]
This tag provides a configuration many developers _may_ appreciate:

```html
<meta name="apple-mobile-web-app-capable" content="yes">
```

From the docs ([one](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html#//apple_ref/doc/uid/TP40008193-SW3), [two](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html)): 

> If content is set to yes, the web application runs in full-screen mode; otherwise, it does not. The default behavior is to use Safari to display web content.

> On iOS, as part of optimizing your web application, have it use the standalone mode to look more like a native application. When you use this standalone mode, Safari is not used to display the web content—specifically, there is no browser URL text field at the top of the screen or button bar at the bottom of the screen. Only a status bar appears at the top of the screen.

There are a few more tags of note:

* `<link rel="apple-touch-startup-image" href="/launch.png">` for the splash screen
* `<meta name="apple-mobile-web-app-title" content="AppTitle">` for alternative title for the homescreen icon used instead of document.title
* `<meta name="apple-mobile-web-app-status-bar-style" content="black">` or with `black-translucent` for status bar styling.

### However...

Firt wrote up a nice article on this topic: [Don’t use iOS meta tags irresponsibly in your Progressive Web Apps – Medium](https://medium.com/@firt/dont-use-ios-web-app-meta-tag-irresponsibly-in-your-progressive-web-apps-85d70f4438cb)

..which describes why the `apple-mobile-web-app-capable` tag does a few things you probably don't expect:

1. user gets no more back button, so you have to provide those to the user yourself unless its fine if they can't navigate back..
2. any `<a href>` links will open in Safari rather than the homescreen instance.
3. The user might have saved a leaf node URL to homescreen, but really you want them loading a start URL. in this case, you have to `if (navigator.standalone) location.href = myStartURL;` during the load...

---

Given all that, the audit might be a suggestion to go read firt's article more than anything. Thoughts?

**Comment by ebidel** [comment]
Not against an audit for these since they provide iOS users with an "improved" mobile experience. However, it does raise an interesting question about whether we add/support audits for proprietary, non-standards track features. e.g. do we also add and audit for the `msTile` stuff too?

For these meta tags, I'd suggest a single _information_ audit instead of a bunch of individual ones. Something like "Supports iOS's web capable homescreen features", possibly under Fancier stuff.

**Comment by paulirish** [comment]
>  I'd suggest a single information audit instead of a bunch of individual ones. Something like "Supports iOS's web capable homescreen features", possibly under Fancier stuff.

Yes same. I am currently moving the existing a2HS stuff to be a single audit, anyway.

**Comment by patrickhulce** [comment]
I like it! I'm in favor of informing developers of really helpful things they could be doing that have a sizable impact even if they're not exactly open. Especially since the Safari public stance on SW/the open standards to accomplish this is so murky.

> I'd suggest a single information audit instead of a bunch of individual ones. 

Down for this across the board! +1!

Aside, @ebidel do you know what might account for discrepancy between [caniuse](http://caniuse.com/#feat=web-app-manifest) and [chrome status](https://www.chromestatus.com/features/6488656873259008), just FF proprietary?

**Comment by ebidel** [comment]
All of the browser support info on chromestatus is manual. I'd trust
caniuse. Not sure who added the proprietary API note. Could be outdated.

**Comment by paulirish** [comment]
Instead, let's await their PWA implementation.
