### ISSUE TITLE
lighthouse hangs on specific websites

### ISSUE THREAD

**Issue by cedricbellet** [GoogleChrome/lighthouse#1891]
Noticed the issue with 1.6.0 and 1.5.2, running lighthouse against some specific websites results in errors (lighthouse hangs until SIGINT). Specifically observed on thomson.co.uk with the following error:

status Retrieving: AnchorsWithNoRelNoopener +1s
(node:90614) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'value' of undefined
(node:90614) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

to reproduce:
lighthouse https://www.thomson.co.uk

**Comment by brendankenny** [comment]
thanks for reporting!

The fix for the unhandled exception here is pretty simple (the property value is optional over the protocol but we assume it will be there), but I haven't figured out why this site fails compared to all the other ones we've looked at.

For reference, this is from looking up anchor elements with no rel="opener". The first anchor in question that has an issue has outerHTML of `<a href="http://www.gov.uk/travelaware" target="_blank" class="stay-safe">www.gov.uk/travelaware</a>`, has an `href` *attribute* of  `http://www.gov.uk/travelaware`, but its href property isn't returning any value. `driver.evaluateAsync` of `anchor.href` correctly returns `http://www.gov.uk/travelaware`.

Not sure what's going on yet.
