### ISSUE TITLE
"Uses HTTPS" result is incorrect on WPT

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#1904]
LH report:  https://www.webpagetest.org/lighthouse.php?test=170324_KB_5MBY&run=1
WPT details: https://www.webpagetest.org/result/170324_KB_5MBY/

On this report you can see "uses https" fails but the test URL is "https://...". It was captured on chrome stable on android. 

We've seen some issues with the Security domain in Headless and it's possible we're encountering similar problems here. 

Does someone have an android they can debug this with?

**Comment by ojanvafai** [comment]
Interestingly, https://mobile.twitter.com only fails the uses https check for me if I run lighthouse on an android device.

Incidentally, I'm hitting this on a personal project of mine as well. I think this is probably why I'm not able to get the add to homescreen banner to prompt. I thought we had broken the prompt in canary because the desktop version of my site passes all the https lighthouse tests. But I see that the prompt still works on flipkart in canary.

Happy to share the URL to my site privately if it would help debugging.
