### ISSUE TITLE
Process.exit inside gulp example

### ISSUE THREAD

**Issue by Bubbit** [GoogleChrome/lighthouse#1955]
What is the reason process.exit() is required at the end of the run? 
https://github.com/GoogleChrome/lighthouse/blob/master/docs/recipes/gulp/gulpfile.js#L75
I'm trying to integrate pwmetrics as part of my CI-chain, but currently the only solution is to spawn it in a different process. I've asked the question within the pwmetrics repo, but they redirected me to lighthouse: https://github.com/paulirish/pwmetrics/issues/88

**Comment by ebidel** [comment]
The `process.exit()` is not strictly needed. Instead, the `gulp lighthouse` task should just return the promise chain and exit cleanly with a status 0. This would indicate to the CI that everything went fine.

On the other hand, if you wanted to fail the build due to a low LH score, you could `process.exit(1)` in `handleOk`:

```
const handleOk = function(results) {
  stopServer();
  // process.exit(1) or throw if score falls below a desired threshold.
  return results;
};
```

I'll update the example.

**Comment by pedro93** [comment]
I apologise beforehand on commenting on a closed issue but I don't think my question is relevant enough to open a new issue.
@ebidel With the new updated gulp recipe https://github.com/GoogleChrome/lighthouse/blob/master/docs/recipes/gulp/gulpfile.js shouldn't lighthouse be run as a ```child_process``` due to JS's-single threaded nature? Will there not be a resource competition between the server and the lighthouse process? If its a server-side rendering server (nodejs with react for example) won't there be a large impact on obtained metrics (especially perf)?

**Comment by ebidel** [comment]
Good question. I'm not a Node event loop expert :) FWIW, I didn't see a large amount of variance when I tried the code below on the index.html example page. Would be interested to see numbers if you do some testing against a heftier site.

You could do something like this if you want to be cautious:

```js
const exec = require('child_process').exec;

const runLighthouse = function() {
  const url = `http://localhost:${PORT}/index.html`;
  const lighthouseOptions = {outputPath: 'temp.report.html', output: 'html'};

  return new Promise((resolve, reject) => {
    const cmd = `lighthouse --output=${lighthouseOptions.output} \\` +
        `--output-path=${lighthouseOptions.outputPath} ${url}`;
    exec(cmd, (error, stdout) => {
      if (error) {
        return reject(error);
      }
      resolve(stdout);
    });
  });
};
```

Most of the interesting stuff LH does runs in the browser/chrome. Other than that, we do some message passing with the chrome debugging protocol + some post processing/calculations. By that time, the server has already fulfilled its results.

I see the gulp recipe more of a sanity check...a quick way to get folks testing changes locally. If someone really cares about accurate performance numbers, they should run lighthouse against a staging server that mimics a production setup.  For example, there won't be http/2 support if `localhost` isn't served over ssl. That will change perf numbers.
