### ISSUE TITLE
Audit: Animations on layout inducing properties.

### ISSUE THREAD

**Issue by tdresser** [GoogleChrome/lighthouse#2208]
People often animate top or margin instead of transform, for example.

In most of these cases, animating transform would work fine. In an ideal world, we could identify when switching to transform will work, but I suspect just flagging all animations on layout inducing properties which move things around would be a good place to start.

**Comment by paulirish** [comment]
yes! definitely want this.

we can also quantify the amount of time doing style/layout/paint/raster during these animations.

Dependent ticket on the chromium side: [230229 - Reporting for animations that weren't accelerated - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=230229&desc=2)

Design doc: [Surfacing Composited Animations in DevTools](https://docs.google.com/document/d/1koGgZ6NMsr27RdpqxJtv7w5uNgok2EmgQ7nfuELL8zc/edit)
cc @suzyh

**Comment by tdresser** [comment]
Awesome, didn't know this work was underway.

Depending on timelines, would it be worth doing something cheap and hacky in the meantime? I think just handling position, margin and padding would give us 80% of the benefit, for a low fraction of the time. Since these are never composited, this should be easy, right?

**Comment by paulirish** [comment]
> would it be worth doing something cheap and hacky in the meantime?

Yeah I'm up for it. 

Cheap and hacky being parsing all stylesheets?

We _could_.. and we could look for transitions affecting these properties and keyframe anims including these properties.  `transition: all` is an interesting case.
Generally we found user-side css parsing to be realllly slow, but perhaps there's some room for improvement there.

Other approaches could be `Animation` events over the protocol (or in the trace) could include what style properties they are associated with. But that doesn't seem too cheap 'n hacky to me. :)

**Comment by tdresser** [comment]
You're probably right that there's a happy medium here.

Including the associated style properties would be a lot easier than the currently listed plan, but would also support a decent incremental approach. I'll kick off an email thread.

**Comment by paulirish** [comment]
nice nice! thanks for pushing this one. agree it's high impact and the right place to do it.

**Comment by tdresser** [comment]
It looks like we already pass information on what property we're animating in the Animation trace event.
Isn't that enough to do a decent job here?

https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/inspector/InspectorTraceEvents.cpp?rcl=c5b0d3fffea7f2b8a54718903d82f221ca204d85&l=1172

**Comment by paulirish** [comment]
(a few years later..)

> It looks like we already pass information on what property we're animating in the Animation trace event.

FWIW it looks like the CSS property **isn't** in the trace event. But https://chromium-review.googlesource.com/532435 added reasons that I think are the exact signal we want. @adamraine is looking into surfacing those reasons into the Animation trace event.

----------


locations in today's codebase: 

* trace event data construction: [inspector_trace_events.cc](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/inspector/inspector_trace_events.cc;l=1430-1444;drc=cd7526f9401d3f925424ed65e44688eb15dbe1a5?originalUrl=https:%2F%2Fcs.chromium.org%2F)
* trace event location: [animation.cc - Source](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/animation/animation.cc;l=2167-2177;drc=da80e5c2a6aec79d0a1283658f36cb6f264ce2dc)
* failure reasons why an anim can't be composited: [compositor_animations.h](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/animation/compositor_animations.h;l=58-103;drc=f5c26dea72747aa434da84c57655cac5272d5ad4?originalUrl=https:%2F%2Fcs.chromium.org%2F) and the reason is determined via `CheckCanStartAnimationOnCompositor`

**Comment by adamraine** [comment]
Would it be a good idea to pass a failure code to the user?  We could theoretically add more descriptive strings for each failure reason or pass a link to more info about the codes.

**Comment by connorjclark** [comment]
(note: the links @paulirish shared used to point to error strings, but those were removed. turned into error codes. so we must create our own strings now. This is better for us, b/c we still need to i18n)

I'm no expert in animations. Are the error cases enumerated by `FailureReasons` really useful for guiding action? deferring to @tdresser and @paulirish as I think they've more experience here.

**Comment by tdresser** [comment]
I think we probably should add the property to the trace, sorry I was mistaken about that already existing.
@flackr.

**Comment by paulirish** [comment]
@flackr fyi we're adding the failure reason to the trace here https://chromium-review.googlesource.com/c/chromium/src/+/2283289

we'd definitely appreciate your help in carrying over the css property


-----


@connorjclark the key reason is `kUnsupportedCSSProperty` which is very actionable. it looks like there may be ~4 others that might be developer actionable, although i'm not super familiar with them. Many of these aren't actionable. 

So we essentially could surface just two primary reasons to the LH user: "failed because of unsupported css property" or "failed because of other/browser reasons".

**Comment by adamraine** [comment]
@paulirish We may only want to report animations with failure reasons that are actionable.  Is it useful to know which animations fail to composite for browser related reasons?
