### ISSUE TITLE
bump speedline version and enable fastMode

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2227]
thx to patrick's amazing feature addition: https://github.com/pmdartus/speedline/pull/49

v1.2.0 https://github.com/pmdartus/speedline

**Comment by brendankenny** [comment]
this is cool. What's the difference in PSI score like?

**Comment by patrickhulce** [comment]
@brendankenny depends on the site

if the layout is very unstable than it can theoretically be quite different, but in practice there's a <1% deflation since differences of <1% get essentially floored until you reach a 1% difference. On several traces I tested there was not a difference at all since the frames were either identical and layout was occurring offscreen or there were significant enough changes to avoid the fast. Ideally we should monitor this with plots and tweak as needed.

There's a much more significant change bundled with that PR for PSI than fastMode which fixes https://github.com/pmdartus/speedline/issues/48, but we should probably just move speedline's implementation to be in line with the one in visualmetrics
