### ISSUE TITLE
Allow custom TMP_PROFILE_DIR

### ISSUE THREAD

**Issue by sundeepnarang** [GoogleChrome/lighthouse#2291]
Launcher kept failing when started with default user data dir on macOS Sierra.  Now this probably is an issue with chrome or directory permissions on my system.

However, I was easily able to fix this by passing a custom --user-data-dir in additionalFlags
This does double the --user-data-dir argument, and maybe we could allow for it to customizing TMP_PROFILE_DIR in configuration.

**Comment by paulirish** [comment]
@sundeepnarang sounds like you're using LH as a module rather than on the CLI?

also.. are you using Lighthouse from master/canary?

if so, would you be willing to look at why https://github.com/GoogleChrome/lighthouse/blob/master/chrome-launcher/utils.ts#L32-L45 is failing?

An alternative solution here is to use some `tmpdir` node module that solves this issue already, rather than our custom version. And that way you wouldn't need to provide this argument.
how does that sound?

**Comment by sundeepnarang** [comment]
@paulirish Yeah you are correct I am using it as a module, just for the purpose of launching chrome using chrome launcher module.

Also, am using master.

https://github.com/GoogleChrome/lighthouse/blob/master/chrome-launcher/utils.ts#L32-L45 is not failing for me, The directory is indeed created. Chrome just crashes when started with the the temp dir created here, as the user data dir. If is pass a different user data dir it works, with logging and other things still taking place in the temp dir created here.

This makes me believe that the issue is just with user data dir with chrome on mac and not something to do with LH.

However it is easily mitigated by passing a custom user data dir, so I wanted to suggest that if we could allow user data dir flag to be passed as config option for chrome launcher.

Something like this, but its still missing rimraf for this new user data dir and maybe other things.
https://github.com/sundeepnarang/lighthouse/blob/master/chrome-launcher/chrome-launcher.ts#L86-L100

**Comment by paulirish** [comment]
I see i see.

okay that's convincing. :)
