### ISSUE TITLE
Measure the execution time of each task more accurately

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#2304]
Right now some audits that request computed artifacts are before the audit that most clearly identifies what's being computed (loadfast4pwa uses first interactive and looks like it takes a very long time while first interactive later appears to be very fast since it's using the now cached result.

**Comment by kscm** [comment]
Since v2.0.0, performance measures are baffling, like here:
 _Consistently Interactive_ 850ms, but registering _First meaningful paint_ 851.9ms

First meaningful paint 851.9ms
First Interactive (beta) 850ms
Consistently Interactive (beta) 850ms

And somehow the "850ms" ~ "1+ sec" I get as results don't really match what I see:
https://www.webpagetest.org/result/170521_31_TBB/

LH v1 was measuring those at about 250ms in the last tests.

Are those new values due to the same issue?

[kinoseed.com_2017-05-21_19-56-32.json.zip](https://github.com/GoogleChrome/lighthouse/files/1017179/kinoseed.com_2017-05-21_19-56-32.json.zip)

**Comment by benschwarz** [comment]
I'm seeing this too on plenty of runs

**Comment by brendankenny** [comment]
@kscm that sounds unrelated to the original post. This is talking about the wall clock time to compute an audit, not the time an audit measures. Would you mind filing a separate issue?

**Comment by patrickhulce** [comment]
@paulirish's awesome idea: put the timing of each audit and gatherer into the LHR's `timing` object
