### ISSUE TITLE
Lighthouse 2.0.0 FF issues

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#2320]
I'm using Firefox 54 beta on Windows 7 64-bit

1. Some of the new SVG icons don't show up here
2. The score on the sidebar shows NaN

![screen shot 2017-05-20 at 20 01 33-fullpage](https://cloud.githubusercontent.com/assets/349621/26277798/0eaa3512-3d98-11e7-8f89-ef9d2e0b4898.png)

**Comment by patrickhulce** [comment]
re-opening for the second half of this issue that wasn't addressed by #2361 "Some of the new SVG icons don't show up here"

**Comment by ev1stensberg** [comment]
I'll pick it up tomorrow, sorry!

**Comment by ev1stensberg** [comment]
Last item to fix is the bugs due to `details` and `summary` in firefox, where `chrome` uses `::-webkit-details-marker` to completely forget about this issue

**Comment by XhmikosR** [comment]
@ev1stensberg: can't we do what the MDN article suggests? https://developer.mozilla.org/en/docs/Web/HTML/Element/details

**Comment by ev1stensberg** [comment]
Problem is source code using flex inconsistently

**Comment by ev1stensberg** [comment]
You can use display: list-item instead , but will render on chrome very badly if we don't use a psudoelement accordingly :)

**Comment by ev1stensberg** [comment]
I was actually tempted to correct the manual audits class in `<summary>` to be compliant to the passed audits, in order to at least make the colors depend, instead of implicitly. Regardless, this is an issue with `::-webkit-details-marker` and `list-item` styling that differs in chrome from FF. 
![skjermbilde 2017-05-29 kl 15 29 38](https://cloud.githubusercontent.com/assets/16735925/26551660/db20e432-4483-11e7-9a22-36f315830199.png)
![skjermbilde 2017-05-29 kl 15 29 26](https://cloud.githubusercontent.com/assets/16735925/26551661/db226a3c-4483-11e7-97d6-6fccc33d076c.png)

**Comment by ev1stensberg** [comment]
Actually, let me take the first things I said back. We use the psudo-element to style. In firefox, doesn't seem to work cause display doesn't get updated / `::-webkit-details-marker` doesn't apply the marker changes, as we've disabled the native bullet point/arrow. This is a hack ❌

**Comment by ev1stensberg** [comment]
Could we move this to #2385 ?

**Comment by XhmikosR** [comment]
I haven't verified with the latest master myself. If you confirm only this
is left feel free to close.
