### ISSUE TITLE
performance measures, since v2.0.0

### ISSUE THREAD

**Issue by kscm** [GoogleChrome/lighthouse#2327]
Since v2.0.0, performance measures are baffling, like here:
_Consistently Interactive_ 850ms, but registering _First meaningful paint_ 851.9ms

First meaningful paint 851.9ms
First Interactive (beta) 850ms
Consistently Interactive (beta) 850ms

The "850ms" ~ "1s+" I get as results don't really match what I see:
https://www.webpagetest.org/result/170521_31_TBB/

LH v1 was measuring those at about 250ms in the last tests.

JSON export:
[kinoseed.com_2017-05-21_19-56-32.json.zip](https://github.com/GoogleChrome/lighthouse/files/1017566/kinoseed.com_2017-05-21_19-56-32.json.zip)

**Comment by patrickhulce** [comment]
@kscm a couple of things are going on here

* The WPT run I see looks like no throttling was applied (using "Cable" network settings), are you comparing to a Lighthouse run without throttling as well?
* Assuming you're using the default LH setup, the drastic increase in metric times is a result of harsher throttling that we've made default in 2.0 (#2238)
* FMP seemingly after interactive is fixed by #2295

**Comment by kscm** [comment]
Thanks.
