### ISSUE TITLE
Runs with very slow network connections will not resolve a firstMeaningfulPaintCandidate

### ISSUE THREAD

**Issue by benschwarz** [GoogleChrome/lighthouse#2331]
When slowing a page down to a 2G connection (via chrome's definition of this), lighthouse times out the run at 30 seconds, and then attempts to grab the trace… only to find that there is no `firstMeaningfulPaintCandidate` present. 

Given that 2G connections make up around 60% of global mobile connections, I think its worth pursing this issue. Keen to hear your ideas.

**Comment by patrickhulce** [comment]
@benschwarz we've been discussing potential timeout changes, but since any site with an FMP of >30s will fail nearly every perf audit we have with a 0, it's not super clear what value we get out of identifying exactly how bad it is since we'd also be slowing down the default runs of all other sites. 

In those situations where you're trying to track performance beyond 30s and as a workaround, you can use the CLI flag `--max-wait-for-load 60000` or the node flag `flags.maxWaitForLoad: 60000` to increase the timeout to 60s (or whatever number you'd like). You'll start to face some OOM problems with large traces on certain sites though so fair warning :)

**Comment by benschwarz** [comment]
@patrickhulce Yeah, I was thinking that would be the case — Perhaps the timeout could be raised for runs that have network set below x many bytes per second? At least that way the runs wouldn't take longer for no reason. 

I don't know that theres any LH action to take here, but I wanted to share it somewhere that you can come back to it when looking at network timeout. :1st_place_medal:

**Comment by patrickhulce** [comment]
@benschwarz we're going to consider this closed, but feel free to comment if you think there's more to be done on our side.
