### ISSUE TITLE
Cannot read property 'args' of undefined

### ISSUE THREAD

**Issue by awebdeveloper** [GoogleChrome/lighthouse#2339]
```
Performance
These encapsulate your app's performance.
Metrics
These metrics encapsulate your app's performance across a number of dimensions.
First meaningful paint
Audit error: Cannot read property 'args' of undefined
First Interactive (beta)
Audit error: Cannot read property 'args' of undefined
Consistently Interactive (beta)
Audit error: Cannot read property 'args' of undefined
0
Perceptual Speed Index
Audit error: Cannot read property 'args' of undefined
0
Estimated Input Latency
Audit error: Cannot read property 'args' of undefined
```

**Comment by ebidel** [comment]
Do you have repro steps? What site were you testing and what version of Lighthouse?

**Comment by awebdeveloper** [comment]
it's a internal under dev site so can't share the url yet 

Looks like restarting chrome fixed the issue

**Comment by ebidel** [comment]
K. Let us know if you run into this again.

**Comment by lifeiscontent** [comment]
@ebidel I ran into this issue running benchmarks in this repo: https://github.com/A-gambit/CSS-IN-JS-Benchmarks/blob/master/packages/tests/index.js

**Comment by mxstbr** [comment]
@ebidel same, I can reliable reproduce by running the repo @lifeiscontent mentioned.

**Comment by ericwooley** [comment]
This should probably be reopened?

**Comment by Hoten** [comment]
Please open an issue with that repo. It uses v1.6.5 of Lighthouse. If it worked at one point, and no longer does, I suppose it could be due to a incompatibility between old Lighthouse and new Chrome.

If a URL exists that running lighthouse directly (via Node or Chrome Devtools) results in `Cannot read property 'args' of undefined`, please share and we can reopen this issue.
