### ISSUE TITLE
Fix inconsistencies between CLI and module

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#2401]
| Using as a module  | Using from the CLI |
| ------------- | ------------- |
| 0: LHR contains artifacts (`lhr.artifacts`) | LHR does not contain artifacts ([nuked here](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-cli/bin.ts#L173))  |
| default output is `json`  | default output is `html`  |
| 1: no way to specify `html` output |  choose format with `output` flag |
| 2: [user needs to set log level](https://github.com/GoogleChrome/lighthouse/tree/master/docs#turn-on-logging) to see `ChromeLauncher` output | logging is setup for the user |

**0**:

LHR should be exactly the same no matter how you run LH.

**1**:
User is required to use `report-generator`:

```javascript
const ReportGenerator = require('lighthouse/lighthouse-core/report/v2/report-generator');
runLighthouse('https://example.com').then(lhr => {
  const html = new ReportGenerator().generateReportHtml(lhr);
  console.log(html);
});
```

We should support `output: 'html'` in core so users can use the same flag as the CLI.

**2**:
User is required to use our `log` module:
```javascript
const log = require('lighthouse/lighthouse-core/lib/log');

async function launchChromeAndRunLighthouse(url, flags) {
  const chrome = await chromeLauncher.launch();
  flags.port = chrome.port;
  const results = await lighthouse(url, flags, config);
  await chrome.kill();
  return results;
}

const flags = {logLevel: 'info'};
log.setLevel(flags.logLevel); // logs the ChromeLauncher output.

launchChromeAndRunLighthouse('https://example.com', flags);
```

**Comment by brendankenny** [comment]
we're actually pretty happy with how this (very eventually) turned out :)

- CLI *does* have to use `-G` or `--save-assets` to get artifacts, but it's not part of the LHR, which is indeed [the same](https://github.com/GoogleChrome/lighthouse/blob/5aeef234faf8a342bf5d195529019d61f5b05cbb/types/lhr.d.ts) no matter where you run it
- default report output formats are still different, but don't manually need to use a `ReportGenerator`, `output` will do fine
- you can specify `output` for the module and CLI
- chrome-launcher takes a `logLevel` option same as lighthouse, no need to mess with `lighthouse-logger`

<3
