### ISSUE TITLE
Lighthouse on headless chrome - Some performance tests are not running

### ISSUE THREAD

**Issue by r-tock** [GoogleChrome/lighthouse#2434]
The following three fails with the same error. Is this a known issue? I tried running it with Chrome Canary and Chrome Beta.

Page load is fast enough on 3G
Audit error: The main thread was busy for the entire trace recording. First Interactive requires the main thread to be idle for several seconds.

First Interactive (beta)
Audit error: The main thread was busy for the entire trace recording. First Interactive requires the main thread to be idle for several seconds.

Consistently Interactive (beta)
Audit error: Main thread activity continued through the end of the trace recording. Consistently Interactive requires a minimum of 5 seconds of both main thread idle and network idle.

**Comment by patrickhulce** [comment]
@r-tock what URL are you running against?

Note that if you are reaching the 30s timeout then this is expected behavior because the page did not have the minimum required idle time. However, there are known issues with particular loading patterns causing Lighthouse to prematurely stop tracing.

**Comment by r-tock** [comment]
https://next.tocktix.com. the page loads very fast an di have put a 5minute timeout.

**Comment by patrickhulce** [comment]
Thanks for sharing your URL! In your case, these audits are failing because it looks like stripe has a recurring timer firing that does large chunks of JavaScript work. To pass these checks, you might have to reach out to stripe to see if its unexpected use of their SDK or something on their end to sort out. Keeping latent script executions under 50ms is important to ensure the page is free to handle user input.
![image](https://cloud.githubusercontent.com/assets/2301202/26789707/ba663f3c-49d6-11e7-9950-7caf05264894.png)

**Comment by r-tock** [comment]
Ah. Thanks for pointing that out. I thought the tests were busted. Yes! indeed stripe is doing something bad. I will close this. The tests are running correctly against other sites.

**Comment by chrisdwheatley** [comment]
Rather than opening a new issue I figured I'd ask here about the same issue I'm seeing when running Lighthouse through webpagetest.

Here's what I'm seeing https://www.webpagetest.org/result/170608_KH_4a8be412cf0ef89d56e3cb13a8eed676/ (this is running as Mobile - Faster 3G from https://www.webpagetest.org/easy)

Here's a similar test but using Mobile - Emerging Markets where the waterfall looks pretty similar but the Lighthouse results don't fail as much https://www.webpagetest.org/result/170607_PW_1d454612c736a65ddff058cf16b8842e/

The website is https://nextjs-hn.chrisdwheatley.com/, when running Lighthouse via the Chrome extension or in the devtools in Chrome Canary I'm unable to replicate the issue.

If you have any thoughts as to what's causing this issue it'd be much appreciated.

**Comment by patrickhulce** [comment]
hey @chrisdwheatley thanks for the report! let's go ahead and start a new issue though since @r-tock's case was indeed some misbehaving scripts preventing the main thread from ever quieting and it looks like your issue might be a different root cause

**Comment by chrisdwheatley** [comment]
Yes, sorry, that makes sense.

I've raised #2475.

**Comment by dekkofilms** [comment]
@r-tock did you ever reach out to Stripe? I think I might be having the same issue as you with stripe.

**Comment by r-tock** [comment]
@dekkofilms did not, the issue went away when we migrated to stripe js v3 from v2

**Comment by dekkofilms** [comment]
ah, i was thinking that might be the case ... i'm looking into the migration guide from v2 to v3, so I might go ahead and try that. thanks for the quick reply @r-tock

**Comment by drobertsacbj** [comment]
I get this error but don't have anything to do with Stripe.

**Comment by patrickhulce** [comment]
@drobertsacbj if you have a different root cause but consistently experience this, please file a separate issue with a trace and/or URL so we can investigate. Thanks for searching for duplicates first :)
