### ISSUE TITLE
Discard / stop run in extension if popup dismissed.

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/lighthouse#248]

**Comment by kdzwinel** [comment]
UX here is really bad - audit takes solid 20s to finish and you can't do anything during that time since popup has to be focused for script to finish. Also, since 20s is already quite a lot (and I assume it will get even longer over time), it'd be nice to show some kind of a progress bar.

IMO audit script has to be moved to the background page and progress should be shown on the extension button (e.g. [using a build in solution](https://developer.chrome.com/extensions/browserAction#method-setBadgeText)).

I can give both issues a try. WDYT?

**Comment by paullewis** [comment]
@kdzwinel totally hear you, but for performance data we need you to not interact with the page, otherwise it gets skewed. But yeah we could give more of an update on the processing. Let me think on it a little first, I know it's an issue, I'm not sure what the best solution is just yet.

**Comment by boopathi** [comment]
Spawn a new window in the background and run audits in that ? - Have this as an option in the popup where you can choose to run on current tab or a new window.

**Comment by kdzwinel** [comment]
> for performance data we need you to not interact with the page, otherwise it gets skewed
TBH I haven't really thought of that, it does complicate things.

Progress bar will definitely ease the pain of waiting a bit. It can also expose which tests are especially time-consuming.

> Spawn a new window in the background and run audits in that ?
Unfortunately, a new window doesn't change anything as it would have to be focused through the whole audit to avoid skewing the data.

**Comment by paulirish** [comment]
This seems like less of a pain point recently. The progress indications help.

Also the popup closing doesn't affect the run, though I can imagine people not knowing that.
I'm open to adding text to the popup communicating "you can do stuff while this completes, but preferably not in the same browser" :p
