### ISSUE TITLE
audit: Omnibox matches brand colors

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#25]
Manual evaluation:  manifest has  `theme_color`, `<head>` has `<meta name="theme-color" content="_any valid CSS color_">`

##### input:
* parsed manifest - #22

##### audit:
* parse manifest for `theme_color`. 
* Grab DOM and parse `document.head` for the `theme-color` meta.

Currently both are required. Chrome will be transitioning to use manifest theme-color by default: go/fizz-feature-backlog has a tracking item for this.

See also "PWA validator" bookmarklet - #17

_Docs_:  [Support for theme-color in Chrome 39 for Android](https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android?hl=en), and [whatwg/meta-theme-color: Spec for the `theme-color` meta extension](https://github.com/whatwg/meta-theme-color)

**Comment by paulirish** [comment]
@brendankenny i think we have the pieces for this. can you hook them up to an aggregator so it gets surfaced?

**Comment by paulirish** [comment]
I have a PR up that'll take care of this.

**Comment by paulirish** [comment]
@mounirlamouri question that came up in #104.. what happens if color are specified in both meta and manifest and they differ?

**Comment by mounirlamouri** [comment]
If `theme_color` is defined in the Manifest, it will be used as a default `theme_color`. Each page can then override it using the `meta` tag. Though, using the Manifest `theme_color` has the added benefit of being used for the splash screen.

**Comment by paulirish** [comment]
Perfect. That's just what we needed to know. Thanks!

**Comment by brendankenny** [comment]
I think I still don't understand the purpose of this audit. Maybe it's just that the title of this issue is throwing me off. What are brand colors? :)

Is the idea:
- Chrome won't by default fetch the manifest, so `<meta> theme-color` is needed
- When Chrome does fetch the manifest, it will use the manifest's `theme_color` for things like the splash screen, so you need it there too

but if the `<meta> theme-color` overrides the manifest `theme_color`, do you need a manifest one for the omnibox if you have a `<meta>` one? It seems like one or the other is sufficient, unless you want a splash screen color as well?

**Comment by brendankenny** [comment]
Oh, I might be missing the other way. If you have a `theme_color` in your manifest, you need a `<meta> theme-color` in your page because we don't currently fetch the manifest on page load.

But it seems like if you have a `<meta> theme-color`, the manifest `theme_color` should be optional still?
