### ISSUE TITLE
Image audit: check for correct aspect ratio

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/lighthouse#2579]
The aspect ratio of an image element should match the aspect ratio of the image displayed, even if the dimensions are different.

Test by comparing `img.naturalWidth`/`img.naturalHeight` with `img` element `clientWidth`/`clientHeight`.

Need to ensure image element `load` event has fired before testing.

**Comment by ThisIzKp** [comment]
I volunteer to take a look at this one. 

Never did any open source, Any pointers on how to start on this one? Should I've to read the entire code base first and then jump into it? or try fixing and slowly figure it out?

**Comment by patrickhulce** [comment]
Thanks for volunteering @ThisIzKp! No need to understand the whole code base, but I'd definitely read through the various docs we have on [writing custom audits](https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/custom-audit) and [contributing](https://github.com/GoogleChrome/lighthouse/blob/master/CONTRIBUTING.md) in general to understand how Lighthouse overall works.

To get started with this specifically you can take a look at the [responsive images audit](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/byte-efficiency/uses-responsive-images.js#L47) to see how we consume image size information.

**Comment by ThisIzKp** [comment]
@patrickhulce started working on this, have some queries related to that

- should the aspect ratio audit be grouped into `performance-info` or `best-practices` category?
- will the aspect ratio have any potential byte savings? I'm not sure about this, dimensions will have savings, but that is already being handled
- should it handle only images for now? or should be generic to handle both images & videos?

**Comment by patrickhulce** [comment]
Great! This definitely seems like a best practices audit since the (potential) byte savings is already captured by the responsive images audit. If it's super easy to handle videos in the same audit without much complexity go for it, otherwise it's fine to leave it for images only for now.

**Comment by ThisIzKp** [comment]
<img width="690" alt="screen shot 2017-08-20 at 5 52 18 am" src="https://user-images.githubusercontent.com/4737336/29491002-d204b918-856b-11e7-9ac8-83da13a78b16.png">

Is this info good enough? Or should I reduce the aspect ratio's to simplest fractions? 
How should the errors like 0/0 (Zero division) be handled?

**Comment by ThisIzKp** [comment]
I see that for few of the images I'm getting `clientWidth/clientHeight` as 0/0, I think this is because of some lazy loading on the images or Audit being fired before the layout/Images are loaded. How can I make sure to run the audit after the Image `loadEvent` has been fired

@samdutton any ideas about this? Are you mentioning about this in the issue description?

**Comment by patrickhulce** [comment]
@ThisIzKp that looks good though I might add the decimal aspect ratio as well and allow for a reasonable amount of slop (maybe if `Math.abs(aspect1 - aspect2) < .05` it's ok?), we should probably also ignore this entirely if the [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) property is set since it's then intentional.

`388 x 291 (1.33)`, `411 x 308 (1.33)`

As for the 0 clientWidth, we generally ran into that when the images weren't being displayed at all yet, for now I'd say it's safe to ignore them since we're already waiting for network idleness before the `afterPass` methods on the gatherers are run.

**Comment by GCDeveloper** [comment]
I seem to be getting 0 clientHeight when height is set to auto on a slow connection, before the image is loaded. Then it is ok. This fails the aspect ratio test.
Bearing in mind I only checked the element height in dev tools on slow 3g network, and didn't check clientHeight programatically.
