### ISSUE TITLE
Potential for multiple emulators?

### ISSUE THREAD

**Issue by thearegee** [GoogleChrome/lighthouse#2700]
More of a question than an Issue. I'm working on a project using the lighthouse emulation file (https://github.com/GoogleChrome/lighthouse/blob/63b4ac14d0a871ade0630db2885edd7848843243/lighthouse-core/lib/emulation.js) to configure a headless Chrome using the DevTools Protocol. 

It's a great resource but it feels like it could potentially be abstracted into it's own module and have support for multiple devices running on different networks conditions.

Any thoughts?

**Comment by paulirish** [comment]
@thearegee hey dude. 

I imagine that emulation.js could be split up a little so that it'd be easier to use other emulation definitions. We'd be open a PR like that.

Alternatively you could use device definitions from https://github.com/ChromeDevTools/devtools-frontend  .. somewhere in the JS are the devices and throttling settings. Not terrible accessible to CJS, but that's where it is.

**Comment by paulirish** [comment]
lastly, we dont plan to publish a new npm module with this, but hey you certainly can. :)

Holler if any of that sounds crazy. You got my number. ☎️
