### ISSUE TITLE
Offline audit: is start_url cached?

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#279]
We've seen some cases where the start_url in the manifest is slightly different than what is cached by the service worker.

* https://m.example.com/?from=homescreen is in the manifest start_url
* https://m.example.com/ cached via the SW Toolbox cache

This results in a sad tab.

**Comment by paullewis** [comment]
This bears a striking resemblance to the offline check. However for cleanliness I think we should dupe that, parse the start_url and then ping it when offline.

**Comment by paullewis** [comment]
Okay, after a little more investigation we're going to have to make a decision or two. This audit needs to have access to the manifest's gather before it does its work, since it needs to know the start_url. At the moment we don't expose the other artifacts to a gatherer.

An option here would be to have an object which is passed to the gatherers that they add their results to, and we can add a bail on this gatherer if the manifest artifact isn't present. I'll code that up to see what it looks like.

**Comment by paulirish** [comment]
now tracked in #507

**Comment by paullewis** [comment]
Merged, so closing this.
