### ISSUE TITLE
Print option is not working in report page

### ISSUE THREAD

**Issue by gokulkrishh** [GoogleChrome/lighthouse#281]
Adding screenshot for reference. Not sure if this print option is in progress or not

![screen shot 2016-05-05 at 9 17 56 am](https://cloud.githubusercontent.com/assets/2944237/15035672/663636f4-12a2-11e6-82d8-ab2a74a8d100.png)

**Comment by paullewis** [comment]
I know what the issue is: the extension doesn't allow scripts in the page because of CSP. I'll either need to move this script to a separate file, or allow it via CSP.

**Comment by gokulkrishh** [comment]
@paullewis 👍

**Comment by paulirish** [comment]
We could remove the option to print?

**Comment by paullewis** [comment]
The logic also makes the nav sticky. I think we're going to need to be able to bundle JS properly for the report anyway, because it'll need to support a bunch of additional behaviors at some point, so I'm more inclined to create a proper way to inline JS for the CLI, and include separate files for the extension.

**Comment by gokulkrishh** [comment]
Sound good @paullewis
