### ISSUE TITLE
Launcher Request: Hide Dock Icon

### ISSUE THREAD

**Issue by shellscape** [GoogleChrome/lighthouse#2818]
Just what the title says. I'd like to request an option for `chrome-launcher` to hide the dock icon while running in headless mode.

**Comment by ebidel** [comment]
Applications in the Dock (or Windows task menu) are controlled at the OS level. Not sure we can do much about this one from Node.

https://discussions.apple.com/thread/7444141?start=0&tstart=0 has some instructions on hiding a running app from the Dock, but it involves editing the app bundle. Probably not something you want to do since you'll be modifying the installed version of Chrome on your machine.

**Comment by paulirish** [comment]
Aye.. this is a known issue for headless chrome on mac. 

It's filed upstream here, so i'll close this one: https://bugs.chromium.org/p/chromium/issues/detail?id=750505

**Comment by shellscape** [comment]
@paulirish hey buddy :) I'm getting involved with headless chrome, gonna be releasing mocha-chrome soon, loving the work you all have done. Thanks for that link, I'll keep an eye on it!

**Comment by unilynx** [comment]
The dock icon fix is now in stable chrome (62.0.3202.62)

**Comment by shellscape** [comment]
@unilynx fantastic news
