### ISSUE TITLE
AMP and Best Practices

### ISSUE THREAD

**Issue by photocoder** [GoogleChrome/lighthouse#2819]
Hello everybody,

I use AMP pages on my website, but after checking by Lighthouse I see in section "Best Practices":
Uses passive listeners to improve scrolling performance:

https://cdn.ampproject.org/v0/amp-carousel-0.1.js | line: 31
https://cdn.ampproject.org/v0/amp-carousel-0.1.js | line: 22

Could somebody tell me "why"? :) I can't control that scripts and I think teams Google products should to "synchronising" between each other...

**Comment by brendankenny** [comment]
Sounds like an issue to file on https://github.com/ampproject/amphtml/ :)

More seriously, "best practices" are just that: ideal ways of setting things up, but sometimes reality gets in the way of doing the "best" thing. Maybe the performance impact is negligible, so no one has bothered to make the change yet. Maybe there's some reason those handlers need to not be passive (some functionality or some corner case of build tools or some issue with older browsers), so they're stuck like that.

Ideally Lighthouse would be able to measure the performance impact that not using passive scroll handers incurs, but it's not there yet (that's why the audit is in "Best Practices" and not "Performance" yet). In the meantime, it's worth keeping in mind the separation between Lighthouse score and that actual measurable performance. It may end up being worth living with a slightly lower Lighthouse score in order to get all the advantages that AMP can bring, especially if the scroll handlers have minimal impact.

Looks like there has been some discussion around this in AMP, so you may want to do some more investigating there:
https://github.com/ampproject/amphtml/issues/4820
https://github.com/ampproject/amphtml/pull/4895
https://github.com/ampproject/amphtml/pull/5109

**Comment by Stefany93** [comment]
Is that going to be fixed any time soon ?

**Comment by connorjclark** [comment]
Kinda looks like amp already fixed this here: https://github.com/ampproject/amphtml/pull/10721

Please provide more details if that is not the case. If the issue still exists, what @brendankenny said is still relevant.
