### ISSUE TITLE
Accessibility audits for color-blindness ?

### ISSUE THREAD

**Issue by EricGrange** [GoogleChrome/lighthouse#2844]
It would be nice to consider adding some audits related to color blindness (which affects 8% of males, cf https://en.wikipedia.org/wiki/Color_blindness).

This issue is notably prompted by Chrome's own dev tools poor color choice sometimes (wrt color blindness), using red / green colors with very similar intensity levels (Audit coverage red /green bars being an illustration).

- In terms of helping non-color-blind people see what is wrong, this could be through applying filters to the rendered page.
- In terms of metrics, a basic approach could be to convert the rendered page to HSL (or similar) and then compare H dispersion to L dispersion.

**Comment by patrickhulce** [comment]
Thanks for the great idea @EricGrange! Do you have any references to existing tools that do this? Identifying which elements on the page need to be distinguishable seems rather difficult, and it'd be nice to have a reference implementation.

**Comment by brendankenny** [comment]
The accessibility `color-contrast` audit is designed to check exactly this, so that even in the absence of differences in (perceived) hue on a test page you'll still see a difference in luminance. See more information about this test on the [axe information page for it](https://dequeuniversity.com/rules/axe/2.6/color-contrast).

This gives at least base coverage, so I feel comfortable closing this issue. But if folks have ideas for audits more specifically targeting color blindness, please do open new issues to propose them!
