### ISSUE TITLE
Document that service worker needs to be registered early

### ISSUE THREAD

**Issue by zoumiaojiang** [GoogleChrome/lighthouse#2924]
URL: https://zoumiaojiang.win
Chrome Version: 60.0.3112.90
Lighthouse Version:  2.3.0

![a3e11ce6773167aed1c120b42211a230](https://user-images.githubusercontent.com/3365978/29154497-8efc9d1c-7dc7-11e7-8766-2bcf4423f344.png)

PS: Service Worker registration is asynchronous

**Comment by patrickhulce** [comment]
Hm, this looks like another case of #599 resurfacing. The registration takes quite some time after network quiet. Though I'm not sure what we can reasonably do about these cases. 5s is already a pretty long time to give room for the service worker to register, and we don't want to wait needlessly for a service worker that will never be registered either. Ideas welcome :)

**Comment by canarslan12** [comment]
I think title of error can be changed to "Does not register a Service Worker or its registration is too slow" and add to information that "registration might be faster" etc

**Comment by patrickhulce** [comment]
That's a good call @canarslan12, let's put that information in the Learn More link. 👍

**Comment by paulirish** [comment]
We identified theres two possible cases here:

1. You called register() very late in the page load cycle. (after Lighthouse detected the page is totally loaded (or after 30 seconds))
1. You called register() early but then the browser was really busy loading the page and never got around to starting the registration/activation process.

**Comment by patrickhulce** [comment]
FWIW, several URLs in #5527 appear to add a third possible case given our new lower 500ms network quiet threshold with Lantern,

3. The service worker was in the process of registering but didn't get to finish before we moved on.

**Comment by brendankenny** [comment]
> You called register() early but then the browser was really busy loading the page and never got around to starting the registration/activation process.

I think this is ruled out, too. The test added in #6648 doesn't strictly keep the page busy, but in my testing, as soon as `navigator.serviceWorker.register()` is called the SW is set to `installing` and it's picked up with a `ServiceWorker.workerVersionUpdated` event, so I believe main thread activity is irrelevant to knowing that registration has started.

At least as of current Chrome (m72), SW installation continues to happen at that point, even if you navigate away from the page before the first script bytes have downloaded.

I had forgotten how this worked. [A long time ago](https://github.com/GoogleChrome/lighthouse/pull/1864), @wardpeet updated the SW version fetcher to wait if the page had no activated service workers but there were SWs in any sort of installation phase:

https://github.com/GoogleChrome/lighthouse/blob/5f369150417c492ca29bcf0d10a7596aec190c99/lighthouse-core/gather/driver.js#L434-L449

Since this check runs in the `beforePass` method of the ServiceWorker gatherer (run in the second, offline pass), interestingly a slow service worker load/startup manifests in the second pass on `about:blank`(!), not in the initial page load, while the browser waits for the SW script to finish downloading and then be installed.

The [new smoke test](https://github.com/GoogleChrome/lighthouse/pull/6648) tests this nicely. If you set its delay to like 50s (and run `static-server.js` and then `lighthouse http://localhost:10200/offline-ready.html?slow`), you'll see it a little more clearly, confusingly pausing on `status: Resetting state with about:blank` for about 50s.

**Comment by brendankenny** [comment]
So for known error cases, I think we currently have
1. You called `register()` very late in the page load cycle. (after Lighthouse detected the page is totally loaded (or after 30 seconds))
2. Page is actually doing something odd (e.g. UA sniffing) and `register()` isn't being called at all when loaded by LH.

With the new smoke test, I think we can now be fairly confident that if `serviceWorker.register()` has been called in a page, `driver.getServiceWorkerVersions()` in `ServiceWorker.beforePass()` would have either blocked until that turned into an `activated` SW or it would have timed out and killed the whole LH run.

**Comment by adrianaixba** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse will be deprecating the PWA category in the next upcoming release. For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/). Marking this as closed!
