### ISSUE TITLE
'sandbox' CSP policy causing some failures

### ISSUE THREAD

**Issue by vcsjones** [GoogleChrome/lighthouse#3020]
I tried running lighthouse on https://vcsjones.com and several tests failed with:

>Audit error: Required Accessibility gatherer encountered an error: The asynchronous expression exceeded the allotted time of 60s

Sometimes it fails saying the Promise has been collected.

I *suspect* it's because vcsjones.com has `sandbox` in its CSP policy.

**Comment by patrickhulce** [comment]
Several cases like this have occurred due to antivirus/extensions/other software interfering with Chrome and the Lighthouse run. Have you tried temporarily disabling all extensions (even just an emoji extension, see #2723) and antivirus software while running?

**Comment by brendankenny** [comment]
There have been some significant changes in axe since this was filed. The test site might have changed since this was filed (I don't see `sandbox` in the CSP header), but on my machine the accessibility gatherer completes in less than a second for this site, so given the age of this issue, I'm going to close.
