### ISSUE TITLE
Localize all numbers in report renderer

### ISSUE THREAD

**Issue by Garbee** [GoogleChrome/lighthouse#3115]
As a question on [StackOverflow](https://stackoverflow.com/questions/45723680/chrome-lighthouse-comma-and-full-stop-in-performance-option) brings up, the number formatting within Lighthouse isn't locale specific. Currently `undefined` is [passed as the locale](https://github.com/GoogleChrome/lighthouse/blob/5c8d4ec7cd23fa84da485261427197d89e757921/lighthouse-core/report/v2/renderer/util.js#L42) which essentially translates to `''`. As far as what happens from there I'm not too sure sifting through the ECMAScript specification.

Either way, one solution for rendering it out properly would be to pass in the navigator's current locale if defined. So something like:

```javascript
 static formatNumber(number, decimalPlaces = 1) {
    const locale = typeof navigator === 'undefined' ? undefined : navigator.language;
    return number.toLocaleString(locale, {maximumFractionDigits: decimalPlaces});
  }
```

**Comment by patrickhulce** [comment]
This is a good find :) this seems more like an issue with the node locale not matching the Chrome locale to me though. For the CLI, some of the numbers are converted into strings in node and others are put into the report as numbers and only turned into strings by the report renderer in the browser. The browser ones appear to be fine but the node ones are erroneously english due to the lack of node i18n support.

**Comment by patrickhulce** [comment]
My point is that the in-browser strings are already being handled properly in the report and the fix is not to pass `navigator.language` (which is taken from the OS in Chrome) but to instead not generate the strings under two different locales. We can just localize all in the browser.

From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString)
> If the argument is undefined, this method returns localized digits specified by the OS

**Comment by Garbee** [comment]
Ah, missed that part reading over MDN's details. Thanks for pointing it out.

**Comment by paulirish** [comment]
p2 fix is forcing 'en-us'. 
p3 fix is not shipping displayValues and formatted values in the JSON.

**Comment by brendankenny** [comment]
mostly done! Moving over to #5719 for the rest.
