### ISSUE TITLE
Ability to generate an HTML-report that does not require JavaScript to render

### ISSUE THREAD

**Issue by shahkashani** [GoogleChrome/lighthouse#3190]
We're hoping to generate a Google Lighthouse report for each PR via our Jenkins builds, but HTML files displayed within Jenkins are not permitted to execute JavaScript (https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy). We are not permitted to loosen the security policies, so it would be great if Google Lighthouse had an option for a pure HTML report.

**Comment by patrickhulce** [comment]
Thanks for the report @shahkashani! FWIW, our easiest path to achieving this is also your best bet for achieving this: rendering the report and saving the resulting HTML. 

You might want to look into something like https://github.com/gajus/usus to render the HTML for you and save that as your Jenkins output instead of what Lighthouse outputs.

**Comment by shahkashani** [comment]
@patrickhulce Hey Patrick, thanks so much for the quick and helpful response! I'll definitely take a look. I'll keep an eye on this ticket, will allow me (and probably others) to rip some code out in the future 😬

**Comment by paulirish** [comment]
I used usus recently and had a great time with it. I would definitely recommend you using that.

Should be reallllllly straightforward. Try it out. :)
