### ISSUE TITLE
Where JSON results documentation is?

### ISSUE THREAD

**Issue by LeMoussel** [GoogleChrome/lighthouse#3336]
Hi,

I'm using `LightHouse` programmatically 
```
const flags = {port: 9222, disableDeviceEmulation: true};
const config = null
const url = 'https://www.google.fr/'
lighthouse(url, flags, config).then((results => {
  // How to use results?
});
```
I want to generate my own report with Json results.

But I don't find documentations about Json results.

**Comment by paulirish** [comment]
Right now there isn't any real documentation on this results object. So you're welcome to explore it yourself. I'd recommend [using Chrome DevTools to look at it ](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27) since it's pretty big.

But yeah we'll work on real docs :)

**Comment by LeMoussel** [comment]
If you have some docs on on GitHub , I can help you :)
