### ISSUE TITLE
PWAs Audit Incorrectly Failed?

### ISSUE THREAD

**Issue by zoerf21** [GoogleChrome/lighthouse#3472]
We were testing out Lighthouse today, so we inputted a site which we know correctly generates a PWA prompt as a means of verification. 

The site we used was m.flybe.com which, when visited on mobile successfully prompts users to install the web app: 
![image-1](https://user-images.githubusercontent.com/32519115/31184019-3101eff8-a920-11e7-96d5-b578327c2c50.jpg)

However this is the report generated by lighthouse:
![flybe](https://user-images.githubusercontent.com/32519115/31184077-5218d652-a920-11e7-8c6c-f28facf73fb2.JPG)

Did we do something wrong? What's going on?

**Comment by patrickhulce** [comment]
Hey there @zoerf21 thanks for the report!

The Lighthouse results you're seeing are accurate because that site is not a PWA. The UI prompt in the screenshot is *made by them* and not the browser actually prompting the user to Add to Homescreen. After all, any site can create a dialog box with text that asks the user to go through the manual steps to bookmark their page :)

This site seems to have gone the route of manually asking users to add to their homescreen instead of satisfying the requirements of the having the browser prompt the user (read more [here](https://developers.google.com/web/fundamentals/app-install-banners/). The site is served over http not https, they didn't register a web app manifest, and they did not register a service worker to make the site work offline.

If you're interested in learning more about PWAs you can read all about them [here](https://developers.google.com/web/progressive-web-apps/).
