### ISSUE TITLE
Rename webp messaging to "next-gen image formats"

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#3557]
On the recent reddit thread some users were flummoxed by the recommendation to adopt and serve webp: https://www.reddit.com/r/webdev/comments/75w7t0/so_exactly_what_do_i_do_google_put_my_css_in_js/doatllq/

Indeed, it is only supported by 1 rendering engine. And unfortunately it's fairly difficult to pull off. 

Given the difficulty and the reduced impact, we should consider removing the audit from the default. WDYT?

**Comment by benschwarz** [comment]
Wellllll, there's also HEIC, Jpeg2000 and other options. The fact is that because adoption *sucks*, one of these can't be recommended individually atm. I'd opt to change it to be "use a modern image format like WebP, HEIC, Jpeg2000, etc… or, where possible use a transcoding CDN that is clever enough to do client hints. 

The point of the audit is to point out that there are alternatives that will improve performance or user experience. Recommending superior image formats is definitely worth doing.

**Comment by wardpeet** [comment]
I really like this audit as well as this gives a performance boost when running a lot of images as news websites do. We see image decode time, download time and such drop when using webp

I would try to put more options in the audit like @benschwarz is stating as this might be a bit hard to do.

**Comment by patrickhulce** [comment]
I like @benschwarz's approach and believe we had aspirations to do that at one point (at least I did :) ). At the very least, changing the copy to say "adopt next-gen image format" or something seems reasonable
