### ISSUE TITLE
Document which CLI flags are/aren't available from node module

### ISSUE THREAD

**Issue by factordog** [GoogleChrome/lighthouse#3587]
Hi there,

Been doing some digging into using lighthouse programmatically. 
https://github.com/GoogleChrome/lighthouse/tree/04b685fa9f492039ba54d60bbfaa8345c85c64dd/docs
Looking into passing flags to generate JSON files I noticed that this only actually utilizes this flag in the lighthouse-cli.

So by passing an outputPath would as a result do nothing? This is more of a confirmation more than anything. As I know you get the result set on the response etc and could just create your own file using nodes file system. Im more just wanting to see if I am missing something in utilizing lighthouse to do this for me.

**Comment by mingsterism** [comment]
Hi, I noticed that there is no documentation on the format of flags if using lighthouse through nodejs. 
For example: I've tried using `outputPath: "./myfile.json"` and `outputpath: "./myfile.json"` but none works. 
Thanks

**Comment by patrickhulce** [comment]
Hey folks, thanks for raising this. You are correct. Output path is a flag that is only respected by the CLI and not when using Lighthouse programmatically under the assumption that if you're using Lighthouse from node you want to consume the results yourself in the object it returns rather than just dump to disk somewhere. 

I'm converting this issue to better documenting this fact. 👍

**Comment by nhodges** [comment]
@patrickhulce, @factordog 

Has the documentation been updated? Just ran into this while implementing the node module and subsequently discovered this issue.

**Comment by paulirish** [comment]
@factordog @mingsterism do you recall why you wanted to set outputpath? did you want html results also?

**Comment by factordog** [comment]
@paulirish Been a while since I have had to come back to this situation. But from what I recall yes. It was about passing in the command line flags and getting back similar results as you would there. In fact I dont even think it was just for the HTML but also the JSON (lighthouse --output json --output html). 

However once it was bought to my attention that the data returned was all the raw data that we could use as we wish I could see why it wasn't technically necessary to be able to pass those types of flags.

**Comment by nothingismagick** [comment]
I posted first over at https://github.com/GoogleChrome/lighthouse/issues/4715 - but this is more appropriate I believe.

We are integrating lighthouse into the [quasar-framework](https://github.com/quasarframework/quasar-cli) as the fourth and final component of our new testing mode, and I have been looking literally way too long (3 hours?) for how to get access to the opts. 
<details>
It got to the point where I started tracking the way that functions were passing variables within lighthouse core, and then I just caved and decided that before I file an issue I should search for it, because with this many stars I cannot be the first to have this problem. Low and behold, no - this has been an issue for over 6 months... :| 
</details>

### Anyway, I have several recommendations to resolve this.  
1. Make it clear that it is possible to access the CLI options via config files (for the CLI or the NODE interface). Explicitly give an example of this in a prominent place, such as in the README.md in the root folder of this repo.
2. Differentiate between **settings**, _options_ and _**configurations.**_ These are all so semantically similar, that I think the use of all three should be canonised with regard to how the Lighthouse project understands them and uses them. (If this has been done, please point me toward it!) 
3. Decide if the project wants to use .json or .js for the configuration files that hold options and settings. I have seen both. Does It matter? Tell us. 
4. Does one need an `=`on the command-line between the key and the value? I have seen both. Does it matter? Tell us.

**Comment by taytus** [comment]
> @factordog @mingsterism do you recall why you wanted to set outputpath? did you want html results also?

Hello Paul, I'm still struggling to define the outputPath, and yes, I would like to dump the HTML report too.

Thanks!

**Comment by patrickhulce** [comment]
@taytus output path is one of them that is CLI-only and [has been thoroughly documented](https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#differences-from-cli-flags).

**Comment by taytus** [comment]
Thank you @patrickhulce. You are right, I was just starting diving into lighthouse and honestly, I thought it was odd I couldn't *easily* define the output path for the reports.

I posted my hacky workaround here: https://github.com/GoogleChrome/lighthouse/issues/5269#issuecomment-467974452

I appreciate your help.

**Comment by patrickhulce** [comment]
@taytus if that's all you're doing you should probably just be using the CLI, that's what it's made for, and also why there is an outputPath option there but not in node.

**Comment by taytus** [comment]
@patrickhulce, for now, I will follow your advice and go with node. We need to generate different config files for different scenarios, hence the need to set up that inside the .js file.

Thank you again.
