### ISSUE TITLE
[feedback] make section titles of release notes linkable

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#3602]
When linking out to the release notes from other docs, it'd be helpful if I could link directly to a section of the release notes. It doesn't look like GitHub automatically does this, but maybe you can hack in the functionality...

**Comment by patrickhulce** [comment]
Ya we can with `<a name="the-hash-we-want></a>` :)

**Comment by brendankenny** [comment]
Weird that github doesn't do that since it does for most markdown.

FWIW we also have https://github.com/GoogleChrome/lighthouse/blob/master/changelog.md with the same notes in it and the headings in there are auto-anchored (though for some formatting reason the PR numbers *don't* get auto-linked in there)

**Comment by kaycebasques** [comment]
Either works for me, LMK whether to use changelog or release notes

**Comment by brendankenny** [comment]
I think @paulirish wanted the changelog file specifically for this kind of thing, but I don't want to put words in his mouth :)

**Comment by patrickhulce** [comment]
@kaycebasques so does changelog work for you then and we can close?
