### ISSUE TITLE
[discussion] How Lighthouse does scoring

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#3610]
In an email thread we were discussing scoring so I wanted to tease things apart and bring the discussion here.  cc @patrickhulce @vinamratasingal @brendankenny 

### The current components of Lighthouse scoring

1. **Metric scoring.** How we turn a single metric's value (usually in milliseconds) into a score on a 100 point scale
1. **Metric targets.** How the "target" (aka `optimalValue`) is set and how it's related to #1
   - Currently... the optimalValue is exactly the same as the Point of Diminishing Returns control point for the scoring curve. (I just verified this). PoDR is a score of 98, btw.  
      - There is ONE exception to this and that's "Total Byte Weight" which has an arbitrary value which is different from the PoDR. We should fix that. (DOM size also is pretty odd) 
1. **Color grading.** How we apply color to scores (red/orange/green).   
   - Spoiler alert: 0-44 is red. 45-74 is orange. 75 - 100 is green.
1. **Named bucket grading.** We don't currently apply named buckets to these colors. (Names like fast/average/slow or ok/average/poor or good/ok/poor).  We could.
1. **Category score blending.** How separate metric scores within the Performance category blend into an Overall Performance score (on a 100 point scale)

_I should point out we're mostly happy with how we do these now, but we're definitely considering making improvements._

### Proposal: Let's kill "target"
I would prefer to remove "target" from the Lighthouse metric results entirely. Trying to explain a scoring curve with a single point on it doesn't make sense. **WDYT?**

### Explaining metric scoring in the report redux
We can explain scoring with a fair amount of detail in the docs and we should. Showing a scoring curve there feels right.

Now how do we explain the scoring curve within the Lighthouse UI?  I see a few possibilities:
1. That [rich graphical scoring curve](https://user-images.githubusercontent.com/39191/31742819-c282741e-b40d-11e7-9830-66cebb92ed88.png) I pitched yesterday. It's entirely too complicated so this is probably not the best idea. 👎 
2. Some pithy text summary of the two control point values (median and podr control).  
3. Some pithy text summary of other points on the curve (like scores of 80, 90, 100)
4. A graphical thermometer-like viz that shows where where some of these points are. (points TBD) We optionally could apply red/orange/green ranges (45, 75) to this. We could optionally also apply names to these ranges. 
5. Some other bright idea

Options 3-5 sound most promising to me. Naturally, we'll need some UX iteration regardless.

-------

Questions:

* Hopefully the breakdown in "current components" sounds correct to everyone?
* Does killing target now make sense to you?
* Of the metric scoring explanation approaches... which direction are you leaning?

**Comment by vinamratasingal** [comment]
Thanks for writing this up Paul! Here are some early thoughts. 

re: scoring documentation- I think what you're saying makes sense, agreed we should explain with graphs. 

re: how to explain in UI --> I'm onboard of explaining our scoring curve more like a curve (i.e. range of points) rather than a singular point. If I had to pick, #4 would probably be my favorite option (this concept is much easier to understand with a visual explanation IMO). 

One question: do we want to have an opinion about the scoring itself? (i.e. what is a good TTCI vs FCP). My intuition is yes we do because we're going to have teams/devs come to us (who often times are learning about this performance stuff for the first time) and ask us what they should be aiming for. Therefore, I think it's worth us having some sort of opinion of what score they should be aiming for. As long as we tie that into the illustration, this SGTM'es to me. 

As a side note, I really like what TestMySite did to visualize performance score, perhaps we can leverage some of their UI? 

![screen shot 2017-10-12 at 3 12 09 pm](https://user-images.githubusercontent.com/1828723/31752194-61ee56e4-b44f-11e7-9e09-daeebfd268fb.png)

**Comment by paulirish** [comment]
> One question: do we want to have an opinion about the scoring itself? 

Yes we definitely do. The individual scoring curves we established for each metric pretty much captures that. We will give a hint of this in the report (somehow). We also _could_ have an extended explanation for it in scoring.md, like a big curve for each of the metrics, but this may be overkill.


> I really like what TestMySite did to visualize performance score

Oh yeah this viz is perfect. I like using this kind of approach.. hinting at the distribution of the web's measurements. We'll have to tie it to our bucketing and/or change our bucketing... but overall this approach sgtm. We'll probably have to defer comparisons to a particular vertical. :)

**Comment by patrickhulce** [comment]
Sorry for the delay here :)

> Hopefully the breakdown in "current components" sounds correct to everyone?

Yes, it sounds correct to me. I can explain a bit behind the total byte weight. I pitched the existing scoring curve based on the rationale that you shouldn't be doing poorly if you can still meet the TTCI target we had (i.e. if you reach network quiet within 10s you should get a 100), so the target was based on getting a 100 with that value and the PODR was just the calculation off of that. 

> Does killing target now make sense to you?

Yes, we should not express a single target value.

> Of the metric scoring explanation approaches... which direction are you leaning?

I lean towards 4, the thermometer method seems the most approachable, leaves room for nice flexible designs, and brings us one step closer to bucketing 😄

**Comment by paulirish** [comment]
fixed by #3436
