### ISSUE TITLE
No usable firstMeaningfulPaint event for frameset

### ISSUE THREAD

**Issue by bencollinsuk** [GoogleChrome/lighthouse#3654]
I am trying to run a performance audit on Chrome but realised it can't get a paint event if the site is running within a frameset?

**Comment by patrickhulce** [comment]
You should still receive a first meaningful paint event if your page just consists of frames though each will only count as a single element.

Have you encountered a URL where you never receive a firstMeaningfulPaint event? Sometimes tracing can fail and produce this error which would be unrelated to a frameset issue if you can rerun successfully.

**Comment by FGM** [comment]
I have this on a (locally hosted) page on which the audit on a page incorrectly spends its time loading another URL instead of the request page, then finishes by displaying the originally requested page, but reporting on the other URL. The report then complains "Audit error: No usable `firstMeaningfulPaint(Candidate)` events found in trace"

**Comment by gbhojraj** [comment]
I saw this while running an audit on a wordpress site from the devtools. Running via the Chrome extension did not result in this error.

**Comment by emily-plummer** [comment]
I'm also seeing this running an audit on publish.buffer.com 🤔
