### ISSUE TITLE
restore speed index raw value reporting

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#366]
it was removed by accident

**Comment by brendankenny** [comment]
so, this is two issues.

The easier one is that the raw value is correctly being displayed still, it's just being dropped when the raw value is zero (since zero is falsey and the template checks against that [here](https://github.com/GoogleChrome/lighthouse/blob/b9941b19744cd65c1df6611ff1e93894cb2b7a5e/report/templates/report.html#L109)). That's an easy fix if we want to support 0 (though zero is basically impossible to get as a real score).

So when speedline is working/being used correctly, it all works. For some reason, we're often getting a 0 out of speedline, though, and I'm not sure why. Two consecutive runs on airhorner gave me the following:

```
{
  'frames': [...],
  'first': 352,
  'complete': 352,
  'duration': 3417,
  'speedIndex': 352
}
```

```
{
  'frames': [...],
  'first': 310,
  'complete': 310,
  'duration': 3366,
  'speedIndex': 0
}
```

I don't know much about it, but it seems like if those other values don't indicate an error, something else is going on. Maybe something about that jpg issue you mentioned, @paulirish?

**Comment by paulirish** [comment]
I think we're concluding its an upstream issue, but mostly for simple sites with <= 3 frames. 
https://github.com/pmdartus/speedline/issues/21

**Comment by paulirish** [comment]
@brendankenny this is closable now yah?

**Comment by brendankenny** [comment]
Except on the speedline side. On our side, a 0 score should now be an error, yeah
