### ISSUE TITLE
Selenium sendkeys in chrome is opening new tab and redirecting to settings page every time.

### ISSUE THREAD

**Issue by santhoshmakam** [GoogleChrome/lighthouse#3667]
Chrome version - 62.0.3202.75 (Official Build) (64-bit)
Selenium version - 3.5.3
Mac OS - Sierra 10.12.6 (16G29)

**Comment by patrickhulce** [comment]
@santhoshmakam did you mean to file this in a different repo? Maybe [selenium's](https://github.com/SeleniumHQ/selenium)?

**Comment by santhoshmakam** [comment]
Updating the chromedriver to **2.33** solved the issue.

**Comment by FreeFly19** [comment]
I faced the same issue:
Chrome                      **62.0.3202.75**
Mac OS Sierra           **10.12.6 (16G29)**
ChromeDriver            2.33.506106
Selenium Webdriver 3.6.0

**Comment by appiumnovice** [comment]
Hi,
same problem:
- Chrome 62.0.3202.75 (Build officiel) (64 bits)
- Mac OS Sierra 10.12.6
- Appium 1.7.1 with selenium-java : 3.5.3 and 3.7.0

**Comment by patrickhulce** [comment]
@FreeFly19 @appiumnovice how did you arrive at the Lighthouse repo to comment on this issue?

This project is not responsible for Selenium, and we'd like to update any misleading links that might suggest it is :)

**Comment by FreeFly19** [comment]
@patrickhulce I found this repo by Issue title :)

@appiumnovice 
To solve the issue just run: `webdriver-manager update`

`npm install -g selenium-webdriver` didn't work in my case.

**Comment by appiumnovice** [comment]
@patrickhulce : same way, I found this repo by Issue title.
@FreeFly19 : thank you, I will test this solution.

**Comment by newhouse** [comment]
Apologies if this is not where any fix comes from, and I think that an upgrade will solve it, but for some that may not be an option. I've also come across this issue (seemingly) since Chrome updated to 62.x. SendKeys is when it happens. Here's my setup that I had trouble:

On Mac 10.12.6
We're using  [selenium-standalone](https://www.npmjs.com/package/selenium-standalone) and npm says I've got 5.11.2 installed.
Perhaps more importantly:
selenium server: 2.53.1-server.jar
chromedriver: 2.27-x64-chromedriver

For me to fix, I had to update `selenium-standalone` to the latest version, then run the install script again...and then update nightwatch to use the new selenium server and chromedriver files...and then I was good!
