### ISSUE TITLE
Report Download Format

### ISSUE THREAD

**Issue by slistudios** [GoogleChrome/lighthouse#3674]
When I select to Download the Report, the report itself does not contain a file extension.  What format is the report to be in?  

Example: www.mywebsite.com-20171027T145832 (no extension: .pdf, .docx, ...?)

**Comment by patrickhulce** [comment]
The downloaded report from DevTools is the JSON of the Lighthouse Results Object (LHR) which you can read more about [here](https://github.com/GoogleChrome/lighthouse/blob/master/docs/understanding-results.md). The extensionless file was intended so that this format remains flexible and the only contract being that you can drag 'n drop the file onto devtools to view it at a later date (or share it with others, etc).

**Comment by vinamratasingal** [comment]
Is there a particular format that you would like to share out the report in?

**Comment by MarcusMorba** [comment]
@vinamratasingal - I would prefer a readable PDF-Format which I can send directly to a developer or manager.
