### ISSUE TITLE
[perf] investigate Manifest gatherer slowness

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#3706]
The manifest gatherer can take a significant amount of time (~1s on flipkart.com). Presumably this is because we wait to fetch the manifest until the gatherer runs. Either way we should investigate and try to improve.

**Comment by brendankenny** [comment]
This is quite faster now (only a few ms on flipkart...file loading by the protocol from cache now?), and this was so long ago we've had like two revisions of manifest fetching since then, so it's difficult to tell exactly what was going wrong back then and what has changed.

I think good to close now, though, @patrickhulce?

**Comment by patrickhulce** [comment]
Yeah let's close
