### ISSUE TITLE
Blogger page speed problem

### ISSUE THREAD

**Issue by sudhirlucky** [GoogleChrome/lighthouse#3737]
Hello My website is hosted in blogger, I'm unable to speedup my blog, Please help me to solve this problem..Here is my url http://www.employment-news.net/

**Comment by patrickhulce** [comment]
Thanks for your interest in Lighthouse @sudhirlucky! GitHub issues are primarily for filing bugs or feature requests about the tool and asking questions that aren't covered by our documentation rather than individual performance advice though.

That being said, the Lighthouse report for your page has identified a few opportunities, but your page's activity is dominated by an insane amount of ad activity (~90% of the total network and CPU activity is from ad scripts). Consider reducing the number of providers you rely on or finding a lighter weight ad experience.

![image](https://user-images.githubusercontent.com/2301202/32383188-87b00b30-c074-11e7-81c7-ad1e2e7be7d3.png)
