### ISSUE TITLE
TTI/FI: split debugString for "activity continued through end of trace" warning for LH mistake vs slow site

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#3786]
If we move WPT to use 90s timeout for the trace, sites that were busy (cpu or network) for the entire trace would score a 0 on TTI even if they weren't busy the entire time.

We could reduce the importance of the `debugString` in this case to try to separate the cases of "The trace was cut off at < 75s but on later inspection the network/cpu was busy the entire time, so LH cut off too early"
vs
"The trace was cut off at > 75s and the network/cpu was busy the entire time, but if LH waited longer, even if reaching network/cpu quiet, would still have given the same 0 score"

**Comment by patrickhulce** [comment]
Not sure I understand this distinction. I definitely see the need to internally identify "we didn't reach the timeout and yet we couldn't find 5s quiet" vs. "we reached the timeout and couldn't find 5s quiet" because the former is us cutting off too early on accident.

In either case though, our message to the user should be "Your TTI is *at least* X seconds and we don't know how much worse"

**Comment by paulirish** [comment]
We should expose a topLevelWarning for pageLoadTimeoutReached. That's nice for the user and will make this ^ EZ.
