### ISSUE TITLE
Group similar performance optimizations together

### ISSUE THREAD

**Issue by vinamratasingal** [GoogleChrome/lighthouse#3828]
To help users understand different buckets of optimizations (and how they should be adding together different optimizations to figure out how much page load time they can shave off), we need to bucket our current optimizations into categories (i.e. using image offscreen or using WebP for images could be under an "images" category, etc.) 

In other words- optimization categories should be those that you pick 1 within the category to complete, and it makes it easier for folks to add up the amount of time they could save. It also helps them understand which optimizations they can do serially, and which are more pick and choose (i.e. image optimizations). 

 ☂️

**Comment by patrickhulce** [comment]
Really excited to noodle on better UX for surfacing the opportunities!

This might be tricky to combine this with the need to show savings on each metric. 

If the goal is to make it so you can add up all the savings, then we might want to approach this differently using Lantern since that property still won't necessarily hold across categories.

**Comment by vinamratasingal** [comment]
Closing in favor of the umbrella issue.
