### ISSUE TITLE
WebP detection doesn’t take into account FetchEvent.respondWith in a service worker

### ISSUE THREAD

**Issue by andybons** [GoogleChrome/lighthouse#3909]
When performing a performance audit, LightHouse suggests that I serve webp images, but I have a service worker below that responds with a webp image upon a fetch of jpg/png resources.

## sw.js

```js
this.addEventListener('fetch', e => {
  if (
    !e.request.url.endsWith('.jpg') &&
    !e.request.url.endsWith('.jpeg') &&
    !e.request.url.endsWith('.png')
  ) {
    return;
  }

  let supportsWebp = false;
  if (e.request.headers.has('accept')) {
    supportsWebp = e.request.headers.get('accept').includes('image/webp');
  }
  if (!supportsWebp) {
    return;
  }

  e.respondWith(
    fetch(e.request.url + '.webp', {
      mode: 'no-cors',
    })
  );
});
```

/cc @samccone @paulirish

**Comment by patrickhulce** [comment]
Clever! :)

Since the first load does not have a service worker pre-registered though, this logic is likely never kicking in for the images that we are analyzing. To pass with vanilla Lighthouse, this would need to be a server-side detection of the accept header. If you think the service worker is being registered early enough/you're doing something fancy in your LH setup and have a URL that repros this behavior though we'd love to take a look!

**Comment by andybons** [comment]
Hm ok cool. Since I can’t pre-register SWs and LightHouse always performs loads as if it were the first request, this looks like it’s WAI. Thanks for the quick response!
