### ISSUE TITLE
Right click on issue doesn't take you to line in inspector anymore

### ISSUE THREAD

**Issue by HugoPalomares** [GoogleChrome/lighthouse#3926]
I know this isn't an issue but was a feature that helped our QA team a lot. This feature was removed in this new version and our Dev team hopes you can bring it back :) Maybe as a Christmas gift?

Thanks!

**Comment by patrickhulce** [comment]
Thanks for reporting @HugoPalomares! 

Could you provide a bit more detail here? It seems like you're referring to element revealing for audits in DevTools, but a list of repro steps with a screenshot or two would help a lot here to help us understand, since I don't think we intentionally removed what you're talking about :)

**Comment by patrickhulce** [comment]
Our best guess at what you were talking about @HugoPalomares is captured by #2289
