### ISSUE TITLE
Accessibility Audit: my site doesnt contain [user-scalable="no"] but still giving me the error

### ISSUE THREAD

**Issue by mara90** [GoogleChrome/lighthouse#3927]
I've looked everywhere for this [user-scalable="no"] but I don't have it, still, I'm getting hit by it. I tried changing the minimum and maximum scales but that didn't help.
The error:
![image](https://user-images.githubusercontent.com/22651469/33278160-ad9cdede-d368-11e7-9800-f422c5932a19.png)

my code: 
![image](https://user-images.githubusercontent.com/22651469/33278234-e46094c4-d368-11e7-99a0-7f36cc92a464.png)

please advise, thank you!

**Comment by patrickhulce** [comment]
Hey @mara90 thanks for filing!

Does you also get this error when running [axe](https://github.com/dequelabs/axe-core)/[axe extension](https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US) directly? If so, I'm sure they'd appreciate filing this issue over there. Otherwise, a URL here where we can reproduce this would be super helpful.

Lighthouse uses axe for this audits so a fix there will fix us too!

**Comment by mara90** [comment]
Thank you @patrickhulce  for replying, I had no idea there are other accessibility testing tools.
Anyways I ran a test through axe and I got a similar error 
![image](https://user-images.githubusercontent.com/22651469/33280508-5625b61e-d370-11e7-8ad6-11e31081f5ec.png)

I think I'll file an issue there see if they can help.
Thanks!

**Comment by paulirish** [comment]
resolved in https://github.com/dequelabs/axe-core/issues/625
