### ISSUE TITLE
Resolve istanbul ignored code

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/lighthouse#395]
We ignore a few bits and pieces for coverage, for example https://github.com/GoogleChrome/lighthouse/blob/master/src/scheduler.js#L89-L119

I didn't want to block the test coverage work I'm doing on resolving these, but there's a question here of testability, mainly that we should either move those pieces of functionality to a separate module, and test it, or add it to the exported functions, and test it. My preference is the former, because it prevents us exposing functionality unnecessarily because a module happens to use it, i.e. the scheduler can save artifacts, but that shouldn't really be exposed there, rather a separate AssetSaver (or something), which can be tested, would be better, and internally to the scheduler (or elsewhere) we would instantiate an AssetSaver.

wdyt?

**Comment by brendankenny** [comment]
I think you’re getting at the critical point correctly.

I do think we need to be careful with code coverage of unit tests alone. Code coverage can introduce a perverse incentive to optimize for coverage by sacrificing architecture, understandability, etc. Exposing internal functions just for testing should be a red flag as we’re then testing that the implementation is implemented in a certain way, not whether it fulfills the promises of the public API. In some cases this tradeoff is worth it, but often it can mean even tiny changes to existing code requires touching dozens of files to update tests.

Decoupling can be a great solution to this (and seems like #388 will do exactly that for the example you linked to), but only if the individual parts can really be decoupled. Sometimes the "decoupled" parts end up so tied together that they might as well be one unit, and any changes to a module will be touching its code and tests for that code, but also the mocks for that module in all the other code that depends on specific behavior from the module.

One solution to this is to take a step back from unit testing and do component testing, e.g. the formatter component, the aggregator component, etc. This allows unit tests to cover what's explicitly the API of individual modules, but component tests to handle things like how the modules fit together (without adding so many mocks that the test is more a test of the mocks than of the module itself) and better hit the various code paths (like the example you link) without having to run end-to-end tests with every permutation of input.

**Comment by brendankenny** [comment]
some more thoughts:

- we should be more careful of why a test is being added. Just because internal implementation details are testable doesn't mean they should be if their exact configuration doesn't affect output and ensuring they fit a single execution pattern doesn't ease development.

- centralize mocking. Component-level testing helps here, as there are fewer things to mock and the mocking of them can be more easily centralized. If the `driver` API ever changes, there are a lot of tests that are going to have to be updated individually; a central driver mock would help alleviate this.

- rely on type checking more. No need to write an ad-hoc type checker in tests. Closure (or TS) will check that for us, and it has the benefit that refactors of an internal type will only have to change where that type is produced (with type annotations) and consumed, not where it's produced, consumed, and shape tested.

- rely on runtime assertions more. JS is a dynamic language; it's OK to sometimes act like it. If a certain state is required at some point, throw at that point if not in that state. Trying to test the input on every possible path to that point is a fool's errand in an ever-growing codebase. Assertions can be useless for end-users if you give a very specific error deep down the stack, so we want to avoid that, but when used judiciously an assertion error means we probably should have had a test that hit that code path, or it's a helpful signal to a user specifically making changes (e.g. they're writing their own audit)

**Comment by paullewis** [comment]
In general I agree with all those points. My overriding concern is that we have some coverage for areas we take for granted as "working" today. I also hear you that the driver stuff may be an issue, but realistically we can over-engineer here, too. We have mocks for the driver, which itself has to do a bunch of stuff, so we lose confidence that the test doesn't itself need testing. I'm of the general persuasion that we get basic coverage and resolve issues over time. If, for example, we anticipate a big driver refactor, then we may at that point choose to introduce a driver mock (or some version of replay system), but until then a simple in-test mock that triggers the appropriate paths of the test is a good start. But yeah, for sure there's always a better test.

**Comment by paullewis** [comment]
Also in _this_ particular situation, saving assets has exactly nothing to do with a scheduler, it's just a case of the assets being available at that point in Lighthouse's lifecycle that we can take advantage of it. Even if there's a certain amount of coupling, I'd rather we made a conscious (and documented) decision here, which is why I've included comments against each `istanbul ignore` statement. But ideally I'd like to reduce the number of those that we have.
