### ISSUE TITLE
Text compression test should not run for binary files

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/lighthouse#4039]
When you analyze https://airhorner.com, Lighthouse complains about text compression not being active for ```/sounds/airhorn.mp3```, which is a binary file.

**Comment by patrickhulce** [comment]
Thanks for filing @tomayac good find!

We do currently filter to text type for this audit, but it seems like Chrome's sniffing thinks it's a text file anyway since it's issued as an XHR.
https://github.com/GoogleChrome/lighthouse/blob/5e23dbba1a7129c17d71927b9b039dbbaeedaba4/lighthouse-core/gather/gatherers/dobetterweb/response-compression.js#L28-L34

A simple sanity check of excluding audit/video/image mime types might be a good idea here 👍

**Comment by reddysridhar53** [comment]
Can I work on this?

**Comment by paulirish** [comment]
@reddysridhar53 yup. we'll have to look at the contenttype response header and exclude binary ones

**Comment by reddysridhar53** [comment]
@paulirish thank you, Can you please tell me how to debug ?

**Comment by reddysridhar53** [comment]
@paulirish I have added the following code in the file lighthouse/lighthouse-core/gather/gatherers/dobetterweb/response-compression.js.

const isContentBinary = record.responseHeaders.find(header =>
  header.contentType.toLowerCase() === 'application/octet-stream'
);
const isTextBasedResource = record.resourceType() && record.resourceType().isTextType() && !isContentBinary;

Is my approach correct and how do I debug this?Thank you.

**Comment by paulirish** [comment]
@reddysridhar53  #4144 already started to explore this. I think we'll continue from that one. thank you though!

**Comment by underbyte** [comment]
Looks like this issue was address. Probably good to close.

**Comment by paulirish** [comment]
fixed by #4144
