### ISSUE TITLE
Lighthouse doesn't run in DevTools on ChromeOS

### ISSUE THREAD

**Issue by warbrett** [GoogleChrome/lighthouse#4132]
Running lighthouse on Chrome in ChromeOs on the Pixelbook seems to just freeze at the first step of "Auditing your web page..." The loading spinner is there but after 30 minutes nothing seemed to happen. This is happening for any site I run it on.

**Comment by patrickhulce** [comment]
Hey @warbrett sorry you've run into this one! Audits panel is a "remote module" in Chrome DevTools which means it isn't bundled with the Chrome download. Currently, Chrome OS doesn't support these remote modules which is why you're experiencing the issue.

The tracking bug is over in [crbug.com/747349](https://crbug.com/747349)

related #2627

**Comment by paulirish** [comment]
[Fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=747349#c25) as of 67.0.3378.0
We're hoping to merge the fix to 66
