### ISSUE TITLE
Some thoughts on n passes & configuration

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/lighthouse#415]
Below is a suggested format for configuring a Lighthouse run. The theory here is that you configure passes, audits and the report you want out of the other side. I figure we can encode what we currently have as the default and essentially allow anyone to override it with the `.lighthouserc` file.

As part of this we can allow a couple of extra flags:

* `--config=/some/config.json`: Allows you to set your own config file (we can `Object.assign` perhaps, so there are defaults?
* `--custom-gatherers=/some/gatherers/`: Allows you to add your own set of custom gatherers (we need to define the API they use). This would import all the files in that folder?

Finally, I think we should look at allowing multiple trace files to be collected. I added `loadDataName` as a disambiguator in the format below so that an audit can look at `artifacts[loadDataName].(networkRecords|traceContents)` if we have n runs, each with its own trace & network data.

```json
{
  "passes": [{
    "network": true,
    "trace": true,
    "loadDataName": "first-pass",
    "loadPage": true,
    "gatherers": [
      "url",
      "https",
      "viewport",
      "themeColorMeta",
      "html",
      "manifest",
      "accessibility",
      "screenshots",
      "criticalRequestChains",
      "speedline"
    ]
  },
  {
    "loadPage": true,
    "gatherers": [
      "serviceWorkers",
      "offlineResponseCode"
    ]
  },
  {
    "loadPage": true,
    "gatherers": [
      "redirectsHTTP",
      "htmlWithoutJavaScript"
    ]
  }],

  "audits": [
    "is-on-https",
    "redirects-http",
    "service-worker",
    "works offline",
    "viewport",
    "manifest-display",
    "without-javascript",
    "first-meaningful-paint",
    "speed-index-metric",
    "user-timings",
    "screenshots",
    "critical-request-chains",
    "manifest-exists",
    "manifest-background-color",
    "manifest-theme-color",
    "manifest-icons-min-192",
    "manifest-icons-min-144",
    "manifest-name",
    "manifest-short-name",
    "manifest-short-name-length",
    "manifest-start-url",
    "theme-color-meta",
    "aria-valid-attr",
    "aria-allowed-attr",
    "color-contrast",
    "image-alt",
    "label",
    "tab-index"
  ],

  "report": [{
      "name": "Progressive Web App",
      "scored": true,
      "audits": {
        "first-meaningful-paint": {
          "value": 100,
          "weight": 1
        },
        "speed-index-metric": {
          "value": 100,
          "weight": 1
        }

        // Etc...
      }
    }, {
      "name": "Best Practices",
      "scored": false,
      "audits": {
        // Etc...
      }
    }]
}
```

wdyt?

**Comment by brendankenny** [comment]
My main concern with this proposal is that while lighthouse becomes super configurable (with a configuration default for the status quo), there's basically only a state of configure nothing or configure everything. We run the risk of gaining configurability in exchange for making it a pain to configure anything. This can mean losing some usability even if small configs are taken as diffs on the default due to configuration internal redundancy, e.g. it requires knowledge of the whole system to do things like "only run the gathers necessary to run audit X". For the same reason, lighthouse also becomes much more fragile for users to use reliably.

I don't know if there's necessarily a solution to hit all desired constraints, but I have been wondering recently if the driver/gather stage should only be aiming to hit configurability for the 80% use case (basically defaults and a little bit of configuration) and allow those who need to do more sophisticated things to
a) just drive the browser themselves, produce a trace/HAR, and pass it to lighthouse for analysis or
b) treat lighthouse as a library and extend it programmatically

If we look at the major needs users have right now, we have basically:
1. Rock solid import for artifact analysis
2. A lot more performance diagnoses
3. Whitelisting on audit category (e.g. run only the performance audits)
4. N/A signal so aggregators understand when a test wasn't run on purpose

I don't really see an immediate customer for extensive (declarative) configuration yet, and so we have a little bit of room to explore the usability space before jumping in, especially in teasing out the orthogonal bits so that a configuration file isn't an exercise in repetition.

**Comment by brendankenny** [comment]
as a concrete example, audit whitelisting (with associated gather culling) is amazing while writing audits. It would be very unfortunate to lose that with this change.

**Comment by paullewis** [comment]
> My main concern with this proposal is that while lighthouse becomes super configurable (with a configuration default for the status quo), there's basically only a state of configure nothing or configure everything. We run the risk of gaining configurability in exchange for making it a pain to configure anything.

We can either allow overriding of defaults, or we allow partial configs, i.e. you don't set `aggregations`, we don't run them. We can also break this down to multiple files, and then we `Object.assign` to a single config. So you cherry pick the bits you want to override.

> This can mean losing some usability even if small configs are taken as diffs on the default due to configuration internal redundancy, e.g. it requires knowledge of the whole system to do things like "only run the gathers necessary to run audit X". For the same reason, lighthouse also becomes much more fragile for users to use reliably.

This we can be smart about. We still have the requiredArtifacts object, and we can use that still if we want to check that post-passes we should have the artifacts required. In fact we'd need gatherers to declare the artifacts they *supply* to make that work, but that's solvable.

> I don't know if there's necessarily a solution to hit all desired constraints, but I have been wondering recently if the driver/gather stage should only be aiming to hit configurability for the 80% use case (basically defaults and a little bit of configuration) and allow those who need to do more sophisticated things to
a) just drive the browser themselves, produce a trace/HAR, and pass it to lighthouse for analysis or
b) treat lighthouse as a library and extend it programmatically

This one I think we do want to separate out Lighthouse some (which is part of an offline convo @paulirish and I have had), and that would tally well with this config, actually. We'd have a Lighthouse driver config, a Lighthouse core config, and a Lighthouse report / aggregation config. These three we can `Object.assign` together to look like this config object, but we also allow you to create the objects separately, and we of course provide default configs.

In any case, this decoupling of all three components is another refactor, and I suspect you don't want me to make this PR any bigger :D

> I don't really see an immediate customer for extensive (declarative) configuration yet, and so we have a little bit of room to explore the usability space before jumping in, especially in teasing out the orthogonal bits so that a configuration file isn't an exercise in repetition

Sure, except that we have that with the `--fast` flag that @paulirish wrote, and...

> as a concrete example, audit whitelisting (with associated gather culling) is amazing while writing audits. It would be very unfortunate to lose that with this change.

This is the same thing, you actually just provided a good rationale for the config! You just create a config with the audit and gatherer you're interested in, and that's what you run LH with and, when it's ready for prime time, you merge those extra items into the default config.

**Comment by brendankenny** [comment]
> This we can be smart about. We still have the requiredArtifacts object, and we can use that still if we want to check that post-passes we should have the artifacts required.

It isn't being smart about this, though, which is part of my point. If I'm asking for a set of gatherers and an audit in my config, wouldn't I expect those gatherers to always run? What are the rules here?

> In any case, this decoupling of all three components is another refactor, and I suspect you don't want me to make this PR any bigger :D

on the contrary, a refactor in multiple, separate, decoupled stages, each runnable and correct on their own? sounds great :P

> Sure, except that we have that with the --fast flag that @paulirish wrote

that didn't land, and not sure what it has to do with reducing redundancies in the config file?

> This is the same thing, you actually just provided a good rationale for the config! You just create a config with the audit and gatherer you're interested in, and that's what you run LH with and, when it's ready for prime time, you merge those extra items into the default config.

I have to create a config file with a pass which has options and a gather, an audit, and an aggregation, all with correct properties, nesting, etc, then change it whenever I want to try something else (like compare audits), as opposed to `--audit-whitelist=service-worker`. This isn't insurmountable, but it should be addressed.

I think the changes in this direction will be easy, but incremental building towards a clearer plan would be better, I think, as it's easier to discuss, easier to review (\*cough\*), and we can be sure it's matching our needs as they develop.

**Comment by paullewis** [comment]
> It isn't being smart about this, though, which is part of my point. If I'm asking for a set of gatherers and an audit in my config, wouldn't I expect those gatherers to always run? What are the rules here?

Yeah we can iterate some more and highlight unnecessary gatherers. At the moment if you define it, it gets run. Which I think is a pretty sensible default.

> on the contrary, a refactor in multiple, separate, decoupled stages, each runnable and correct on their own? sounds great :P

I can make this one bigger instead?

> that didn't land, and not sure what it has to do with reducing redundancies in the config file?

It didn't, it was about limiting the amount of stuff that LH needed to run, which is one of the major drivers of having a config. Works well for devving LH, and for anyone who _does_ want to limit the audits, gatherers or aggregators that runs.

> I have to create a config file with a pass which has options and a gather, an audit, and an aggregation, all with correct properties, nesting, etc, then change it whenever I want to try something else (like compare audits), as opposed to --audit-whitelist=service-worker. This isn't insurmountable, but it should be addressed.

There's a fundamental difference here for those of us who make gatherers and audits daily, and those who simply run Lighthouse, which is that we would regularly update our configs, whereas others (I expect) will only change their configs as needed. And many won't change from the defaults at all, especially so in the case of the extension. This change favors the use-case of people who want to set up a config once and update rarely.

I also think it can be resolved by doing an `Object.assign()`, or making it super clear how you're expected to set the config. At the present moment #414 pretty much maintains functionality, though it does remove the immediate ability to limit on a whitelist.

**Comment by paulirish** [comment]
Good conversation here so far.

I don't see a need to split apart the PR. Yes, there are a lot of changed files... but many of them rote; the substantial changes are easy to spot.
Moreover, The test coverage from last week is good money in the bank here, and it provides nice evidence that the PR is stable.

It's obvious to me that in `master`, our specific ordering in both lighthouse.js and scheduler.js is a code smell, and I'm excited about the direction here, as it really simplifies how the scheduling is exposed.

@paullewis i, too, really really like the `--audit-whitelist` functionality and have been using it in place of a `--fast`. I don't want to regress here. Let's make sure that is retained with the new model. sg?

And +1 to having 3 separate configs somehow (driver, audits, aggregations), so for configurability you don't need to understand all the pieces in order to just customize what data is reported. But I think this can wait a bit, as we get ongoing feedback from our customers.

**Comment by paullewis** [comment]
@paulirish fair enough, I've added that in #414. I've also pushed a [copy of this to origin](https://github.com/GoogleChrome/lighthouse/tree/refactor) so if you feel you need to make changes before this lands you can do that.
