### ISSUE TITLE
Inline Render blocking scripts 

### ISSUE THREAD

**Issue by KathiresanRamkumar95** [GoogleChrome/lighthouse#4154]
How to get time taken by the inline render blocking scripts time.
I wrote tiny inline scripts in my HTML file. I want to know the scripting time and the scripts block the parsing of the html? I am trying to know the scripting time of the inline script. But I cant the chrome dev tool takes inline scripting as parsing.

**Comment by vinamratasingal** [comment]
Hi! Thanks for writing in. We release a new bootup time audit in Lighthouse 2.6.0+ that should answer your query. Otherwise, we'd recommend investigating the timeline panel in Lighthouse DevTools. 

I'm closing this out since I think we've sufficiently answered your query, but feel free to reopen if any questions come up again.

**Comment by KathiresanRamkumar95** [comment]
Any update on above feature? Please let me know when the above feature or Issues solve with the latest release.

Thanks in advance.
