### ISSUE TITLE
Check for Application Cache support

### ISSUE THREAD

**Issue by niutech** [GoogleChrome/lighthouse#418]
My web app targets older browsers, which do not support Service Workers, only Application Cache. I do not need to implement Service Workers since AppCache works fine. Can Lighthouse check for AppCache support too?
Progressive web apps should be backwards compatible. Why should I be penalized for not using the latest bells'n'whistles like Service Workers when the old AppCache is enough and works almost everywhere?

**Comment by samccone** [comment]
I like the idea of detecting if a site has appcache, since service workers are not everywhere yet. :+1:

**Comment by paullewis** [comment]
AppCache isn't something I would recommend people deploy today, and I wouldn't really want Lighthouse to imply that they should. On balance I don't think we want to add this.

**Comment by slightlyoff** [comment]
We will not do this. See: https://infrequently.org/2016/05/service-workers-and-pwas-its-about-reliable-performance-not-offline/

**Comment by samccone** [comment]
Hmm interesting.

Let me give you my usecase. I would like to provide users an experience that works "offline" for IOS. What should I do for these users?

While I agree the network flake situation is a good counter point for appcache.. however providing my users with a 0 experience is no good imho. I want to provide an experience that gets better and better depending on what their given browser supports. I think ignoring app cache just because it is bad in some cases is not ideal and is not a good idea. 

> I want to state that giving users a poorly performing webapp is no good as well (which the flake network condition would give the illusion of {with app cache}) however plz read on...

Instead the step down experience would be:

Always use service worker if supported (offline first yay)
Fall back to appcache to at least provide some experience (if the app has such a thing)

---

I think if we promote this path things will be OK. ignoring app cache in my mind is very similar to giving users a screen that says

"THIS WEBSITE ONLY WORKS ON SUPER BROWSER 3000 --- plz download and come back"


But instead of that screen we just give them

![image](https://cloud.githubusercontent.com/assets/883126/15939651/9399eff4-2e2d-11e6-97d6-1129de6ef4ba.png)

**Comment by niutech** [comment]
I support @samccone's view. Until Service Workers are widely supported, AppCache should not be deprecated.
