### ISSUE TITLE
Roadmap for Smoothhouse

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#4204]
Smoothhouse is a proposed product/set of changes that reduce the variance of LH performance measurements and scores. More details soon.

**Comment by tdresser** [comment]
Are there design docs on what's planned for this effort?

I'm interested in the approach being taken here, and want to make sure we don't lose too much in the attempt to get more stable data.

**Comment by patrickhulce** [comment]
Early thoughts:

### MVP

add the following to CLI:
* --runs (must be odd number), specifies how many times to run LH
* --max-retries, specified how many times to retry when a LH run fails (no FMP found in trace, etc)
* when runs > 1, take all runs and select a "winning"/median LHR as the HTML/report output
* when runs > 1, output some stddev stat to CLI

### Later
Handle even number of runs
Fail fast for bad runs
Merge LHRs instead of just picking winning
Smoothouse CLI using the LH CI docker image, lantern, and --runs/--max-retries for you

### Progression in Docs
1. Tell people to use --runs/--max-retries
2. Tell people to use --runs/--max-retries inside the Lighthouse CI docker container with Lantern
3. Package up 2 into a single command
4. (Maybe) extend available environment options to not need to run on your machine

**Comment by tdresser** [comment]
There's some subtlety around max retries.

If your page load is uniformly distributed between 20 and 40 seconds, and we trace for 30 seconds, then with adequate max-retries and runs, you'll find that your page load is an average of 25 seconds.

Just dropping runs where we "failed" can create skew in the metrics which could easily go unnoticed.

**Comment by patrickhulce** [comment]
> Just dropping runs where we "failed" can create skew in the metrics which could easily go unnoticed.

Yeah should've clarified here, there's a class of failures that are retryable and some that aren't. Taking too long would not retry. Completely missing all the trace events we expect to exist within 45 seconds (tracing started in page, FCP, FMP, etc) would retry.

**Comment by sakshij** [comment]
Any updates here?

**Comment by Rubaka** [comment]
any updates or plans for this?

**Comment by HexaVFX** [comment]
Would love to hear some updates about this, I'm currently writing a tool with lighthouse and the runs feature would make it so much easier for me... If anyone knows something let me know!

**Comment by denysmedynskyi** [comment]
Cool initiative 🎉 
Sad, but it looks like it is not alive 😢 

Guys, can you share what do you use to have consistent results?

**Comment by brendankenny** [comment]
It is alive! We just stopped calling it smoothhouse, so we might want to close this :)

There are a few initiatives around this.

You might want to check out:
- [Score Variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md)
- #7488
- [Lighthouse Integrations](https://github.com/GoogleChrome/lighthouse#lighthouse-integrations) and [Related Projects](https://github.com/GoogleChrome/lighthouse#related-projects)

many of which support the options that @patrickhulce mentioned in https://github.com/GoogleChrome/lighthouse/issues/4204#issuecomment-361443259
