### ISSUE TITLE
Support remote debug devices within DevTools

### ISSUE THREAD

**Issue by itchina110** [GoogleChrome/lighthouse#4212]
If I use chrome://inspect/ remote debug my android chrome，lighthouse can not run

![image](https://user-images.githubusercontent.com/285661/34708952-21e05b50-f550-11e7-894d-fcfe3afaa76a.png)

if remote debug my android  other browser,can not find lighthouse

![image](https://user-images.githubusercontent.com/285661/34709072-99f21a16-f550-11e7-9799-aaa8753cbd3e.png)

**Comment by paulirish** [comment]
Currently we don't support using Lighthouse via devtools while remote debugging.

However, you can use the [Lighthouse CLI](https://github.com/GoogleChrome/lighthouse#using-the-node-cli) against a remote debug mobile device. Here are the docs for that: https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#testing-on-a-mobile-device

**Comment by connorjclark** [comment]
Remote debugging works today.

**Comment by connorjclark** [comment]
Remote debugging Audits does work today. I tested with 78.0.3904.90. Notably, Chrome 76 had some emulation issues, which we fixed with #9377.

I didn't expect anything to be broken, since the [connection layer](https://cs.chromium.org/chromium/src/third_party/devtools-frontend/src/front_end/sdk/Connections.js?q=f:devtools-frontend+connection&sq=package:chromium&dr=CSs&l=95) is completely abstracted from the rest of the DevTools frontend, such that I don't see what would need to be done to enable remote debugging support. It seems free.

**Comment by slhck** [comment]
Sorry for necromancing this thread, but I am a but confused about whether it is possible to start a Lighthouse measurement from DevTools programmatically (i.e., using the DevTools Protocol). Per this issue, it seems that it should be feasible? But it's unclear which API I'd need to use here.

My use case would be launching Lighthouse from within an Electron application. I can open DevTools there, and I can start the browser window with remote debugging enabled, so I could, in principle, access the DevTools via API. (I'm trying to leverage the builtin Lighthouse functionality so I don't have to ship Lighthouse and the browser twice …)

Perhaps it's possible by using a [custom frontend](https://github.com/ChromeDevTools/devtools-frontend/blob/main/docs/workflows.md#running-from-file-system) such as described by [this user](https://stackoverflow.com/questions/74860683/running-lighthouse-audit-programmatically-using-the-chrome-devtools-protocol-fro)? Seems a bit convoluted though …
