### ISSUE TITLE
Lighthouse as trace processor

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#422]
In addition to driving the browser to load a page, we'd like Lighthouse to also function as an offline trace processor.

This will only work for a subset of existing audits, however the common usecase is for performance metrics.

Lighthouse will require 2 things.

1. A trace with these categories enabled: https://github.com/GoogleChrome/lighthouse/blob/a0c8b05d4c706821535ae365c7ed2ac0cc3373a3/src/lib/drivers/driver.js#L30-L42

2.  A log of all `Network` domain events.  ChromeDriver supports this via the [`enableNetwork` flag in `perfLoggingPrefs`](https://sites.google.com/a/chromium.org/chromedriver/capabilities#TOC-perfLoggingPrefs-object).

LH will consume this protocol log in this format:
![image](https://cloud.githubusercontent.com/assets/39191/15980735/86a95e88-2f22-11e6-8000-24a7401e1943.png)

As a strawman for the CLI interaction, this might look something like..

```sh
> lighthouse --list-trace-categories

# capture data with separate test runner

> lighthouse trace_data_nAj2xS.json --event-log=performance_log_nAj2XS.json
```

Internal complementary doc: [go/lighthouse-latencylab](https://go/lighthouse-latencylab)

@zhaoz @paullewis sound about right?

**Comment by paulirish** [comment]
A few steps I'm seeing

[ ] ingest the "event-log" of Network protocol events and chuck them into Network Recorder to build our model.
[ ] add the CLI flag and support for trace.json instead of URL as primary `lighthouse` argv
[ ] bypass the gatherer stages completely
[ ] something about the configuration?

**Comment by paulirish** [comment]
I believe we're done here!

The docs in the readme capture usage.

**Comment by guilhermevrs** [comment]
Hi, I have a question about the trace processor.

The idea was to work as an offline trace processor right? So why do I need to launch a new chrome browser (as shown in the lighthouse docs example)?

Shouldn't be sufficient the logs provided in the config?

We are trying to integrate the Lighthouse metrics to our Protractor environment, but before running the audits, we would like to interact with the app in order to place it in the desired state.
