### ISSUE TITLE
Address dependency tree size

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#428]
* [ ] [yargs](http://yargs.js.org/) is already available in g3. do we want to move to it and leave meow?  
* [x] do we need to address babar/loud-rejection/meow within speedline? possible to spoof via shrinkwrap, but unclear if that's even neccessary.
* [x] `devtools-timeline-model` has to match the version speedline uses.

**Comment by brendankenny** [comment]
> do we need to address babar/loud-rejection/meow within speedline? possible to spoof via shrinkwrap, but unclear if that's even neccessary

these are only loaded by speedline's `cli.js`, so aren't needed by us (and verified that manually deleting `babar` and `loud-rejection` still gets us full speedline results.

@zhaoz not sure how the equivalent of `npm install` works for you. Do you control what dependencies are needed independent of what's in speedline's `package.json` file? If so, then you should be fine just skipping those two completely (and their four dependencies) as they're never touched by a lighthouse run

**Comment by brendankenny** [comment]
Moving to yargs is fine with me; we don't do anything crazy on the command line so the migration wouldn't be too difficult, and [not much has changed since the 3.30 version](https://github.com/yargs/yargs/blob/master/CHANGELOG.md#v3300-20151113-1629-0700) we currently have. Someone with interest in touching the cli is welcome to take this.

**Comment by zhaoz** [comment]
@brendankenny we can control dependencies independent of the package.json so we should be able to skip those things.
