### ISSUE TITLE
rel="canonical" root of same origin false negatives

### ISSUE THREAD

**Issue by AndrewMInsk** [GoogleChrome/lighthouse#4295]
I have AMP homepage [https://a-site.by/amp](https://a-site.by/amp) with 
link rel="canonical" href="https://a-site.by/" 
but LightHouse shows me the next error:
Document does not have a valid rel=canonical
Canonical links suggest which URL to show in search results. Read more in Use canonical URLs.
**Points to a root of the same origin**
 On other AMP pages i dont have such problems

**Comment by AndrewMInsk** [comment]
I have the same problem at website https://remok.by/amp as well

**Comment by patrickhulce** [comment]
Thanks for filing @AndrewMInsk!

@kdzwinel @rviscomi this seems like a rather unfortunate situation caused by the more warning-y logic in rel=canonical audit. Could we consider revisiting that particular check or maybe move it to just details without failing the audit?

**Comment by AndrewMInsk** [comment]
I have another bug for you :)
I have AMP page - https://a-site.by/amp
Section Accessibility:
Are IDs not unique?
![bug](https://user-images.githubusercontent.com/31008882/35117413-a4f23db4-fc9f-11e7-8c28-cbb3efdad1fd.png)

**Comment by kdzwinel** [comment]
Check that fails here aims to catch a common mistake of canonicalizing all pages to the root page. We were aware that it will show false negatives for things like `/index.html`, `/index.php`, `/home` etc. IMO it should be a warning, but showing them in the "details" section of a passed audit may be hard to discover because both 'Passed audits' and 'Details' are collapsed. Maybe we should open a discussion about a way to show warnings in LH?

**Comment by rviscomi** [comment]
How gross would it be to add an exception for `/amp` URLs?

**Comment by AndrewMInsk** [comment]
It is not necessary to look to the URLs, they can be quite different and unpredictable. Just parse attribute AMP in the HTML tag.

**Comment by TomLeVine** [comment]
I have a similar problem. Except mine is for a mobile version of a page. 
As per best practice, the recommendation is for the main version to have an rel alternate pointing to the mobile version. The mobile version has a rel canonical pointing to the desktop version. 
The SEO audit is giving me a Failed Audits 'document does not have a valid rel=canonical pints to a root of the same origin' error. Yet I don't think it is a fail? 
Thoughts (sorry for jumping in on this thread...appreciate its not entirely the same issue)
Thanks

**Comment by rviscomi** [comment]
@TomLeVine thanks. That does seem related to the AMP use case described above.

@kdzwinel we should talk about how to handle these use cases of subdomains for AMP/mweb versions.

**Comment by rviscomi** [comment]
Rather than updating the audit to handle these edge cases and possibly introduce false positives, let's add something to the documentation to the effect of "it may be valid in some cases for a subdomain to refer to the domain root as the canonical, for example from AMP or mobile web page variations."
