### ISSUE TITLE
Chrome's infobars distort screenshots

### ISSUE THREAD

**Issue by mixed** [GoogleChrome/lighthouse#4451]
Some indicators are not normal due to "Auto Translate". The screenshots too. 
I have to deal with [pwmetrics#140](https://github.com/paulirish/pwmetrics/issues/140#issuecomment-343197696) to solve this issue.

### Enable auto translate
<img width="672" alt="2018-02-08 1 40 44" src="https://user-images.githubusercontent.com/22300/35928844-83901af6-0c71-11e8-9bf2-c911c4e0ddf3.png">

### Disable auto translate
<img width="672" alt="2018-02-08 1 40 52" src="https://user-images.githubusercontent.com/22300/35928845-8408d5a4-0c71-11e8-904b-25c8054f45b8.png">

Do you have any plan for this issue?
Thanks.

ps. My env is 
 - `Chrome Version 66.0.3342.0 (Official Build) canary (64-bit)`
 - `lighthouse 2.8.0`

ref.
- https://github.com/paulirish/pwmetrics/issues/140
- https://codereview.chromium.org/2819813002/
- https://github.com/GoogleChrome/chrome-launcher/issues/88

**Comment by paulirish** [comment]
thanks for reporting! does `--disable-infobars` fix the bad screenshots?

**Comment by mixed** [comment]
@paulirish 
Yes. It is still not disabled auto translate. 😢

**Comment by paulirish** [comment]
hmm.. still trying to understand. 

two questions:

1) do you see an infobar like this one show up when LH is loading this page? 
![image](https://user-images.githubusercontent.com/39191/35929743-0c9f9660-0be5-11e8-91db-e72478fe4a18.png)

2) does chrome actually change the page contents (translating them to english or another language)?

**Comment by mixed** [comment]
> 1.do you see an infobar like this one show up when LH is loading this page?

---> Yes

> 2.does chrome actually change the page contents (translating them to english or another language)?

---> No

**Comment by mixed** [comment]
And My OS is Mac(OS X El Capitan - 10.11.4).

**Comment by paulirish** [comment]
A ha!

The infobar is messing up the screenshots (which will also mess up our speed index calculations).

And this is why we have bad screenshots in the extension. Because it always has a infobar while it's doing its thing.

**Comment by mixed** [comment]
Yes. You're Right. Currently I have to deal with https://github.com/paulirish/pwmetrics/issues/140#issuecomment-343197696 to solve this issue.

**Comment by paulirish** [comment]
Ah! so `--disable-infobars` was also removed! oh boy.

@mixed a shortterm fix for you: `--enable-translate-new-ux`. This uses a different dialog instead of the infobar and so screenshots are fixed.

I'll still look into:

1) how we can avoid all infobars 
2) if we can fix screenshots while infobars are shown.

**Comment by mixed** [comment]
Oh. Thanks @paulirish 
I fixed using `--enable-translate-new-ux` more easy.

**Comment by brendankenny** [comment]
seems like this is fixed now with the new translate UI now used everywhere?

**Comment by paulirish** [comment]
Ah. Yes the translate stuff is good now since it uses a diff infobar.

However the Chrome extension still trigger a full-width infobar which still messes up the screenshots.

![image](https://user-images.githubusercontent.com/39191/60138151-21205d80-975e-11e9-9d12-6da411cc1b43.png)

So mixed's original issue is resolved, but this ticket is now tracking the generalized chrome extension issue.

**Comment by brendankenny** [comment]
sounds perfect for #2287 :)
