### ISSUE TITLE
Relying on Lighthouse test results for amp pages

### ISSUE THREAD

**Issue by atishaybaid** [GoogleChrome/lighthouse#4490]
HI,
 Should we rely on lighthouse test results for amp pages also?
I tested my amp page https://m.timesofindia.com/amp_business
 the report gives us low scores for our page,(report attached)
it gives first meaning full paint in 6s, how can this be true for amp pages?

if it is true how can go ahead and improve page performance.

**Comment by fchristant** [comment]
@atishaybaid I'm not part of the Lighthouse team but wanted to comment anyway. 

The way Lighthouse retrieves your page is fundamentally different from how it would be retrieved in an AMP scenario, in two major ways:

- AMP would normally be served from Google's AMP cache, which is a world-class CDN few could compete with in terms of speed

- More importantly, your AMP will typically be preloaded and prerendered before you even open it. Here's how this works: search on mobile for your page. In search results,  scroll close to your AMP page. In the network tab, you can see how Google is already preloading and prerendering your entire page. Next, you tap it and it seems to perform instantly.

The above has two implications:

- Technically, an AMP page not served from cache and not served from Google search doesn't have to be that fast at all.  As your finding shows, it can be equally slow to a normal web page in slow 3G conditions. 

- You can build the fastest non-AMP page in the world, and it will still be slower than any AMP page, because of the way AMP pages are retrieved (from cache, preloaded and prerendered).

I consider this an unfair performance advantage, but this isn't the place for that discussion.

**Comment by patrickhulce** [comment]
Thanks for the question @atishaybaid! @fchristant already highlights some great points on the subject, but to add to this, here is what I get for the URL you provided.

![image](https://user-images.githubusercontent.com/2301202/36041201-9f46be56-0d7c-11e8-84d8-1f629457056b.png)

AMP's limited feature set keeps First Interactive and Consistently interactive quite low, and the page's biggest issue (Keep server response times low) is addressed by loading from the AMP cache which would shave off another ~1.4s, making the page quite performant.

You should be able to audit the URL that is served from the AMP cache instead of your self-hosted URL to observe these performance changes and how it affects your load times.
