### ISSUE TITLE
Idea: add toggle to report to filter all flagged resources to same-origin only / 3rd party / 3P

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#4516]
In audits like passive event listeners (#4434) we used to restrict to same-origin URLs but nearly all recent audits flag all resources. It might be nice to add the filtering at the report level instead so you can get a view with "easiest to fix first" and remove it from the audit level across the board.

cc @hwikyounglee in case you have thoughts here :)

**Comment by hwikyounglee** [comment]
Idea - add an indication of source location
![3p](https://user-images.githubusercontent.com/7561395/46123897-c90bf900-c1d5-11e8-9f8b-e31971eda4ec.png)

**Comment by patrickhulce** [comment]
didn't mean to steal this from you @wardpeet! just wanted to investigate what we'll run into before it was assigned to anyone. you're free to still handle it if you'd like :)

**Comment by wardpeet** [comment]
Haha, no worries feel free to take it

**Comment by patrickhulce** [comment]
I really think you should take this back @wardpeet :)

I don't think I'm going to get to it immediately, and it's a nice juicy important piece for ya 😃

**Comment by wardpeet** [comment]
recap before I start:
We will add a toggle to filter out all third party requests from our tables with a toggle button but we won't touch the scores.

This is what i'll add:
1) a toggle button at the top that just hides all tables
2) a toggle button for each table (audit) that has need of it.
3) an indicator in each table to show that we have marked it as third party (i'm thinking of an icon with a tooltip instead of text (wdyt @hwikyounglee ?)
4) We consider a request a third party when it doesn't matches it's root domain, am I correct?

🎉 thanks patrick for the PR!

@patrickhulce @paulirish @brendankenny did I miss anything?

**Comment by brendankenny** [comment]
fixed in #6351!
