### ISSUE TITLE
First meaningful paint fires too late for Angular-Universal apps

### ISSUE THREAD

**Issue by EdwinChua** [GoogleChrome/lighthouse#4578]
The First meaningful paint metric seems to be incorrectly calculated on my Angular-Universal application. It seems to only consider the paint meaningful when some of the larger assets have loaded. However, as Angular-Universal renders the initial page in HTML first, and pushes the rest of the files later, this timing is quite inaccurate.

Am I doing something wrongly? Or is this expected behaviour?

Page tested: https://blog.crazy.technology/post/Clash-of-Clans---How-to-use-the-Web-API-570dd2b2

Report exported to: https://gist.github.com/EdwinChua/8c0b4544daa766ec67b4899ac1af38c4

Direct link to report (paste in viewer): https://gist.githubusercontent.com/EdwinChua/8c0b4544daa766ec67b4899ac1af38c4/raw/b0b72551b48104a4dc0112bb69d18f333c16cd22/blog.crazy.technology_2018-02-19_15-48-04.lighthouse.report.json

Open in Viewer: https://googlechrome.github.io/lighthouse/viewer/

**Comment by patrickhulce** [comment]
Thanks for filing and attaching the report @EdwinChua! You've bumped into an unfortunate edge case where the heuristic used by first meaningful paint fails. Apparently the hydration step of angular universal touches/adds enough elements to fool the heuristic into selecting the later paint instead of the real first one.

Looking at the performance monitor in DevTools for your page, the first paint where the page looks complete (beginning of timeline) is about ~600 elements, the hydration step shoots this up to ~2000 elements peaking at ~2400 before settling back down at around ~1200. This shoot up to 2000 is what gets labelled as "first meaningful paint" even though the initial 600 looked nearly identical.

![image](https://user-images.githubusercontent.com/2301202/36438885-0eed3df6-1620-11e8-90c7-168f6c5a44ca.png)

Unrelated protip: in the future you can directly use viewer's permalinks with the gist ID like so https://googlechrome.github.io/lighthouse/viewer/?gist=8c0b4544daa766ec67b4899ac1af38c4 :)


cc @tdresser @paulirish This is another good example case where hero element timing or visual completeness might outperform FMP.

**Comment by EdwinChua** [comment]
@patrickhulce thanks for looking into my issue, and providing such an in-depth clarification 😁

**Comment by EdwinChua** [comment]
So, I ran the assessment again on https://developers.google.com/web/tools/lighthouse/run 

https://googlechrome.github.io/lighthouse/viewer/?gist=3a31fbfef6745a044cf0efb7902fec0a

Seems like FMP is correctly identified now. :)
