### ISSUE TITLE
Recalibrate proposal for default network preset for LH

### ISSUE THREAD

**Issue by vinamratasingal** [GoogleChrome/lighthouse#4594]
Ideally, we'd also have this default preset across WPT

**Comment by benschwarz** [comment]
Another thing to consider based on feedback I've heard a few times from people now: 

* The RAIL recommendations for network are being used by a lot of people. It'd be great if that setting was available in LH, or updated to reflect LH's new default. Because right now they're wondering how to use the same network settings as that.

**Comment by patrickhulce** [comment]
FYI https://github.com/google/WebFundamentals/pull/6732 updates the documentation

**Comment by patrickhulce** [comment]
I'll defer to @kusler for the PWA checklist changes though :)

**Comment by paulirish** [comment]
fixed by #6732

**Comment by benschwarz** [comment]
Incorrect ref @paulirish
