### ISSUE TITLE
Link to explanations

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/lighthouse#46]
Loving the plugin so far. One thing that might be beneficial is to link to explanations for things. ex: I'm missing a canonical URL on one of my sites but if I don't know what a canonical URL is there's no explanation for how I can add one :D

**Comment by paullewis** [comment]
Yeah since this was based on @PaulKinlan's logic, I'm wondering if he can elaborate. First I've come across it as a criterion for a Progressive Web App.

**Comment by Garbee** [comment]
@paulirish Just pushed commit 71c4680bc8653de0d7d9919e70c5d4f103f3a05f which added an inline note about this.

imo if that note is accurate and it is "just a warning" then:

1. We should have an "intermediate" state for things like this. Yellow icon and warning triangle.
2. Anything like this should not show Red since they aren't necessary.
3. As Rob is asking for, let's link to documentation to help developers along in deciding whether or not they should apply a given practice. Whether intermediate or outright failure of error states.

**Comment by paullewis** [comment]
Yeah we need some version of severity in here.

**Comment by Garbee** [comment]
btw, I think canonical URLs are an SEO aspect.

**Comment by robdodson** [comment]
yeah I was less concerned about the severity and just a general explanation of how I fix the problem :)

**Comment by Garbee** [comment]
[Webmaster docs](https://support.google.com/webmasters/answer/139066?hl=en) on the topic. Should be very enlightening.

cc @PaulKinlan in case there is other relevant documentation to add here to explain why Canonical URLs are encouraged.

**Comment by addyosmani** [comment]
Fwiw, a lot of the existing PWAs we've shipped pass all of the tests minus the canonical URL one. It's unclear to me why it's a must-have vs. nice to have for SEO purposes :)

**Comment by cwilso** [comment]
It would be nice to more clearly describe the canonical URL one.  For building a simple site, where you DON'T have multiple ways to get to the content, you still have to put in a rel=canonical link, with "<this>".

**Comment by paulirish** [comment]
these are mostly in now.
