### ISSUE TITLE
setting cookies via extraHeaders not working for mobile

### ISSUE THREAD

**Issue by mohanrohith** [GoogleChrome/lighthouse#4632]
I have the site say 'https://example.com' on which I am running LH perf audits programmatically connected via puppeteer for both desktop and mobile sites. I am trying to set cookies for testing pages behind authentication. It works fine for desktop but  for mobile emulation, it doesnt.
I am pasting snippet of code below. 

```javascript
function delay(ms) {
    return new Promise(r => setTimeout(r, ms));
}

async function asyncForEach(urls, callback) {
    for (const url in urls) {
        await callback(urls[url], url)
    }
}

function filtersn(cookies) {
    return cookies.filter(cookie => cookie.name == "SN")
}

(async() => {
    const url = 'https://example.com';

    const paths = {
        "myaccount": "/account",
        "notifications": "/notifications",
        "wishlist": "/wishlist"
    }



    await asyncForEach(paths, async(path, key) => {
        const browser = await puppeteer.launch({ headless: true });


        browser.on('targetchanged', async(target) => {
            const page = await target.page();

            await page.setViewport({
                "isMobile": true, // toggling this setting along 'disableDeviceEmulation" for dekstop/mobile runs
                "width": 480,
                "height": 768
            })

            // Below Code didnt work
            // if (page && page.target().url() === url) {
            // const client = await page.target().createCDPSession();
            // await client.send('Network.enable');
            // await client.send('Network.setCookies', {
            //     "cookies": [{
            //         "name": "SN",
            //         "value": "xxxxxxxxxxxxxxxxxx",
            //         "domain": ".example.com",
            //         "path": "/",
            //         "session": true
            //     }]
            // })

            // }


            // Even this didnt work
            // await page.setCookie({
            //     "name": "SN",
            //     "value": "xxxxxxxxxxxxxxxxxx",
            //     "domain": ".example.com",
            //     "path": "/",
            //     "session": true
            // });

            console.log(`=================================== Loading...  ${url}${path}`);

            page.on('load', async() => {
                console.log('Page Loaded......');
                console.log(filtersn(await page.cookies()))

                const p = `${__dirname}/SS_${key}.png`;
                await delay(2000).then(() => {
                    return page.screenshot({ path: p, fullPage: true }).catch(e => console.error(e))
                });
            })
        });




        const lhr = await lighthouse(`${url}${path}`, {
            port: (new URL(browser.wsEndpoint())).port,
            output: 'json',
            logLevel: 'info',
            disableNetworkThrottling: true,
            disableCpuThrottling: true,
            disableDeviceEmulation: false, // Toggling this setting for desktop/mobile emulation
            extraHeaders: {
                "Cookie": "SN=xxxxxxxxxxxxxxxxxx;domain=.example.com;path=/"
            }

            // Finally extraHeaders worked for Dekstop but didnt work for mobile
        }, perfConfig);

        console.log('\n\n-------------------------------');
        console.log(`Lighthouse score: ${lhr.score}`);
        console.log('-------------------------------\n\n');
        await browser.close();

    })

})();
```

Mobile site uses service workers for providing offline capabilities. I am not able to figure out why the cookie is not getting set when deviceEmulation is switched true for enabling mobile.

**Comment by patrickhulce** [comment]
@mohanrohith when you say it's not working, what precisely are you referring to? Are you not seeing the cookie come through on the server or in the service worker?

> Mobile site uses service workers for providing offline capabilities. I am not able to figure out why the cookie is not getting set when deviceEmulation is switched true for enabling mobile.

Makes me think you might be talking about the service worker, in which case, we don't fully support this workflow yet and will need to wait to address #709 before it can be done.

**Comment by slamdunking** [comment]
Who needs a flexible fluid experienced service worker

**Comment by Vhoakab84** [comment]
Substances which will promote illogical thinking and impulsiveness to the point where the recipient would be discredited in public.Substances which increase the efficiency of mentation and perception.Materials which will cause the victim to age faster/slower in maturity.Materials which will promote the intoxicating effect of alcohol.Materials which will produce the signs and symptoms of recognized diseases in a reversible way so they may be used for malingering, etc.Materials which will cause temporary/permanent brain damage and loss of memory.Substances which will enhance the ability of individuals to withstand privation, torture, and coercion during interrogation and so-called "brain-washing".Materials and physical methods which will produce amnesia for events preceding and during their use.Physical methods of producing shock and confusion over extended periods of time and capable of surreptitious use.Substances which produce physical disablement such as paralysis of the legs, acute anemia, etc.Substances which will produce a chemical that can cause blisters.Substances which alter personality structure in such a way the tendency of the recipient to become dependent upon another person is enhanced.A material which will cause mental confusion of such a type the individual under its influence will find it difficult to maintain a fabrication under questioning.Substances which will lower the ambition and general working efficiency of men when administered in undetectable amounts.Substances which promote weakness or distortion of the eyesight or hearing faculties, preferably without permanent effects.A knockout pill which can be surreptitiously administered in drinks, food, cigarettes, as an aerosol, etc., which will be safe to use, provide a maximum of amnesia, and be suitable for use by agent types on an ad hoc basis.A material which can be surreptitiously administered by the above routes and which in very small amounts will make it impossible for a person to perform physical activity.

On March 1, 2018, at 12:35 PM, slamdunking <notifications@github.com> wrote:

Who needs a flexible fluid experienced service worker

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/GoogleChrome/lighthouse","title":"GoogleChrome/lighthouse","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/GoogleChrome/lighthouse">https://github.com/GoogleChrome/lighthouse</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@slamdunking in #4632: Who needs a flexible fluid experienced service worker"}],"action":{"name":"View Issue","url":"<a href="https://github.com/GoogleChrome/lighthouse/issues/4632#issuecomment-369687208">https://github.com/GoogleChrome/lighthouse/issues/4632#issuecomment-369687208</a>"}}}

**Comment by brendankenny** [comment]
no movement in here, so I'm going to close (related discussion over in #6207)
