### ISSUE TITLE
"First meaningful paint, "First Interactive" values are mapped to 

### ISSUE THREAD

**Issue by vikramvi** [GoogleChrome/lighthouse#4634]
Please refer to 2 screen shots attached.

1. First one is from Network tab under chrome tool

![google_1](https://user-images.githubusercontent.com/308490/36721384-0ec6ba4c-1bab-11e8-8e57-f955869d59eb.png)

2. Second one is report generated by lighthouse tool

![google_2](https://user-images.githubusercontent.com/308490/36721392-135dd2fc-1bab-11e8-8b10-36e61ce05881.png)

Please clarify how does "First meaningful paint, "First Interactive" values can be mapped to values seen under Network tab ?

**Comment by vinamratasingal** [comment]
Hi Vikram- I think there might be some confusion here. The values for First Meaningful Paint don't map to network activity, but rather map to paint values. Therefore, there shouldn't be a consistency with what you see in the networks tab and in the LH report.

**Comment by vikramvi** [comment]
@vinamratasingal  Thanks for answer but still it's not clear to me

1. Without LH how to view values of  **First meaningful paint**,   **First Interactive** in chrome developer tools ?

2. Can you please explain in detail the terms  **First meaningful paint**,   **First Interactive** ?

**Comment by patrickhulce** [comment]
Answers to your questions are below @vikramvi but they may not be exactly what you were hoping for. Lighthouse provides these metrics to you precisely because they are relatively difficult to obtain on your own and on the cutting edge :)

1. You can see FMP in DevTools by first enabling the "Timeline: paint timing markers" setting and recording a trace of your page load in the performance tab.
![image](https://user-images.githubusercontent.com/2301202/36988400-a3e2150c-2053-11e8-9ce8-72472fd7dc8a.png)
You cannot see first interactive anywhere, but on a recorded trace in the performance tab you can examine the trace manually to determine where First Interactive should be by following the algorithm outlined in "TTI explainer" link.


2. [FMP explainer](https://docs.google.com/document/d/1BR94tJdZLsin5poeet0XoTW60M0SjvOJQttKT-JK8HI/view)
[TTI explainer](https://docs.google.com/document/d/1GGiI9-7KeY3TPqS3YT271upUVimo-XiL5mwWorDUD4c/edit)

**Comment by vikramvi** [comment]
Thanks for detailed info @patrickhulce

**Comment by shuangq** [comment]
@patrickhulce Are the experiment settings still available in later version of Chrome? I'm using ver 67 but didn't find 'Experiments' in the settings. Or do I need to turn it on somewhere else?

**Comment by shuangq** [comment]
@patrickhulce Thanks a lot 😃

**Comment by lmakarov** [comment]
@patrickhulce has this changed in Chrome 68?

After enabling "Developer Tools experiments" in `chrome://flags/` I still don't see an option to enable **Timeline: paint timing markers** in DevTools > Settings.

![image](https://user-images.githubusercontent.com/1205005/43808580-8ebb8ca6-9a62-11e8-8d0c-cf237652bb2a.png)

**Comment by lmakarov** [comment]
Finally found the answer to this. You have to press "Shift" six times in DevTools > Settings > Experiments to uncover the hidden experiments.

![image](https://user-images.githubusercontent.com/1205005/43930690-a5b40508-9bef-11e8-8942-df35675db58d.png)

**Comment by shrutiseth** [comment]
Hello. Am still not getting the option for **Timeline: paint timing markers in DevTools > Settings.**

**Comment by shrutiseth** [comment]
![image](https://user-images.githubusercontent.com/45349166/49862017-387fa500-fe23-11e8-8553-73e373085c18.png)

I want to get FMP and FCP for a URL. Please help

**Comment by patrickhulce** [comment]
@shrutiseth it might have been taken out of experiments. I'm seeing a much better UI for the timing markers now in Canary 😍 

![image](https://user-images.githubusercontent.com/2301202/49876516-2d0f8800-fde9-11e8-80c7-44f454241ae3.png)
