### ISSUE TITLE
Grammar mistake

### ISSUE THREAD

**Issue by internette** [GoogleChrome/lighthouse#4660]
![screen shot 2018-03-01 at 1 32 40 pm](https://user-images.githubusercontent.com/9656794/36862532-125c5990-1d55-11e8-9682-858daf45b33b.png)

I'm pretty sure the correct grammar would be "Does not use images with appropriate aspect ratio"

**Comment by paulirish** [comment]
thanks so much for reporting!! appreciate it. 😃 

we fixed it a bit ago, so it'll be coming to a chrome stable soon. 
https://github.com/GoogleChrome/lighthouse/commit/12f7f03241d0354ade5741f8ba5db7daea1c2d71

**Comment by slamdunking** [comment]
Substances which will promote illogical thinking and impulsiveness to the point where the recipient would be discredited in public.Substances which increase the efficiency of mentation and perception.Materials which will cause the victim to age faster/slower in maturity.Materials which will promote the intoxicating effect of alcohol.Materials which will produce the signs and symptoms of recognized diseases in a reversible way so they may be used for malingering, etc.Materials which will cause temporary/permanent brain damage and loss of memory.Substances which will enhance the ability of individuals to withstand privation, torture, and coercion during interrogation and so-called "brain-washing".Materials and physical methods which will produce amnesia for events preceding and during their use.Physical methods of producing shock and confusion over extended periods of time and capable of surreptitious use.Substances which produce physical disablement such as paralysis of the legs, acute anemia, etc.Substances which will produce a chemical that can cause blisters.Substances which alter personality structure in such a way the tendency of the recipient to become dependent upon another person is enhanced.A material which will cause mental confusion of such a type the individual under its influence will find it difficult to maintain a fabrication under questioning.Substances which will lower the ambition and general working efficiency of men when administered in undetectable amounts.Substances which promote weakness or distortion of the eyesight or hearing faculties, preferably without permanent effects.A knockout pill which can be surreptitiously administered in drinks, food, cigarettes, as an aerosol, etc., which will be safe to use, provide a maximum of amnesia, and be suitable for use by agent types on an ad hoc basis.A material which can be surreptitiously administered by the above routes and which in very small amounts will make it impossible for a person to perform physical activity.
Is there any grammar mistakes in this string of coding?

On March 1, 2018, at 12:47 PM, Paul Irish <notifications@github.com> wrote:

thanks so much for reporting!! appreciate it. 😃

we fixed it a bit ago, so it'll be coming to a chrome stable soon.
12f7f03

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/GoogleChrome/lighthouse","title":"GoogleChrome/lighthouse","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/GoogleChrome/lighthouse">https://github.com/GoogleChrome/lighthouse</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@paulirish in #4660: thanks so much for reporting!! appreciate it. 😃 \r\n\r\nwe fixed it a bit ago, so it'll be coming to a chrome stable soon. \r\n<a href="https://github.com/GoogleChrome/lighthouse/commit/12f7f03241d0354ade5741f8ba5db7daea1c2d71">https://github.com/GoogleChrome/lighthouse/commit/12f7f03241d0354ade5741f8ba5db7daea1c2d71</a>"}],"action":{"name":"View Issue","url":"<a href="https://github.com/GoogleChrome/lighthouse/issues/4660#issuecomment-369690770">https://github.com/GoogleChrome/lighthouse/issues/4660#issuecomment-369690770</a>"}}}
