### ISSUE TITLE
JS & CSS From Extensions Is Effecting Performance Figures

### ISSUE THREAD

**Issue by glenn2223** [GoogleChrome/lighthouse#4714]
On my machine I have Grammarly. This extension loads 2 JS files and 1 CSS file, these are affecting the outcome. 

I don't think that it should be included, mainly because it's specific to my machine. Not everyone has the Grammarly extension on the version of Chrome.

It mainly affects "Performance > Diagnostics > JavaScript boot-up time is too high"

❤️ Love it though! ❤️

**Comment by paulirish** [comment]
Aye. Well our challenge is that we can't report accurate performance numbers since we know a chrome extension is on the page and can be affecting performance quite a bit.

We can hypothetically remove it from JS Bootup Time, but we can't model how the performance metrics would be adjusted if the extension weren't present. So we'd rather take the approach of summarize ALL the costs and let you handle them.

Incognito is a quick way to test things without extensions getting in the way.
 
cc #3776, #4013 #3600

how does the solution here sound to you? https://github.com/GoogleChrome/lighthouse/issues/3776#issuecomment-358138867
