### ISSUE TITLE
mixed-content/https audits missing a insecure requests

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#4722]
https://www.paulirish.com/2006/think-you-can-recycle-the-single-serving-coffee-packets-think-again/ has a `<img src=http://....` insecure image request.

But I don't see anything in the report:

![image](https://user-images.githubusercontent.com/39191/37227126-0583557e-2391-11e8-93dd-d91c28923f16.png)

It is a little odd the score of the particular audit is 92, but it doesn't list any problematic requests.

cc @christhompson do you know what's going on here?

And fwiw I do have 'Upgrade Insecure Requests' enabled on the site, but i'm not sure that's related to the issue so far.

**Comment by wardpeet** [comment]
there is another issue with mixed-content that I forgot to report but it think it's a chrome issue. The network request is set to `"securityState":"unknown"` even if it's running https and on the devtools security tab it says all is GOOOD.

you can repro with
`yarn start --mixed-content --disable-device-emulation https://www.nieuwsblad.be`

**Comment by christhompson** [comment]
Sorry, was OOO and playing catch-up now.

I think requests handled by UIR are still getting caught by the insecureRecords collection, but any that fail on upgrade (looking at https://github.com/GoogleChrome/lighthouse/pull/4723#issuecomment-371938541) will not be counted as upgradeable.

However, these won't be mixed content (they shouldn't be able to cause errors, as the HTTP request would never actually occur). Digging into the requests, I was not expecting a certificate validation failure to result in `securityState: 'unknown'`, which is causing them to get filtered as "insecure". In Chrome, these subresource requests would just get blocked, rather than being loaded insecurely.

It might be better to explicitly filter insecure records, rather than secure records (that is, `secureRecords` would be `!IsRecordInsecure(records)`, rather than the current `insecureRecords = !IsRecordSecure(records)`). Or, we could explicitly filter out `url.startsWith('https://') && securityState == 'unknown' && failed == true` cases from insecureRecords (which should capture all cert validation failures, but I'm not sure whether there are potential false-negatives).

One other solution could be to try to maintain a list of certificate failures and match the localizedFailDescription against them, but that seems brittle and hard to maintain.
