### ISSUE TITLE
Page is blocked from indexing (libUrl.parse is not a function)

### ISSUE THREAD

**Issue by magtesyan** [GoogleChrome/lighthouse#4794]
Hi,

Get this fail on every website. 
By the way clicking "Learn more" becomes 404.
![indexing](https://user-images.githubusercontent.com/37150324/37557132-2dd35426-2a11-11e8-8b57-3f03e01ef04a.jpg)

**Comment by CymruUSA** [comment]
Same thing and yes, "Learn More" link returns a 404.

**Comment by patrickhulce** [comment]
@kdzwinel looks like we'll need to provide a shim for `url` that references our `url-shim` file instead.

robots-parser needs the `url` module and our gulpfile ignores it since we ship `url-shim`

**Comment by kdzwinel** [comment]
@patrickhulce yep, it's definitely the parser I included. It doesn't have any external deps, but it uses 'url' and 'punycode' nodejs modules. It's my bad, sorry for that. I'll look at it ASAP. Should I pull that library into LH? Configure webpack to replace native modules with polyfills? Fork the library and make it work in both node and web environment? 🤔

**Comment by patrickhulce** [comment]
> Should I pull that library into LH? Configure webpack to replace native modules with polyfills? Fork the library and make it work in both node and web environment? 🤔

ideal fix from my perspective would be adding a `.parse` method to our url-shim and seeing if there's a browserify way to have `require('url')` calls just use our shim instead rather than ignore. close 2nd would be using https://github.com/ds300/patch-package that @wardpeet found to patch it in LH repo to support node and web :)
