### ISSUE TITLE
False negative on Accessible links

### ISSUE THREAD

**Issue by adrianengine** [GoogleChrome/lighthouse#4854]
Links with an SVG and text are triggering the following error in Accessibility:

![image](https://user-images.githubusercontent.com/1206844/37800869-5243c1d0-2df2-11e8-855b-72e11de64ad0.png)

The code:
```
<a href="//twitter.com" target="_blank" aria-describedby="opensNewTab" rel="noopener">
    <svg class="icon" aria-hidden="true"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-twitter"></use></svg>
    <span class="invite">Follow us on Twitter</span>
</a>
```
Testing on Voice Over the text inside the `<span>` is been read.

[Audited Website](https://www.grand79vodka.com/)

Any thoughts?

**Comment by paulirish** [comment]
Aye. I can reproduce this:
![image](https://user-images.githubusercontent.com/39191/37807652-d6430a52-2e03-11e8-8977-e38b1b58997d.png)


Can you file it upstream at axe-core? https://github.com/dequelabs/axe-core/issues

They've had this longstanding one https://github.com/dequelabs/axe-core/issues/20 -- but I don't think your issue is the same. Yours is easier to fix.

Thanks for filing!

**Comment by adrianengine** [comment]
Thank you @paulirish !

Here it is the ticket on axe-core to follow up:
https://github.com/dequelabs/axe-core/issues/799

Regards,

**Comment by paulirish** [comment]
perfect. thx adrian
