### ISSUE TITLE
Audit Error: Cannot read property of 'OuterHTML'

### ISSUE THREAD

**Issue by ericseandevlin** [GoogleChrome/lighthouse#4857]
URL:  https://waitressthemusical.com/index.php

Report Gist: https://googlechrome.github.io/lighthouse/viewer/?gist=d8d3e016510391e784451b76b0d68af6

Affects all audits within Accessibility

![screen shot 2018-03-23 at 1 10 28 pm](https://user-images.githubusercontent.com/14153867/37844215-6e9a574e-2e9d-11e8-8071-71b968bc1fc1.png)

**Comment by paulirish** [comment]
Hey Eric. thanks for reporting!

I can't reproduce this.. Were you running Lighthouse from Chrome DevTools? Do you get the same result if you run multiple times?

**Comment by masya2503** [comment]
Я незнаю когда у меня будет время я совсем ничего не умею. Извинте если что то не так сделала


Отправлено из Почта для Windows 10

От: Paul Irish
Отправлено: 23 марта 2018 г. в 20:43
Кому: GoogleChrome/lighthouse
Копия: Subscribed
Тема: Re: [GoogleChrome/lighthouse] Audit Error: Cannot read property of'OuterHTML' (#4857)

Hey Eric. thanks for reporting!
I can't reproduce this.. Were you running Lighthouse from Chrome DevTools? Do you get the same result if you run multiple times?

**Comment by ericseandevlin** [comment]
Hey Paul!

Yes I’m running it in Chrome DevTools latest version. (Version 65.0.3325.181 (Official Build) (64-bit)) 

Yes I get the same result if run multiple times, which I’ve been doing over the last couple days. The last time I ran it successfully was 3/15 and nothing significant was changed on the site since then.

It’s also happening here: https://chicagothemusical.com/ <https://chicagothemusical.com/>. Also ran successfully 3/15 (before I updated Chrome to recent version)

We inherited these sites from another company and they’re quite buggy.

**Comment by paulirish** [comment]
Interesting. can't reproduce on 65.0.3325.162..  

I have a suspicion a chrome extension is involved here. Can you try in incognito (where they should be disabled)?

**Comment by ericseandevlin** [comment]
Oh you’re right, the AXE extension seems to be causing the issue https://www.deque.com/axe/ <https://www.deque.com/axe/>

Thanks for your help!

 - Eric

**Comment by dylanb** [comment]
@paulirish we cannot pass elements across iframe boundaries. When you use the `elementRef : true` option, you are asking for elements to be returned but axe-core cannot do this across iframes and so it nulls them out.

Why does this only happen when the aXe extension is installed? The answer to that is because the aXe extension is injecting axe into the iframes but the lighthouse extension is not. The version of axe-core from the aXe extension is probably responding to the lighhouse extension's messages. This should not happen if the application is set correctly by both parties because we check to ensure that the message is only responded-to from the correct application...so it would appear as though there is some bug in this part of the code...either in the aXe extension or axe-core.

**Comment by dylanb** [comment]
one more thing: the reason that a different version does not respond is because we also check the version for a match.

**Comment by brendankenny** [comment]
resolved (I believe) in https://github.com/dequelabs/axe-core/pull/825
