### ISSUE TITLE
Add ability to filter out expected errors through audit options

### ISSUE THREAD

**Issue by Eccenux** [GoogleChrome/lighthouse#4881]
**Steps**:

1. Create an application using REST API.
2. The app checks authorization on load.
3. Make Best Practices audit in Chrome/Lighthouse.

**Result**: detects "Browser errors were logged to the console".

**Expected**: ignore error that (to my knowledge) is a standard REST response.

**Comment by patrickhulce** [comment]
It seems like you want *browsers* to stop reporting 401 responses as errors :) 

This audit just raises all errors that appear in the console and has no opinion about them which we're unlikely to change.

**Comment by Eccenux** [comment]
No, not really :-). The 401 might be an important error if you were supposed to be logged in... But I think that is not the case for Lighthouse audits. Lighthouse audits (at least when you prepare for PWA) are run for the start page. And it's quite natural that the user is not logged in on start.

**Comment by patrickhulce** [comment]
Some folks have had success using LH on a logged in application and we'd like to support this best effort basis (#1418). Since we won't be changing the console error audit to ignore specific cases, it seems like some sort of audit option with a 'whitelist' of acceptable errors is what you're looking for? Then you'd be able to configure LH to ignore any potential error that you consider expected for your use case.

**Comment by Eccenux** [comment]
That would work yes. I guess it's a minor annoyance really... I don't have to have 100 ;-).

**Comment by paulirish** [comment]
We're not going to pursue this at this time.

Though we do understand the usecase and motivation.
