### ISSUE TITLE
start_url manifest fetch failure for keep.google.com?

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#4898]
Using extension 2.9.3

Keep is a PWA!

The results are kind of confusing for it, however.
https://googlechrome.github.io/lighthouse/viewer/?gist=17ebadc102e691e971ac55a476982176

![screen shot 2018-03-30 at 12 00 24](https://user-images.githubusercontent.com/316891/38150057-fc2cdb6c-3411-11e8-9857-8da1f281046b.png)

A manifest is definitely fetched for the PWA checks (custom splash screen fails on icons, not "No manifest was fetched"), but the serving start_url fails on "No usable web app manifest found on page.".

(Incidentally, from a UI perspective, we never definitively say in that report that we successfully fetched a manifest for all the other PWA checks, so seeing a `No usable web app manifest found on page` in the install prompt audit makes me think the manifest is failing, not that something start_url specific is failing (either on the site or a bug in the LH audit). I wonder if we should go back to having an explicit "Has a valid manifest" audit in addition to the current PWA audits.)

**Comment by brendankenny** [comment]
@wardpeet not sure if you want to take a look.

For extra fun, when I start setting breakpoints I start getting `Unable to fetch start URL via service worker` instead of `No usable web app manifest found on page` :(

**Comment by wardpeet** [comment]
@brendankenny I did some digging and keep seems not to be a PWA. It doesn't register a service worker, at least when I run it (even manual inspection doesn't tell me a SW is registered).

I agree that the error messages could be better when the manifest can not be retrieved. The message `No usable web app manifest found on page` is added because the start_url gatherer can't retrieve the manifest as there is no service worker registered and the offline audit can't retrieve the current page (so the dinosaur page is the current url). We could fix these issues inside the webapp install banner. I wouldn't remove them from the start_url gatherer as it is actually correct in that context.

I'll write a PR to make it a bit more clear

**Comment by wardpeet** [comment]
@brendankenny can you have a look that It's fixed with #5067

**Comment by wardpeet** [comment]
I'm going to close this one as we updated the message to be clearer.
