### ISSUE TITLE
Why not pass the CSS through a real minifier?

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#4901]
Whilst writing a reference doc for the CSS minification audit, it looks like the audit calculates savings based on removing whitespace and comments.

Yet, can't minifiers do clever stuff like reducing `#000000` to `#000`? And restructuring something like:

    h1 {
      background-color: blue;
    }
    h2 {
      background-color: blue;
    }

To:

    h1,h2{background-color:blue}

Long story short, seems like LH's estimate is rather conservative, meaning users may not realize that they could potentially be saving a lot more?

Seems like easier path would be to just run the CSS file through a bona fide minifier?

I'm sure you all prob discussed. I just didn't see any discussion around this in the issues.

**Comment by patrickhulce** [comment]
Yes indeed it is, mostly the same reasons we did this for javascript: **parsing/minifying is incredibly slow**

Outlined the options here in this comment https://github.com/GoogleChrome/lighthouse/issues/3459#issuecomment-345330671, parsing and minifying CSS/JS can easily take 30s which was just way too long. This was also the reason we originally had to drop the other CSS audits from default run because parsing CSS alone was taking way too long

**Comment by kaycebasques** [comment]
Missed that comment. Makes sense.
