### ISSUE TITLE
viewport-fit=cover still not allowed?

### ISSUE THREAD

**Issue by mackelito** [GoogleChrome/lighthouse#4938]
Audits give the text marked in red saying "Invalid properties found: {"viewport-fit:cover"}.
Now it says it passes.. I think..? (shows a green check) but it's till under "Failed audits".. ?

**Comment by brendankenny** [comment]
@mackelito do you have a URL handy that we can test?

**Comment by mackelito** [comment]
@brendankenny yeah sure.. if you don't judge the site ;) (work in progress)
https://butik.fodi.se/

**Comment by wardpeet** [comment]
hi @mackelito sorry, I went a bit to fast on this issue.
I ran lighthouse with version 2.9.3 and I didn't get any issue. It was apparently fixed in version 2.9.0. 
The fix was done by @paulirish [fe17df0539bde1d423269285d209522c617a7509](https://github.com/GoogleChrome/lighthouse/commit/fe17df0539bde1d423269285d209522c617a7509#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

devtools is running on LH 2.8.0 which still has this issue so I would say use the LH extension or the CLI to have the latest LH version.
