### ISSUE TITLE
Offscreen images - 100% potential saving offered

### ISSUE THREAD

**Issue by alexckent** [GoogleChrome/lighthouse#4942]
Using Lighthouse 2.9.3 as a Chrome Extension.

The Offscreen images section is promising a 100% potential saving by lazyloading images. 

1) 100% shouldn't be possible
2) Some of the images referenced are being lazy loaded

![image](https://user-images.githubusercontent.com/6452347/38466773-b3d794d6-3b25-11e8-9c9c-0cc25f538cc3.png)

**Comment by patrickhulce** [comment]
It looks like from your URL you have an automatic carousel rotating images such that some initially used images become offscreen later. #1922 tracks addressing this case.

General answers to your questions though
1. Why not? If the image is 100% offscreen, you could save 100% of the bytes on load by deferring it until interaction.
2. If the images had a lazy load mechanism but still loaded earlier than your TTI resources, it's not truly lazy. Since LH doesn't scroll or interact with the page before TTI, an offscreen image should not be needed to trigger real lazy loading.

**Comment by alexckent** [comment]
Thanks Patrick, fair play to point one but the lazy-loading does happen after TTI (you can see it loading images when you scroll down) so I guess LH isn't smart enough (yet!) to deal with our particular case.

**Comment by okankocyigit** [comment]
i agree with @alexckent,

My home page has a slider on top of page which is also lazy loaded content but LH still says "hey consider lazy-loading bla bla"
