### ISSUE TITLE
Discussion: separate repos vs monorepo

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#4955]
There are a few efforts that make sense to be published independently and consumed by other projects not using the entire Lighthouse stack:

* [manifest-parser](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/lib/manifest-parser.js)
* [lantern simulator](https://github.com/GoogleChrome/lighthouse/tree/master/lighthouse-core/lib/dependency-graph)
* the [robots.txt validator](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/seo/robots-txt.js)
* streaming [trace parser](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/lib/traces/trace-parser.js) & [trace writer](https://github.com/GoogleChrome/lighthouse/blob/5bacdff524616b61b772f2870ad116a72f613cee/lighthouse-core/lib/asset-saver.js#L189-L223)
* proposed [JSON-ld validator](https://github.com/GoogleChrome/lighthouse/issues/4359)
* [chrome-launcher](https://github.com/GoogleChrome/chrome-launcher) (lives in separate repo)
* speedline

There are definite benefits for projects like these to be available independently. The primary benefit is that, availability as a standalone module increases likelihood of use by other projects, and that increases likelihood of receiving bug reports, fixes, features and maintenance. 

-----------

At the same time, we've also found challenges working with separate repos:
 
* issues/pull requests don't fall into the same UI, so it's much easier that they're ignored and not prioritized.
* Each change that touches LH and a "child" project now requires 2 PRs and 2 review cycles. 
* After the change in the child project is landed, its package must be released (publicly) for the parent to use the new commit.
* harder to reuse tooling (unit testing, CI projects, changelog generation)

These reasons are what leads me to favor keeping projects within the mono-repo.

However the less that we expect code changes/issues/reviews that affect LH, the more it is reasonable to live in it's own repo.

-------

@brendankenny @patrickhulce thoughts?
@rviscomi @kdzwinel what are you thinkin?

**Comment by brendankenny** [comment]
I think the easiest decision to make is to spin the submodule out of our repo when it will have a clear owner who maintains the project for more reasons than just as a Lighthouse dep. aXe is really great because we can hand off bugs and get pinged when we can bump the dep.

The contrast is `chrome-launcher`, where it's hard to care about proposed fringe features since Lighthouse is already served pretty well, we're the maintainers anyways, and the only person to ping us to bump the dep is ourselves :)

There's also the question of scope. I think having a project within Lighthouse implies that it's a part of Lighthouse that might be useful independently, not just that it's a thing that the LH team also maintains and part of it is used in LH. How much bandwidth can we spare for these projects when/if they expand beyond things that LH contributors care about? Sometimes new features are complicated and subtle, and it can take a good deal of research before even knowing if a PR is a good idea, let alone implemented well.

There's also a question of complexity of implementation. Some of these things (e.g. trace parser, manifest parser, robots.txt parser?) are very bounded in scope and can basically be "finished", only adding new things if/when the specs update or bugs need to be fixed. That really lowers the bar on how often we need to open PRs against them/bump the version in LH.

- trace parser and writer seems like it could fall well within the notion of "part of LH that could be useful on its own" without much scope beyond that
- manifest parser is as well if LH is still considered the authority on PWA verification (there's not really anything in web app manifests that LH doesn't care about, even if to just flag a validation error)
- lantern simulator I see more as a component of LH than a separate project, but it is possible it could be useful to projects to depend on in the future
- JSON-ld and robots.txt validators I'm not sure about, though. What's the scope for them beyond what LH cares about? If it's large, it seems that they should be external (and it seems like @rviscomi is optimistic that it could have maintainers outside our team)

**Comment by brendankenny** [comment]
We also don't want to overdo architecture organization for the sake of itself. I think that there are definitely productivity improvements we could make here, but LH as currently designed is pretty tightly coupled, and we make decisions all the time that adds to that. We shouldn't have our project/build infrastructure pretend otherwise or we'll just end up with impedance mismatch in the other direction :)

**Comment by rviscomi** [comment]
I'm amenable to a monorepo approach with independent modules. That addresses my biggest concern about downstream consumers. I still find it cumbersome that anyone who wants to spin it off would need to fork the entire LH codebase. Or would that not be the case?

> JSON-ld and robots.txt validators I'm not sure about, though. What's the scope for them beyond what LH cares about? If it's large, it seems that they should be external (and it seems like @rviscomi is optimistic that it could have maintainers outside our team)

I guess it's similar to `chrome-launcher` in that it's designed to fit the needs of Lighthouse, but is expected to be a generalized enough solution for other applications. I hope to have it able to validate all forms of structured data like JSON-LD, open graph, microdata, etc - all things LH will care about and validate - but other consumers may want finer controls. As for who will maintain it if external, I'm more hopeful than optimistic that it'll be community-maintained. Haven't explicitly asked anyone yet.

So I think we have consensus that we can start developing the SD validation within the LH repo in a way that enables the module to be published independently. If and when it gets big enough, we can spin it out as @brendankenny suggests.

**Comment by paulirish** [comment]
> So I think we have consensus that we can start developing the SD validation within the LH repo in a way that enables the module to be published independently. If and when it gets big enough, we can spin it out.

Groovy. SGTM.

----

Closing this issue, but it was super valuable to record our thoughts here. Thx ya'll!
