### ISSUE TITLE
ByteEfficiency reports no savings in animated GIF->video cases

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#5017]
repro:

1. use https://github.com/GoogleChrome/lighthouse/pull/4885
1. `lighthouse --perf https://gif.ski/ -GA`

the report says its 100 even tho there was almost 5MB of savings.

![image](https://user-images.githubusercontent.com/39191/39141268-28a045a8-46dc-11e8-867b-51a109da714f.png)

why?

The `computeWasteWithTTIGraph` reports 0 savings because there's only 1 network request affected and no long tasks touched. However taking the end of each graph, the difference is **23 seconds**. 

Patrick said one option is to calculate impact on end of graph, rather than impact on estimated TTI. Onload would also be indicative especially when the focus is on 1 or 2 problematic requests.  Both seem good to me.

**Comment by patrickhulce** [comment]
Yeah I think we decided after the original change that we're just trying to report "load"ish savings rathe than on specific metrics anyhow, it seems like savings on load instead of TTI is what we want in most cases (except offscreen images, render-blocking, etc where we're telling folks to "defer" rather than "eliminate")

**Comment by kaycebasques** [comment]
I was going to suggest a GIF->video audit in response to Jeremy's new article, but it looks like this issue covers it

https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/replace-animated-gifs-with-video/
