### ISSUE TITLE
Request: Documentation around gatherers & debugging

### ISSUE THREAD

**Issue by moondit** [GoogleChrome/lighthouse#5048]
Hey Everyone,

I have been trying to create some custom audits and am having some difficulty "gathering" the necessary information to perform a basic audit. Is there any documentation around the gatherers within lighthouse-core? Also, are there any ways to set breakpoints and evaluate code - similar to `node inspect` or `node debug`? 

For my first custom audit, I was hoping to verify that the page title of a document matched a particular format. I tried following the structure of the [meta-description gatherer](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gatherers/seo/meta-description.js), with a difference being that a `title` tag is not self-closing like a `meta` tag, nor does it have a `content` attribute. I tried filtering the nodes within the entire document to return the `title` element itself but that didn't work. Any thoughts here? I would like to make this process of adding custom audits easy for anybody on my team to contribute to without having to invest a significant amount of time.

Thanks in advance.

**Comment by patrickhulce** [comment]
@moondit have you already checked out the [recipes under the docs folder](https://github.com/GoogleChrome/lighthouse/tree/e61a34d82f10da9f72e4bb52a02aca95ff8fb51a/docs/recipes/custom-audit) of the repo?

That's the most documentation we have around custom audits/gatherers at the moment.

As for setting breakpoints, you have a few options:

1. Instead of invoking `lighthouse` you can invoke `node --inspect-brk /path/to/lighthouse.js`
   example: 
```sh
> PATH_TO_LH=$(readlink -f `which lighthouse`)
> echo $PATH_TO_LH
/Users/phulce/.nvm/versions/node/v8.11.1/lib/node_modules/lighthouse/lighthouse-cli/index.js
> node --inspect-brk $PATH_TO_LH --config-path=./my-custom-config.js
```
1. If you checkout the lighthouse project, after `yarn install-all`, we have a package script that runs lighthouse with debugging on, so it's just `yarn debug https://the-url.com --config-path=../path/to/config`

**Comment by moondit** [comment]
Hey Patrick,

Thanks for the response. I did checkout that example, but I was looking for a little more information around the different gatherers. I'll be sure to check out the debugging options. Thanks for all the effort behind this project.

**Comment by underbyte** [comment]
@moondit If you use VSCode, hitting a breakpoint can be a little easier.

1. Open the project in VSCode and set any breakpoints
2. Enable [Auto Attach](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_auto-attach-feature)
3. Use VSCode terminal and run the CLI `node .lighthouse-cli/index.js URL`

@patrickhulce Would this be worth documented in the doc folder?

**Comment by moondit** [comment]
Thanks for the suggestion @underbyte. I'll look into it.

**Comment by patrickhulce** [comment]
@underbyte yeah I think so! PR welcome ;)
