### ISSUE TITLE
Polymer CSS reported incorrectly 

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/lighthouse#5114]
Steps to reproduce:

1) Run a Lighthouse report for https://tuicruises.org/
2) Notice the unused CSS recommendation showing CSS code in lieu of the URL:
![af1bf619-a861-4ca0-81fc-aeb9336e6c84](https://user-images.githubusercontent.com/145676/39615681-cfa38f6a-4f77-11e8-9b7f-6831cc014084.png)
An [archived report](https://builder-dot-lighthouse-ci.appspot.com/report.1525414368248.html) is available.

**Comment by patrickhulce** [comment]
It seems like that URL isn't publicly accessible right now, so I can't take a deeper look, but the unused CSS is shown as code instead of URL when it's inlined/doesn't have its own URL. In your case it seems like you're injecting ~4KB of CSS into shadow roots that then isn't used? 

Agreed it's odd UX to be showing that a bunch of times especially since it probably only came over the wire once.

**Comment by paulirish** [comment]
This site doesn't load. :/ Gonna have to close until we have a repro
