### ISSUE TITLE
Lighthouse command doesn't use headless when ran through childprocess exec

### ISSUE THREAD

**Issue by smanwaring** [GoogleChrome/lighthouse#5121]
Hello - 

I am setting up a script to run a lighthouse check on CircleCI. When I run the commands straight in my terminal I can see the Chrome launcher start and it returns a report; however, when I run the same command through the node `childProcess.exec()` function in my script I don't see the chrome launcher launching (but I still get a report back). 

I have an idea that this may be why the Chrome Launcher is not booting up in my Circle CI job and because of that I am getting a perfect lighthouse score on my CI (perhaps indicating that it is not using `--headless` and being throttled correctly). 

Is there a known issue with using the lighthouse command with `childProcess.exec`? Does it need to be run as a raw bash command? 

Many thanks!

Examples
===

```javascript
/* This DOES NOT start up the chrome launcher when I run this script locally -- at least I cannot see it launching in the terminal */
const asyncExec = promisify(childProcess.exec);

async function runLighthouseCheck() {
  const results = asyncExec(`lighthouse --perf --output json --chrome-flags="--headless --no-sandbox" https://airhorner.com`);
  const parsedResults = JSON.parse(results.stdout);
  return parsedResults.score;
}

runLighthouseCheck();
```

Running this in the terminal does start up the Chrome Launcher
```
$: lighthouse --perf --output json --chrome-flags="--headless --no-sandbox" https://airhorner.com
```

I am using the latest version of `google-chrome-stable` and I have the latest version of `lighthouse` globally installed.

**Comment by nanliouhu** [comment]
because I do not use bash!


2018年5月5日星期六，Stephanie Manwaring <notifications@github.com> 写道：
> Hello -
>
> I am setting up a script to run a lighthouse check on CircleCI. When I
run the commands straight in my terminal I can see the Chrome launcher
start and it returns a report; however, when I run the same command through
the node childProcess.exec() function in my script I don't see the chrome
launcher launching (but I still get a report back).
>
> I have an idea that this may be why the Chrome Launcher is not booting up
in my Circle CI job and because of that I am getting a perfect lighthouse
score on my CI (perhaps indicating that it is not using --headless and
being throttled correctly).
>
> Is there a known issue with using the lighthouse command with
childProcess.exec? Does it need to be run as a raw bash command?
>
> Many thanks!
>
> Examples
>
> /* This DOES NOT start up the chrome launcher when I run this script
locally -- at least I cannot see it launching in the terminal */
> const asyncExec = promisify(childProcess.exec);
>
> async function runLighthouseCheck() {
> const results = asyncExec(`lighthouse --perf --output json
--chrome-flags="--headless --no-sandbox" https://airhorner.com`);
> const parsedResults = JSON.parse(results.stdout);
> return parsedResults.score;
> }
>
> runLighthouseCheck();
>
> Running this in the terminal does start up the Chrome Launcher
>
> $: lighthouse --perf --output json --chrome-flags="--headless
--no-sandbox" https://airhorner.com
>
> I am using the latest version of google-chrome-stable and I have
lighthouse globally installed.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/8BR2h4A28R41ZdivheCQr-koZC25cPmYcVMrOPv9wRBoHdAsIvk5VtrKRWMSJqqA1M_Vk7is1nYXePil1bKbQfTpTPZqVQ8Sv_VMBqj5U8HA53KMUTr3smRznD4C1hI9vUhE3YSIb8FH6rqfykRW9rOy_TLwxQ=s0-d-e1-ft#https://github.com/notifications/beacon/AlCJyVlvnKIRbzRDUa9hA9o_qQsVsU_Iks5tvI3AgaJpZM4Ty_kg.gif>

**Comment by smanwaring** [comment]
Turns out this was a non-issue and that my dummy pages we really scoring close to 100. Added some more content to the page and started to see the scores go down like we anticipated.
