### ISSUE TITLE
Report: chevron direction is backwards

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#5169]
Down arrows usually represent the expanded state rather than the collapsed state.

<img width="894" alt="screen shot 2018-05-09 at 12 01 28 pm" src="https://user-images.githubusercontent.com/238208/39834091-c0e35e80-5380-11e8-96da-f48e76c0d1b0.png">

**Comment by hwikyounglee** [comment]
Thanks for bringing this up, @ebidel! 

Admitting the counter-intuitiveness, here's an attempt to explain that the down arrow is an intentional choice. 

The uses of down arrows are mixed.
▶(collapsed) + ▼(expanded): e.g. tree view in file explore
▼(collapsed) + ▲(expanded): e.g. show/hide on data tables, show/hide toolbar
▼(without state change): e.g. dropdown

Reflecting on those, a rationale for LH to use 'v' is to indicate the *forthcoming action*  or to indicate 'there's something *more* when you click it'. 'v' works better than '^' to indicate there's *more'*. 

A side-effect/trade-off is that, when trying to describe the current state, the arrow direction is counter-intuitive. But hopefully, it doesn't stop the user's motivation to click on the icon to view more details, which is the primary role of the icon.

I hope this explanation works. Feel free to discuss further though!

Thanks!
