### ISSUE TITLE
Lighthouse audit always returns to homepage

### ISSUE THREAD

**Issue by bassmo** [GoogleChrome/lighthouse#5180]
Whichever page I set in the browser window, running the lighthouse audit in dev tools always returns to the site homepage.   Even though the lighthouse blurb states:  "You can run it against any web page, public or requiring authentication."  This happens when switching into or out of mobile emulation mode.
Chrome version: Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by patrickhulce** [comment]
If the server is redirecting mobile users to the homepage instead of the URL you requested then this is what you would expect. You can try to disable mobile emulation with the dropdown in Chrome Canary

![image](https://user-images.githubusercontent.com/2301202/39876896-41086dbe-5429-11e8-810a-52f3d8dcf895.png)

**Comment by wardpeet** [comment]
Adding pending close as I believe this is a none issue and @patrickhulce answered the question.

**Comment by paulirish** [comment]
This is happening because of useragent emulation. So you'll probably want to change how you handle mobile UAs. or test desktiop
