### ISSUE TITLE
lighthouse gives different results when running the same test

### ISSUE THREAD

**Issue by liorg2** [GoogleChrome/lighthouse#5288]
hi 
i'm running the lighthouse program again and again, and each time see a little bit different results.
for example in performance > minify javascript,
i can see 1 resources to minify, and in the next run i can see 3 resources to minify, and then 2.
any flag i can give lighthouse in the console mode, to prevent such cases, as I'm listening to its score, and currently it changes a lot
i'm using the audit tab of chrome (Version 66.0.3359.181 (Official Build) (64-bit))

**Comment by patrickhulce** [comment]
Is the URL you're running against exhibiting non-deterministic behavior? If you're running against a live site, frequently the ads/analytics scripts that end up on the page change every time it's loaded.

If you have a specific URL it's happening with, we can take a look.

**Comment by RickyIta68** [comment]
Hi, me too, I have the same problem testing in localhost : sometimes performance is 80, 90 and sometimes around 50 / 60. 
And also under Seo I see 100 and sometimes 82 
[Lighthouse_Rep.pdf](https://github.com/GoogleChrome/lighthouse/files/2040805/Lighthouse_Rep.pdf)
[Lighthouse_Rep_2.pdf](https://github.com/GoogleChrome/lighthouse/files/2040813/Lighthouse_Rep_2.pdf)

**Comment by patrickhulce** [comment]
@RickyIta68 do you have a public URL of that site available?

**Comment by RickyIta68** [comment]
@patrickhulce , good morning :) ... no at the moment the site is only on localhost. 
Since the differences on the results of the lighthouse tests are more on the performance, I think that perhaps the reason is that my notebook is a bit 'outdated or maybe depends on the differences in speed of the internet connection. As soon as I move the site to a hosting I'll try to better understand the situation. Thank you

**Comment by patrickhulce** [comment]
We strive to have consistent numbers in as many environments as possible, but there's [lots of sources of variance](https://docs.google.com/document/d/1BqtL-nG53rxWOI5RO0pItSRPowZVnYJ_gBEQCJ5EeUE/edit), when you do get that site up let us know 👍

**Comment by RickyIta68** [comment]
hi @patrickhulce good morning , I fixed the problem now I recive stable results from the lighthouse test. 
The problem was about the power setting on windows 10. I have changed the power setting of the CPU to 100%... and now is all ok. 
I have a question. According to you if I move this web site (wordpress) from my pc notebook localhost to an hosting provider with HTTP/2 and SSD and others nice things the performance should increase or more or less should be the same ? 
I have attached my last tests: one is with no network throtteling (99% performance)  and the otherone is with network throtteling (93% performance) ... 
[Lighthouse Report-2018-06-01-(test -no-opt-network-throttling).pdf](https://github.com/GoogleChrome/lighthouse/files/2062485/Lighthouse.Report-2018-06-01-.test.-no-opt-network-throttling.pdf)
[Lighthouse Report-2018-06-01-(test-with-opt-network-trottling).pdf](https://github.com/GoogleChrome/lighthouse/files/2062486/Lighthouse.Report-2018-06-01-.test-with-opt-network-trottling.pdf)

**Comment by liorg2** [comment]
hi, sorry for disappearing since opening this issue..
my case is a little bit different now. 
i want to record the lighthouse score for all performance metrics once in an hour, and give an alert for major change.

i'm using the node.js lighthouse package that runs in AWS lambda, and still the score can change a lot.
my problem is that for a given metric, for example: uses-responsive-images,
the score can be changes in each run i do.
i noticed in the node.js code, that the score is given by the WastedMS, and it's changing a lot as well.
the score can be changed from 0 to 65 to 100 few times a day, and in that way my alerts for dramatic change is not valuable .

im attaching the code, i've written so far. any feedback will be most appreciated!

`
const perfConfig = require('lighthouse/lighthouse-core/config/perf.json');
const chromeFlags = [
    '--disable-gpu',
    "--no-sandbox",
    "--headless",
    "--disable-translate",
    "--disable-extensions",
    '--no-zygote',
    '--single-process'
    , '--disable-background-networking',
    '--safebrowsing-disable-auto-update',
    '--disable-dev-shm-usage',//# https://github.com/GoogleChrome/puppeteer/issues/1834
    '--no-default-browser-check',
    '--process-per-tab',
    '--new-window',
    //   '--silent-debugger-extension-api',
    '--disable-notifications',
    '--disable-desktop-notifications',
    //'--allow-running-insecure-content',
    '--disable-component-update',
    '--disable-background-downloads',
    '--disable-add-to-shelf',
    '--disable-datasaver-prompt',
    '--disable-domain-reliability',
    '--autoplay-policy=no-user-gesture-required',
    '--disable-background-networking',
    '--disable-sync',
    '--disable-default-apps',
    '--mute-audio',
    '--no-first-run',
    '--disable-background-timer-throttling',
    '--disable-client-side-phishing-detection',
    '--disable-popup-blocking',
    '--disable-prompt-on-repost',
    '--enable-automation'
];
const opts = {
        logLevel: 'silent',
        output: 'json'
    };

    const flags = _.clone(chromeFlags);

    if (user_agent) {
        flags.push(`--user-agent=${user_agent}`);
    }
    const chrome = await chromeLauncher.launch({chromeFlags: flags, chromePath});

    opts.port = chrome.port;

    const results = await lighthouse(url, opts, perfConfig);

    const clean_results = _.pick(results, "userAgent", "lighthouseVersion", "audits", "runtimeConfig", "score");

    const results_fields = [];

    const lambda_result = {
        create_date: moment().format("YYYY-MM-DD[T]HH:mm:ss")
    };

    _.each(clean_results.audits, audit => {

        if (!exclude.includes(audit.name)) {


            const res = _.pick(audit, "name", "description", "helpText", "displayValue", "rawValue");

                try {
                    res.score = wz_utils.formatNumber(audit.score, 2);
                    res.wz_score = res.score;//initial value
                    if (audit.details) {
                        _.extend(res, _.pick(audit.details, "itemHeaders", "items", "type"));
                    }

                    results_fields.push(res);
                } catch (e1) {
                    console.log("error with audit:", audit)

                }

        }
    });

    // console.log(`result: ${JSON.stringify(results)}`);

    lambda_result.results = results_fields;
    lambda_result.overall_score = wz_utils.formatNumber(clean_results.score, 2);


    try {

        await chrome.kill();
        console.log('killed chrome instance');
        console.log("lambda_result: ", JSON.stringify(lambda_result));

    } catch (e) {

    }

    return lambda_result;`

**Comment by liorg2** [comment]
hi guys, did you had the chance to look? waiting for an advice

**Comment by patrickhulce** [comment]
@liorg2 nothing looks wrong with your lambda code. The audit you're pointing to that's being variable is just returning how long it takes the server to reply. This variance is coming from the server that's loading the page, not lighthouse. If the server swings between very slow and slow then the report will reflect this as well. You'll get the best results with LH if you run in a more controlled environment on every change to your site rather than hourly against your production site.

**Comment by liorg2** [comment]
Lighthouse 3 gives much better scores.
Great job

בתאריך יום ד׳, 11 ביול' 2018, 19:06, מאת Patrick Hulce ‏<
notifications@github.com>:

**Comment by paulirish** [comment]
Resolved on LH 3. 
Please open a new bug if you're facing problems with significant variability.

**Comment by nvnph** [comment]
Hello, I am new to the Lighthouse and a bit confused about the scores. Do the scores belong to one single page or does it check all other pages of the Website? For example, if I start from one page, does this evaluate the linked pages or do I need to run it on every single page?
