### ISSUE TITLE
Image aspect ratio audit is too strict

### ISSUE THREAD

**Issue by nrsbus** [GoogleChrome/lighthouse#5356]
Running Lighthouse as a plugin in the latest version of Firefox (Lighthouse 3.0.0-beta.0).

   How can I correct this??  I have tried everything I can think of - and I don't understand why the image is not being displayed correctly.

Thanks,
Todd

RESULTS FROM LIGHTHOUSE SCAN (nrsmart.com):
Displays images with incorrect aspect ratio
Image display dimensions should match natural aspect ratio.
URL
Aspect Ratio (Displayed)
Aspect Ratio (Actual)
	
/assets/nrsmart-logo-longtext.png(www.nrsmart.com)
412 x 36 (11.44)
800 x 69 (11.59)

**Comment by patrickhulce** [comment]
The issue here is that there is no precise way to scale down the image without distorting the aspect ratio. Example if the image were 800x70 you'd be able to scale it to 400x35. Consider shipping the image in the size you plan on using it.

Either way, our audit could be a little more lenient in these cases. If the image is +/- 1px it should ignore it.

**Comment by nrsbus** [comment]
Yeah, I really don't want to change the image size or it won't scale properly to mobile phones...  Whatever quality loss there may be, it's minimal.  It does not noticeably hurt the user experience as it currently stands...

   With all that being said - I agree that maybe the audit is a bit too strict...
