### ISSUE TITLE
Reports http site as https

### ISSUE THREAD

**Issue by NickTulett** [GoogleChrome/lighthouse#536]
For an internal site on Canary 54 with Lighthouse 0.6.9, I got a Yes for "Site is on HTTPS" but the site is HTTP.

**Comment by brendankenny** [comment]
> Lighthouse 0.6.9

is there a 0.6.9? We're on 1.0.5 on master and npm, but we had some wonky versioning at one point.

If this is an older version of lighthouse, there was a bug fixed in #480 where all URLs were passing the test, so you'll need to update it to get this addressed.

If it's a current version, we use the debugger protocol's `Security.securityStateChanged`, so Chrome DevTools may have the same bug. Does the site show up as secure in the DevTools Security panel?

**Comment by paulirish** [comment]
can you share a screenshot of the chrome devtools security panel viewing this site?
if you can't share here, you can share to me and brendan on email.

**Comment by NickTulett** [comment]
It's the extension that is reporting version 0.6.9

![image](https://cloud.githubusercontent.com/assets/350365/17186086/a9e5ae96-542b-11e6-992a-7b3617d33db7.png)

**Comment by NickTulett** [comment]
Extension from is from 2nd June

**Comment by paulirish** [comment]
reload and view the main origin details?

kinda weird.

here's how we define "is on https" 

https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/driver/drivers/driver.js#L161-L170
https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/driver/gatherers/https.js#L53

**Comment by brendankenny** [comment]
If the extension was from June 2nd, #480 would have been after that (June 29th), so that's likely the issue.

**Comment by paulirish** [comment]
good call.

**Comment by NickTulett** [comment]
It's the version that's live when you click the link for the extension on the home page of this project
On 27 Jul 2016 19:10, Brendan Kenny <notifications@github.com> wrote:If the extension was from June 2nd, #480 would have been after that (June 29th), so that's likely the issue.

**Comment by brendankenny** [comment]
The [extension has been updated](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk) to 0.7.0, so this should now be fixed. Let us know if you see any other issues!
