### ISSUE TITLE
Background-Img declared as Offscreen-Img

### ISSUE THREAD

**Issue by rolben1** [GoogleChrome/lighthouse#5408]
Hello,

when using LH für audit https://www.lebensbluete.de/entry.html (test-site with only the background picture) it declares that background-img as offscreen-img. For all other pages on that site as well.
css is: background: url(/bilder-bg/fruehling-wald-bergpfad.jpg) top center/cover no-repeat fixed #fc9;
css instead with top center/100% 100% works fine with LH but that's not what i want to display to users.

Thanks for help
Roland
webmaster @ https://www.lebensbluete.de

**Comment by patrickhulce** [comment]
Thanks for reporting @rolben1, you've bumped into an unfortunate wrinkle with the body tag! We detect images that don't have any size by getting its bounding rect, but because there's no content, the bounding rect for `body` has an area of 0! If you set the height of html, body to 100%, it should stop complaining. Rest assured there's nothing wrong with the way you're doing the background image though.

The good news is that in v3 we're not flagging this as a failure anymore since the savings is minimal (even though we still show the image as offscreen)

**Comment by rolben1** [comment]
Thank you very much for insvestigation and the workauround. 
I did as you ordered me to do and now the failure ist gone.
Thx again
Roland
