### ISSUE TITLE
Reducing filesize of JSON report - "Summary Mode"

### ISSUE THREAD

**Issue by sambokai** [GoogleChrome/lighthouse#5490]
## Feature request (and a usage question)

**Summary**
LH's JSON reports can add up pretty quickly in size, if run frequently and stored. I've discovered that the following keys contribute the most to the filesize (ca. 96%) while adding "only" advanced information:

```javascript
const stemmed = deleteKey(report, [
    'result', // 225kb
    'details', // 288kb
    'extendedInfo', // 35kb
    'helpText' , // 90kb
    'description', // 26kb
]);

// Stemmed = ca. 17 KB
// Report = ca. 462 KB
```
_The KB sizes of the keys are just estimations and are definitely not entirely accurate since key can be nested_

I will be modifying lighthouse in order to fulfill my project's requirement of a lesser detailed "Summary Mode", where scores are the most interesting information. 

Would this be something that others are interested in as well? I have a feeling that i can't be the only one with this problem. I was running into issues with MongoDB since some reports were over 16mb large. The summary file is needed for being able to query large report sets. The complete report will be stored somewhere else for further examination i.e. using the LH Report Viewer.

Is it worth it to coordinate this effort and possibly integrate it into the main project? I will be working on it anyway and would be happy to share.

Tell me what you think. :)

P.S: 
The usage question part: Is there maybe already a way of reducing the file size / the json object's depth that i'm not aware of?

**Comment by sambokai** [comment]
I stumbled upon #4063 where deleting `result.artifacts` is suggested. It helped reduce my testfile from ca 30mb to 1.5mb. 

That's already something 👍

**Comment by patrickhulce** [comment]
It looks like you're using v2.x and not v3.x?

We've already eliminated much of the duplication and trimmed down the size quite a bit in v3. The artifacts were never meant to be part of the report and are removed entirely from the LHR by default in v3 (now the result object you're used to is placed on a separate property `.lhr` as a sibling of `.artifacts`) so you should never get an object over 16MB to store. 

That being said, if you really don't care about any of the details and just want scores, you'd probably be better off coming up with your own storage schema since it could be *much* more efficient. 

```
categories: {performance: .89, pwa: ...},
audits: {redirects: 0, 'first-contentful-paint': 0.9, ...},
```

**Comment by sambokai** [comment]
Thank you. Don't know how i missed v3.. I was even wondering why `results.lhr` (as it is described in the docs) doesn't work. 

I guess this can be closed - for now. ;) Thank you for this awesome tool, will hopefully be able to contribute soon.

Greetings
