### ISSUE TITLE
Cache Control Not Parsed Correctly.

### ISSUE THREAD

**Issue by dtapuska** [GoogleChrome/lighthouse#5572]
#### Provide the steps to reproduce
1. Run LH on https://dir.indiamart.com/impcat/floral-printed-kurti.html
2. Observe audits in devtools
3. Cache control on the resources it reports insufficient cache control on static images has whitespace in directive.

#### What is the current behavior?
Warnings when "cache-control: max-age = 31536000, public" is used.

#### What is the expected behavior?
No such warnings on "cache-control: max-age = 31536000, public"

#### Environment Information
* Affected Channels: DevTools 
* Lighthouse version: 2.9.1
* Node.js version:
* Operating System:  Chrome 67.0.3396.87 on Debian

**Related issues**
See issue: https://bugs.chromium.org/p/chromium/issues/detail?id=856770

**Comment by patrickhulce** [comment]
Thanks for the refile @dtapuska :)

We're closing this because it's WAI. [Per the spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9) and our parsing library, whitespace is not allowed between the equals sign and its directive/value (even though the [ABNF](https://www.w3.org/Protocols/rfc2616/rfc2616-sec2.html) for cache-control does permit whitespace between directives)
