### ISSUE TITLE
Higher FMP number since Last week

### ISSUE THREAD

**Issue by pkamran** [GoogleChrome/lighthouse#5636]
Hi team,

Since last week, We are seeing high number for FMP on all are sites. We wanted to know whether there is any change in Calculation Formula. 

We are triggering Lighthouse using WPT  private agent.

Thanks
Pankaj Kamran

**Comment by patrickhulce** [comment]
If you've been using Lighthouse on public WPT, then nothing should have changed in FMP calculation. It's just whatever is reported by Chrome.

I'm not sure about your private agent setup though. Make sure both the agent and LH are up to date with latest versions.

**Comment by patrickhulce** [comment]
Oh I think I know what's going on here. I believe @pmeenan recently made a change to WPT that always used the "3G Fast" profile when doing the Lighthouse run since that's what our scoring curve expects and a lot of folks were accidentally picking the wrong profile. 

Since you're comparing the Cable connection output, the change is probably the difference between  "3G Fast" and "Cable".

@pmeenan I wonder if there's a happy medium for private instance users that still want to continue getting the LH metrics on other connection types. A `--live-dangerously-I-know-what-I'm-doing` flag/checkbox?

**Comment by pmeenan** [comment]
I'm open to adding a test option (and config setting) that disables the forced "3G Fast" profile for lighthouse and uses the test settings.  The performance scores will be inaccurate but the timings would be more what you'd expect.  FWIW, WebPageTest itself exposes FMP (and FCP) directly without having to run lighthouse if you're just looking for the metrics.  If you're looking for the scores too then running at a different speed makes them invalid.

**Comment by patrickhulce** [comment]
Yeah at this point I suppose TTFCPUI and EIL are the only ones you're not getting with WPT out of the box.

**Comment by pmeenan** [comment]
You will need to sync the latest server (release or master branch) from Github (if you are using the AWS AMI it should sync within the next hour).  The agents will pick up the supporting code within the next hour as well.

On a per-test basis you can pass lighthouseThrottle=1 as a test option to disable the forced 3G throttling.  This will work on the public or a private instance.

On a private instance to disable it globally you can just add lighthouseThrottle=1 to settings.ini on the server.
