### ISSUE TITLE
Seeing unexpected failure for "Cache contains start_url from manifest"

### ISSUE THREAD

**Issue by tjsavage** [GoogleChrome/lighthouse#566]
https://shop.polymer-project.org fails the "Cache contains start_url from manifest" but I'm not sure why.

start_url is just listed as "/", which appears to be navigable from the cache?

**Comment by paulirish** [comment]
I think this is resolved in the latest master.

Are you in the chrome extension?

**Comment by tjsavage** [comment]
Yes this was from the chrome extension. I'm actually seeming to get a "No" for every item under "App can load on offline/flaky connections" for https://shop.polymer-project.org from master.

**Comment by paulirish** [comment]
okay thanks for reporting.  i'll dig in.

**Comment by paullewis** [comment]
Yeah the start URL stuff is because sw-precache is rewriting URLs. It's in my (immediate) future to try and make this test far more robust than it is at the moment. I can't repro the "App can load on offline/flaky connections" issue though:

<img width="803" alt="screen shot 2016-08-13 at 3 41 17 pm" src="https://cloud.githubusercontent.com/assets/617438/17643803/69623832-616c-11e6-8e6a-36594681c90c.png">

That's from the extension on master (1.1.2)

**Comment by wardpeet** [comment]
closing, should be fixed (haven't heard any issues about this)
//cc @paulirish

**Comment by brendankenny** [comment]
We disabled the cache-start-url audit because of this issue. We should probably retitle and reopen? Or file a new issue to fix the audit and reinstate
