### ISSUE TITLE
Lighthouse 3.0.3 Metrics vs. Trace Metrics (FCP, FMP etc)

### ISSUE THREAD

**Issue by georgiee** [GoogleChrome/lighthouse#5751]
Hello Lighthouse Team!
what fantastic job you are doing to with this amazing tool! I really love to use Lighthouse to get a solid feeling how good or bad a page is doing and to explain people what's wrong with a page.

Just now I'm using Lighthouse 3.0.3 with Google Canary and also with the CLI. I think the trace is not generated properly. To demonstrate the issue I run a Performance Audit for google.com (CLI or via Canary doesn't matter) and displayed both the Lighthouse Result and the Performance Trace side by side. Here a screenshot and I attached all generated assets as a zip file too.

![screen shot 2018-07-28 at 16 31 35](https://user-images.githubusercontent.com/1701755/43357623-dc8c0dba-9284-11e8-9ceb-6a9e0c7b1dd2.png)

You can see different measurements for FP and FMP between Lighthouse and the Trace.

|                   | FP  | FMP  | Delta |
| ----------------- | --- | ---- | ----- |
| Lighthouse        | 930ms | 1160ms | 230ms   |
| Performance Trace | 469ms | 605ms  | 136ms   |

Here another table for a more complex page I'm in the process of analyzing so you can see how much off the values are.

|                   | FP  | FMP  | Delta |
| ----------------- | --- | ---- | ----- |
| Lighthouse        | 2070ms | 3630ms | 1560ms   |
| Performance Trace | 680ms | 1260ms  | 580ms   |

Back to the google.com example. Looking at the frames I can perfectly spot the moment FP is measured. See the following image.
![screen shot 2018-07-28 at 16 32 46](https://user-images.githubusercontent.com/1701755/43357667-7cfdcf36-9285-11e8-9736-5c8a96edcc71.png)

This confirms the value of 469ms displayed but I think the overall timeline in the Performance Trace is off. From doing other analysis before my gut tells me Lighthouse is right. But I don't understand why the deltas are not constant at least.

What do you think? Are you aware of this?

[Archive.zip](https://github.com/GoogleChrome/lighthouse/files/2238056/Archive.zip)

Thanks.

**Comment by brendankenny** [comment]
@georgiee yes, they're expected to be different. By default, Lighthouse 3.0 has switched to simulated throttling. It loads the page at full speed for the machine it's running on (these are the results you see in the trace), but then does a simulation over the network and cpu task graphs to approximate what the load would have been like on a slower machine and a slower network (these are the results you see in the Lighthouse report).

There is ongoing exploration of generating a trace out of the simulation process that would match the simulated numbers (e.g. #5428 for the network side of things), but if you really want them to match you can also use devtools's throttling with a `--throttling-method=devtools` on the command line or using the "Applied" throttling option (instead of "Simulated") in the Audits panel in DevTools.

**Comment by georgiee** [comment]
Hello @brendankenny,
thanks for taking your time to answer my question. I have read about simulated throttling and the issues with the devtools approach. So I understand the difference between both variants and I really want to stick to the simulated version for more sane measurings.

Is Lighthouse therefore running both variants `simulated` and `devtools` or where does the Performance Trace file come from ? I mean I run something like that:
```
lighthouse http://www.google.com  --throttling-method=simulate  --save-assets
```

Which will save the html summary including the performance trace in json format. So I wonder where the non-matching performance trace comes from?

**Comment by patrickhulce** [comment]
@georgiee the trace that gets saved with `--save-assets` is the one we observed, not the one we simulated and used to compute the metrics which is why you see the deltas. If you want to take a look at what the simulated traces look like, you can try running with an experimental env variable

```
LANTERN_DEBUG=1 lighthouse http://www.google.com  --save-assets
```

That will dump out **lots** of trace files that we used to simulate everything (from the metrics to the opportunities). The one you're probably most interested in is `pessimisticInteractive` which contains pretty much everything.
