### ISSUE TITLE
Moonlight is reporting no HTTPS on site with HTTPS

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/lighthouse#576]
For https://events.google.com/io2016/

![image](https://cloud.githubusercontent.com/assets/8204171/17562442/c9379264-5edf-11e6-804c-9d1761112823.png)

**Comment by wardpeet** [comment]
looks like something related in the past #536 but than the way around

**Comment by paulirish** [comment]
Latest moonlight also has this bug:

![image](https://cloud.githubusercontent.com/assets/39191/20081608/8383b448-a505-11e6-8aa9-d23c43ea83d5.png)
![image](https://cloud.githubusercontent.com/assets/39191/20081611/85a18304-a505-11e6-8201-51e566f39618.png)


.. 

It's a bug in headless. Being tracked here: https://bugs.chromium.org/p/chromium/issues/detail?id=609394

Closing as the bug is upstream in moonlight and headless but not ours.
