### ISSUE TITLE
consider replacing driver.evaluateAsync with new async debugger evaluate

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#580]
Should simplify it a good bit. Will require all client-side scripts to evaluate to a promise (instead of calling `__returnResults`)

https://chromedevtools.github.io/debugger-protocol-viewer/tot/Runtime/#method-evaluate

**Comment by paulirish** [comment]
the `awaitPromise` param in particular,, yeah. 
FWIW this landed in https://codereview.chromium.org/2196003002/ which makes it m54. We may want to wait until Chrome stable hits 54 (around Oct 18th) before moving to this.

**Comment by wardpeet** [comment]
Would it be a lot of work to support both? With a feature check? (not sure how __returnResults is used atm)

**Comment by paulirish** [comment]
We could "feature-detect" the protocol to see if there's support for it, but I'd rather do the switch in a few months at once, rather than support two codepaths simultaneously.

(TBH, our evaluateAsync has been totally stable, so i'm not particularly concerned about maintenance, but we're not in any rush either.)

**Comment by wardpeet** [comment]
That's true :) perhaps add a milestone or a label to it.

**Comment by paulirish** [comment]
cc @ak239
