### ISSUE TITLE
Cannot recognize redirect HTTP traffic to HTTPS

### ISSUE THREAD

**Issue by zijianhuang** [GoogleChrome/lighthouse#5813]
#### Provide the steps to reproduce
1. Run LH on https://apsmd.medilink.com.au

#### What is the current behavior?

In the report about PWA, keep saying:
"Does not redirect HTTP traffic to HTTPS",

while my IIS does have the rewrite module for redirect, with the site setting:
```xml
        <rule name="ForceHttps" enabled="true">
          <match url="(.*)" />
          <conditions>
            <add input="{HTTPS}" pattern="off" />
          </conditions>
          <action type="Redirect" url="https://{HTTP_HOST}/{R:1}" appendQueryString="true" redirectType="Permanent" />
       </rule>
```

and the rule is working well actually 

#### What is the expected behavior?

No such warning in the report, thus higher score.

#### Environment Information
* Lighthouse version: 3.03
* Operating System: Windows 10 Pro
* Chrome version: 68.0.3440.106 64-bit

**Comment by justinribeiro** [comment]
Testing that rule locally on IIS 10 Express on Windows 10, the rule appears to run without issue. Testing the url you provided however, that rule doesn't quite seem to be working as intended. It appears that the root only redirects, not subsequent paths that have a `{REQUEST_URI}`. Example:
```
[GOOD] http://apsmd.medilink.com.au > https://apsmd.medilink.com.au/login?returnUrl=%2F
[FAIL] http://apsmd.medilink.com.au/login?returnUrl=%2F > http://apsmd.medilink.com.au/login?returnUrl=%2F 
```
The reason LH reports this as `Does not redirect HTTP traffic to HTTPS` is because Lighthouse follows the first redirect from the root (https://apsmd.medilink.com.au/login?returnUrl=%2F), and the removes the HTTPS on that URL to test for HTTP (which fails because non-root doesn't redirect at the moment on that server).

I would check the IIS or web.config rule that's currently in use. If you find that the rule doesn't work (though your rule did work on my test setup), you might try something similar to this as well:

```xml
<rule name="HTTP to HTTPS" enabled="true" patternSyntax="Wildcard" stopProcessing="true">
  <match url="*" negate="false" />
  <conditions logicalGrouping="MatchAny">
    <add input="{HTTPS}" pattern="off" />
  </conditions>
  <action type="Redirect" url="https://{HTTP_HOST}{REQUEST_URI}" appendQueryString="false" redirectType="Permanent" />
</rule>
```

**Comment by zijianhuang** [comment]
@justinribeiro, the rewrite rule is with the Rewrite module that is installed in IIS, while IIS Express is ignoring such config for sure.

My app is an Angular 2+ app, currently with Angular 6.1. 

And there's another rewrite rule:
```xml
        <rule name="Angular Routes" stopProcessing="true">
          <match url=".*"/>
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
            <add input="{REQUEST_URI}" pattern="^/(webapi)" negate="true" />
            <add input="{REQUEST_URI}" pattern="^/(tasksapi)" negate="true" />
          </conditions>
          <action type="Rewrite" url="/"/>
        </rule>
```
So if the user key-in the url routing, the NG routing is still working well. But I guess this shouldn't has impact on the OP.

**Comment by justinribeiro** [comment]
Regardless of my test setup, I can reproduce this on the URL you provided. Said issue doesn't seem to be a Lighthouse specific, but that rather non-root URLs don't redirect to HTTPS (which lighthouse correctly identifies for that url in this case).

Obviously I don't have access to all the routing configor the entirety of your setup to know exactly where the issue is. At the end of the day, you know your setup better than I do. :smiley:

**Comment by zijianhuang** [comment]
I had recognized that it was the rewrite config not good enough, since some manually key-in URL could not be redirected to HTTPS. The solution is simple, put the "ForceHttps" rule before the "Angular Routes" rule.

Now my site is 100% LightHouse happy site. 

It is up to you to consider to 

The case could be closed.
