### ISSUE TITLE
Audit: total byte weight 

### ISSUE THREAD

**Issue by hsablonniere** [GoogleChrome/lighthouse#584]
From the I/O and PWA summit talks I watched, I saw that total transfered size has a cost and is a big problem in Africa and other regions where data is expensive.

> https://whatdoesmysitecost.com/

I also remember that when [Google+ did its redisign](https://developers.google.com/web/showcase/2015/googleplus), they talked a lot about their budget target : 

> We hit our goal of never downloading more than 60k of HTML, 60k of JavaScript and 60k of CSS at any one time!
1. Would this kind of audit be interesting and relevant?
2. What kind of scoring could we propose?
3. Should this be part of the **Performance Metrics** or is this something new which could group stuffs related to caching strategies (HTTP cache, SW cache...)?

This is maybe where configuration will help since the kind of business and target of the PWA have influence over the budget target.

**Comment by paulirish** [comment]
Yeah I think we should have a diagnostic to surface this number:

* Total byte weight of page: 32,432Kb. ($$$$)

And the $$$$ could link off to whatdoesmysite cost like [how webpagetestdoes it](https://github.com/WPO-Foundation/webpagetest/blob/566e0c77b117412630cb047aab6b037b49c605bb/www/include/RunResultHtmlTable.php#L324-L339)

We can start with it being unscored, but later apply a flexible scoring to it so that we punish the crap out of pages which go above 5MB (or whatever high threshold we want).

**Comment by nhoizey** [comment]
It's definitely much needed, and it has to take into account all downloads, including the ones done by Service Workers: https://nicolas-hoizey.com/2017/01/how-much-data-should-my-service-worker-put-upfront-in-the-offline-cache.html

**Comment by patrickhulce** [comment]
I'm going through and fleshing out the new "Using bytes efficiently" section, so I can add this in too.

**Comment by nhoizey** [comment]
@patrickhulce awesome, thanks!
