### ISSUE TITLE
doctype code

### ISSUE THREAD

**Issue by bazilisek987** [GoogleChrome/lighthouse#5926]
Hi,

why will not 

!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"
html xmlns="http://www.w3.org/1999/xhtml" lang="en"

pass the doctype test if the browsers keep their standard modes (i.e. not a quirk mode)?

If its sole purpose is to prevent a browser from switching into so-called “quirks mode” when rendering a document, then the code above should be fine, right?

**Comment by justinribeiro** [comment]
Hi thanks for the question!

The reason that doesn't pass the audit is because `PUBLIC` is defined (which is specifically for legacy DTD definitions and should not be used today unless you have a specific case you're trying to meet). The current guidance is to use `<!DOCTYPE html>` as per https://developer.mozilla.org/en-US/docs/Glossary/Doctype

As a note, that doctype you have won't _necessarily_ keep you from quirks mode; that doctype isn't valid as is (and I can't be sure as to your case for using it), but the valid legacy definition would be:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
```

**Comment by bazilisek987** [comment]
Can you please tell me how your code differs from mine? Except those greater- than and less-than signs (I didn't write them in my code because github deletes what is between these signs apparently). 

As I can not see the difference, are you saying I am using a valid legacy definition and because of that I didn't pass the audit? That would be ridiculous. Oh well.
