### ISSUE TITLE
Publish more in-depth guidance on lab test implementation details and caveats

### ISSUE THREAD

**Issue by fchristant** [GoogleChrome/lighthouse#5931]
I hope I'm posting this in the right category. I'd like to give some feedback on the confusion I have when picking a runtime context for doing an audit. Example page::

https://www.eon.earth/silva

Run 1: Simulated Fast 3G, which is listed as a faster audit with "similar accuracy".

Result is a performance score of 99, with an FCP of 1.6s and a FMP of 2.3s. Runtime settings at the end of the report state a RTT of 150ms.

Run 2: Applied Fast 3G

A performance score of 90, with the FCP at 2s and FMP in orange, at 3.6s. Runtime settings at the end of the report state a RTT of 562ms.

Run 3: webpagetest.org, picking the closest possible match, Nexus 5 as device, "fast 3G" as connection:
https://www.webpagetest.org/video/compare.php?tests=180829_8D_6f10a7534085fdddbf629fcda2c959d9-r%3A1-c%3A0&thumbSize=200&ival=100&end=visual

FCP here is 4.7s, FMP at 4.9s.

From my perspective, as a mere user of these audit tools, this raises a few questions:

- The difference between Fast 3G and Applied Fast 3G is unclear to me. The label say they deliver similar accuracy, but my results show a wildly different result between the two, about a 50% difference.
- Why is the RTT of Applied Fast 3G so sky high? 562ms is quite a stretch from 150ms. I'm sure there's a reason for it, but it is unknown to me
- Although I know webpagetest.org is likely not in the control of your team, would you have any explanation of why results there are yet even worse, despite picking the same device and connection profile?

These 3 runs are my (perhaps naive) attempt at auditing in circumstances as closely matching as I can pick, yet the results range from an almost perfect performance score and a FCP of 1.6, towards a relatively poor situation at the other end with a FCP at 4.7. It's a pretty dramatic difference between excellent and quite poor, and I don't have an explanation for it. I'm hoping you can fill some gaps in my understanding.

**Comment by patrickhulce** [comment]
Thanks for filing @fchristant good questions!

> The label say they deliver similar accuracy, but my results show a wildly different result between the two, about a 50% difference.

In the grand scheme of web performance 1.6s and 2s FCP are very similar and within the range of normal variance which is what we're referring to with "similar accuracy". When judging performance our foremost concern is getting the same ranking between different methods i.e. slow sites are correctly identified as slow and fast sites are correctly identified as fast. FMP has much more quirky characteristics and can vary more between the two.


> Why is the RTT of Applied Fast 3G so sky high? 562ms is quite a stretch from 150ms. I'm sure there's a reason for it, but it is unknown to me

They are RTTs at different network layers. The simulated is applied at the transport layer (TCP). It refers to the round trip time of a packet from client to server. The applied throttling acts at the application layer (HTTP). It refers to the round trip time of a request including DNS/TCP/SSL/server response time/etc. It's much higher because it includes many different components (3 TCP RTTs minimum for SSL connections to new domains).

> Although I know webpagetest.org is likely not in the control of your team, would you have any explanation of why results there are yet even worse, despite picking the same device and connection profile?

WebPageTest is actually the most realistic, when in doubt trust these numbers :) The other throttling methods are underestimating primarily because there's a shocking amount of DNS, SSL, and server response time on your requests. Simulated assumes the [optimal SSL handshake settings](https://hpbn.co/transport-layer-security-tls/#enable-1-rtt-tls-handshakes) and more optimistic DNS/server response times. DevTools underestimates simply because it always applies 562ms across the board. which is exceeded 3-4x by all the initial requests.

**Comment by fchristant** [comment]
@patrickhulce Thanks a lot for your quick and excellent reply!

With your answers in mind, I guess I can understand a high performance score in LH, as it largely targets developers who often have no direct influence over delays caused by SSL, DNS, etc. In a way, they've done "their job" in delivering a performant application, after which the real world can destroy it, cynically speaking :)

I understand the RTT difference now too, thanks. And a very clear answer regarding trusting WPT as closer to reality as I heavily use it, also in a work context (SpeedCurve). 

I had asked this question with an even larger scope in mind, as there's more tools, such as CRUX, Pagespeed Insights, and the mobile readiness score (or whatever it is called). Each outputs wildly different outputs for the same page tested. Web performance auditors can learn about these differences to put them in the proper context, but the problem is that in a larger organization, it confuses several stakeholders. They don't know if we're doing well or poor, and which output is the "reality".

Anyway, I'll stop going off-topic. I'd end with wondering out loud how the above information in your answers could possibly be integrated or documented into the experience.

**Comment by brendankenny** [comment]
>  I'd end with wondering out loud how the above information in your answers could possibly be integrated or documented into the experience.

Closing in favor of #8594, where we're trying to figure out this very thing
