### ISSUE TITLE
V3 changes to scoring (live in chrome extension) & updating internal data TTI Problems

### ISSUE THREAD

**Issue by kusler** [GoogleChrome/lighthouse#5941]
#### Provide the steps to reproduce
1. Run LH on <affected url>
URLs are:

https://web.movistar.es/particulares/promociones/fibra-optica - Score 52
https://web.movistar.es/particulares/promociones/oferta-fibra - Score 55
https://promociones.movistar.es/oferta-terminales/ - Score 40

#### What is the current behavior?

We are seeing quite poor scores (<55) for some AMP URLs - it seems to be caused by poor TTI scores. 

#### What is the expected behavior?

Normally we see AMP URLs score >80 on Lighthouse and have good TTI, so we are wondering if the reason these pages score poorly is because of the way Lighthouse measures TTI on AMP, or if there's actually something wrong with these pages and the TTI is a true reflection.

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**
CC Craig Adolph

**Comment by midzer** [comment]
Here is more info about AMP pages and lighthouse https://github.com/GoogleChrome/lighthouse/issues/4490

**Comment by justinribeiro** [comment]
Inline with the issue @midzer provided, the AMP pages served from the AMP cache for urls 1 and 2 above perform significantly better, taking into account a number of factors (more efficient delivery of assets, et cetera) and they score around ~90 (though the third one doesn't seem to be valid AMP; it wasn't in the AMP cache).

From a non-AMP cache perspective, the reason they perform poorly in terms of TTI is because there appear to be a lot of long tasks that keep firing on the main thread, resulting in the poor score:

![image](https://user-images.githubusercontent.com/643503/45039888-75185500-b019-11e8-9da9-b1496cf7545a.png)

The FMP looks fine, but the amount of longer than 50ms tasks that run appear quite a bit (resulting in 18000ms in this test run for the first url above).

Similarly, if we look at the trace for the non-AMP cache version, we can see a lot of those long tasks (note, this was a different run from the above debug session, but it's pretty close):

![image](https://user-images.githubusercontent.com/643503/45040161-359e3880-b01a-11e8-8750-0e009c351c4b.png)

Given the nature of the existing code in LH and the trace, I would expect those scores for those URLs. Having tested other non-AMP urls that don't have the long task issue, these urls don't seem representative  of a typical non-AMP cache delivery (but I didn't test this heavily). 

Whether that's correct I'll leave that to @patrickhulce or @paulirish; LH I believe used https://docs.google.com/document/d/1GGiI9-7KeY3TPqS3YT271upUVimo-XiL5mwWorDUD4c/edit#heading=h.d06i5ycfxaow and https://docs.google.com/document/d/1yE4YWsusi5wVXrnwhR61j-QyjK9tzENIzfxrCjA1NAk/edit#heading=h.yozfsuqcgpc4 as the defined approach the Time to Interactive and  First CPU Idle metrics.

**Comment by brendankenny** [comment]
closing as obsolete (we have better ways of tracking these now)
