### ISSUE TITLE
Prestashop product link format causes SEO test to fail

### ISSUE THREAD

**Issue by johanlantz** [GoogleChrome/lighthouse#5951]
#### Provide the steps to reproduce
This type of product link is ok.
https://psos.givensa.com/en/home-accessories/7-mug-the-adventure-begins.html

This type of link fails 100%. 
https://psos.givensa.com/en/men/1-1-hummingbird-printed-t-shirt.html#/1-size-s/8-color-white
Lighthouse does something weird and the https page is marked as non secure and the SEO score is just a ?

The only difference I can spot is the link format. The second product has combinations that are reflected in the url.

#### What is the current behavior?
Prestashop product with combinations gets a ? SEO score in LH.

#### What is the expected behavior?
Same result as product with no combination.

#### Environment Information
Using Chrome LH on normal CPanel hosting.

**Related issues**

**Comment by johanlantz** [comment]
Corresponding Prestashop ticket: https://github.com/PrestaShop/PrestaShop/issues/10261

Even if they change it, maybe it is worth having a look in LH so it behaves as expected.

**Comment by exterkamps** [comment]
I tried to reproduce this in LH DevTools and LH cli, but both times SEO was 100.

The [PR](https://github.com/PrestaShop/PrestaShop/pull/9456) to fix this [issue](https://github.com/PrestaShop/PrestaShop/issues/10261) seems to have been resolved, so I think it is fixed from their end.  Seems like an issue with rendering the canonical URL without a default ID causing a redirect as seen in their [fix](https://github.com/PrestaShop/PrestaShop/issues/9508), but I'm not 100% if that would be the root cause?

This might be a case of their SEO being non-optimal and LH catching it, because now that they introduced the fix, it seems like their SEO has recovered. Without some steps to reproduce now I'm not sure if we can conclude that it was an error on our end.  Can you reproduce this again with more details?

**Comment by johanlantz** [comment]
I think this was a Prestashop bug so thanks for investigating.
