### ISSUE TITLE
Differences in reported metrics between CLI and Audit page?

### ISSUE THREAD

**Issue by krausest** [GoogleChrome/lighthouse#6009]
I'm trying to update lighthouse for version 3 in the [js-framework-benchmark](https://github.com/krausest/js-framework-benchmark/). I plan to use the "Run the Node module programmatically" approach, but I've run into a issue and look for your help.
 
Some metrics appear to differ a lot between a command line execution and the results from the audit tab. Both report lighthouse version 3.0.3.

metric | cli | LH chrome audit
-------|---|----------------
bootup-time | 0 | 62.728
mainthread-work-breakdown | 600.29 | 280.34 
total-byte-weight | 159231 | 157601
interactive | 2493.52 | 2304.82
json | [cli.json](https://github.com/GoogleChrome/lighthouse/files/2376577/cli.json.txt) | [chrome_audit.json](https://github.com/GoogleChrome/lighthouse/files/2376576/chrome_audit.json.txt)

(Subsequent results return similiar results for both. The config settings look similar -  I can't spot any difference concerning throttling.)

cmd line invocation:
`./node_modules/.bin/lighthouse https://stefankrause.net/js-frameworks-benchmark6/domvm-v2.1.4-keyed/ --output json > cli.json`

Chrome LH audit:
Device: "Mobile"
Audits: "Performance"
Throttling: "Simulated Fast 3G, ..."

I might understand the difference for interactive, but I do not understand the 0 for bootup-time and the very large difference for mainthread-work-breakdown and any difference for total-byte-weight.
Maybe it's just a silly mistake I made, but I can't find it - thanks for any help.

**Comment by justinribeiro** [comment]
Hi thanks for the issue! A few things I notice when looking at your included output:

> bootup-time

The boot-time difference is because when running from Audits tab in Chrome, you didn't run it in Incognito mode or in an empty profile, resulting in the 60ms boot time difference being attributable to a Chrome extension `injected.min.js` (in this case, 1Password based on the extension id in the log). This has been discussed before, but the general guidance currently is that when using Incognito mode or in an empty profile to limit said side effects for extensions.

> total-byte-weight

The difference here is that the CLI has downloaded the favicon.ico (resulting in the ~1.6KB difference). I can duplicate this behavior for other sites with LH; Audits panel nor CLI --headless doesn't surface the this record when calculating that number.

> mainthread-work-breakdown

Most the difference stems from the increase in `Style & Layout` time, which has seems to be specific to the CLI opening the new profile (CLI --headless seems to surface a number more similar to the Audits panel). I feel like there's a ticket for this somewhere but I couldn't locate it (@patrickhulce do you happen to know)?

**Comment by krausest** [comment]
Thanks for your great answer for total-byte-weight and bootup-time. Stupid me - forgot about the extensions. Please don't tell anyone :bowtie:.

But I'm afraid the mainthread-work-breakdown does not go significantly down when running headless on OSX (Chrome 69 + LH 3.0.3).
`./node_modules/.bin/lighthouse https://stefankrause.net/js-frameworks-benchmark6/domvm-v2.1.4-keyed/ --chrome-flags="--headless" --output json > cli2.json`
It's still something like 589.068 for the cli and 205.168 for the incongnito browser LH audit.

Do you have any further pointers for it?

**Comment by brendankenny** [comment]
> Do you have any further pointers for it?

You might want to check out the [variability docs](https://github.com/GoogleChrome/lighthouse/blob/ad1e2ca5f38f35f5a43d7d38f0a6a9f84c1504fe/docs/variability.md), as well as #8594, which links to a whole bunch more :)
