### ISSUE TITLE
Failed to execute 'getComputedStyle' on 'Window'

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#6068]
> `Audit error: Required CSSUsage gatherer encountered an error: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

Repro'd with:

```sh
lighthouse http://theverge.com --only-categories=performance -GA
```

We also see this happening pretty often in sentry.

**Comment by wardpeet** [comment]
@paulirish do you get this all the time? I ran the verge a few times and I don't get the issue.

**Comment by paulirish** [comment]
Nope not getting it on theverge anymore. (Though I do get `Unable to gather Scripts/Stylesheets/HTML Imports on the page: Cannot read property 'filter' of undefined` now.)

in sentry we can pull out the URLs where this hit recently.

**Comment by wardpeet** [comment]
i'll just look in sentry to reproduce as the verge is not throwing any errors 😛

**Comment by greengalaxy2016** [comment]
got the same error. running lighthouse from command line. 
`lighthouse http://localhost:4200/boc-operations/edit/15001900007 --port 59020 --output json --output-path=perf-moi-list.json --preset=perf --view --throttling-method provided --disable-storage-reset true --emulated-form-factor desktop --max-wait-for-load 6000
`

**Comment by brendankenny** [comment]
It's weird that this would throw as not an Element:

https://github.com/GoogleChrome/lighthouse/blob/df85d681886d1ae163798c715fd29c72cc96c58f/lighthouse-core/gather/gatherers/css-usage.js#L30

since trying to set `document.body` to anything but an `HTMLElement` throws for me, and an `HTMLElement` is definitely of type `Element`.

Since I'm no longer seeing an issue on the verge and don't see these errors in recent sentry, going to close.
