### ISSUE TITLE
DevTools Error: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by ReaL19318** [GoogleChrome/lighthouse#6087]
**Initial URL**: https://chrome.google.com/webstore/detail/advanced-font-settings/caclkomlalccbpcdllchkeecicepbmbm
**Chrome Version**: 69.0.3497.95
**Error Message**: Cannot read property 'value' of undefined
**Stack Trace**:
```
TypeError: Cannot read property 'value' of undefined
    at sendCommand.then.result (chrome-devtools://devtools/bundled/audits2_worker/audits2_worker_module.js:1008:211)
```

**Comment by exterkamp** [comment]
This issue seems like a duplicate to #6026.  I am going to close it as a duplicate, but if you could provide more info on the run that would be appreciated to help solve this, e.g. you were running in devTools/extension/cli + the settings (full audit/subset of audits/throttling) and was this issue transient or is it still occurring?  Thanks!
