### ISSUE TITLE
Detected JavaScript libraries test fails to detect Workbox.js version number

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/lighthouse#6125]
**Context:** Go to [*Slate Magazine*](https://slate.com/), run the Lighthouse Chrome extension v3.2.0.

**Background:** [Workbox.js](https://github.com/GoogleChrome/workbox) detection was added to [*Library-Detector-for-Chrome*](https://github.com/johnmichel/Library-Detector-for-Chrome) in https://github.com/johnmichel/Library-Detector-for-Chrome/pull/121 and works fine in the extension. Here is a screenshot of it running on *Slate Magazine*:

<img width="135" alt="screenshot 2018-09-27 at 10 28 30" src="https://user-images.githubusercontent.com/145676/46153008-3f454580-c240-11e8-9e24-1f08f2a3e7a0.png">

Lighthouse uses *Library-Detector-for-Chrome* in v5.1.0 as of https://github.com/GoogleChrome/lighthouse/commit/b49a1d2267fcc9eaf7c0f5f94a1bea3423cd9474, which includes the version number detection.

**Problem:** It seems like the version number detection check fails in in the *Detected JavaScript libraries* test in Lighthouse 3.2.0, though:

<img width="830" alt="screenshot 2018-09-27 at 10 28 15" src="https://user-images.githubusercontent.com/145676/46153007-3f454580-c240-11e8-95e2-08b77012d242.png">

**Expected Behavior:** The version number of Workbox should be extracted in the *Detected JavaScript libraries* test. We would love to have this level of detail in the HTTP Archive eventually, where Lighthouse results get stored as a component of Web Page Test.

(CC: @rviscomi @jeffposnick)

**Comment by tomayac** [comment]
Thanks for looking into this. The test checks for a `ServiceWorkerRegistration`, so if the sites activates an installed service worker immediately, it should succeed.

**Comment by tomayac** [comment]
The relevant code snippet starts here: https://github.com/johnmichel/Library-Detector-for-Chrome/blob/ab1288ffc0a8c437b9e2b5bc4fe5e4708ba39dc5/library/libraries.js

**Comment by brendankenny** [comment]
When @exterkamp was trying the extension, it wasn't reporting Workbox on an initial, clean load of slate. Only on the second load would it show up.

So it does seem like we might need to tweak the detection script.

**Comment by exterkamp** [comment]
On first load of slate Workbox isn't detected in the extension:
![screenshot_1_detection](https://user-images.githubusercontent.com/6392995/46176622-ef2caa00-c264-11e8-8718-2c608726691a.png)

But after refreshing it is detected:
![screenshot_2_libs](https://user-images.githubusercontent.com/6392995/46176652-0c617880-c265-11e8-9e76-e5efa5d8165a.png)

Even though the first load has a service worker the test won't pass until the page is reloaded and contains a service worker from the beginning.  This is why Lighthouse can't pass the test, it runs the js-libraries before a second load, so it is still on the load w/o the service worker there initially.

**Comment by tomayac** [comment]
Right, because Slate doesn’t call Workbox’s `workbox.skipWaiting()`, but if it did, then the detection should work, as the library has a [timeout](https://github.com/johnmichel/Library-Detector-for-Chrome/blob/0c0acdc35870da23812290bf2c85a38c8f5c713b/content_scripts/lib_detect.js#L48) before it injects itself (or are you doing the injection differently?). Am I wrong with this assumption?

**Comment by exterkamp** [comment]
We are doing the injecting during the `afterPass` of the [Gathering stage](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gatherers/dobetterweb/js-libraries.js) which is after the page has loaded and the trace collected, etc.  So there is some time after page load and before the `test()` methods fire.  It isn't a consistent 2 seconds like the extension since this is a more custom method of injecting it.

Is this a problem with Slate's implementation of Workbox?  If someone can get around being detected by not calling `skipWaiting()` or misusing Workbox is this method of detection reliable?

Is there another website using Workbox we could test with?

**Comment by jeffposnick** [comment]
- https://so-pwa.firebaseapp.com currently uses version 3.4.1 of Workbox.
- https://www.target.com/ currently uses version 3.5.0 of Workbox.

We've got many more you could test with if that's helpful.

**Comment by brendankenny** [comment]
Sounds like we need to keep this bug limited to sites calling `workbox.skipWaiting()`. Sites like Slate that don't probably fall under #5527 ("how do we wait long enough to see the SW while not making LH runs slower for everyone else")

**Comment by jeffposnick** [comment]
`skipWaiting()` determines whether a previously installed service worker can prevent a new/updated service worker from being activated. If there is no previously installed service worker for a given scope, then `skipWaiting()` doesn't have any effect—the new service worker will become active immediately.

One thing that is more likely to be an issue is whether `clients.claim()` is being called or not, because that's what determines whether a newly activated service worker will have a chance to take control of potential clients, i.e. any open tabs.

If Lighthouse checks whether a service worker is in control (i.e. `navigator.serviceWorker.controller !== null`, or listening for `controllerchange` events on `navigator.serviceWorker`) then it would be `clients.claim()` that mattered. An alternative to listening for that is just listening for an active service worker, which can be done by waiting for the `navigator.serviceWorker.ready` promise to resolve.

(https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle is a great resource for all of this.)
