### ISSUE TITLE
Speed Index is now expressed in seconds?

### ISSUE THREAD

**Issue by darylljann** [GoogleChrome/lighthouse#6130]
**Summary**

Is there any supporting documentation regarding this change? 

Can't find any info in
https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index
https://github.com/paulirish/speedline

## Lighthouse v2
![image](https://user-images.githubusercontent.com/7110546/46182618-1648b180-c321-11e8-9353-453b15065188.png)

## Lighthouse v3
![image](https://user-images.githubusercontent.com/7110546/46182512-6a9f6180-c320-11e8-9894-551a8f71e504.png)

**Comment by paulirish** [comment]
hi @darylljann.

We think that the milliseconds unit communicates too much resolution for these values. On repeated runs all these numbers can move around a bit, so presenting them with the seconds unit hopefully clarifies their precision.

Also we noticed that typically when people were talking about their lighthouse report, they were mentally converting to seconds before sharing the metric results.

That's about the best documentation we have on the topic. :)

cc original PR #5914

**Comment by darylljann** [comment]
Fair enough. Is Lighthouse using Speed Index now vs Perceptual Speed Index? The score used to be unitless as well.

**Comment by paulirish** [comment]
ah. just clicked through on WPT's docs page and I better understand why you brought this up.
![image](https://user-images.githubusercontent.com/39191/46184305-dedaf600-c289-11e8-816a-81c18ae42a70.png)

And I recalled that historically Speed Index is shown unitless. (Mostly because nothing significant happened at that particular timestamp.)

--------------

So here's the backstory:


* When Lighthouse first added Speed Index, we showed it as unitless, keeping consistency with how it's historically been shown.
* At some point (LH v3.0 I think), we decided to show it with the `ms` unit. Because, really, it is. And it clarifies that these metrics are on the same timescale.  (@benschwarz actually helped convince me that adding a unit was valuable. He was telling me one of his customers had couldn't effectively explain it to people outside of the dev team without the unit)
* Now in LH v3.1.0 we changed our load metrics from milliseconds to seconds f[or the reasons i listed above](https://github.com/GoogleChrome/lighthouse/issues/6130#issuecomment-425291951). :)

+@pmeenan: I figure I should ask the owner.. :) Does this work for you? A speed index of "4570" being displayed as "4.5s"? 

---

> Is Lighthouse using Speed Index now vs Perceptual Speed Index?

Yeah while we like some of the ideas in Perceptual Speed Index, it has some flaws too. And it since it's so similar to Speed Index, it wasn't worth it any longer to present a different metric than you see other performance tools. :)

**Comment by pmeenan** [comment]
sgtm.  I just updated WebPageTest to display it in seconds as well since that's generally how we think about it anyway.

**Comment by paulirish** [comment]
Hah. Works for me!  👍

**Comment by darylljann** [comment]
Cheers folks 🙌🏼
