### ISSUE TITLE
waiting for load event + Xms isn't sufficient time for some sites

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#627]
one example: https://shop.polymer-project.org. See where the load event fires here:

<img width="816" alt="screen shot 2016-09-01 at 15 29 39" src="https://cloud.githubusercontent.com/assets/316891/18186695/fdcfb33c-7058-11e6-8c09-b8bb01cbc1d9.png">

One way this manifests is that the service worker isn't given enough time to even start downloading (so #599 wouldn't help), so the SW and offline tests fail. Presumably the e.g. Speed Index score is also very wrong, as most of the content hasn't actually loaded.

Interestingly, the extension audits the page somewhat successfully because the trace apparently takes a lot longer (a few seconds) to come across to Lighthouse in the extension than on the CLI, giving the page enough time to finish loading the service worker, recording more (most?) of the network requests, etc.

This can be solved for sites specifically instrumenting for LH by #519, but we also need a solution for the general case...something like "we're past load event and the network is calmish".

**Comment by paulirish** [comment]
My idea for `waitForLoad` is...

* Wait until window load + 500ms (implemented)
* Also, if there is any network activity, wait until there's 1s of network idle
  * Perhaps a timeout here if the time since onload is like >15s
* Cutoff at 25s total
* Optional: If load evt fires within first 5s, wait until 5000ms total at least

Tested this approach with a few things including youtube watch page, and it works well.

**Comment by wardpeet** [comment]
#599 would fix the serviceworker tests right? if it waits until activation? But that doesn't mean it can display a proper offline experience.
