### ISSUE TITLE
x-robots-tag not recognized

### ISSUE THREAD

**Issue by postme** [GoogleChrome/lighthouse#6303]
checked for duplicate issue: yes

#### Provide the steps to reproduce
1. Run LH on https://www-preview.secumail.nl

#### What is the current behavior?
x-robots-tag not recognized, LH states that page is indexable with SEO audit

#### What is the expected behavior?
x-robots-tag recognized, LH states that page is not indexable with SEO audit

#### Environment Information
* Affected Channels: not applicable
* Lighthouse version: 3.0.3
* Node.js version: not applicable
* Operating System: User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Related issues**
none

**Comment by patrickhulce** [comment]
Hm I'm not able to reproduce this behavior on that page. LH correctly stated that the x-robots-tag was blocking on my run. Any more steps that might be helpful for us to know?

![image](https://user-images.githubusercontent.com/2301202/47095283-95c7f300-d1f2-11e8-964c-867032c1847e.png)

**Comment by exterkamp** [comment]
Looking at all the images that load, their response headers all contain:
`x-robots-tag: noindex`
which is being picked up by the `is-crawlable` audit and throwing this audit failure.
![image](https://user-images.githubusercontent.com/6392995/50192082-acb7be00-02e5-11e9-8e3f-06087d88bb1e.png)
This is blocking the site from being indexed, which is the expected behavior as you say.  So I'm not seeing the error here?  Or is it that you think it should be indexed?

**Comment by postme** [comment]
Hi there, apologies @exterkamp I should have closed this one, I was able to the issue after the feedback from @patrickhulce. Closing now.
