### ISSUE TITLE
Audit: Desktop-friendly (responsive) design

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/lighthouse#631]
Most definitions of PWAs include responsive design as one of its necessary qualities (e.g. [1](https://infrequently.org/2015/06/progressive-apps-escaping-tabs-without-losing-our-soul/), [2](https://developers.google.com/web/progressive-web-apps/), [3](https://www.smashingmagazine.com/2016/09/the-building-blocks-of-progressive-web-apps/)). However, whilst Lighthouse has "mobile-friendly" audits (`content-width.js` and `viewport.js`), it does not evaluate "desktop-friendliness".

Some examples of things to look at (not not entirely sure how to go about testing for these):
- good use of space, and in particular no large area of whitespace in the middle of the page (on the sides could be acceptable, if at an suitable scale)
- text is appropriately sized

Some examples of desktop unfriendly PWAs:

![screen shot 2016-09-06 at 6 00 38 pm](https://cloud.githubusercontent.com/assets/51244/18283187/f4237df8-745b-11e6-8587-8e2f8f3d1018.png)
![screen shot 2016-09-06 at 6 00 56 pm](https://cloud.githubusercontent.com/assets/51244/18283198/f8b48d12-745b-11e6-85f9-66799e5a7cc3.png)
![screen shot 2016-09-06 at 5 43 49 pm](https://cloud.githubusercontent.com/assets/51244/18283227/1ce46cfc-745c-11e6-882c-c59acb37922d.png)
![screen shot 2016-09-06 at 5 44 02 pm](https://cloud.githubusercontent.com/assets/51244/18283229/21113e0e-745c-11e6-8d35-94c93bcd731b.png)

**Comment by addyosmani** [comment]
> good use of space, and in particular no large area of whitespace in the middle of the page (on the sides could be acceptable, if at an suitable scale), text is appropriately sized

Interesting idea, Michael! Imo auditing based on design decisions such as use of whitespace and text-size might be tricky to generalize down to a rule that can be universally applied for desktop.  If we took WaPO as one example where desktop friendliness could be better, the heading size and width of the images could be part of an aesthetic (although we know it's not in this case).

![screen shot 2016-09-07 at 9 20 15 pm](https://cloud.githubusercontent.com/assets/110953/18336945/f1314176-7540-11e6-83e1-119d81d6f898.jpg)

I wonder if the problem is more complex than just responsive design though (some folks may trigger very different experiences for desktop with their own distinct performance problems: https://twitter.com/wilto/statuses/63284673723375616).

**Comment by brendankenny** [comment]
without a full proposal here, it's not clear yet where exactly this should go.

I'm going to close for that reason (unless someone wants to write up a [complete audit proposal](https://github.com/GoogleChrome/lighthouse/blob/4c658d272705cc68f1b55a898a2c7fb5f881b57c/docs/new-audits.md)!), but we're tracking similar ideas under the UX audits @egsweeny is planning, so I think it should be covered to the extent that such things are automatable.
