### ISSUE TITLE
core: Add smoke test coverage for perf metrics when redirecting

### ISSUE THREAD

**Issue by Hoten** [GoogleChrome/lighthouse#6359]
Before #3707 can release, we need to add some additional coverage to catch the problem created after the first go (#4310) (see https://github.com/GoogleChrome/lighthouse/issues/4499#issuecomment-365018491).

There's already a test re: redirects, just need to add some expectations there re: perf.

**Comment by brendankenny** [comment]
We've had problems in the past with repeatable perf tests because our CI machines are usually underpowered and the load on the host machines can vary by quite a lot. For example, take a look at the [very loose expectations on the perf tests](https://github.com/GoogleChrome/lighthouse/blob/42a48c7971fb048584e216c50863f8385a46fbd7/lighthouse-cli/test/smokehouse/perf/expectations.js) currently run by smokehouse. They are more or less only testing that the audits are running without error, with a tiny bit of sanity checking (and the tests are *still* sometimes flaky).

Maybe something to do with DZL is the answer? @patrickhulce

**Comment by patrickhulce** [comment]
Well the good news is that the scenario @Hoten is describing should be assertable with no errors + `TTI > X ms` we should always be able to do smoke tests like that. The trick is when we need to assert that particular resources happened before other particular resources (opportunity savings) or that a metric value is *below* a particular value. The tricky-tti test is an example of a current smoke test that has been successfully catching regressions of this sort and is not very flaky. Nearly all of the current flakiness in the smoketests today is from Chrome process problems (affects all smokes) and tracing/screenshot problems (affects only the perf tests hence our increased sensitivity to perf flakiness).

I agree DZL should be our solution to the type of metric regressions we can't handle in CI where savings and metrics can be more predictable across a large number of runs 👍

**Comment by Hoten** [comment]
I'm closing this b/c 1) punting on #3707 and 2) after getting the previous implementation working again, the redirects smoke test I was going to update (this issue) was already failing. I fixed the implementation in the WIP branch, and got that smoke test to pass. So there's not much need to explicitly check for perf metrics in that smoke test anymore.
