### ISSUE TITLE
Extension Error: INSECURE_DOCUMENT_REQUEST

### ISSUE THREAD

**Issue by lordlouis** [GoogleChrome/lighthouse#6455]
Is there a way to ignore o disable INSECURE_DOCUMENT_REQUEST when is running in localhost? in previous versions this error hasn't triggered

**Lighthouse Version**: 3.3.0.4000
**Lighthouse Commit**: 40e1120765eb76a610421cc3f786b0a1c130634d
**Chrome Version**: 70.0.3538.77
**Initial URL**: https://localhost/mitienda/
**Error Message**: INSECURE_DOCUMENT_REQUEST
**Stack Trace**:
```
LHError: INSECURE_DOCUMENT_REQUEST
    at Function.assertNoSecurityIssues (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:19559:7)
    at Function.afterPass (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:19694:6)
```

**Comment by brendankenny** [comment]
Does it work with `http://localhost/mitienda/` (dropping the https)? Or are you really serving a valid certificate on your localhost server?

**Comment by patrickhulce** [comment]
If you're here because you're trying to do localhost development with https, make sure you're using the same Chrome profile you've modified and/or are using appropriate [Chrome flags](https://peter.sh/experiments/chromium-command-line-switches/).

Note that you might need to add the certificate as trusted at the OS level for Chrome to not throw the security warning.

**Comment by paulirish** [comment]
Currently we require a cert to be installed correctly. Look up docs on doing that.
