### ISSUE TITLE
Define trace parser preference

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/lighthouse#65]
We can either use the DevToolsTimelineModel (which we currently do in FMP), or we can require in traceviewer.

My preference is to try and use the latter wherever we can, but fall back to the former where it offers other insights into the data.

Thoughts?

**Comment by natduca** [comment]
I'm all for y'all doing what you gotta do to bootstrap the project. In the end, I think its on pavel and I to figure out how to make these one and the same, and in the meantime, for us to keep good notes tracking what is using which so that we can understand what its going to take in the future to undo the schism!
