### ISSUE TITLE
Explicit order for report categories

### ISSUE THREAD

**Issue by Hoten** [GoogleChrome/lighthouse#6563]
The order is mutated during proto message, and results in a different order in web.dev. Let's sort the categories explicitly.

**Comment by patrickhulce** [comment]
This is fairly amusing we made a breaking change in 3.0 to convert the categories from an array with explicit order to an object keyed by name :)

Is the plan here to add an order property to the keyed by name object?

**Comment by paulirish** [comment]
@patrickhulce yah makes the most sense. we can read that in all the places (devtools UI, etc).

**Comment by wardpeet** [comment]
Is this the correct order?
1) performance
2) Progressive web app
3) Accessibility
4) Best practices
5) SEO

**Comment by brendankenny** [comment]
Correct (it's the order in the config).

I guess the question is: rather than have a redundancy, could we instead
a) go back to an ordered collection or
b) fix it just when the proto gets turned back into json or
c) use a repeated field instead of a map for categories in the proto (since report categories also already have their `id` as a property)

**Comment by paulirish** [comment]
Proposal: I think we should move PWA to the end.

#6526 will now place the badge as the last of the score gauges. And since we use this as a navigational element for clicking to the reports, I think they must match. Lastly, PWA cat is the least relevant for the typical user.

@kusler @brendankenny et al: wdyt?

**Comment by patrickhulce** [comment]
I'd be against `a`, we just moved them to object keys for usability and b/c both fix this proto-specific problem

> Proposal: I think we should move PWA to the end.

+1 though I had already thought we did with brendan's PR 😆

**Comment by brendankenny** [comment]
There are other stakeholders involved, but I personally don't really care.

I can see the case that it could be important to many sites (SW can help more than PWAs, so I'm not sure if I buy the "typical user" argument), but on the other hand it might help folks who have absolutely no need to be a PWA focus on more important things in the report (many of whom have explicitly brought up the placement of the PWA category as an issue).

I will point out, though, that switching a score gauge style is a bad impetus for a change like this, though :)

**Comment by paulirish** [comment]
sorry. i meant to reassign this to @wardpeet.
agree that an `order` prop on the category in the config makes the most sense.

**Comment by brendankenny** [comment]
what happened to option b? Seems like the only problem in the pipeline is the step through a golang map?

**Comment by exterkamp** [comment]
Fixed on the api side! 😄 

Though I still think that the renderer should handle order independent categories!
