### ISSUE TITLE
Lighouhouse viewer: Accept post data?

### ISSUE THREAD

**Issue by ecumike** [GoogleChrome/lighthouse#6623]
**Summary**

This online Lighthouse Viewer is awesome!:   https://googlechrome.github.io/lighthouse/viewer/

Question: Does it accept POST data? I'd like to be able to link to it and post the data from a test so users can view it.

**Comment by patrickhulce** [comment]
It does not since it's on github pages which is just static files. You can take a look at how our report communicates with the viewer to show a specific report though.

https://github.com/GoogleChrome/lighthouse/blob/7715eda3c5debe85f1cb903606bea4a516d839db/lighthouse-core/report/html/renderer/report-ui-features.js#L353-L384

**Comment by ecumike** [comment]
AH, OK cool. Thanks!
