### ISSUE TITLE
LH API: missing throttling settings in LHR

### ISSUE THREAD

**Issue by NochEinKamel** [GoogleChrome/lighthouse#6654]
Hi,

Rob told me to file an issue here :-)

I was testing one of my clients pages with the new web.dev tool and was surprised by the low performance score.
First I thought it may only be because the page is hosted in germany and the online tools perhaps only tested from US servers, so I tested with some other well known german pages.
And then I read something about walmart saving 1% in the tips that are displayed when the tool is running in Chrome dev tool, so I tried that too and in all cases I get much better performance results testing it from my local system.
In the end even nic.com and google.com are faster on my local machine testing from germany.

**Performance score**

| URL        | web.dev           |  PSI  | Chrome Dev Tools, Germany |
| ------------- |:-------------:| -----:|----:|
| https://www.fsb.de | 57 | 68 | 100 |
| https://www.heise.de | 19 | 33 | 100 | 
| https://t3n.de | 49 | 42 | 100 | 
| https://www.walmart.com | 28 | 26 | 63 | 
| https://nic.com | 63 | 67 | 99 | 
| https://www.google.com | 96 | 96 | 100 |

**First Contentful Paint**

| URL        | web.dev           |  PSI  | Chrome Dev Tools, Germany |
| ------------- |:-------------:| -----:|----:|
| https://www.fsb.de | 2.5s | 2.5s | 400ms |
| https://www.google.com | 0.9s | 0.9s | 200ms |

So I was wondering
a) If others are able to reproduce those results (please state your location)
b) How helpful the performance score really is if there are such big differences between different (but namely the same => lighthouse) testing methods.

And perhaps if a tool like web.dev might need to check performance from different continents for those building pages with international audience.

If there is anything else you wnt to know, just let me know,

- Kai

**Comment by paulirish** [comment]
with the API/PSI, we are using these setting for throttling:

* mobile: https://github.com/GoogleChrome/lighthouse/blob/7715eda3c5debe85f1cb903606bea4a516d839db/lighthouse-core/config/constants.js#L19-L26
* desktop: https://github.com/GoogleChrome/lighthouse/blob/7715eda3c5debe85f1cb903606bea4a516d839db/lighthouse-core/config/lr-desktop-config.js#L14-L20


We don't include these values in `lhr.configSettings.throttling` response mostly because we weren't sure it was necessary to share them yet. That's something we can consider.

-----------

The score/metric differences certainly catch my eye though. 

@NochEinKamel when you're testing from DevTools, the first option is selected?
![image](https://user-images.githubusercontent.com/39191/49031985-4913f800-f160-11e8-802b-84bbb23128f0.png)

those 100s are pretty uncommon so I feel like your local testing is set to "no throttling"...

**Comment by NochEinKamel** [comment]
@paulirish No, I was not using throttling. With simulated 3g it's much much closer score wise.
But just from the web.dev page I was not able to understand that the scores represent the simulated 3G settings - and the other pages had such bad scores that I thought something was wrong on web.dev. Now it's clear that those pages are just bad mobile sites ;-)
