### ISSUE TITLE
bug report - question

### ISSUE THREAD

**Issue by DaveSimon01** [GoogleChrome/lighthouse#6680]
pagespeed insights reports zero repeatedly: www.kneeshaws.net

**Comment by patrickhulce** [comment]
If you're referring to the 0 performance score, that's because the performance is very poor. There's dozens of uncompressed render-blocking resources. If this is your site, follow the opportunities guidance to improve things.

https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=http://www.kneeshaws.net#performance

![image](https://user-images.githubusercontent.com/2301202/49247785-be403100-f3dd-11e8-9286-b1d50183064a.png)
