### ISSUE TITLE
Add ability to disable audits depending on config

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/lighthouse#6687]
Related to #1769

**Feature request summary**

When running Lighthouse in desktop mode, there may be certain audits that are mobile-specific and would be irrelevant and misleading.

Applicable audits should be marked as mobile-only and disabled when run in a desktop configuration. This may also apply to desktop-only audits for mobile configs.

**What is the motivation or use case for changing this?**

If you run Lighthouse in a desktop configuration, mobile-specific audits (for example the Mobile Friendly group of SEO audits) would also run and affect the SEO score. In that case, the results would not be applicable to the page.

**How is this beneficial to Lighthouse?**

Showing only relevant audits improves the accuracy/applicability of the results.

cc @mattzeunert

**Comment by paulirish** [comment]
SG. If we're not emulating as mobile, then we should mark the audit as notApplicable.
We can use the settings provided in the audit context?

**Comment by brendankenny** [comment]
> We can use the settings provided in the audit context?

Yeah, since we don't have that many audits that will need to be marked `notApplicable`, I think we should do this audit-by-audit rather than add another audit `meta` entry.

In `audit(artifacts, context) {}`, adding a `if (context.settings.emulatedFormFactor === 'desktop') return {rawValue: false, notApplicable: true};` should be sufficient.

(it isn't possible to get `context.settings.emulatedFormFactor === 'none'` in devtools/extension/PSI, but if we want to support more of the CLI we would need some runtime detection. Not sure if that's worth it?)

**Comment by mattzeunert** [comment]
I think @rviscomi and I decided we only need to do this for tap targets.

The font size audit is applicable on desktop, but should not fail because of a missing viewport meta tag.

**Comment by rviscomi** [comment]
In addition to tap targets, I could see the font size audit getting disabled for desktop as well. The motivation for that audit is to catch mobile unfriendliness and while small font sizes also affect desktop usability there is no direct connection to SEO.
