### ISSUE TITLE
Not applicable audits appear to be passing when N/A

### ISSUE THREAD

**Issue by fpsjobs** [GoogleChrome/lighthouse#6779]
** I analyse my website manually and on this tool also. I found two errors which this tool says is fine but not.
1. In the Crawling and Indexing section it says robots.txt is valid but i still didn't upload robots.txt

2. It also show that my website has valid rel=canonical, but in real it is missing in my website. 
Thanks
**
![image](https://user-images.githubusercontent.com/45818519/49865381-cf039480-fe2a-11e8-8323-1b7baa5479eb.png)

**Comment by patrickhulce** [comment]
@fpsjobs can you share your URL?

**Comment by frvge** [comment]
Based on his screenshot it's http://new.fpsjob.com/ .

@fpsjobs , both those check are under the "Not Applicable" section. Probably because it's not there, so it can't be sure if it's valid or not. Maybe the text needs to change to "robots.txt exists and is valid".

**Comment by exterkamp** [comment]
Looked into this, and there is definitely room for clarity on how we handle "Not Applicable" audits visually; I agree having a green check and positive text when the audit wasn't really 'passed' can be confusing.

To answer the original question, since there is no robots.txt or rel=canonical the audits are under 'not-applicable' and are not passing even though the flavor text indicates they exist.

**Comment by paulirish** [comment]
It's fixed now
