### ISSUE TITLE
Inconsistent results once google analytics added

### ISSUE THREAD

**Issue by DavidBanksNZ** [GoogleChrome/lighthouse#6803]
Hi there. Just something I've run into today - working on a beta for a while which had been consistently scoring 100 or just under on performance. But I've added in Google Analytics and now the time metrics have degraded quite a bit and it doesn't seem accurate to me.

#### Provide the steps to reproduce
Run LH on https://beta.howickweather.co.nz. I don't have a version without GA live though for comparison

#### What is the current behavior?
Before I added GA, was consistently getting performance scores 98-100 with time to interactive around 2 seconds or less. But just making one pageview tracking request to google analytics is causing the time to interactive to jump up to 4 seconds, yet the request in the browser in completed after less than 100ms.

#### What is the expected behavior?
I would have expected very little change with the addition of GA. But maybe there is a valid reason for it and I'm not aware

#### Environment Information
* Lighthouse version: tested on dev tools (3.2.0) and CLI (4.0.0 alpha)
* Operating System: mac and windows, doesn't seem to make a difference.

**Comment by DavidBanksNZ** [comment]
And another think I forgot to mention is that the performance trace always ends around the 2 seconds mark, despite the 4s TTI / CPI idle times

**Comment by regulus33** [comment]
I'm having the same issue, any updates on this? @paulirish I see this has been prioritized. Would love to know if some fixes are being planned. 

Thanks!

**Comment by brendankenny** [comment]
@DavidBanksNZ well, first of all, the new site looks great and performs really well!

Analytics can definitely hurt performance: two network requests and often a long task on its startup. From what I can tell from the trace, however, it's dragging the TTI out to ~4.5s, but without it, TTI would still be ~4s due to other stuff going on in the page (looks like when the api requests complete?), so I'm not sure if dropping it would be worth it.

Main things to improve would be to get an earlier first paint by doing something with the render blocking stylesheet and to move up those API requests if possible. Note that there's a warning on the "Preconnect to required origins" audit that the link to `https://api.howickweather.co.nz` wasn't used by the browser for whatever reason (maybe CORS)...might be helpful to look into that.

For thoughts on improving page load performance when using Google Analytics in general, see Phil Walton's excellent article: https://philipwalton.com/articles/the-google-analytics-setup-i-use-on-every-site-i-build/
