### ISSUE TITLE
Extension Error: INSECURE_DOCUMENT_REQUEST

### ISSUE THREAD

**Issue by betagoo** [GoogleChrome/lighthouse#6809]
**Lighthouse Version**: 3.3.0.4001
**Lighthouse Commit**: 66100367e39d970f8208bd30c10bd97cc7240784
**Chrome Version**: 72.0.3626.14
**Initial URL**: http://www.pro-vent.pl/
**Error Message**: INSECURE_DOCUMENT_REQUEST
**Stack Trace**:
```
LHError: INSECURE_DOCUMENT_REQUEST
    at Function.assertNoSecurityIssues (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:20163:7)
    at Function.afterPass (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:20298:6)
```
I know, that this issue is resolved.
But I can not find the cause of the issue.
HTTPS is necesary? I mean https://www.pro-vent.pl/

**Comment by exterkamp** [comment]
How are you running LH?  I can run against http://www.pro-vent.pl/ just fine from cli, extension, etc.  But get an INSECURE from https://www.pro-vent.pl/ because the cert is indeed invalid.  You aren't required to have HTTPS, you can run against just HTTP, but you can't run against an HTTPS site with an invalid cert, then it will throw an INSECURE error.

**Comment by betagoo** [comment]
Thanky You For help.
**Short solution: I see, we need SLL certificate anywhere.**

**Long solution:**

I use Lighthouse for Google Chrome Developer Edition.

This website normaly work on http://, (we do not have SSL).
There is self signed certificate for https:// , and there is redirection set into .htaccess file (from https to http):

`RewriteEngine On
RewriteCond %{HTTPS} =on
RewriteCond %{HTTP:X-Forwarded-Proto} =https [NC]
RewriteRule ^(.*)$ http://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]`

But! - before browser redirect page, have to connect to insecure https, and accept safety exception - google chrome do not do this - that is the problem perharps.
I know this problem, and I know, the self signed certificate is insecure.
We have to install certified SSL.

Thanks, You confirm my supposition.

One thing is strange. Two, maybe three weeks ago I use Lighthouse to analyze website http://www.tcmeble.pl and then everything worked fine. Maybe Lighthouse has made changes since then, because it does not work now.

Anyway. Once again thank You for help.

**Comment by exterkamp** [comment]
Hm.  We have been making changes to how INSECURE_DOCUMENT_REQUESTS have been handled lately #6457  #6608 #6739 etc. so I wouldn't be too surprised if it was changing recently from that if you are on dev channel or from the new M71+ chrome rollout.  

I can run against http://www.tcmeble.pl right though on v4.0.0-beta:
![image](https://user-images.githubusercontent.com/6392995/50239440-04523a00-0377-11e9-9138-57ce61d516a3.png)

But can't run against https://www.tchmeble.pl because the cert:
![image](https://user-images.githubusercontent.com/6392995/50239618-8e9a9e00-0377-11e9-836a-cb13f154cfd9.png)
