### ISSUE TITLE
Generate PageSpeed-Report with Lighthouse CLI

### ISSUE THREAD

**Issue by ac-webdesign** [GoogleChrome/lighthouse#6939]
It is possible to create a PageSpeed report via Lighthouse Command Line. Especially since the total score is not displayed in Lighthouse Report. 

Thank you for an reply.

**Comment by patrickhulce** [comment]
There's a PageSpeed insights REST API, but the lighthouse CLI is not a client. You could do some CURL commands though.

```bash
curl 'https://www.googleapis.com/pagespeedonline/v5/runPagespeed?key=<YOUR API KEY GOES HERE>&locale=en_US&url=https%3A%2F%2Fexample.com%2F&strategy=mobile'
```

Could you elaborate on what you mean by "since the total score is not displayed in Lighthouse Report." To what total score are you referring? PageSpeed UI just shows the performance category, so the "total" is just the score of Performance in a regular Lighthouse report.

**Comment by ac-webdesign** [comment]
@patrickhulce 
Ah okay then it's clear. I knew the CURL method, but maybe I thought this would go easier with  Lighthouse. 

Thanks

**Comment by ac-webdesign** [comment]
Ah okay then it's clear. I knew the CURL method, but maybe I thought this would go easier with  Lighthouse. 

Thanks

**Comment by brendankenny** [comment]
Looks resolved :)
