### ISSUE TITLE
Page load doesn't wait for FCP before network quiet

### ISSUE THREAD

**Issue by kusler** [GoogleChrome/lighthouse#6941]
#### Provide the steps to reproduce
For a simple HTML that generates content through JS, both PSI and the audit done through the developer tools states an "error!" instead of metric value - [screenshot](https://screenshot.googleplex.com/D35kVNsPQh0). 

URL: http://hkahkjaswke1.appspot.com/SlowServe?page=jsContent.html

**Comment by patrickhulce** [comment]
This one is also the result of a somewhat intentional decision. To keep runs fast, we only wait 500 ms after network quiet/load/CPU quiet. The page does not paint any content within 500 ms though, and instead they set a timer to render all the content after 3s.

We should probably wait for FCP first before waiting for all the quiets...
