### ISSUE TITLE
Programmatic performance scores are consistently worse than from DevTools

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/lighthouse#6942]
For some URLs, but not others, I'm getting consistently lower performance scores when running Lighthouse programmatically than from Chrome DevTools.

For example:

```
https://marksandspencer.com
Programmatic: 64, 64, 63, 64, 55
DevTools: 86, 73, 84, 77, 80

https://www.littlewoods.com
Programmatic: 46, 48, 50, 50, 49
DevTools: 60, 59, 57, 57, 60

https://asos.com/emporio-armani/emporio-armani-logo-slippers-in-navy/prd/10336705
Programmatic: 10, 8, 10, 9, 8
DevTools: 22, 25, 18, 17, 23
```

By comparison, for many other sites I get quite consistent results: 

```
https://www.houseoffraser.co.uk
Programmatic: 20, 22, 22, 21, 18
DevTools: 20, 24, 23, 21, 21

https://www.johnlewis.com
Programmatic: 55, 58, 54, 58, 57
DevTools: 56, 53, 52, 52, 52
```

For the programmatic audit I'm running the Lighthouse [sample code](https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#using-programmatically) with Node 10.6.0. 

For the DevTools audit I'm using Canary 73.0.3659.0. AFAIK I don't have any extensions installed that could affect Lighthouse.

I'm using a Mac, and I've tried on home wifi (around 30 Mbps) and work wifi (>100 Mbps).

FWIW I've tried headless and non-headless — as expected, that doesn't seem to make any difference.

**Comment by patrickhulce** [comment]
Thanks for filing @samdutton!

Whenever there's a difference between DevTools and node it's usually because in DevTools you've already visited the page (i.e. in order to audit the page you have to navigate to it first). This seems to be the case for these three pages.

1. This URL redirects to the [www site](https://www.marksandspencer.com), the cost of the extra redirect is the difference here. 
2. This page conditionally performs extra logic based on a cookie that's been set if you've visited before. (We clear everything but cookies by default). When changing a programmatic script to visit the URL before auditing, the scores are the same.
3. This URL redirects to the [mobile site](https://m.asos.com/emporio-armani/emporio-armani-logo-slippers-in-navy/prd/10336705), the cost of the extra redirect is the difference here.

**Comment by samdutton** [comment]
Thanks for the quick response @patrickhulce!

1. This makes sense — I've changed the URL and I now get fairly consistent results.

2. I've tried deleting (and not deleting) cookies from DevTools before then running an audit, but I still get consistently higher scores than when running programmatically. When you say you 'clear everything but cookies by default', do you mean when running Lighthouse programmatically? Does selecting **Clear storage** from DevTools clear everything except cookies? 

3. I've tried using the m. URL for both programmatic and DevTools audits, I still get the same consistent difference in results. Do I need to do something else?

**Comment by patrickhulce** [comment]
> I've tried deleting (and not deleting) cookies from DevTools before then running an audit, but I still get consistently higher scores than when running programmatically. When you say you 'clear everything but cookies by default', do you mean when running Lighthouse programmatically? Does selecting Clear storage from DevTools clear everything except cookies?

It's possible they're doing some sort of fingerprinting server-side to reinstall cookies. I might expect this of some sites that try to workaround DNT preferences and whatnot. The data stands though that if you visit the page first, and then revisit it a second time I get different page behavior than if I visit it in a fresh profile. 

From Lighthouse's perspective, it's a good thing that the scores are different because the page is behaving worse for the user in one setting compared to the other.

> I've tried using the m. URL for both programmatic and DevTools audits, I still get the same consistent difference in results. Do I need to do something else?

It's possible you're experiencing some combination of 1 and 2 then. Auditing the mobile site directly resolved the discrepancy on my machine, but there could be other factors at play re: repeat visits.

**Comment by samdutton** [comment]
OK — thanks for the detail @patrickhulce .

**Comment by Hoten** [comment]
Please note that there is currently a bug in the latest stable Chrome DevTools that results in `Clear Storage` never  happening - https://github.com/GoogleChrome/lighthouse/issues/6772

This is fixed in Canary and will be in Chrome 72.

**Comment by patrickhulce** [comment]
Thanks for the reminder @Hoten! I think he was using Canary to start with 👍 

Since this is WAI in Lighthouse, I'm going to go ahead and close, but feel free to chime in with more examples if they don't seem to fall into one of these categories!
