### ISSUE TITLE
FCP discrepancies between DevTools and PSI

### ISSUE THREAD

**Issue by egsweeny** [GoogleChrome/lighthouse#6943]
For a static page (http://hkahkjaswke1.appspot.com/SlowServe?page=SpeedTest1.html), we added a 5-second delay in the server. 

While analyzing it the developer tools, we get a reasonable measurement for FCP - 5.8s ([screenshot](https://screenshot.googleplex.com/uG4S2eRV8hx)). However in PSI, we get a much smaller value - 0.6s ([screenshot](https://screenshot.googleplex.com/UQuH9RK5WoG)). The results we got are consistent. 

This might be due to some caching done in trawler or some other optimization. Regardless of the reason, this might look very confusing for users. I suspect this is one of the reasons for the difference between field and lab data.

**Comment by patrickhulce** [comment]
This is the result of a lantern "feature" (or bug depending on your viewpoint 😄). We're relatively optimistic about server response times. We use the index median of all server response times instead of each request's actual server response time to mitigate some variance between runs. In this extreme case, that optimization fails because there's just two requests: one takes 5s (the main document) and one is nearly instant (the favicon request). Because we pick the faster of two middle values, we come up with only 0.6s seconds.

We could start splitting server response time by resource type which could help with this but would also reintroduce the variance from variable server response times.

**Comment by sions** [comment]
Thanks for the explanation. Just to make sure I understand the existing behavior. The median is computed over all the requests done within the context of a single analysis, right? Or does it look at historical data from previous analysis?

**Comment by patrickhulce** [comment]
> The median is computed over all the requests done within the context of a single analysis, right?

Correct it's all requests from this origin on a single run.

> Or does it look at historical data from previous analysis?

Currently it does not. I've got a proposal in the works that would make this possible, but it'd be a long way off from landing even if it's well received.
