### ISSUE TITLE
Gist api is hitting limit 

### ISSUE THREAD

**Issue by roderickhsiao** [GoogleChrome/lighthouse#6966]
#### Provide the steps to reproduce

https://googlechrome.github.io/lighthouse/viewer/?gist=533366b2f8bfc084d994963023eef4ae

#### What is the current behavior?

Gist API is return 403
```
{
  "message": "API rate limit exceeded for 64.71.162.123. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

#### What is the expected behavior?

Showing lighthouse result

**Comment by patrickhulce** [comment]
Thanks for filing @roderickhsiao! We make GitHub requests client-side though. That error likely means *your* specific IP address has exhausted the rate limit for GitHub, and it's not an issue with the viewer. 

Perhaps your organization has done a lot of unauthenticated GH API activity recently?

**Comment by exterkamp** [comment]
Thanks for filing this! So, @patrickhulce is definitely correct.  It is due to a lot of unauthenticated viewer use from IP's within the same org probably.  Github is experiencing some issues [right now](https://www.githubstatus.com/) but should be unrelated?  But might be resetting api rates?  Because mine is at 0/60 right now for unexplained reasons...

I'm curious why you would be making so much traffic against the viewer, because there is probably a more suitable way to render and view these reports en masse.

**Comment by roderickhsiao** [comment]
Thanks for the reply! Just check the network request its indeed a client side call. We didn't hit the github api at all which is interesting to see the the rate limit reach.

**Comment by brendankenny** [comment]
I *just* got the email notification for opening this issue (~3 hours later) so I think it's very possible it's a github-side issue causing this for you.

**Comment by roderickhsiao** [comment]
Yes, we got high latency of email notification as well

>
