### ISSUE TITLE
Performance Audit attribution from third-party wrapping

### ISSUE THREAD

**Issue by nicjansma** [GoogleChrome/lighthouse#7005]
**Feature request summary**

[We](https://akamai.com) are a [third-party analytics](https://www.akamai.com/us/en/products/web-performance/mpulse-real-user-monitoring.jsp) provider that provides Real User Monitoring (RUM) and other features such as JavaScript Error Tracking through a JavaScript library our customers include on their pages called [Boomerang](https://github.com/akamai/boomerang).

Lately, we've had several customers raise support issues over their concerns that our JavaScript library is causing excessive JavaScript CPU usage, according to Lighthouse/PSI reports.

Here's an example:

![image](https://user-images.githubusercontent.com/1004649/51137113-1a370b80-180c-11e9-8a87-988ec91827ba.png)

Upon investigation, we found that our [Error Tracking plugin](https://akamai.github.io/boomerang/BOOMR.plugins.Errors.html) was causing Lighthouse to be confused about work being done in our customer's app.  The plugin wraps several high-level functions, and the callbacks of, `setTimeout()`, `addEventListener()` and others.  It does this to ensure that the customer's application can get detailed error messages (instead of the generic `Script error.` message) when errors are generated from scripts in other origins.  More details are [here](https://akamai.github.io/boomerang/BOOMR.plugins.Errors.html#toc11__anchor), and other [error tracking](https://docs.trackjs.com/browser-agent/sdk-reference/agent-config/#callbackenabled) libraries do this wrapping as well.

Because Boomerang is wrapping the callbacks in `setTimeout()`/etc, _any_ function in _any_ file that calls `setTimeout()` will be attributed to Boomerang instead, because Boomerang's wrapped callback is at the "bottom" of the stack.  As you can imagine, this accounts for a lot of the JavaScript CPU time on many sites.  The actual work done in the wrapped function is [minimal (but non-zero)](https://github.com/akamai/boomerang/blob/master/plugins/errors.js#L1319), but the time of the _entire_ callback is attributed to Boomerang instead of the "real" work being done.  Our understanding is the "URL" of the _JavaScript boot-up time_ /etc tables are based on the function/URL at the bottom of the stack.

If we were to disable Error Tracking and re-load the same page, we can see the real attribution moves a lot to the Page and other scripts (as well as Boomerang), but the "cost" of Boomerang has decreased from 770ms to 127ms:

![image](https://user-images.githubusercontent.com/1004649/51137239-65e9b500-180c-11e9-87f6-fbdff22f06b8.png)

We were hoping there would be a way to change it so these wrapping functions don't get blamed for the entire callback cost.  One idea would be to have a list of files or functions that could be excluded from "blame" if at the bottom of the stack, similar to [library blackboxing](https://developer.chrome.com/devtools/docs/blackboxing).  

We're not sure if that's feasible though:
* We'd still want the non-wrapping code in Boomerang to be judged based on the work it does, of course.
* We'd like for our customers's Lighthouse/PSI runs to have this exclusion applied without them having to make any changes or configure any lists (can this be built-into Lighthouse?)
* Each of our customers load our third-party library from distinct URLs

The only other alternates we've come up with is better education (explaining the issue to the customer, which we're doing now), or disabling Boomerang's wrapping if Lighthouse is detected (which we'd prefer to not do).

I have a repro page here, which merely does a `setTimeout()` that busy-loops for 2 seconds:

* Boomerang Error Tracking enabled: http://dev.nicj.net/lighthouse-attribution/?errortracking=on

![image](https://user-images.githubusercontent.com/1004649/51137713-37b8a500-180d-11e9-92b4-3e1039a0733e.png)

* Boomerang Error Tracking disabled: http://dev.nicj.net/lighthouse-attribution/?errortracking=off

![image](https://user-images.githubusercontent.com/1004649/51137732-430bd080-180d-11e9-9f89-4fdf6b9d3136.png)

I'm willing to work on this change, if there's agreement on a correct approach.

**What is the motivation or use case for changing this?**

To accurately reflect JavaScript CPU cost when third-party libraries are in the callstack.

**How is this beneficial to Lighthouse?**

More accurate JavaScript CPU attribution.

**Comment by patrickhulce** [comment]
Thanks so much for the detailed information and willingness to work with us @nicjansma !

I agree we should be trying to attribute these costs more accurately in Lighthouse core (and therefore PSI, etc) without needing the user to do any opting-in to a plugin/config/options.

Let's start with where the cost *should* be going and follow up with how we're not quite getting there yet.

There are a couple ways to look at this.

1. We attribute time to each script according to the aggregate selfTime of all its executions. i.e. if we have jQuery on the page, then jQuery would receive the attribution for all the users' calls to `$.whatever`. This is typically what a developer wants to see when working on identifying bottlenecks during a performance deep dive. **However, this is probably not what we want to surface in Lighthouse**. This somewhat presumes that the calls to functions are fixed and we're trying to have the largest overall impact improving things, but we're trying to surface what scripts *instigated* the most work. Let's take a look at number 2.
2. We attribute time to each script according to the aggregate totalTime of all tasks it initiated. i.e. if we have jQuery on the page, then jQuery would receive attribution for its initial installation and any handlers, setTimeouts, or additional work it defers, but *not* for any calls to jQuery functions from other scripts. This is what we're trying to achieve, but you've identified a hole where we are attributing to the first URL that executed in the timeout instead of the URL that scheduled the timeout.

Does that sound right to everyone?

Assuming it does, fixing this is a bit tricky for a first-time contribution.

We will need to bring the same logic we have for tracking timer installations over in `page-dependency-graph.js` and bring it into the way we compute `attributeableURLs` in `main-thread-tasks.js`

https://github.com/GoogleChrome/lighthouse/blob/017574be143532436ff5ac5506a3461d2ddc1dcc/lighthouse-core/computed/page-dependency-graph.js#L204-L215

https://github.com/GoogleChrome/lighthouse/blob/017574be143532436ff5ac5506a3461d2ddc1dcc/lighthouse-core/computed/main-thread-tasks.js#L150-L167

**Comment by nicjansma** [comment]
Totally agree on the above thoughts @patrickhulce and https://github.com/GoogleChrome/lighthouse/pull/7059 looks like a great start.  It looks like that may solve our customer-facing issue (with boomerang on the page), though possibly not the specific repro case above, correct?

Anything I can look into to help?

**Comment by patrickhulce** [comment]
That is correct, #7059 should solve your customer-facing issue 👍

I think it just needs to be reviewed so no further action needed on your part!

**Comment by cheneytsai** [comment]
@nicjansma Is this another example of misattribution to boomerang? 
![Screen Shot 2020-08-27 at 10 26 08 AM](https://user-images.githubusercontent.com/672494/91474941-c0a01b00-e84f-11ea-8bec-f7d2a2832949.png)

Seems abnormally high for a script eval. Tested URL is www.hilton.com/en/

**Comment by patrickhulce** [comment]
@cheneytsai I can't reproduce that behavior on latest Lighthouse. Boomerang is way at the bottom with 188ms

![image](https://user-images.githubusercontent.com/2301202/91477024-66a95080-e863-11ea-8b5b-bd5c7bfdd59b.png)


What version of LH is that?

**Comment by cheneytsai** [comment]
Oops forgot to list. This was LH 6.0.0 as part of Chrome 84.0.4147.135

**Comment by patrickhulce** [comment]
Hm, well it's possible it's been fixed in past couple months I can't observe that behavior on 6.3.0.

**Comment by nicjansma** [comment]
@cheneytsai Yeah I certainly wouldn't expect Boomerang to be anything more than ~200ms in most scenarios.

If you have the trace file, you could share it (or drop me an email nic at nicj dot net) and we can take a look.
