### ISSUE TITLE
Confused about whether Lighthouse provides lab data or field data

### ISSUE THREAD

**Issue by jon-lin** [GoogleChrome/lighthouse#7081]
I was reading Google's docs on ["How To Think About Speed Tools,"](https://developers.google.com/web/fundamentals/performance/speed-tools/) which characterizes Lighthouse and WebPageTest as tools that collect lab data rather than field data. Google's docs [elsewhere](https://developers.google.com/web/fundamentals/performance/navigation-and-resource-timing/) refer to Lighthouse results as "synthetic tests" that don't reflect how the site is performing for "real users in the field."

But when running a Lighthouse audit on nytimes.com, I'm seeing a message regarding my Chrome extensions negatively affecting the page's load performance:
![image](https://user-images.githubusercontent.com/24951135/51634681-e0a88380-1f22-11e9-84af-d288dd2123ef.png)

I'm confused as to how Lighthouse could be said to be collecting lab data if Chrome extensions on my local browser are affecting its performance audit. 

l get that this specific issue has been raised before (https://github.com/GoogleChrome/lighthouse/issues/6644), but I'm hoping someone could clarify to what extent Lighthouse's audits are affected by the local environment in which they're executed. 

Given that Lighthouse is being done inside Chrome devtools, is it just running audits using my own computer and my own Internet connection? Or is it using a computer somewhere out there (like [WebpageTest](https://www.webpagetest.org/) does, where you can pick a Thinkpad in Dulles, VA and a specific connection speed)? When I hear "lab data," I think of the latter, which seems like a much more controlled environment.

**Comment by patrickhulce** [comment]
Thanks for filing @jon-lin!

When we say "lab data" we don't mean that it was necessarily collected in a dedicated lab like WebPageTest. We just distinguish it from "field data" that is collected from all of your *actual* users. The "lab" part in this case is your machine!

The audit is being done on your machine with your Chrome extensions with your internet connection. It's not field data because this is an artificial visit to your page for the express purpose of collecting performance/diagnostic information about it, i.e. it does not come from an actual user.

Does this help clarify things?

**Comment by jon-lin** [comment]
Yes, thanks for the thorough response! Much appreciated.
