### ISSUE TITLE
Move viewport audit logic to computed artifact

### ISSUE THREAD

**Issue by mattzeunert** [GoogleChrome/lighthouse#7084]
Tap targets and font size audit currently call the viewport audit, and we don't like audits calling each other.

https://github.com/GoogleChrome/lighthouse/pull/5846#discussion_r250334020

**Comment by brendankenny** [comment]
We should maybe expose some sort of `notApplicable` in the result from that computed artifact if the test was done with a desktop form factor. Since this will be at least three audits using it, we may not want to replicate it in each one, but it might also be overkill.

See #6687 and https://github.com/GoogleChrome/lighthouse/pull/5846#discussion_r250335779

@patrickhulce were you just talking about form factor information on the audit `context`? Or was that fixes for the report `Runtime settings` I'm mixing up with this?

**Comment by patrickhulce** [comment]
> @patrickhulce were you just talking about form factor information on the audit context? Or was that fixes for the report Runtime settings I'm mixing up with this?

Yep I just filed #7043 that's very similar to this concern. Separately, I also want to fix runtime settings that I'm fairly vocal about in chat but I haven't collected my thoughts enough into an issue yet haha :)

**Comment by chrisandflora** [comment]
> Tap targets and font size audit currently call the viewport audit, and we don't like audits calling each other.
> 
> [#5846 (comment)](https://github.com/GoogleChrome/lighthouse/pull/5846#discussion_r250334020)

This is really Awesome..

**Comment by mattzeunert** [comment]
Should we create a `viewportMeta` computed artifact for this, which basically does the logic of the viewport audit and exposes the results?

@patrickhulce https://github.com/GoogleChrome/lighthouse/issues/7043 is just similar but wouldn't actually share code, right?

**Comment by patrickhulce** [comment]
Yeah @mattzeunert I don't think they would end up sharing code, just related 👍
