### ISSUE TITLE
Discrepancy between Lighthouse and Axe contrast ratio reports

### ISSUE THREAD

**Issue by jonoliver** [GoogleChrome/lighthouse#7121]
Lighthouse does not appear to catch color ratio failures when the fg/bg colors are the same or similar. These failures are caught by the Axe extension for Chrome.

#### Steps to reproduce
1. Run LH on https://jonoliver.codes/axe-vs-lighthouse/
1. Run Axe on https://jonoliver.codes/axe-vs-lighthouse/

#### What is the current behavior?
- Axe displays color ratio failures for 3 elements: `.fails-lighthouse`, `.does-not-fail-lighthouse`, `.also-does-not-fail-lighthouse`
- Lighthouse only displays failure for 1 element: `.fails-lighthouse`

 Please note: 
- `.does-not-fail-lighthouse` element has the same fg and bg color (`red`)
- `.also-does-not-fail-lighthouse` has slightly different fg/bg colors:
  -  bg: `#ff0000`, fg: `#ff0011`

#### What is the expected behavior?
Lighthouse should display the same failures as Axe

#### Environment Information
* Affected Channels: Node,  DevTools 
* Lighthouse version: v4.1.0 in Node, v3.2.0 in DevTools
* Node.js version: v10.4.0
* Operating System: macOS 10.13.6
* Chrome Axe extension version: v3.7.0 (axe-core 3.1.2)

**Comment by patrickhulce** [comment]
Thanks for filing @jonoliver and for the simple test! 

When I add axe 3.1.2 directly to the page from a CDN, I get the same result as Lighthouse.

It's worth noting that the extension caveats its result.

![image](https://user-images.githubusercontent.com/2301202/52010655-ac414400-249b-11e9-8ded-b33bfbc04a85.png)

Lighthouse is only interested in the explicit `violations` from axe and these elements don't make the cut for violations (presumably because it's a technique to make text invisible if it's exactly the same?). If and when axe reclassifies these as violations, Lighthouse should pick this up automatically.

**Comment by jonoliver** [comment]
@patrickhulce Thanks for the explanation! That makes sense, I'll close the issue.
