### ISSUE TITLE
pagespeed lighthouse loads uncompressed content

### ISSUE THREAD

**Issue by eugenem** [GoogleChrome/lighthouse#7138]
Something happened to pagespeed today at morning. My site had rating 20/60 and it dropped to 5/40. I see complaints about huge content size that all text content (scripts, css, etc.) reports uncompressed size.  Even facebook and google scripts show the same huge sizes. I've checked another site of mine and it also dropped to 5/26 with the same complaints.

I've checked that compression is enabled at my local chrome and firefox. Also, local lighthouse shows mobile rating 40 and doesn't complain about huge sizes. And at morning pagespeed also didn't complain about huge script sizes too.

You can check these sites for example:
https://web3d.co.il/
https://blog.nli.org.il/

**Comment by patrickhulce** [comment]
Thanks for filing @eugenem! I don't see the same uncompressed assets issue you're referring to. I see lots of unused CSS (400-600kb) though on each page blocking first paint, so that's probably responsible for a decent score drop if that wasn't there before.

![image](https://user-images.githubusercontent.com/2301202/52169769-6ab2d200-2703-11e9-8e66-ba9698bcee9b.png)

**Comment by eugenem** [comment]
at 'Avoid enormous network payloads' section I've got:

…1/9d72fcd….css(web3d.co.il) | 635.9 KB

which is minified CSS. But if you look at the local audit, you will see:

…1/9d72fcd….css(web3d.co.il) | 122.3 KB

And I'm pretty sure that yesterday PageSpeed was showing the same 120K

**Comment by paulirish** [comment]
Aye. The thread @peixotorms linked is the canonical issue thread.

And this is now all resolved: https://groups.google.com/d/msg/pagespeed-insights-discuss/by9-TbqdlBM/AoAh70JBGgAJ

sorry and thx!
