### ISSUE TITLE
Showing changes in manifest in pwa app but lighthouse saying no manifest detected.

### ISSUE THREAD

**Issue by amitgandole** [GoogleChrome/lighthouse#7142]
I have my website in AWS and there everything creating dynamically. Somehow I tried pwabuilder.com for manifest and SW. Now whatever I change in my manifest its showing in my PWA app. Like change in name and logos and all that. But lighthouse saying there in no manifest. and due to that 4 errors are showing and also pop up not appearing.

**Comment by patrickhulce** [comment]
Do you have a URL for this site?

**Comment by amitgandole** [comment]
Hi,

Yes. Url is : https://www.microsidd.com/en/

 and I have put my manifest in root. Url for manifest : https://Microsidd.com/manifest.json
(I provided reference of the manifest through headers not from this url. I provided this url only for reference)

**Comment by exterkamp** [comment]
Looking in the devtools Application panel I'm not seeing a manifest?
![image](https://user-images.githubusercontent.com/6392995/52309636-9d540900-2955-11e9-90a9-262b665da6a7.png)

Is the manifest loading normally without Lighthouse?  Because if it isn't found for that panel it will never show up in Lighthouse afaik.

**Comment by amitgandole** [comment]
Yes manifest is loading normally. I also saw this but if i change app name in manifest it reflects in original name also. But lighthouse not fetching an manifest. I dont know why? Manifest is working as normal.

**Comment by exterkamp** [comment]
I might be missing something, how exactly is the manifest setup?  Is there a `<link rel="manifest">` tag in the head to the json file? I'm not seeing any manifest referenced anywhere in the page, or loaded in the network records, which is why Chrome & Lighthouse can't find it.  Is it setup differently?

Are you saying that your browser _can_ find the manifest, and lighthouse can't, or that Chrome also can't find it?  If Chrome can't find it I suggest hosting it statically and adding a `<link>` to it in the header so Chrome can find it.

**Comment by brendankenny** [comment]
Closing since it's been a while without an update. If it's still an issue, please comment and we can reopen.

**Comment by connorjclark** [comment]
@dev-digipopo open a new issue with the form filled out.
