### ISSUE TITLE
document how much each item contributes to the PWA score

### ISSUE THREAD

**Issue by mstorus** [GoogleChrome/lighthouse#725]
I have a goal to improve my site's Progressive Web App score in Lighthouse to a certain number. But I can't tell how much each item in the report contributes to the overall PWA score.

As an enhancement, I would like to see each item in the PWA report have a description of how much its score contributes to the overall score. Or each item could show what its maximum score is, or the algorithm it uses to compute its score.
Alternatively, there could be a documentation page that explains the scoring of each component of the report.

**Comment by addyosmani** [comment]
Everything currently in Lighthouse currently has an equal weighting (this is because we haven't been sure what the weighting should be for a lot of items just yet). @paulirish could probably confirm if this is still the case. 

My _personal_ opinion is I like the approach of considering offline/network resilience just as important as having good perf, a proper manifest etc setup. Although LH currently highlights an overall numeric score, I could imagine (maybe as part of https://github.com/GoogleChrome/lighthouse/issues/746) the project moving more towards just saying "you are a PWA", "you are a gold-star PWA" etc.

**Comment by mstorus** [comment]
Hi @addyosmani ,
It's not clear to me from the UI, however, what some of the individual scores mean.
For example:

![lighthouse report_ http___www cnn com_](https://cloud.githubusercontent.com/assets/1182738/19142182/9446c186-8b69-11e6-9790-a09d050dd1d3.jpg)

what do the green numbers mean here? Does it mean 20% and 44% respectively of the max score for each component?

It would be good to show what those numbers mean with respect to the overall score.

**Comment by ebidel** [comment]
+1 explaining what all numbers mean.

**Comment by addyosmani** [comment]
Oh gotcha. Agree in that case that it would be good to explain what those mean. My understanding is that its a score out of a max of a hundred. @brendankenny might know for sure.

**Comment by paulirish** [comment]
We have scoring docs now!


https://github.com/GoogleChrome/lighthouse/blob/master/docs/scoring.md
https://developers.google.com/web/tools/lighthouse/scoring
