### ISSUE TITLE
Results may not display properly warning

### ISSUE THREAD

**Issue by zenythgroup** [GoogleChrome/lighthouse#7250]
Warning: Results may not display properly. Report was created with an earlier version of Lighthouse (3.2.0). The latest version is 4.1.0.

**Comment by exterkamp** [comment]
Hi, can you describe more of what is going wrong for you?

I assume you are viewing a report made by the DevTools audit panel which is in version 3.2.0 and then loading it into the viewer and getting a message like this:
![image](https://user-images.githubusercontent.com/6392995/52829489-dc830800-3081-11e9-84ce-4747c0d57283.png)

Which is WAI, since DevTools on production Chrome is using version 3.2.0; in order to use the latest Lighthouse version (4.1.0) you can use the CLI, web.dev, psi, or Chrome canary for a more-latest than 3.2.0 version.

**Comment by zenythgroup** [comment]
Hi! Thanks for the quick response. Correct, I'm generating a report made by the DevTools audit panel, loading the json file into https://googlechrome.github.io/lighthouse/viewer/.
I've installed Chrome Canary now and get following:
Warning: Results may not display properly. Report was created with an earlier version of Lighthouse (4.0.0). The latest version is 4.1.0.

**Comment by exterkamp** [comment]
Right, this is expected.  DevTools runs 3.2.0 in production and Canary runs 4.0.0, neither of which are the bleeding edge of 4.1.0.  In order to generate 4.1.0 results you need to run the CLI or web.dev or PSI.  But if you want the most up to date results the CLI is the best option.

While the warning on the renderer might be worded strongly, there is nothing wrong, simply that the lighthouse version that made the report was not the latest possible version.

If you want to look at reports without that warning appearing, you can run 4.1.0 on the CLI which will generate an `html` report automatically, or [web.dev](https://web.dev/) also renders reports that you can view or download.  Hope that helps!

**Comment by zenythgroup** [comment]
That's great, thank you. Yes, web.dev solves the issue.
I really appreciate your help!
