### ISSUE TITLE
How to understand this configuration “--emulated-form-factor” and "--disable-storage-reset"

### ISSUE THREAD

**Issue by chaihongjun** [GoogleChrome/lighthouse#7261]
**Summary**
hi~
I don't know the parametric meaning of this configuration item  :--emulated-form-factor=desktop|mobile|none
desktop ,Is it suitable for desktop websites?
mobile, for  mobile website?
and what does this "none" mean here?
____________________________________________

the "--disable-storage-reset" means lighthouse will not clear all the local storage before it run
and if i dont add this parameter to the CLi,it will clear all the local storage ,
otherwise it will retain caches that were previously accessed。
Is this correct?
Thanks！！！

**Comment by patrickhulce** [comment]
> --emulated-form-factor=desktop|mobile|none

This is what type of device should Chrome declare itself to be through the user agent and screen resolution. None means it will use whatever local Chrome will default to on your machine.

> if i dont add this parameter to the CLi,it will clear all the local storage ,
otherwise it will retain caches that were previously accessed。

Correct. Note that by default a fresh Chrome instance is used and so this doesn't really have any effect. It only applies if you are setting up Chrome before you run Lighthouse.

**Comment by chaihongjun** [comment]
@patrickhulce thank u ，it has solved my question
