### ISSUE TITLE
Documentation on website doesn't seem to be udpated to v4

### ISSUE THREAD

**Issue by molant** [GoogleChrome/lighthouse#7282]
Lighthouse is currently on v4 but the documentation seemt to talk about v3 ([Lighthouse v3 scoring guide](https://developers.google.com/web/tools/lighthouse/v3/scoring)). Also there are a few audits that have been disabled in the latest version but are still listed in the website. These are the ones I know of but there might be more:

https://developers.google.com/web/tools/lighthouse/audits/date-now
https://developers.google.com/web/tools/lighthouse/audits/console-time
https://developers.google.com/web/tools/lighthouse/audits/mutation-events
https://developers.google.com/web/tools/lighthouse/audits/old-flexbox

**Comment by antross** [comment]
Here are the PRs those were disabled/removed in:
* [Avoids Date.now() in its own scripts](https://developers.google.com/web/tools/lighthouse/audits/date-now) (removed in PR #2160)
* [Avoids console.time() in its own scripts](https://developers.google.com/web/tools/lighthouse/audits/console-time) (removed in PR #2160)
* [Avoids Mutation Events in its own scripts](https://developers.google.com/web/tools/lighthouse/audits/mutation-events) (removed in PR #5509)
* [Avoids old CSS flexbox](https://developers.google.com/web/tools/lighthouse/audits/old-flexbox) (commented out in PR #2153; haven't found when it was removed)

I assume these were probably meant to be marked in the documentation as deprecated since that's what was done for [the WebSQL audit documentation](https://developers.google.com/web/tools/lighthouse/audits/web-sql) when it was removed.

**Comment by Hoten** [comment]
@kaycebasques could we deprecate these?

@patrickhulce for https://github.com/GoogleChrome/lighthouse/pull/2153 it seems like you wanted to do some followup, but I didn't find any discussion on it after this PR. Think we could bring back the checks that this PR removed?

**Comment by patrickhulce** [comment]
@Hoten are you referring to old flexbox? I'm not sure we *want* to bring that back 😆

**Comment by Hoten** [comment]
I meant the checks (against) using old flexbox

**Comment by patrickhulce** [comment]
Yeah I'm not sure that audit is really in line with the direction LH has taken over the past 2 years and certainly couldn't pass our new audit guidelines today. If you feel strongly about old flexbox though, by all means I would seriously love to read the questionnaire responses for someone making the case! :D

**Comment by Hoten** [comment]
\~insert fry idc meme\~

let's keep it dead then.

**Comment by brendankenny** [comment]
@mfriesenhahn is starting to take this over with #9084
