### ISSUE TITLE
Document DEVTOOLS_RTT_ADJUSTMENT_FACTOR and DEVTOOLS_THROUGHPUT_ADJUSTMENT_FACTOR

### ISSUE THREAD

**Issue by tollmanz** [GoogleChrome/lighthouse#7330]
I am working on a Lighthouse integration and am trying to implement custom "profiles" that allow a user to set `requestLatencyMs`, `downloadThroughputKbps`, and `uploadThroughputKbps`. In the preset `mobileSlow4G` and `mobileRegluar3G` conditions, the values are augmented by `DEVTOOLS_RTT_ADJUSTMENT_FACTOR` or `DEVTOOLS_THROUGHPUT_ADJUSTMENT_FACTOR`. 

I'm trying to understand why these values are used and how to apply similar values to custom profiles. The comment for the constants point to a [Chromium ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=721112) that states:

> Concerns have been raised about the accuracy of DevTools network throttling presets. After conducting an analysis, I determined that the existing network throttling presets are too optimistic and don't realistically show how slow websites load on mobile connections.

I assume that this means that an adjustment factor is added to the down/upload speeds and RRT timings to better estimate real world timings.

I have a few questions and should there be an answer to them, I think should be documented:

1. How were these numbers chosen (`DEVTOOLS_RTT_ADJUSTMENT_FACTOR = 3.75` and  `DEVTOOLS_THROUGHPUT_ADJUSTMENT_FACTOR = 0.9`)?
1. Why are the adjustment factors the same for Slow 4G and Regular 3G, when the factors used in [Chromium](https://chromium.googlesource.com/chromium/src.git/+/8a4e4200086bc67a61c83d60edfb450844377e5a%5E%21/) and [DevTools](https://github.com/ChromeDevTools/devtools-frontend/blob/ecf32a28e6156b8a2c9dc025faa9315ec8652e6a/front_end/sdk/NetworkManager.js#L247-L259) are different depending on the target profile (e.g., the RTT adjustment factor is `5` for the slow 3G condition in Chromium and DevTools)? I do understand that the profiles are different in Chromium and DevTools, but I'm still curious why those projects tailor the adjustment factors to the different profiles.
1. If I wanted to create another profile, perhaps based on WPT profiles, should I add adjustment factors? For instance, if I wanted to emulate WPT Cable conditions in Lighthouse, which uses 5/1 MBPS and 28ms RTT, would I apply an adjustment factor to it?

I should also mention that all of this is assuming the use of the `devtools` throttling method.

Thanks for hearing me out. I've tried to piece together the history of how these numbers came to be, but some information seems to be missing. I'd really appreciate it if you can help me out.

**Comment by patrickhulce** [comment]
Good questions! This was documented but the docs weren't public until 5 minutes ago :) (see #7332)

1. This [google doc](https://docs.google.com/document/d/10lfVdS1iDWCRKQXPfbxEn4Or99D64mvNlugP1AQuFlE/edit) details the research behind coming up with the multipliers.
2. Lighthouse only has a single throttling profile which is identical to "Fast 3G" in DevTools. If you're going off the beaten path, it's mostly up to the developer (though if you're going off the beaten path I'd highly recommend against using DevTools throttling and go with a packet level solution instead, see [our throttling doc](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md) for more)
3. If you're using DevTools throttling, yes. It works at the HTTP layer instead of the TCP layer and so the RTT is not what nearly all other tools use to refer to RTT. ~4-5x is usually appropriate. That being said, again, I'd highly recommend using a packet-level throttling solution instead of devtools. At the lower RTTs it will devolve into a NOOP given its inability to differentiate server latency from connection latency.

**Comment by tollmanz** [comment]
> Good questions! This was documented but the docs weren't public until 5 minutes ago :) (see #7332)

Wow...thanks for the fast response. Glad to see "chenwilliam" listed as author as it seemed from the bug that he did some of this work. 

> 2\. Lighthouse only has a single throttling profile which is identical to "Fast 3G" in DevTools

True. I conflated the fact that you have `mobileSlow4G` and `mobileRegluar3G` defined, but only one is used to configure a Lighthouse run.

> 3\. That being said, again, I'd highly recommend using a packet-level throttling solution instead of devtools.

Fair...I've seen this advice elsewhere and I should probably heed it.

Thanks again!
