### ISSUE TITLE
TTI based on FMP or FCP?

### ISSUE THREAD

**Issue by pmeenan** [GoogleChrome/lighthouse#7412]
The [WICG docs](https://github.com/WICG/time-to-interactive#definition) use FMP as the basis for TTI but the dev web [docs for lighthouse](https://developers.google.com/web/tools/lighthouse/audits/time-to-interactive) mention FCP as the basis (and then link to the WICG docs).

WebPageTEst [currently uses FCP](https://github.com/WPO-Foundation/webpagetest/blob/master/www/page_data.inc#L269) as the baseline since it is consistently available but it would be good to have all the implementations and docs aligned.

**Comment by patrickhulce** [comment]
Oh I didn't realize the docs are still quoting FMP, I thought we had all moved on to FCP! 😆 It looks like that repo is archived too, we should probably update the dev web docs to point to a better place...

Lighthouse uses FCP as its floor.

https://github.com/GoogleChrome/lighthouse/blob/268441e66f551883c6e8956c533debb80520b0ca/lighthouse-core/computed/metrics/interactive.js#L173-L179

In the simulated world, we're still using FMP in our fancy optimistic/pessimistic prediction model because it was slightly more accurate to real world FCP-TTI, but there isn't a difference in most cases.

**Comment by exterkamp** [comment]
The modern web.dev TTI docs do not reference the WICG "spec".
