### ISSUE TITLE
Heading Tags For HTML Report

### ISSUE THREAD

**Issue by jhomme** [GoogleChrome/lighthouse#7575]
Hi,
To make it easier for screen reader users to view the HTML report, would it be possible to make the bold section headers use heading mark-up, as in <h?> tags? I found this when using Lighthouse from the command line as a Node module. If this is user error on my part, I apologize. I'm just learning JavaScript and am dangerous to myself right now. :)

**Comment by johnemau** [comment]
+1 
Making the report gauges headings would allow screen reader users to easily navigate between the headings directly.

Here is a screenshot of an empty heading list provided by the NVDA screen reader Element List feature which would otherwise be used to jump between headings.

![gauge-should-be-h2](https://user-images.githubusercontent.com/309310/61573866-9126b880-aa6a-11e9-85c1-fc8aec40cebe.PNG)

**Comment by brendankenny** [comment]
User names are very close here, I thought at first you were +1ing yourself :)

Closed in #9422
