### ISSUE TITLE
TTFB Difference in Google page insight

### ISSUE THREAD

**Issue by mukeshbaba** [GoogleChrome/lighthouse#7805]
Hello My name is mukesh kumar, my website name is https://www.eklavyaoverseas.com/mbbs-in-russia/ when i check my website on Lighthouse scores are 100 in Performance , there is no error for TTFB. But when i check my results in Google page insight it shows different results , score is less also it shows an error of 1 second for TTFB, Please help me in Resolving this issue, i am using a indian based VPS server and running results in India.

**Comment by mukeshbaba** [comment]
![Screen Shot 2019-03-29 at 8 09 05 PM](https://user-images.githubusercontent.com/49070256/55240352-c068ae00-525e-11e9-81fe-56aa4d19ad45.png)
![Screen Shot 2019-03-29 at 8 09 25 PM](https://user-images.githubusercontent.com/49070256/55240371-cc547000-525e-11e9-91e3-bb2d81c352ea.png)
![Screen Shot 2019-03-29 at 8 10 05 PM](https://user-images.githubusercontent.com/49070256/55240392-d37b7e00-525e-11e9-8eb5-bc14be1e6b8c.png)
![Screen Shot 2019-03-29 at 8 10 17 PM](https://user-images.githubusercontent.com/49070256/55240404-d7a79b80-525e-11e9-8b98-4e55c7368c62.png)

**Comment by exterkamp** [comment]
Hi!

Thanks for filing!  Our infrastructure is introducing some latency for APAC users, and we are working on fixing that.

In the meantime though, local testing and PSI scores will always be slightly different, however such a large difference in TTFB is most likely an underlying infrastructure problem.  If your website is meant for a global audience, then I'd recommend distributing it to more locales in order to ensure a more consistent TTFB worldwide.  If it is meant to be local only then ignore that, and we are trying to improve APAC latency, so stay tuned.

**Comment by exterkamp** [comment]
Over the past months we have been upgrading our infrastructure [as announced in the v5 PSI update](https://docs.google.com/document/d/11hXs4zZXxGdxRFYueWh1JDh45wiSzMc9TQ9z6NVqB0g/preview), and this should have been improved.  I'd love to know if this has been improved for you.  lmk.
