### ISSUE TITLE
Cache contains start_url from manifest not passing

### ISSUE THREAD

**Issue by jasan-s** [GoogleChrome/lighthouse#783]
I'm using SWprecache and  have my "start_url": "/".  how do I pass this requirement? Is it because  I'm not caching my index.html in swprecache ?

**Comment by addyosmani** [comment]
We've disabled the start_url from manifest check from appearing in reports as of https://github.com/GoogleChrome/lighthouse/pull/766. It's currently a little flaky. 

The idea behind the test is if users are launching an app from the homescreen, the start_url contents should be in the (SW) Cache Storage API.

**Comment by brendankenny** [comment]
@jasan-s it could be, but it's possible it's a Lighthouse bug. The current implementation (which isn't in the default report because of said bug) does not handle URL rewriting, so it's possible that your page start_url is in the cache but Lighthouse isn't finding it.

I'm going to close this issue in favor of the older #566
