### ISSUE TITLE
Feature request: support gatherers in plugin

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/lighthouse#7882]
**Feature request summary**
The plugin supports custom audits, but AFAICT not custom gatherers. It would be great if we were able to append gatherers in the same way as audits.

**What is the motivation or use case for changing this?**
I have a plugin that requires artifacts not currently captured by the existing gatherers. Specifically pulling the contents of scripts that have non-standard types, e.g. `<script type="foo" src="bar.something">` since these won't get requested or parsed and I need their contents.

**How is this beneficial to Lighthouse?**
Moar powerful for plugin makers 👍

**Comment by patrickhulce** [comment]
Heya Paul :)

It was an intentional decision to keep plugins from getting involved in gathering, but I'm struggling to find the document with the discussion since #6070 is *quite* sparse. IIRC, it essentially boiled down to security/privacy concerns, along with the fact that gathering can be significantly more difficult to do correctly than auditing and we'd probably want to be involved if there's an important fact about the page we don't have right now.

For your use case, it seems reasonable for us to collect the URLs and types of all the script elements  on the page even if we don't request the content of ones that weren't loaded. The plugin audit could still fetch the ones that are missing even if it violates the purity of a gather and audit step :)

**Comment by paullewis** [comment]
Yeah, that could work! Since it's a non-core plugin I can theoretically fetch the file in the audit. A little gross, but not the worst thing either. I can totally see why you'd be cautious of adding gatherers to plugins more generally.

Okay, so let's say the Scripts artifact. It currently only returns inline scripts or those that have triggered a network request, and my particular one won't do either, as you rightly noted. If we reduce this request to including non-fetched scripts as well, does that seem reasonable to you?

**Comment by brendankenny** [comment]
Going to close this issue. The tension between limited/simple plugins vs capable/harder-to-support plugins is still there, but we can focus on specific requests and don't need an umbrella tracking issue. For now we still recommend not using plugins if a custom gatherer is needed and to either request the gatherer in core or use a custom config where you can add new gatherers all day.

Maintainably extending Lighthouse is still a wide-open area, so anyone coming across this old issue, please feel free to open new requests.
