### ISSUE TITLE
CSV output does not print to stdout by default

### ISSUE THREAD

**Issue by rajivsingha** [GoogleChrome/lighthouse#8330]
When I use the options --output=json in Lighthouse the JSON is simply output on the command line. A file is not produced.

The documentations suggests it should work though.

**Comment by patrickhulce** [comment]
This is the intended behavior for easier programmatic usage. The docs of the CLI clarify this a bit more.

![image](https://user-images.githubusercontent.com/2301202/56231141-5e23f180-6043-11e9-96d7-12bfbaee2835.png)

If you want it to output to a file you can use `--output-path`, request multiple output types, or pipe stdout to a file.


Would you mind linking to us the documentation that suggests it will output to a file so we can update it?

**Comment by rajivsingha** [comment]
Thank you for the quick response.

My apologies, I assumed all 3 options were equal. If the default for CSV and JSON both is stdout,why does adding --output CSV produces a CSV file.

Sorry if my question is silyl.

**Comment by patrickhulce** [comment]
Oh not silly! *That* would be a bug thanks for raising!

**Comment by exterkamp** [comment]
Just to throw my 2 cents in.  Why does it go to stdout by default?  Why not make a file? When I use `--json` I really want a file, not stdout, esp. since the report is too long to copy now I have to pipe it to a file anyway.

**Comment by patrickhulce** [comment]
The original rationale is that it makes sense to put programmatic things on stdout to do with whatever you like and the only reason HTML isn't stdout by default was because it just makes no sense to try to programmatically consume it. 

We don't eliminate any functionality by making it all file by default though since someone can always `--output-path=stdout` so I'm open to nuking `stdout` default 🤷‍♂️

**Comment by brendankenny** [comment]
yeah, I think `--output-path` came second and LH originally saved to file or printed to stdout just based on `--output`. I believe we discussed making everything write to file by default regardless of output format at some point (maybe when we added `--output-path`? or were changing something related), but it seemed good to still print to stdout for piping so we kept this slightly awkward thing.

I think the argument was that when using LH as a CLI tool it should act like a CLI tool...but that was back when `--output=json` was the default. When we switched to html as the default (which is saved to file), it meant you had to add at least one flag to get LH to print to `stdout`, so that argument doesn't really apply that well anymore.

I'd also be fine with changing it since we have the `--output-path=stdout` escape hatch, the question is how many existing CI/monitoring pipelines will we be breaking in the process, making people have to look up how to print to `stdout` for the benefit of simplifying a thing we basically never get questions about (this one excluded :). It is going to be a major version bump, but is it worth it?

**Comment by brendankenny** [comment]
(re: CSV, though, we should definitely change either the readme to match reality or reality to match the readme)

**Comment by patrickhulce** [comment]
> but that was back when --output=json was the default

Or even when `pretty` was the default 😄

**Comment by brendankenny** [comment]
> Or even when `pretty` was the default 😄

so pretty!

![Screen Shot 2016-09-28 at 15 26 35](https://user-images.githubusercontent.com/316891/56249852-2b3d2600-6062-11e9-8593-ff99f14fcd7e.png)

**Comment by patrickhulce** [comment]
I don't think we reached a final conclusion but it'd be nice to get whatever we decide in for 5.0.


**Options**

1. Fix the help text to say JSON is the only one that defaults to `stdout`, no functionality change.
2. Fix the CSV default output to `stdout`, make the functionality do what we currently says it does.
3. Change the default output of JSON to a file to match the others and update the docs accordingly, fairly significant breaking change for everyone using the CLI for JSON output.


I think I vote number 1 since this has so rarely come up and breaking doesn't seem worth it.

**Comment by Hoten** [comment]
option 3 would mark a descent into madness
