### ISSUE TITLE
Word Fix

### ISSUE THREAD

**Issue by CurryWaffel** [GoogleChrome/lighthouse#8418]
When Audit is openened first time (to me) in DevTools, before clicking 'Run Audit' you can select the device it will test for. If you hover over the both different options, the same Text is shown. Minor fix, maybe a little confusing to unexpierienced Users

![image](https://user-images.githubusercontent.com/46422198/56388017-3a6cd100-6226-11e9-8fd6-0e5936dc7926.png)

![image](https://user-images.githubusercontent.com/46422198/56388053-4f496480-6226-11e9-9e52-f267f29edd90.png)

**Comment by patrickhulce** [comment]
Thanks for filing @CurryWaffel! This has been brought up before, and we're sorry it's confusing, but the tooltip is on the entire fieldset (which includes all options) rather than each individual radio option.

As a whole they decide whether to apply mobile emulation during auditing.

I can't remember @Hoten is there a matching UI refresh for devtools UI coming with the new report?

**Comment by Hoten** [comment]
I don't believe so.

**Comment by CurryWaffel** [comment]
Ok thanks for the reply, i just wasnt shure if that is a little mistake that happens or intended.
