### ISSUE TITLE
Can't install lighthouse

### ISSUE THREAD

**Issue by wwwillchen** [GoogleChrome/lighthouse#854]
I'm using node v6.9 and npm v3 and I get an error when installing lighthouse (`npm install -g GoogleChrome/lighthouse`). I'm using a Mac.

I noticed that I can't even cd into `/Users/wchen/.nvm/versions/node/v6.9.1/lib/node_modules/lighthouse` after the installation fails.

```
/Users/wchen/.nvm/versions/node/v6.9.1/lib/node_modul/Users/wchen/.nvm/versions/node/v6.9.1/bin/chrome-debug -> /Users/wchen/.nvm/versions/node/v6.9.1/lib/node_modules/lighthouse/lighthouse-core/scripts/launch-chrome.sh
npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/wchen/.nvm/versions/node/v6.9.1/bin/node" "/Users/wchen/.nvm/versions/node/v6.9.1/bin/npm" "install" "-g" "GoogleChrome/lighthouse"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! path /Users/wchen/.nvm/versions/node/v6.9.1/lib/node_modules/lighthouse/lighthouse-cli/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/wchen/.nvm/versions/node/v6.9.1/lib/node_modules/lighthouse/lighthouse-cli/index.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/wchen/.nvm/versions/node/v6.9.1/lib/node_modules/lighthouse/lighthouse-cli/index.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wchen/npm-debug.log
```

**Comment by brendankenny** [comment]
> npm ERR! path /Users/wchen/.nvm/versions/node/v6.9.1/lib/node_modules/lighthouse/lighthouse-cli/index.js

I assume this is the issue before `tsc` runs?

`npm install -g lighthouse` should still work, but @samccone is there a typical way of handling this for users who want to `npm install` from master?

**Comment by wardpeet** [comment]
You can only install lighthouse trough npm using `npm install -g lighthouse` instead of 'GoogleChrome/lighthouse'

**Comment by samccone** [comment]
The typical pattern that most repos follow is to have instructions for local dev (as we do):
https://github.com/GoogleChrome/lighthouse#develop

I have a branch locally though to improve this and to raise a meaningful error.

**Comment by brendankenny** [comment]
> The typical pattern that most repos follow is to have instructions for local dev (as we do):
https://github.com/GoogleChrome/lighthouse#develop

I meant not for local dev but if you want to use npm to install Lighthouse as a dependency but want to track master instead of our releases. This can be handy if tracking a branch, as well; I was doing that with smokehouse for a while before it landed directly in LH.

I *was* going to say that `npm install` fails with an error because we attempt to link `lighthouse` to a file that doesn't exist on install (`lighthouse-cli/index.js`), but `index.js` does exist in master, so not sure what's going on here. I can replicate the same issue with and without the global install (just doing `npm install GoogleChrome/lighthouse` wherever I might want that dep is sufficient to see the error).
