### ISSUE TITLE
Lighthouse page on load not in sync with Window onload

### ISSUE THREAD

**Issue by prithveesh** [GoogleChrome/lighthouse#8698]
I am evaluating the performance of my Website - www.makemytrip.com.

In performance evaluation there is a component - "CosmosContainer", which I am loading after window.onload, but in lighthouse report in 'Opportunities to improve page load' section , its showing images which are loaded in CosmosContainer component. 
Although Page Load in chrome dev tools is showing up correctly. Load time is less 1 sec and CosmosContainer is getting loaded after Load Event. As you can see in the screenshot below.

<img width="1659" alt="Screenshot 2019-04-29 at 11 08 26 AM" src="https://user-images.githubusercontent.com/12379746/56878131-0f794d00-6a70-11e9-9d09-f1a52dfe08de.png">
 
Lighthouse report:
<img width="1602" alt="Screenshot 2019-04-29 at 11 15 45 AM" src="https://user-images.githubusercontent.com/12379746/56878157-35065680-6a70-11e9-9405-4b111aa5fffb.png">

Can you please help with this, as why lighthouse is considering components which are loaded after onload and degrading the overall performance.

**Comment by patrickhulce** [comment]
Thanks for filing @prithveesh!

While it's good you are deferring the images until the `load` event has fired, `onload` does not really represent the end of page load. We report savings on images if they were loaded while your page still had plenty of Javascript left to execute.

(side note, those images could really be JPEGs to vastly reduce their impact and you don't even need to mess with WebP)

**Comment by prithveesh** [comment]
@patrickhulce Thank you for explaining the same. 

If the load event which lighthouse considers is not same as Page Load, is there any way to mitigate that. 
My problem is, as I want to improve the performance for the page, which is already improved also in terms of first load and user interaction, but the same is not captured by the lighthouse report.

Is there anyway where this can be fixed?

**Comment by patrickhulce** [comment]
Sorry @prithveesh, but I'm not sure what you're asking to be fixed. 

Those image re-encoding are legitimate performance opportunities to improve the user experience. They are being loaded while other scripts are still being loaded and could be much smaller than they are now.

**Comment by brendankenny** [comment]
Closing since there hasn't been any movement here, but please comment and we can reopen!

**Comment by pxwee5** [comment]
What @prithveesh is saying here is valid. A site I manage completely finished loading at 4s in Lighthouse - this gives me around 80+ score. 

However, because of GDPR cookie consent, I am legally obligated to add a popup and because of that I am penalised for following the law. Loading the popup on `window.requestIdleCallback` or `window.onload` both affected my Lighthouse score, currently at the lower 50s. 

This paints a false score because the page is already interactive when the `load` event is fired. This is very unfair and product owners who heavily rely on Lighthouse score does not understand this concept.

There are other unreliable ways to detect interaction events like `hover, scroll, click` to trigger the popup so that Lighthouse ignores it. But that doesn't solve the problem at hand.

**Comment by connorjclark** [comment]
Can you provide a URL?

**Comment by patrickhulce** [comment]
@pxwee5 could you file a separate issue for that discussion? This is a totally different situation than the one discussed in this issue. This issue discusses poorly encoded images that are loaded in the middle of lots of javascript execution. Your issue is a legitimate concern with the design of a performance metric.

**Comment by dsacramone** [comment]
> @pxwee5 could you file a separate issue for that discussion? That is a totally different situation than the one discussed in this issue. This issue discusses poorly encoded images that are loaded in the middle of lots of javascript execution. Your issue is a legitimate concern with the design of a performance metric.

I am experiencing this same issue. Because of cookie consent, my Lighthouse score is tanking. I even defer the load for like 5 seconds, doesn't matter. I still get dinged by Lighthouse. How can we load these "law required" items without Lighthouse severely dinging us?
