### ISSUE TITLE
Help understanding Speed Index calculation

### ISSUE THREAD

**Issue by verydanny** [GoogleChrome/lighthouse#8758]
I used the Google PSI tool online for [ this url.](https://dv-preconnectnah-8e025c1.r.rent.com/georgia/atlanta/apartments_condos_houses_townhouses)

I get consistently good FCP/FMP, and I'm failing to understand why my Speed Index scores are so outrageously bad. 

From what I understand it's how much of the page is left to render compared to the last frame, and using that, our app seems to be complete much quicker than the simulated score implies.

In fact, whenever I run this site locally in devtools lighthouse, simulated or not, I always get a Speed Index of 3s or less on mobile. It's only when I use the node lighthouse tool that I get horrible Speed Index numbers.

![Screen Shot 2019-04-30 at 9 41 10 PM](https://user-images.githubusercontent.com/13333822/57002895-b2c18380-6b90-11e9-8142-360f5fdd3ece.jpg)

**Comment by patrickhulce** [comment]
Great job on prioritizing FCP on that site, thanks for filing this!

The slow speed index is attempting to capture the impact of late layouts due to the scripts and images that take much longer to load than the initial paint (see the performance timeline below when you apply network throttling to the page)

![image](https://user-images.githubusercontent.com/2301202/57003731-447bc180-6b8e-11e9-9925-165705b3b141.png)

I'm not able to reproduce the lower speed index in Devtools, so I'm not sure what's going on there.

**Comment by verydanny** [comment]
I have a version of the site where I preload the images needed quicker, and even that I get horrible Speed Index scores, even though it seems to be visually complete relatively quickly, even on fast 3g.

I was going item by item to try and optimize things, and I was able to do FCP/FMP relatively easily, but Speed Index baffles me.

**Comment by patrickhulce** [comment]
Hm, this is a good counterexample case thanks for sharing the second URL!

I'm not seeing an enormous difference in the image paint times on my machine, but speed index should indeed be a bit lower than it is.

In this case the simulation is overweighting the large (layout tainting) script evaluations that are going on later in load even though they don't end up visually impacting the page. It's a simulation tradeoff that isn't ideal in your particular setup, but one we're unlikely to be able to fix in the near future since in most cases this captures legitimate speed index concerns. Sorry you've been bitten by this! My best advice would be to test with applied throttling when evaluating your speed index for now.

**Comment by verydanny** [comment]
Hmm, is there something I can do with my script evaluation to not impact this negatively?

**Comment by patrickhulce** [comment]
>  is there something I can do with my script evaluation to not impact this negatively?

Doing things to drive down TTI will be the same sorts of things to drive down speed index in this case, so break up your tasks into smaller chunks of work, code split when possible, etc :)

**Comment by verydanny** [comment]
Does Google PSI use simulated settings? I'm attempting to match those numbers so I could have a baseline to improve upon, and my company seems to prioritize Google PSI numbers.

**Comment by patrickhulce** [comment]
Yes, PSI uses the simulated settings. Addressing the large script executions late in page load should drive down your performance score there.
