### ISSUE TITLE
[Question] are budget audits available programmatically or only via CLI?

### ISSUE THREAD

**Issue by Danon9111** [GoogleChrome/lighthouse#8912]
**Are budget audits available programmatically or only via CLI?**

As I'm experimenting with Lighthouse and Jenkins I'm trying to use also LightWallet metrics. Unfortunately for now I was only able to run budget metrics via CLI. 

Are budget audits available programmatically or only via CLI? 

Thanks

**Comment by patrickhulce** [comment]
You should be able to use budgets programmatically as well.

Example from our tests

https://github.com/GoogleChrome/lighthouse/blob/ffb1debfb6ed909c2d44b9c3cd578a5b6d17da8d/lighthouse-cli/test/smokehouse/perf/perf-config.js#L16-L46

**Comment by Danon9111** [comment]
@patrickhulce works good! 

So doing this budget config as a separate configuration file and injecting it into main config is not a best practice? I mean something like that:

`const samplePerfConfig = {
  extends: 'lighthouse:default',
  settings: {
    budgetPath: '../test/fixtures/simple-budget.json', `

Thanks for help!

**Comment by patrickhulce** [comment]
`--budeget-path` is only a convenience supported via the command-line, assumption is that if you're invoking programmatically you have the budget readily available as an object already (we also try to keep the core module free from arbitrary filesystem access when possible since it gets bundled into environments without that access such as extension, devtools, etc)
