### ISSUE TITLE
"Show 3rd-party resources" checkbox should be hidden when all resources are 3rd party. 

### ISSUE THREAD

**Issue by jburger424** [GoogleChrome/lighthouse#8955]
**Feature request summary**
Similar to how the checkbox is not shown when nothing is 3rd-party, it shouldn't be shown when everything is 3rd-party.

This is specifically applicable to our plugin as we have several audits that will only display 3rd party resources. In that situation it seems to make no sense to provide the user a way to clear the table.

I'd be happy to implement this myself.

**Comment by brendankenny** [comment]
Makes perfect sense to me

> I'd be happy to implement this myself.

👍 sounds great!

**Comment by Hoten** [comment]
sgtm

> This is specifically applicable to our plugin as we have several audits that will only display 3rd party resources. In that situation it seems to make no sense to provide the user a way to clear the table.

We probably shouldn't have [hardcoded the exceptions](https://github.com/GoogleChrome/lighthouse/blob/ffb1debfb6ed909c2d44b9c3cd578a5b6d17da8d/lighthouse-core/report/html/renderer/report-ui-features.js#L159) :)

**Comment by jburger424** [comment]
> We probably shouldn't have [hardcoded the exceptions](https://github.com/GoogleChrome/lighthouse/blob/ffb1debfb6ed909c2d44b9c3cd578a5b6d17da8d/lighthouse-core/report/html/renderer/report-ui-features.js#L159) :)

Haha missed that. What if the exceptions were part of the config file?

**Comment by brendankenny** [comment]
as you noted, there's [already a check for not adding it if there's no third-party URLs](https://github.com/GoogleChrome/lighthouse/blob/ffb1debfb6ed909c2d44b9c3cd578a5b6d17da8d/lighthouse-core/report/html/renderer/report-ui-features.js#L177-L178), it seems completely reasonable  and nicely simple to add a check right next to there for when a table is all third-party URLs.

(and if `uses-rel-preconnect` just turns out to be a specific case of this as the comment above it implies, we could remove the `thirdPartyFilterAuditExclusions`, but I don't think that's a pressing concern)

**Comment by jburger424** [comment]
Agreed, will just stick with this for now.
