### ISSUE TITLE
Simulate packet loss

### ISSUE THREAD

**Issue by hollandThomas** [GoogleChrome/lighthouse#8963]
**Feature request summary**
_"Describe what you want to be added"_

Hey folks. In [the mobile network throttling preset](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md), the recommended configuration for mobile devices is described as follows:

- Latency: 150ms
- Throughput: 1.6Mbps down / 750 Kbps up.
- Packet loss: none.

which leads me to believe that packet loss is a configurable parameter. However, I can't seem to find any documentation on how to do that, especially for the Node CLI.

_"Are you willing to work on this yourself?"_

Probably not since I won't be able to spend enough time on it.

**What is the motivation or use case for changing this?**

At our company, we develop software that is run on airplanes. In the air, packet loss is a significant parameter that affects load times. HTTP/2 might not even be a good idea because of TCP congestion control, just to name one concern. In order to automate our performance audits, lighthouse seems to be a perfect candidate - but seems to be lacking this crucial feature.

**How is this beneficial to Lighthouse?**

Provide even more possibilities to simulate networks under more realistic surrounding conditions.

**Comment by patrickhulce** [comment]
Thanks for filing @hollandThomas great points! ❤️

You're correct in thinking we call it out because some throttling mechanisms enable packet loss (specifically [comcast](https://github.com/tylertreat/comcast) and other packet-level throttling techniques mentioned in that doc).

As for making it configurable within LH itself, I'm not optimistic we'll be able to make it happen. There are limits to the fidelity of `simulated` and `devtools` throttling methods available within LH which is why we encourage the use of more robust and real-world accuracy methods. Attempting to develop an accurate packet loss in-house would run somewhat counter to the goals of our simulated throttling method existing in the first place (low run time cost, stable/less variable results, etc). I love the idea, but I think this might be best left for `--throttling-method=applied` and using other tools to achieve specific throttling effects.

That being said, the net effect of applying packet loss is essentially that RTT appears to increase from the application perspective due to all the retries happening behind the scenes. RTT is a configurable parameter so you can emulate the effect by increasing that (`--throttling.rttMs=600` for example). Hope this helps!

**Comment by connorjclark** [comment]
Like @patrickhulce said, other tools are great for this. Still don't see use focusing on this ourselves.
