### ISSUE TITLE
Disable network throttling, keep cpu throttling

### ISSUE THREAD

**Issue by omares** [GoogleChrome/lighthouse#8986]
Hey,

i would love to disable any network related throttling that lighthouse provides, as the network connection is throttled by other means.

According to the [advanced throttling guide](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md) the options `--throttling.requestLatencyMs=0 --throttling.downloadThroughputKbps=0 --throttling.uploadThroughputKbps=0` in combination with the `simulated` method should remove the network throttling, but this is not the case. The download throughput is still capped at 1,638.4 Kbps.

According to the [load-simulator.js](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/computed/load-simulator.js#L38-L67) code none of the options mentioned are considered when using `simulated`. Explaining why the options don't have any impact. Setting `downloadThroughputKbps` to zero leads to erroneous results.

Using `provided` as throttling method is not an option as this removes the cpu throttling. Which causes wrong results as the host CPU is not throttled.

Same applies for the `devtools` method, which also disables cpu throttling.

The only resort would be to crank up the `downloadThroughputKbps` value as the throughput is limited by the underlying and throttled network connection. but i am unsure if this has undesired side effects.

To run lighthouse, i am using the [sitespeed.io plugin](https://github.com/sitespeedio/plugin-lighthouse). The plugin essentially is a wrapper around lighthouse nodejs.

Any pointers or hints would be appreciated!

**Comment by patrickhulce** [comment]
Thanks for filing with the detailed explanation @omares! 

When you're `--throttling-method=simulated` there's no such thing as "disabling network throttling" because we have to pick *some* network conditions to use :) If you'd like to simulate a cable connection for example though, you might want `--throttling.rttMs=40 --throttling.throughputKbps=50000`

The docs should be updated for that example because it's missing that you'd need `--throttling-method=devtools` for the `--throttling.requestLatencyMs=0 --throttling.downloadThroughputKbps=0 --throttling.uploadThroughputKbps=0` to work. The only way to achieve what you're asking for is

`--throttling-method=devtools --throttling.requestLatencyMs=0 --throttling.downloadThroughputKbps=0 --throttling.uploadThroughputKbps=0` which should disable the devtools network throttling, keep devtools CPU throttling, and use observed metric values in the results.

Does this help?

PR welcome to help make our throttling docs clearer by the way ;)

**Comment by omares** [comment]
Thanks for the swift reply  @patrickhulce 

Somehow i completely disregarded the devtools option.

Is there any way to verify that no throttling was active, besides the output in the report which now states `Network throttling: 0 ms HTTP RTT, 0 Kbps down, 0 Kbps up (DevTools)`

**Comment by patrickhulce** [comment]
@omares You can run it on example.com and if FCP is less than 500ms you know it wasn't throttled.

**Comment by omares** [comment]
It is around 600ms compared to 800. But i guess thats in the expected range. Thanks a bunch for clarification.

Regarding the contribution, ill try my best ;)

**Comment by omares** [comment]
@patrickhulce hey anything i can do to help debunking the issue i am facing?

**Comment by patrickhulce** [comment]
Hm, we haven't really seen that error in the wild it is definitely unexpected!

That possibility has been removed in the latest version of Lighthouse, but if you get something similar in v5 please file a separate bug with repro steps.

I'm going to go ahead and consider this closed for now since it seems like you've figured out the original issue :)
