### ISSUE TITLE
Using unknown Audit.meta.name does not throw

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#905]
As discovered in https://github.com/GoogleChrome/lighthouse/pull/903, using an incorrect name in an audit (`audits.meta.name`) causes the result to not show up in the report.

https://github.com/GoogleChrome/lighthouse/blob/5cf4c131ff6e2fd3976bcd516ca015d84ebb87ac/lighthouse-core/runner.js#L117 stashes the results under `audit.name`. So in the case of the geolocation audit, it was stashing results under "geolocation" (name audit claimed) and not "geo-location-start" (name config used).

For core audits, we could check that `audit.meta.name` is in `Runner.getAuditList()`. Not sure how to approach this for non-core audits.

**Comment by brendankenny** [comment]
After looking into this, I think the current behavior in `config.js` and `runner.js` is actually correct. The "name" of an audit in the config file is actually the *file* name (we just allow the convenience of not including a full path for core audits), *not* the name of the audit. It's the score aggregation that's being too lenient.

(separately we could add a test to make sure core audits are named the same as their file, because that does get a bit confusing, and no reason not to)
