### ISSUE TITLE
Plugins: custom category renderers

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#9053]
Just like we have customer renderers for perf and pwa, so should plugins.

See https://github.com/GoogleChrome/lighthouse/pull/9051#issuecomment-495779502

**Comment by brendankenny** [comment]
I'll warn up front that because of the way we support sharing and rendering lighthouse results, this is either difficult to pull off or an XSS waiting to happen, so I think this is unlikely to work out, at least at the level of flexibility you might be imagining.

Expanding the core category/details renderers to be able to display what you'd like to put in a report is likely to be a lot more fruitful.

**Comment by brendankenny** [comment]
Not feasible today, but we can explore at some point in the future. For now, let's focus on improving the primitives available in categoryRenderer and detailsRenderer.
