### ISSUE TITLE
Improve node snippet values

### ISSUE THREAD

**Issue by mattzeunert** [GoogleChrome/lighthouse#9062]
Right now we use this for node.snippet:

- outerHTML truncated at 300 chars
   - [provided by Axe as `node.html`](https://github.com/dequelabs/axe-core/blob/develop/lib/core/utils/dq-element.js#L15)
   - using `element.outerHTML` in the tap targets gatherer
- `getOuterHTMLSnippet` is used by e.g. the `anchor-elements` gatherer, and as a fallback if Axe doesn't provide `node.html`

Thoughts:

- if we keep `getOuterHTMLSnippet` around it should be renamed to `getOpeningTagSnippet`, because that's what it does
- are there specific audits where we want to show the opening tag snippet instead of the outerHTML? Can we always use outerHTML? For the accessibility audits we shouldn't fall back to `getOpeningTagSnippet` because right now the snippet sometimes misses the actual content of the element.
- `getOpeningTagSnippet` removes style attributes to clean up the snippet, that might be nice for the outerHTML too

Here's an example where we don't show the full outerHTML in accessibility audits, from http://stackoverflow.com:

![Screenshot 2019-05-25 at 19 39 28](https://user-images.githubusercontent.com/1303660/58373354-daec9a00-7f24-11e9-8fd5-83f2802d0771.png)

**Comment by patrickhulce** [comment]
> if we keep getOuterHTMLSnippet around it should be renamed to getOpeningTagSnippet, because that's what it does

👍 

> are there specific audits where we want to show the opening tag snippet instead of the outerHTML?

I think the primary goal was cleanliness. It definitely wasn't the easiest to identify before, but the new `nodeLabel` you've added does a nice job of that. IMO, we could probably switch whole hog to `outerHTML` without much impact so long as we're still aggressively limiting the length.

> getOpeningTagSnippet removes style attributes to clean up the snippet, that might be nice for the outerHTML too

👍

**Comment by paulirish** [comment]
we're updated a few things here since this issue:

- [report: truncate long attribute values in HTML snippets (#10984)](https://github.com/GoogleChrome/lighthouse/commit/bce99308ce499320a75600d04197d6971cd83f51)
- [report: truncate long attribute values in HTML snippets (#10984)](https://github.com/GoogleChrome/lighthouse/commit/bce99308ce499320a75600d04197d6971cd83f51)
- [report: truncate long attribute values in HTML snippets (#10984)](https://github.com/GoogleChrome/lighthouse/commit/bce99308ce499320a75600d04197d6971cd83f51)
- [core: fallback to selector, not tagName for nodeLabel (#12727)](https://github.com/GoogleChrome/lighthouse/commit/25cc9b6ed801ac780cb232c1d85ef71d2d305533)

and then connor's element screenshots stuff. like [core(full-page-screenshot): resolve node rects during emulation (#11536)](https://github.com/GoogleChrome/lighthouse/commit/26074a7906b90eb9877677ee09576947f63ee087)

so i think we're in a good place on this now.
