### ISSUE TITLE
CLI only-categories documentation

### ISSUE THREAD

**Issue by olore** [GoogleChrome/lighthouse#9209]
**Summary**
First time user here! While investigating how to run lighthouse from the CLI, I struggled finding what values are available to the `--only-categories` flag. `lighthouse --help` provides two: `performance,pwa`, but it's not clear what the names of the other categories are, in particular "Best Practices", because it contains a space.

Anyway, I figured it out by looking into default-config.js, but I'm interested in making this more apparent. My first thought was an update to README, but maybe an update to the `--help` output would be better since it seems like plugins can provide other categories, so it may be better to build the list dynamically, if that's even possible. Looking for input on this.

The default list, for anyone that comes across this is 
`accessibility,best-practices,performance,pwa,seo`

**Comment by brendankenny** [comment]
> first thought was an update to README, but maybe an update to the `--help` output would be better

we copy the `--help` output to the README, so having it in both sounds great!

> since it seems like plugins can provide other categories, so it may be better to build the list dynamically

for plugins in particular, I'm not sure that is possible, since the plugins to be used aren't resolved until after the flags are parsed and processed, which I assume happens after `--help` is figured out.

Probably best just to list the default categories, unless other folks have ideas?
