### ISSUE TITLE
Proposed refactor: Check for required artifacts before calling audit()

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#941]
The very top of every audit file's audit() function has a block [like this](https://github.com/GoogleChrome/lighthouse/blob/0ac3fe9f683d207270ccf6b23f067f1d91889037/lighthouse-core/audits/dobetterweb/uses-single-use-event-listeners.js#L49-L57):

```js
    if (typeof artifacts.EventListeners === 'undefined' ||
        artifacts.EventListeners === -1) {
      return SingleUseEventsAudit.generateAuditResult({
        rawValue: -1,
        debugString: 'EventListeners gatherer did not run'
      });
    } else if (artifacts.EventListeners.rawValue === -1) {
      return SingleUseEventsAudit.generateAuditResult(artifacts.EventListeners);
    }
```

It's extremely rote and decreases the signal:noise ratio of the source. I think we could get rid of it.

We could alternatively handle this more automatically. Something like:

1.  For each audit, `runner` grabs its `requiredArtifacts` property.
2. `runner` checks that each requiredArtifact exists on `artifacts` and if it doesn't, `generateAuditResult` with our -1 error
3. `runner` also checks if the artifact value is -1, and if so, `generateAuditResult` with the curried `debugString` on the artifact

This would add some lines to runner.js and drop 5-10 lines from every audit we have.  I bet it would uncover a bug or two as well. AFAIK, currently we don't heavily depend on `requiredArtifacts` being correct or anything, but we could and should, IMO.

Thoughts?

**Comment by brendankenny** [comment]
sounds GREAT. I was going to make a separate bug about standardizing on an error/`debugString` format from gatherers and what audits should do with that. This would take care of all of that and enforce it.

The only thing left to add would be a note in the readme about what gatherers should return :)

**Comment by brendankenny** [comment]
> This would add some lines to runner.js and drop 5-10 lines from every audit we have

and add a few tests to `runner-test.js` but drop one or two tests from every audit :) win/win/win

**Comment by paulirish** [comment]
:+1:

Anyone wanna take this? It's a good first bug. And a good second bug. :)

**Comment by jillesme** [comment]
Did anyone say good second bug? I'll take it!

**Comment by jillesme** [comment]
I'm working on this. 

Currently I'm thinking something like (runner.js):

```js
...
const status = `Evaluating: ${audit.meta.description}`;
const requiredArtifacts = audit.meta.requiredArtifacts;
const hasAllRequiredArtifacts = requiredArtifacts.every(artifact => !!artifacts[artifact]);

// Run each audit sequentially, the auditResults array has all our fine work
return chain.then(_ => {
  log.log('status', status);

  if (!hasAllRequiredArtifacts) {
    return audit.generateAuditResult({
      rawValue: -1,
      debugString: `${requiredArtifacts.join(' or ')} gatherer did not run.`
    });
  }
```
So after running lighthouse on [https://example.com](https://example.com) with some of my debugging code I get:


>[FAIL]: -1 or undefined for  works-offline (-1)

> required [ 'traceContents' ]
>[FAIL]: first-meaningful-paint
>[FAIL]: speed-index-metric
>[FAIL]: estimated-input-latency
>[FAIL]: time-to-interactive
>[FAIL]: user-timings
>[FAIL]: screenshots

Which I guess makes sense because those files don't have a [block like this](https://github.com/GoogleChrome/lighthouse/blob/0ac3fe9f683d207270ccf6b23f067f1d91889037/lighthouse-core/audits/dobetterweb/uses-single-use-event-listeners.js#L49-L57).

**However,** it also fails for ThemeColorMeta. In my code I return `-1` as rawValue but in this implementation we return a boolean:

```js
return ThemeColor.generateAuditResult({
        rawValue: false,
        debugString: 'No valid theme-color meta tag found.'
      })
```

And we get the error "_Runtime error encountered: Error: Expected expectedValue of type boolean, got number: ThemeColor gatherer did not run._"

So I propose something like making the `requiredArtifacts` more verbose. 

```js
// old
requiredArtifacts: ['ThemeColor']
// new
requiredArtifacts: [{ name: 'ThemeColor', rawValue: false }]
```

We could either change it everywhere or do a simple `typeof requiredArtifact === 'string'`.

Maybe I am overcomplicating things? I am not too familiar with the codebase **yet**. What do you guys think of this solution?

**Comment by brendankenny** [comment]
This will require touching a number of gatherers and nearly all the audits, so the errors you see are somewhat expected. I think there is a somewhat simpler way of getting consistency, though. 

@paulirish kind of alludes to this in his numbered list, but to make it explicit, we can standardize gatherer output on something like
```js
{
  value // whatever the gatherer wants to output, undefined if there was an error
  error // true if there was an error, false or undefined if no error
  debugString // if error is true, some kind of error message
}
```

this is slightly more complicated than existing (where a `value` of -1 often means there was an error), but if we're going to standardize on this we're going to need to support gatherers that want to output integers as their value, and -1 may be valid for them. I think we also can't depend on a `value` of `undefined` to indicate an error; with extensible gatherers/audits that's just a hard to debug error waiting to happen for folks. Better to be explicit.

About two minutes went into thinking about this, so opinions very welcome :)

**Comment by brendankenny** [comment]
`traceContents` are a different issue. We'll need to either remove that from `requiredArtifacts` because it doesn't go through the same artifact pipeline. Alternatively we could make sure it exists, but we'd have to have audits publish what `passName` they'll be looking at...

This issue may get a little hairier than we thought. "good first bug" may have been added prematurely, but it may still be fine. Good way to learn the codebase :)

**Comment by ebidel** [comment]
I was thinking we might want to make `error` an object so it can be expanded in the future.  And if you have an `error`, there should really be a `debugString` telling why. 

What if we made `debugString` part of the error response? That way, in code you would only need to check `artifact.error` to know there was an error. Then drill in from there.

```
{
  value // whatever the gatherer wants to output, undefined if there was an error
  error: { // undefined if no error
    debugString // some kind of error message
  }
}
```

**Comment by brendankenny** [comment]
good idea

- we also may want real a real `Error` object at times. A stack trace from a debugger protocol error wouldn't be helpful (it would just point to `Connection`), but if a gatherer uses a library for something, an error stack trace may be very helpful if it can be piped out and surfaced at the end

- right now we have confusion around what a -1 means, mostly at the audit level, but to a lesser extent at the gatherer level. Do we need to have a different error form for actual errors and issues with computing the gatherer.

  The first case (things like couldn't compute this because of a driver error or a type error or whatever) is easily handled by this format.

  The second case is harder. The current canonical example of this is a TTI of -1 because the trace wasn't long enough...there just wasn't enough information to give an answer, but there *is* data (TTI was really long but we don't know *how* long). This can somewhat be handled by better `value` values than just -1, but `debugString` ends up being useful to have an automated way of piping out information about why Lighthouse doesn't handle a particular case at this point.

**Comment by brendankenny** [comment]
@jillesme, we might want to hold off on this. I think we're going to want to explore the space a bit before committing to a solution

**Comment by jillesme** [comment]
Ok @brendankenny, I'll work on DoBetterWeb then 😁

**Comment by patrickhulce** [comment]
What if we just had gatherers set `this.artifact` directly to the value or a Promise that would resolve to the value/would contain any errors. It would convert code that currently looks like this


**my-gatherer.js**
```
afterPass() {
  return myComputation.then(value => {
    this.artifact = {value};
  }, error => {
    this.artifact = {error};
  });
}
```

becomes

```
afterPass() {
  return this.artifact = myComputation;
}
```

**gather-runner.js**
```
artifact[name] = gatherer.artifact
```
becomes 
```
Promise.resolve(gatherer.artifact)
  .then(value => artifact[name] = {value})
  .catch(error => artifact[name] = {error});
```

Each gatherer would still be able to decide in which phase the artifact is computed and would move all the mapping `{value/usage/randomName, debugString, etc}` to the gather runner

**Comment by brendankenny** [comment]
I was thinking something similar, it would be great to get rid of manually handling success/error conditionals with convention when we have perfectly good language features for that, and I think our ideas are basically equivalent.

One constraint is that we *have* to wait for each method of each gatherer to finish before moving on to the next gatherer as they can easily interfere with each other. There are ways around our current approach of waiting for the `beforePass`/`pass`/`afterPass` promise to resolve to screw with the next gatherer, but for the most part, it keeps things serial.

So to make `this.artifact` a promise, we'd have to wait on it until it resolves before moving to the next gatherer, and we'd have to do that for each lifecycle method because any of them can set `this.artifact`.

Easily doable, but I was thinking in that case, why not get rid of `this.artifact`? Basically you'd have two cross-cutting control flows: the promise chain we have now for gather-runner flow, and another that takes the three `beforePass`/`pass`/`afterPass` promises from a gatherer and takes the last non-`undefined` value resolved (or rejected) and uses that as the artifact (similar to the current approach of the last value set to `this.artifact` as the artifact).

As it is now, most gatherers will never worry about the "last resolved value wins" rule since they only create an artifact once, so most would go from
```js
afterPass() {
  return myComputation.then(value => {
    this.artifact = {value};
  }, error => {
    this.artifact = {error};
  });
}
```

to
```js
afterPass() {
  return myComputation;
}
```

this moves the bookkeeping for the artifact of a gatherer to `gather-runner`, which makes it moderately more complicated, but makes writing an artifact that much simpler.

**Comment by patrickhulce** [comment]
> Easily doable, but I was thinking in that case, why not get rid of this.artifact? Basically you'd have two cross-cutting control flows: the promise chain we have now for gather-runner flow, and another that takes the three beforePass/pass/afterPass promises from a gatherer and takes the last non-undefined value resolved (or rejected) and uses that as the artifact (similar to the current approach of the last value set to this.artifact as the artifact).

I like this a lot. It might lead to some strange `.then(() => undefined)` lines if a pass needs to do some cleanup or bookkeeping asynchronously without setting the value, but I think a small price to pay for getting rid of `this.artifact`. My only reason for trying to keep it around originally is that I think it's super-non-obvious that the return values of functions named `afterPass` and `beforePass` sometimes/maybe become artifacts under certain conditions.

**Comment by paulirish** [comment]
A few thoughts, though nothing terribly new:

1. **Killing the -1 checks.** It seems like the #1088 PR sets us up to then deal with all the `if (artifact.value -1)` checks that are strewn throughout the audits. And it appears the consensus is we need to codify our gatherer artifact return values (for errors) first. 
2. **Error handling in gatherers.** 
  * Basically a +1 on [eric's proposal here](https://github.com/GoogleChrome/lighthouse/issues/941#issuecomment-261042483). 
  * An `error` property is false if everythings okay, and an object if there's something to report.  Another property (`severity`?) inside that error object could reveal if it's a catastrophic failure to run or a smaller reportable issue. 
  * And I like the idea of using `new Error()` for all errors, and never applying any `err.message` into `debugString`. IMO debugString should only be text we write to explain a failure or problem.

**Comment by brendankenny** [comment]
Currently gatherers catch all errors and output an error artifact (using various variations of `-1`), then all our audits have -1 checks, outputting a `-1` and a `debugString` of their own as a result. The plan here (and in the associated PRs) was to move to a fast-fail system where an error in a gatherer has to *opt-in* to being recoverable, otherwise Lighthouse would shut down and the error would be reported. This would help a ton with errors that we simply don't know about because they're caught as -1s and never reported, but it would also make the experience of running LH very frustrating while we work through all the various ways errors could crop up.

Today @patrickhulce suggested reversing course and maintaining the catch everything approach, having a way of flagging an error as `fatal` (instead of `recoverable`), and then using error reporting (when it's ready) to make visible all the various error cases we aren't seeing right now. While I'd like to not coddle these bugs and force ourselves to fix them, I'm thinking this is probably the better approach for our users. As @ebidel pointed out, look at how useless Lighthouse was for some users when *some* gatherers failed due to React Dev Tools, but as a result no report was generated at all.

My remaining concern is authoring and testing, as catching everything makes it easy to never see very clear bugs during development. Should it be a flag that makes any error in gatherers fatal? 'DEV' environment variable? Errors should be obvious when writing locally, not just when it runs on Travis, and it should be difficult to forget to set so that we don't accidentally have tests not running with it set.

**Comment by ebidel** [comment]
I agree that a single gatherer/audit bug shouldn't take LH down. That's not a good UX.

> My remaining concern is authoring and testing, as catching everything makes it easy to never see very clear bugs during development.

Could we do a `NODE_ENV` prod/dev setup? I'm not too familiar with how people use that stuff, but it might be a good thing to try.

http://stackoverflow.com/questions/9198310/how-to-set-node-env-to-production-development-in-os-x

**Comment by paulirish** [comment]
`fatal` flagging wfm.

**Comment by brendankenny** [comment]
fixed over the several PRs mentioned above
