### ISSUE TITLE
https://codelabs.developers.google.com/codelabs/pwa-offline-quickstart/#3

### ISSUE THREAD

**Issue by KravMaguy** [GoogleChrome/lighthouse#9424]
**Summary**
My lighthouse results in the first screenshot do not match the results shown in the second screenshot
https://www.dropbox.com/s/yo63i5mtzy17zeh/Screenshot%202019-07-20%2013.50.38.png?dl=0
https://www.dropbox.com/s/qds20ostvt9mu20/Screenshot%202019-07-20%2013.52.44.png?dl=0

Is your tutorial 
https://codelabs.developers.google.com/codelabs/pwa-offline-quickstart/#3
not up to date?

**Comment by patrickhulce** [comment]
Thanks for filing @KravMaguy! 

That codelab is using an older version of Lighthouse in that screenshot. We've made several updates since then. We don't author or manage those codelabs, and it seems anyone can author codelabs that get published to that site (according to https://github.com/googlecodelabs/tools). This one looks like it was written by [Google Developer Training](https://github.com/google-developer-training), you'll probably have to venture over there if you'd like to update the codelab :)

**Comment by KravMaguy** [comment]
@patrickhulce can you provide a link of codelabs that are up to date and that work? 
I am trying to learn how to setup a pwa. I see many versions online of codelabs provided by google or put out by google teams, and all the ones ive went through do not work. Im not trying to author my own codelab, How am I supposed to know how to fix your products? It would be nice to have an up to date tutorial that works. Im currently going through this codelab, it doesnt work either. 
https://codelabs.developers.google.com/codelabs/push-notifications/#6

and the above link seems to be the same content as 👍 https://developers.google.com/web/fundamentals/codelabs/push-notifications/

So which one is current? 
So far in my experience of going through your codelabs none of them work, and by work I mean that they are not producing the outcomes as explained in the tutorials.

**Comment by patrickhulce** [comment]
I'm not sure what to tell you @KravMaguy. I'm sorry you're struggling with the codelabs. Those codelabs are not for Lighthouse but for general features of the web platform. For example, you've linked to push notification codelabs, but Lighthouse doesn't do anything related to push notifications. The fact that the report looks different since a codelab was written by someone else is not something that can be fixed here. AFAIK the latest content written by the Chrome team is all on https://web.dev, but the existence of old tutorials on the internet is likely something that won't go away anytime soon.

**Comment by KravMaguy** [comment]
I hear you, thanks for your sympathies and writing back. I need to know how to build a modern pwa with all the feautures. You are not responsible for maintaining the repo https://github.com/GoogleChromeLabs/web-push-codelab/ but you should know that doing a search on the site you just mentioned for 'push notifications' yields https://web.dev/service-worker and the aforementioned repo is linked to directly from it. 
Its possible I made an error with the lab but it seemed pretty straightforward copying and pasting, ill go over it a second time. I will post to the issue  here for further reference:
https://github.com/GoogleChromeLabs/web-push-codelab/issues/89
