### ISSUE TITLE
Make desktop perf metric score curves identical everywhere

### ISSUE THREAD

**Issue by RustedBones** [GoogleChrome/lighthouse#9436]
When running tests on Lighthouse and PageSpeed Insight, we spotted some inconsistencies in the `speed index` classification of what is a 'fast', i.e. green/orange/red: 

- In Lighthouse, a `speed index` of 3.2s is green

![lighthouse](https://user-images.githubusercontent.com/2845540/61710701-7ac27a80-ad52-11e9-89c6-5618c6ab4c4b.png)

- In Page Speed Insights, a `speed index` of 1.6s is orange

![pagespeed_insights](https://user-images.githubusercontent.com/2845540/61710692-75653000-ad52-11e9-9113-ecc8bc550f8d.png)

Both results are observed in Desktop mode.

Since `speed index` is a Lab Data field, I expected the 2 tools to give the same classification.

**Comment by patrickhulce** [comment]
Thanks for filing @RustedBones! The score scale for desktop in Page Speed Insights is adjusted for the faster connection type, but the score scale is not automatically adjusted in other Lighthouse environments.

We would like to fix this discrepancy in other environments but doing so while supporting all the other available flags in an intuitive way is challenging.

It looks like you were running in DevTools though which should be the most straightforward. @connorjclark do you think this is something we could tackle with an upcoming roll? (Using the desktop config when the "Desktop" radio is selected instead of just setting `emulatedFormFactor`?)

**Comment by RustedBones** [comment]
If my understanding is right, you are meaning that PageSpeed Insights is using the `lighthouse-core/config/lr-desktop-config.js` with
```js
    // 75th and 95th percentiles -> median and PODR
    // SELECT QUANTILES(SpeedIndex, 21) FROM [httparchive:summary_pages.2018_12_15_desktop] LIMIT 1000
    {path: 'metrics/speed-index', options: {scorePODR: 1100, scoreMedian: 2300}},
```
that changes the underlying score from `page speed` hence its color, but Lighthouse doesn't. 
It then scores the metrics the same way for desktop and mobile with the default values.

Is this correct ?

**Comment by patrickhulce** [comment]
Yes exactly correct @RustedBones !

**Comment by paulirish** [comment]
Updated title. Our planned action is to use the `lr-desktop-config.js` score configuration everywhere (dt, cli, etc) when desktop mode is set.
