### ISSUE TITLE
☂️Report changes and goals for v6

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#9438]
Collection of suggestions and possible goals for the next iteration of the report. Implementation of a goal not required for inclusion.

- some kind of indicator at the top of the report it was a mobile or desktop run (#9379)

*companion bug to v6 breaking changes: #9180*

**Comment by andreamoro** [comment]
From my previous comment:

For better UX, I'd suggest to move the Runtime settings panel returned after an audit at the top, perhaps in a collapsed panel.
This is because in case of extensive tests, I can see at least 6 iterations for each page and there's a need to understand quickly what you are looking at.

something in the drop-down would possibly work better.
