### ISSUE TITLE
Seeing an "Uses document.write()" under Best Practices but cannot find it in js

### ISSUE THREAD

**Issue by gulatigautam** [GoogleChrome/lighthouse#9466]
#### Provide the steps to reproduce
1. Run LH on www.americanexpress.com
  

#### What is the current behavior?
Seeing an "Uses document.write()" under Best Practices but cannot find it in js
<img width="812" alt="Screen Shot 2019-07-26 at 11 18 37 AM" src="https://user-images.githubusercontent.com/13562914/61962308-37a51900-af97-11e9-9601-f2fde27ffbb5.png">

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**

**Comment by exterkamp** [comment]
Seems like it might be the line
```javascript
h.write("\x3chtml\x3e\x3cbody\x3e\x3c/body\x3e\x3c/html\x3e");
```
in `function S` in https://aug.americanexpress.com/collector/cc.js

**Comment by gulatigautam** [comment]
@exterkamp Thanks! Since this is not an external script and doesn't meet the criteria for intervening specified here https://developers.google.com/web/updates/2016/08/removing-document-write, is it possible for us to somehow ignore this from the lighthouse report so that our score in best practices can increase?

**Comment by connorjclark** [comment]
We only look at the console messages for violations logged by Chrome. This is logged by [every document.write](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/dom/document.cc?sq=package:chromium&dr=CSs&g=0&l=4313), not just ones that match the intervention criteria listed in that article.}

However, that's not to say that the advice is wrong, just that Chrome has a very narrow case of where it's confident it's better to disallow the document.write

**Comment by gulatigautam** [comment]
Thanks  @connorjclark So we are trying to achieve a score of 90 in all the lighthouse parameters. It seems each of these audit suggestions reduces the score by a certain number. Do we know by how much the score reduces because of each audit message? And is it fair to say there might be scenarios like this where the score won't go beyond 90 because lighthouse is flagging an issue which is probably a false positive?

**Comment by patrickhulce** [comment]
> Do we know by how much the score reduces because of each audit message?

Each audit in best practices is worth ~7 points.

> is it fair to say there might be scenarios like this where the score won't go beyond 90

You'd need to be failing 2 audits to be below 90.

> lighthouse is flagging an issue which is probably a false positive

As @connorjclark mentioned, it is not a false positive. All uses of `document.write` should be avoided. The criteria for a Chrome *intervention* such as the one described in the article you linked is much stricter than when providing best practices *advice*. An intervention is unavoidable browser behavior and has much more impactful consequences than Lighthouse just saying a developer *should* do something :)

**Comment by jflayhart** [comment]
For us at Shipt, this is because Google sabotages their audit with their own scripts! Oh the irony:

<img width="1014" alt="Screen Shot 2019-08-07 at 5 27 25 PM" src="https://user-images.githubusercontent.com/6808172/62663018-9e351a00-b93b-11e9-84b4-f734e3ed9203.png">

<img width="1917" alt="Screen Shot 2019-08-07 at 5 28 57 PM" src="https://user-images.githubusercontent.com/6808172/62663019-9f664700-b93b-11e9-9f17-440b0d09300d.png">

**Comment by exterkamp** [comment]
@jflayhart you can reach out to those API owners specifically to try to get them to fix those issues from their end. That's probably the best way.

If you want us to address this from our end (but there's not much we can/will do since we don't exclude specific domains for audits like this, even Google) you can open your own ticket in this repo.

I'm closing this issue though, since the original issue is works-as-intended.
