### ISSUE TITLE
CNN US (https://us.cnn.com/) Score =0

### ISSUE THREAD

**Issue by chloe-grutchfield** [GoogleChrome/lighthouse#9471]
Hi there, the URL https://us.cnn.com/ has a speed score of 0 which we believe is a bug. What are the next steps to get this sorted? Thanks, Chloe

**Comment by patrickhulce** [comment]
Hey there Chloe!

It looks like the site takes ~38 seconds to become interactive on a mobile device and there's ~17 seconds of main thread execution going on, so the score of 0 you're seeing is likely an accurate reflection of the metric values. In my run, it received a 3.

![image](https://user-images.githubusercontent.com/2301202/61978084-e22c3480-afb5-11e9-8563-bc1ad07b97c1.png)

The first paint at ~9 seconds out is also dragging the score down considerably. If you pop open the Performance panel in DevTools and load with Network Throttling set to "Fast 3G" you can observe first hand how slow the page is to paint due to the high number of blocking scripts.

![image](https://user-images.githubusercontent.com/2301202/61978476-01779180-afb7-11e9-9fb8-73e004a33804.png)


Next steps:
- Reduce the several megabytes of script necessary to render the page
- Limit individual task executions post-render to <50 ms each to keep the main thread available for user input to bring down the remaining metrics.

**Comment by chloe-grutchfield** [comment]
Hi there,

Ok makes sense. I thought 0 was an error. Thank you for coming back to me
so quickly!

Chloe


*Chloe Grutchfield*

Co-Founder


Tel: +44 (0)7587097227

Web: www.redbud-media.com

**Comment by exterkamp** [comment]
Closing since this seems answered :smile: Reopen if you need to.
