### ISSUE TITLE
wth happened?

### ISSUE THREAD

**Issue by STaRDoGG** [GoogleChrome/lighthouse#9495]
So I was messing around in the Inspector and came across the "Audit" tab, which I've never used before, decided to see what it did, clicked the run audits button, it showed a handful of my extensions crashing, and eventually didn't really show anything results-wise.

Now all the layouts in my tabs are screwed up. All of the content es either pushed off to about 1/3 of the left side like this:

![image](https://user-images.githubusercontent.com/1524526/62302016-3c5a4900-b43f-11e9-8012-a0816b2437e8.png)

and/or looks like the CSS is screwing up, like this (Bing example):

![image](https://user-images.githubusercontent.com/1524526/62302215-96f3a500-b43f-11e9-9173-b196645322b9.png)

Or google example:

![image](https://user-images.githubusercontent.com/1524526/62302309-b985be00-b43f-11e9-9ce0-3928de13fb3b.png)

This even happens on newly opened tabs. I've tried re-sizing the browser, closing/reopening the browser, cleaning out chrome's browser data and cookies, reloading all extensions, re-running the Audit in both Mobile and Desktop modes (interestingly, they run fine this time), and nothing seems to fix it? It was in Mobile mode when I ran that original test.

The only ray of hope is when I run a New Incognito window, it seems to load pages normal again. I was under the impression that incog windows were (mostly) just a version with all extensions disabled and doesn't save personal info, so I was assuming clearing Chrome's data and restarting the browser would've effectively do the same thing.

Any ideas on the fix? Chrome is unusable like this.

**Comment by patrickhulce** [comment]
Thanks for filing very strange indeed! The part about Audits crashing your Chrome Extensions is new to us. If you can find out which extensions crashed so we can reproduce and fix that would be very helpful!

As for what's causing that behavior, it appears to almost certainly be one of your Chrome extensions that is injecting and/or messing with CSS. Audits panel does not modify the page in any way when not active and these all look like CSS issues. Potentially caused by the restart of the extension that Audits triggered?

To fix, I would disable your extensions and re-enable one at a time until you find the culprit. The fact that everything is fine in incognito is further evidence that it's one of your extensions since most are disabled automatically in Incognito mode.

**Comment by STaRDoGG** [comment]
Hi @patrickhulce thanks for the fast response. =)

Turns out it was a rogue extension, which I'm embarrassed to say, was my own! LOL

I'm developing one atm and it loads another page within an iframe, in a smaller viewport mode, and somehow after running the Audit it caused that effect, which it had never done up until that point. Removing my extension solved it. *tugs on collar*.

Sorry bout that!
