### ISSUE TITLE
Lighthouse says to defer webside logo  (which is visible)

### ISSUE THREAD

**Issue by johanlantz** [GoogleChrome/lighthouse#9496]
#### Provide the steps to reproduce
1. Run LH on  https://givensa.com

#### What is the current behavior?
Lightouse says to defer the website logo "/img/givensa-logo....jpg"

#### What is the expected behavior?
The logo is always visible and it is always the first image to load on the page, it seems weird that Lighthouse wants to defer it (it will always be above the fold on page load).

#### Environment Information
Latest Lighthouse version through chrome.

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing! I'm not seeing this in version 5.2.0 of Lighthouse which is Chrome Canary, just the facebook.png which is indeed not immediately visible.
![image](https://user-images.githubusercontent.com/2301202/62327173-8100d700-b475-11e9-9026-51bd611d821f.png)

**Comment by johanlantz** [comment]
Hi Patrick, 
Thanks for the quick answer, much appreciated.

Indeed with Canary I get better results (nice UX update btw).

Just fyi, from a 3 min test on Canary I see some potential inconsistencies.

- On the Product page, like this one [jumbo cutlery drainer](https://givensa.com/en/cutlery-drainer-jumbo), the main image is still detected as deferable. In the previous version all images and thumbnails in the product image slider were reported as deferable so now it is much better since only the main image is reported. I still do think that this image is above the fold right and it is also lazy loaded so I am not sure if this is really correct even in canary. On the other hand the social media icons are now reported as you mentioned and they were not in the old version so that is good.
- For accessability I was just about to fix the copyright text in the footer (low contrast) as reported in the old LH version. This is not reported in Canary and I think the comment was actually correct, contrast is very bad there. Just in case it has gone missing.

**Comment by patrickhulce** [comment]
Hm, I'm not seeing the same results for the image deferred as you. It is flagging a product image on that page, but its one that is only shown after you click the thumbnail of it, so that's indeed an offscreen image. The URLs differ by just a single character, is it possible there was some confusion there?

Regarding the copyright text, the latest version of axe does not flag that copyright text as a contrast issue (we use axe-core under the hood). If you believe this is a bug, I'm sure they'd appreciate a bug in their [repo](https://github.com/dequelabs/axe-core/) :) (we would automatically pick up any fix the next time we update)

**Comment by johanlantz** [comment]
Thanks Patrick,
No worries about copyrights, just noticed there was a difference between LH versions.

As for the last image flagged as deferable, this no longer happens on Canary, I have retested various times and it is all good now. No idea why but issue is no longer there in Canary.

Ok to close, many thanks for the support and have a nice weekend.
