### ISSUE TITLE
FMP is higher than TTI on server side rendered page

### ISSUE THREAD

**Issue by jackyef** [GoogleChrome/lighthouse#9500]
#### What is the current behavior?
Hi, we are running lighthouse (5.2.0) via WPT to benchmark a page on our site, and recently we start seeing a strange thing going on.

![image](https://user-images.githubusercontent.com/7252454/62385790-2ef8a800-b580-11e9-9479-840b88717bf0.png)
("First Paint" here is taken from FMP value)
As you can see from the image, the FMP we got from the lighthouse report is almost the same as TTI, and is actually a little bit higher! We run the test 10 times a day, and these are the results over the previous few days.

We then tried running lighthouse cli (5.1.0) from our local machine instead. In one device, we see the same thing happening, FMP and TTI is very close. But in another device, we see that FMP is closer to FCP and quite far from TTI.
 
#### What is the expected behavior?
I assume FMP would not be that close TTI, especially being higher than TTI for a server-side-rendered page, or is that not the case? 

* Lighthouse version: 5.2.0

We tried running 5.0.0 and 5.2.0 locally, and still the same thing happen in one of the device running lighthouse-cli.

We also tried web.dev (which uses 5.0.0), and it shows a result that is similar to what we expect. The lighthouse report from WPT (which uses 5.2.0) shows a strange result.

[web.dev lighthouse report](https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://m.tokopedia.com/discovery/maret)
[WPT lighthouse report](https://www.webpagetest.org/result/190802_6R_f890383449e4787fa30da83ac9d7bc23/)

**Comment by patrickhulce** [comment]
Thanks for filing @jackyef! 

If the page doesn't have any long tasks post-FMP then it's expected for them to be nearly equal. It's actually typically the sign of well-behaved page that does the work it needs to do in order to paint all of its content and keeps all later work to a minimum to ensure interactivity, so well done!

Now just time to bring that FMP time down a touch :)

**Comment by jackyef** [comment]
@patrickhulce Thanks for the answer, I have follow up questions.

The page is a server side rendered react page, which is then running client side hydration. Shouldn't this process cause TTI to always be higher than FMP?

Also, it still doesn't answer the question as to why the same version of lighthouse can behave differently when run on different machine.

**Comment by patrickhulce** [comment]
> The page is a server side rendered react page, the initial HTML already has content in it, like images, search bar, etc. It is then running client side hydration, to bootstrap the react app on the client side. Shouldn't this process cause TTI to always be higher than FMP?

The screenshots show that only a small part of the app is rendered initially and the rest is populated later. Is the small part that renders initially all the SSR part? If so, the results are expected and WAI. If the rest of the page is also supposed to be SSR, then it looks like it's not working properly or at least the hydration step is delaying the rendering of the bulk of the content.

> Also, it still doesn't answer the question as to why the same version of lighthouse can behave differently when run on different machine.

Please see our [variability docs](https://github.com/GoogleChrome/lighthouse/blob/252232db9263750435e471da7ea2da1f97ef0d61/docs/variability.md) for a more thorough explanation of why different environments can return different results.

**Comment by jackyef** [comment]
Hi @patrickhulce, appreciate you taking the time to answer this!

>The screenshots show that only a small part of the app is rendered initially and the rest is populated later. Is the small part that renders initially all the SSR part? If so, the results are expected and WAI. If the rest of the page is also supposed to be SSR, then it looks like it's not working properly or at least the hydration step is delaying the rendering of the bulk of the content.

Yes, not all part of the page is server-side-rendered, but enough to cover the above-the-fold part of the page. The below-the-fold part of the page are lazy-loaded images, which would only start to load after the hydration. Does FMP take into account of the whole page? Or just the initial above-the-fold content? I have always been under the impression that it's the latter.

**Comment by patrickhulce** [comment]
FMP takes into account the paint that adds the most layout objects and increases the content height as a percentage of the viewport height which *helps* to identify above-the-fold changes, but it does not only consider above-the-fold content. If lots of layout objects are being added to increase the height of the page post SSR, then chances are it could be misidentified as the "first meaningful paint". We're in the process of decreasing our emphasis on this metric due to this and some other shortcomings that are better solved by [LCP](https://github.com/WICG/largest-contentful-paint#readme), but for now this I believe the metrics to be WAI on this page.

You can read more on how it works in the [First Meaningful Paint explainer](https://docs.google.com/document/d/1BR94tJdZLsin5poeet0XoTW60M0SjvOJQttKT-JK8HI/view).

**Comment by jackyef** [comment]
Alright, thank you for the explanation!
