### ISSUE TITLE
UNKNOWN_ERROR LHRs cause Rendering Failure

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse#9510]
#### Provide the steps to reproduce
Try to render an UNKNOWN ERROR LHR from PSI.  Seems like we set configSettings and other things to `null` instead of filling them in (requestedUrl is `null` even though we know what url was requested).  This causes renderer problems since it expects some things to exist.

#### What is the current behavior?
```
Uncaught TypeError: Cannot read property 'channel' of null
```

#### What is the expected behavior?
Rendering a failed report.

@patrickhulce ideas for this?  I was thinking we populate most of the LHR in lr-entry before bailing with an UNKNOWN ERROR.

**Comment by brendankenny** [comment]
> Try to render an UNKNOWN ERROR LHR from PSI. Seems like we set configSettings and other things to null instead of filling them in (requestedUrl is null even though we know what url was requested). This causes renderer problems since it expects some things to exist.

This was by design, though (#6014). The result was never supposed to be passed into the report renderer (it's nothing close to an LHR), it was only to satisfy the API needing an object with a top-level `runtimeError`.

https://github.com/GoogleChrome/lighthouse/blob/959c499076ffe99257a15432c829e401003a257c/clients/lightrider/lightrider-entry.js#L74-L89

> I was thinking we populate most of the LHR in lr-entry before bailing with an UNKNOWN ERROR.

I think this is the real phrasing of the issue. Current behavior is/was WAI. If the intent should instead be to always get an LHR back, `lightrider-entry.js` will need to recreate an LHR at that point.

**Comment by exterkamp** [comment]
Brendan has convinced me that this is WAI for Lighthouse, and needs to be handled client side.  I will move this to track internally for PSI/LR.
![Untitled-1](https://user-images.githubusercontent.com/6392995/62555357-9f752280-b827-11e9-80d9-73cc07454660.jpg)
