### ISSUE TITLE
`target="_blank"` links should now imply `rel="noopener"`

### ISSUE THREAD

**Issue by Malvoz** [GoogleChrome/lighthouse#9531]
This is about the [`external-anchors-use-rel-noopener.js`](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js) audit.

In a recent [WHATWG spec change](https://github.com/whatwg/html/pull/4330/files), all `target="_blank"` links should now imply `rel="noopener"`.
And the [`opener`](https://html.spec.whatwg.org/multipage/links.html#link-type-opener) link relation was added.

<s>Perhaps once browsers have implemented these changes, the audit could warn about occurrences of `rel="opener"` links instead?</s>

The [`Cross-Origin-Opener-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy) HTTP header is related.

Additionally, the [`rel` attribute is now supported on `<form>`](https://github.com/whatwg/html/pull/4332) elements as well.

<hr>

Changes to the audit would affect the documentation at https://web.dev/external-anchors-use-rel-noopener, should I open an issue in the web.dev repo too?

**Comment by patrickhulce** [comment]
Great point thanks for filing @Malvoz! We should definitely update the documentation either way to address this development. As for the audit, I guess it depends on what level of ubiquity this needs to reach for us to stop giving out this advice.

IMO, we wouldn't ever flag explicit `opener` values since if you're explicitly opting in the assumption is that you needed to for some reason.

**Comment by Malvoz** [comment]
> IMO, we wouldn't ever flag explicit opener values since if you're explicitly opting in the assumption is that you needed to for some reason.

Yes I agree! :)

**Comment by paulirish** [comment]
@Malvoz do you have tracking bugs for the browsers making this change?

**Comment by Malvoz** [comment]
I tried to find it before opening this, I guess I didn't look hard enough :P 

https://bugs.chromium.org/p/chromium/issues/detail?id=898942
https://bugzilla.mozilla.org/show_bug.cgi?id=1503681

**Comment by connorjclark** [comment]
chromium bug is still open.

and we need time for these older modern browsers to become even older.

**Comment by coliff** [comment]
Update: Safari and Firefox now already `rel="noopener"` on `target="_blank"` links - and Chrome/Edge are due to roll this out in release 88 which is scheduled to hit stable in January 2020.

Hopefully Lighthouse won't warn about having target="_blank" links without  `rel="noopener"` a short while after this release has shipped.
REF: https://www.chromestatus.com/feature/6140064063029248

**Comment by patrickhulce** [comment]
Thanks @coliff! My guess is we'll target this for Lighthouse 8 in the spring, to give ample time for most users to catch up, but we can discuss in the next meeting. 

Action item here would be deleting this audit.
