### ISSUE TITLE
PSI not collecting screenshots 

### ISSUE THREAD

**Issue by pyxarez** [GoogleChrome/lighthouse#9545]
#### Provide the steps to reproduce
1. Run LH on https://www.wmj.ru/, https://rambler.ru/, https://gazeta.ru/
  
#### What is the current behavior?
The speed index has an error on the performance category with the following error: Chrome didn't collect any screenshots during the page load. Please make sure there is content visible on the page, and then try re-running Lighthouse. (SPEEDINDEX_OF_ZERO).
I wanna notice that by running lighthouse on node and in devtools I get at least some result(screenshot is attached).

#### What is the expected behavior?
It should display the real speed index instead of ERROR!

#### Environment Information
* https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fwww.wmj.ru%2F&tab=desktop

![image](https://user-images.githubusercontent.com/23152279/62782129-4248cd80-bac2-11e9-8123-9e92becd0c64.png)

**Related issues**
https://github.com/GoogleChrome/lighthouse/issues/5815
https://github.com/GoogleChrome/lighthouse/issues/9107
https://github.com/GoogleChrome/lighthouse/issues/9027

Local run
![image](https://user-images.githubusercontent.com/23152279/62782494-082bfb80-bac3-11e9-8ac3-07f0bd33cc60.png)

**Comment by pyxarez** [comment]
It is also affects https://rambler.ru/ and https://gazeta.ru/

**Comment by pyxarez** [comment]
@exterkamp , God day! Can you please suggest me some points to start working with?
Is there any open information about settings that are used in PSI for running lighthouse that I can apply locally, or any contact that I can try to ask about it?
Thank you!

**Comment by paulirish** [comment]
@pyxarez hi

you have some weird script on your site.. i'm guessing its bot detection? 
https://gist.github.com/paulirish/b9548ef1981720eb60577b0a16409a7f

if the detection throws... we see `document.body.innerHTML = ''`.

So that ends up being a problem. (and what eventually leads to SPEEDINDEX_OF_ZERO)

I hope that helps.

------

Also.. We won't be able to help you diagnose any further problems on your site. Your script is heavily obfuscated and doing some real nonstandard things..  and ultimately we discovered that it's your own code at fault. G'luck.
