### ISSUE TITLE
New Audit: Discourage early SW registration

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/lighthouse#9551]
#### Provide a basic description of the audit

This would detect scenarios in which a web app calls `navigator.serviceWorker.register()` "too early" in the page's lifecycle. (Where "too early" would be based on some criteria that is already known to Lighthouse, like whether or not the page's critical resources have finished loading.)

Registering a service worker too early can negatively impact a page's overall load time, since starting up the service worker process incurs some overhead, and running the service worker's `install` handler is likely to consume a decent amount of bandwidth if the service worker uses precaching. It's therefore better to wait until things have "settled" on the main page before registering a service worker.

#### How would the audit appear in the report? 

The test would pass if the call to `navigator.serviceWorker.register()` happens after the page has "settled". (I'm not sure what exactly this state is referred to in Lighthouse, but I'm pretty sure there's such a concept.)

The test would fail if the call to `navigator.serviceWorker.register()` happens too early in the page's loading lifecycle, and the call to action would be guidance along the lines of what's detailed in https://developers.google.com/web/fundamentals/primers/service-workers/registration

The test would not be applicable at all if there is no service worker registered.

#### How is this audit different from existing ones?

While other audits detect whether a service worker is registered at all, and detect whether it responds to navigations while offline, neither of those warn developers when a service worker's installation might delay the main page content from loading.

#### What % of developers/pages will this impact? 

Whatever the current percentage of Lighthouse pages register a service worker.

#### How is the new audit making a better web for end users?

The main benefit is that there is less likely to be bandwidth contention between the main page's subresource loading and a service worker's precaching.

#### What is the resourcing situation? 

Unclear! I'm happy to help review things, though.

#### Any other links or documentation that we should check out?

https://developers.google.com/web/fundamentals/primers/service-workers/registration

CC: @slightlyoff

**Comment by patrickhulce** [comment]
Thanks for filing @jeffposnick! :)

I can see this being a bit tricky to message because if they register *too* late our ability to detect that it's there also vanishes. 

My only question is around how big a problem this really is currently. Was there a particular discussion or pattern of behavior that triggered this issue about developers installing service workers too early and delaying page load? 

> What % of developers/pages will this impact?
Whatever the current percentage of Lighthouse pages register a service worker.

Seems to me the better estimate might be the current percentage of pages that are currently doing this "too early" since all developers currently doing it later than this would likely never find out this audit exists :)

**Comment by jeffposnick** [comment]
> I can see this being a bit tricky to message because if they register too late our ability to detect that it's there also vanishes.

The generic rule of thumb that we've [shared as a best practice](https://developers.google.com/web/fundamentals/primers/service-workers/registration) is to delay service worker registration until after the [`load` event](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event) fires for the current page. While not all web apps are doing this (if they were, we wouldn't need a Lighthouse audit!), my gut is that enough of them *are* that if it led to false-negatives in service worker detection, we'd have heard about it already. E.g. https://so-pwa.firebaseapp.com/ is a sample PWA that registers its service worker following the `load` event, and Lighthouse detects its service worker without issue.

Developers who know more about their web app's architecture and loading pipeline might opt to wait even longer—such as until after some framework-specific synthetic event has fired. I'm assuming that this would end being fired _after_ `load`, though. (If whatever they're listening for happens before `load`, then they should probably wait for `load` instead.)

> My only question is around how big a problem this really is currently. Was there a particular discussion or pattern of behavior that triggered this issue about developers installing service workers too early and delaying page load?

I'm going to admit to not having anything other than anecdotes here, but, you know, anecdotally it's a prevalent enough issue that we wrote up https://developers.google.com/web/fundamentals/primers/service-workers/registration to help steer developers in the right direction.

**Comment by patrickhulce** [comment]
> my gut is that enough of them are that if it led to false-negatives in service worker detection, we'd have heard about it already. 

I worry because *we have* gotten quite a few issues in the past (including directly from the angular team) complaining about service worker detection that turned out to be too late registration on the part of the page. 

**In Support of the Audit**

I'm aware of the load event guidance and would totally be on board if that's the extent of the audit. We could even go sofar as to convert the current service worker detection audit to fail with a specific message if it is registered too early. Our docs link to this specific advice already and Lighthouse always waits for the load event completion, so if they follow that advice it's guaranteed we should detect it.

------

**Explanation for Why I Wouldn't Want to Go Further Than That**

I think we will have to be careful about framing the advice so folks don't just push the registration out even further unnecessarily.

For example from the current best practices doc,

> Similarly, if your web app uses a framework that performs additional setup after the page has loaded, look for a framework-specific event that signals when that work is done.

Following this advice is what led to many angular apps by default not being detected and requiring a custom config (only available with lighthouse as CLI) to work as expected, https://github.com/GoogleChrome/lighthouse/issues/5527#issuecomment-483710849. Now like the situation in the doc there are plenty of scenarios where delaying past load is the right thing to do for the user, but without compelling data that it's the right thing to do *across the board* I'd be hesitant to give blanket advice that would make the PWA section unusable. If it tends to be an anecdotal case-by-case sort of situation, then leaving it to the docs like we do right now actually feels about right.

**Comment by Malvoz** [comment]
Related: https://github.com/GoogleChrome/lighthouse/issues/2924.

**Comment by primozs** [comment]
I am registering SW on page load event and would prefer to wait even longer. LH does not detect SW registration tho everything works as expected.

**Comment by patrickhulce** [comment]
@primozs a separate issue with repro steps and an example URL would be much appreciated :)

**Comment by patrickhulce** [comment]
We discussed and decided to flag service workers that are registered before LCP or before `load` event but not tell them to delay it later than that.

**Comment by adrianaixba** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse will be deprecating the PWA category in the next upcoming release. For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/). Marking this as closed!
