### ISSUE TITLE
Audit viewport is not correct 

### ISSUE THREAD

**Issue by thanhtungka91** [GoogleChrome/lighthouse#9597]
We have adde <viewport> meta tag but was not passed lighthouse audit 
![Screen Shot 2019-08-23 at 13 40 41](https://user-images.githubusercontent.com/3795067/63567250-a338d100-c5ab-11e9-926e-757ca328484b.png)

**Comment by exterkamp** [comment]
This is because the site is responding with this page:
![image](https://user-images.githubusercontent.com/6392995/63571299-ac3a8b80-c534-11e9-9158-6652b36fb292.png)

When the UA is set to Lighthouse 5.1's UA of `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36`

And _that_ page doesn't contain a `<meta name=viewport...` tag. (Look at what page is loaded when running Lighthouse, it isn't the same one as the one in your screenshot.)

On 5.2+ this seems to work with the new UA. So use Chrome Canary, or the cli.

**Comment by thanhtungka91** [comment]
@exterkamp thank you for the update, pwa it should be tested for mobile could you please reload the page with mobile agent?
![Screen Shot 2019-08-23 at 17 53 14](https://user-images.githubusercontent.com/3795067/63580071-f2dcc400-c5ce-11e9-8c53-70d870cc9e1d.png)

**Comment by patrickhulce** [comment]
@thanhtungka91, @exterkamp was telling you that the UA that Lighthouse uses when loading the report (which is a real mobile user agent of an older version of Android) gets served a different page by that server. If your server responds with a different page when requested by Lighthouse, then you can expect the results to be different. 

We'd advise expanding the UA-sniffing logic of the server to be more encompassing of other mobile UA strings like the one Lighthouse uses.

**Comment by thanhtungka91** [comment]
thank you, I was testing on chrome canary and it is fine.
