### ISSUE TITLE
Erroneous: "List items (<li>) are not contained within <ul> or <ol> parent elements."

### ISSUE THREAD

**Issue by elijah-schow** [GoogleChrome/lighthouse#9643]
#### Provide the steps to reproduce
1. Run an accessibility audit on https://app.nxtboard.com/meetings/nxtboard-sqa/
  

#### What is the current behavior?

Error:

> List items (`<li>`) are not contained within `<ul>` or `<ol>` parent elements.

<img width="817" alt="Screen Shot 2019-09-06 at 1 11 14 PM" src="https://user-images.githubusercontent.com/17830432/64451165-3d6b3f80-d0a9-11e9-889b-1a847fa22eb1.png">

#### What is the expected behavior?

This error does not appear. The `<li>`s in question are definitely contained inside a `<ul>` element.

<img width="646" alt="Screen Shot 2019-09-06 at 1 21 14 PM" src="https://user-images.githubusercontent.com/17830432/64451432-d437fc00-d0a9-11e9-883f-105567feef59.png">

#### Environment Information
* Affected Channels:  DevTools
* Lighthouse version: I don't know. Chrome version is 76.0.3809.132 (Official Build) (64-bit).
* Node.js version: n/a
* Operating System: macOS 10.14.6

**Comment by patrickhulce** [comment]
Thanks very much for filing @elijah-schow! Did you get a chance to try out the bug report instructions regarding accessibility issues?

> Before creating an Accessibility issue please test that it is reproducible upstream with axe (https://www.deque.com/axe/) first and file the issue there if necessary. 

My guess is that this audit is flagging it because the `ul` now has the role `tablist` and the `li` now need some other corresponding `role` but the axe folks would know better.

**Comment by elijah-schow** [comment]
@patrickhulce It looks like Axe reports the same issue. I think your hypothesis might be right. Replacing the `<ul>` and `<li>` elements with `<div>`s fixes the issue:

```
<div role="tablist" class="nav nav-tabs card-header-tabs">
    <div class="nav-item">
        <a href="#"  class="nav-link active" role="tab">Upcoming</a>
    </div>
    <div class="nav-item">
        <a href="#" class="nav-link" role="tab">Previous</a>
    </div>
</div>
```

This doesn't match [Bootstrap 4's suggested markup](https://getbootstrap.com/docs/4.0/components/navs/#javascript-behavior), but maybe their guide is wrong?

**Comment by patrickhulce** [comment]
> maybe their guide is wrong?

It does appear their guide is incorrect according to axe. If the `role="tab"` were on the `li` elements instead of the `a` elements it would pass.

> Is there is disadvantage to using divs instead of list items?

The primary disadvantage of `div`s is that there is no semantic meaning attached to them by default. By manually annotating `role=X` we are providing that semantic meaning for screen readers, so there should not be a disadvantage compared to `ul`/`li` AFAIK. (and in fact this is the problem here. That example has rewritten the "meaning" of `ul` to be a tablist not a regular unordered list, so the `li` elements no longer have a semantic `ul` parent) 

cc @robdodson who is more knowledgeable here.

**Comment by robdodson** [comment]
> It does appear their guide is incorrect according to axe. If the role="tab" were on the li elements instead of the a elements it would pass.

What happens if you put `role=presentation` on the `li` element? That should essentially remove it from the accessibility tree.

> By manually annotating role=X we are providing that semantic meaning for screen readers, so there should not be a disadvantage compared to ul/li AFAIK.

Yep, that's correct. It's also worth noting that, in Safari at least, if you change the display of a list then they throw out its semantics anyway (see the last comment in [this ticket](https://bugs.webkit.org/show_bug.cgi?id=170179#c1)).

I think over the years it became a common practice to put navigation into ul/li elements, but that practice probably predates ARIA and has just stuck around. Since you're redefining the semantics with ARIA it doesn't matter much what the underlying HTML element is in this case.

**Comment by patrickhulce** [comment]
Thanks @robdodson! Marking this one as closed then but feel free to re-open if you come across something that isn't reflecting axe's rules.

**Comment by hrvojegolcic** [comment]
The main problem is that `<ul>` have `role="tablist"` attribute which prevents it from being announced as an actual list by assistive technologies.

That's why Bootstrap recommends the following:

> Do not add the role to the `<ul>` itself, as this would prevent it from being announced as an actual list by assistive technologies.

From: https://getbootstrap.com/docs/4.3/components/navs/

**Comment by vijay-wappnet** [comment]
> > It does appear their guide is incorrect according to axe. If the role="tab" were on the li elements instead of the a elements it would pass.
> 
> What happens if you put `role=presentation` on the `li` element? That should essentially remove it from the accessibility tree.
> 
> > By manually annotating role=X we are providing that semantic meaning for screen readers, so there should not be a disadvantage compared to ul/li AFAIK.
> 
> Yep, that's correct. It's also worth noting that, in Safari at least, if you change the display of a list then they throw out its semantics anyway (see the last comment in [this ticket](https://bugs.webkit.org/show_bug.cgi?id=170179#c1)).
> 
> I think over the years it became a common practice to put navigation into ul/li elements, but that practice probably predates ARIA and has just stuck around. Since you're redefining the semantics with ARIA it doesn't matter much what the underlying HTML element is in this case.

**>> Yes working fine for me** 
Thanks @robdodson
