### ISSUE TITLE
Performance Avoid an excessive DOM size error

### ISSUE THREAD

**Issue by gulatigautam** [GoogleChrome/lighthouse#9725]
#### Provide the steps to reproduce
1. Run LH on https://www.americanexpress.com
  

#### What is the current behavior?
Seeing this in Diagnostics:

Avoid an excessive DOM size 1,436 elements

Total DOM Elements  1436
Maximum DOM Depth 21
Maximum Child Elements 43

#### What is the expected behavior?
Since all these three values are less than the maximum(1500, 32 and 60 respectively), we should not be seeing this error. Are we missing something here?

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @gulatigautam! The score is computed based on observed DOM size of pages from HTTPArchive rather than the theoretical suggested maximums. Agreed it's confusing and either the documentation or the scoring should change.

My preference would be to remove those stated maximums from the description entirely since they originated from a [single question response from a blink engineer](https://github.com/GoogleChrome/lighthouse/issues/1096#issuecomment-264347889) three years ago with no accompanying documentation or assurances that they're still valid.

**Comment by gulatigautam** [comment]
Thanks @patrickhulce. Will keep an eye on this thread to track the progress!
