### ISSUE TITLE
Defer offscreen images providing Errors.

### ISSUE THREAD

**Issue by crisgaret** [GoogleChrome/lighthouse#9767]
I am trying to figure out what is wrong with the lazy loading on my wordpress site. I have tried several lazy loading plugins, and they all yield a similar 'Error!' result in both PageSpeed Insights and the lighthouse Chrome audit. I don't know how to track down and fix this Error. Any help would be great. Thanks.

I also am not sure what all I should submit for this Issue. The test site is: http://gd.weareredhaus.com/ and attached are 2 screenshots of both the PageSpeed Insights results and the Chrome audit.

![Screen Shot 2019-10-01 at 10 09 28 PM](https://user-images.githubusercontent.com/2897089/66017519-690afb00-e498-11e9-80c3-cbfac9ad1816.png)
![Screen Shot 2019-10-01 at 10 09 12 PM](https://user-images.githubusercontent.com/2897089/66017521-690afb00-e498-11e9-9063-2ee2135b43b2.png)

**Comment by connorjclark** [comment]
Cool site. I dig it.

You see `Error!` here because sometimes, your site takes so long to load that Lighthouse gives up waiting for a "meaningful paint" (that's what NO_FMP means - no "first meaningful paint"). After a quick perusal of your site, I suggest lazy loading your images and encoding them better (as the report suggests).

You can lazy load your images with some super powers that the web got recently. See here for more: https://web.dev/native-lazy-loading#image-loading

To be honest, I don't know if `<img loading="lazy"` will entirely fix your situation. `lazy` [means](https://www.chromestatus.com/feature/5645767347798016) `defer the load until the image or iframe reaches a distance threshold from the viewport.` Just looking at your first carousel, all the images are in the initial HTML response, and I think are technically in the viewport, so they are gonna be loaded even with `loading="lazy". I think I verified this locally using Chrome DevTools [local overrides](https://developers.google.com/web/updates/2018/01/devtools#overrides), but let me know what you find out :) So I think you'll need to dynamically add those images so the browser doesn't load them way too early.

**Comment by crisgaret** [comment]
Thanks for the web.dev link @connorjclark, I'll give that a try. I am using a WP plugin to lazy load the images, and you are right, it doesn't lazy load the first carousel. I will look into also dynamically loading those images separately. The lazy load plugin (and the 4 others I tried) is what gives me the error in lighthouse. Without the lazy load plugin I don't get errors, just a notification to defer offscreen images and a corresponding bad score.

Thanks again for getting back to me.

**Comment by paulirish** [comment]
I've noticed running LH on https://web.dev/blog/ that it reports images that have `loading=lazy` on them.  (also it seemed one was in-viewport, which is odd, but secondary IMO)

If someone is using loading=lazy on an image we definitely shouldn't flag that in offscreen-images.

**Comment by paulirish** [comment]
Going to close. we'll use #10053 for tracking `loading=lazy` support.
