### ISSUE TITLE
Allow `--plugins` flag in build commands

### ISSUE THREAD

**Issue by jburger424** [GoogleChrome/lighthouse#9806]
Allow plugins to be included when generating bundles. This would include audits and i18n if applicable.

**Comment by connorjclark** [comment]
Is this for core plugins? I thought we would always include them.

**Comment by jburger424** [comment]
My thought was that not all plugins will necessarily exist in every plugin. For our lr-bundle, I don't envision that we'll include other plugins. I imagine there will probably be other cases where not all plugins are needed.

**Comment by connorjclark** [comment]
So `--plugins` would be a list of plugins to include in the build?

I think I'd prefer somehow exposing `bundle` in `build-bundle.js browserifyFile`, so downstream projects could tack on whatever they want (in your case, `bundle.ignore(some glob here that captures all plugins you dont want)`.

**Comment by brendankenny** [comment]
Agreed that supporting a generalized `--plugins` isn't worth it just for the nice interface on the bundler, since as far as I know the use case (bundle for lr with a specific plugin) is so specialized that we'll probably only have one user :) 

> EDIT: Has anyone given thought to how we will bundle syndicated plugins? That will probably be important in this discussion :)

Yes :) and I think this is exactly right that the solution will fall out pretty naturally from the implementation. We'll definitely address it, though, @jburger424.

**Comment by jburger424** [comment]
> the use case (bundle for lr with a specific plugin) is so specialized that we'll probably only have one user :)

Valid point :), I'll go ahead and close this and will follow future discussions about plugin bundling.
