### ISSUE TITLE
Paint performance audit

### ISSUE THREAD

**Issue by fchristant** [GoogleChrome/lighthouse#9864]
**Feature request summary**
Include paint performance audits in Lighthouse.

**What is the motivation or use case for changing this?**
Besides optimizing for the network and CPU, optimizing for render performance is a valid area of performance tunning. It is also one of the hardest categories to measure and analyze, and therefore awareness is low. 

I'm just raising it as a general question as to whether this category will be considered. If yes, some early ideas for a possible implementation:

- Express paint performance score (not sure what metric can do that)
- Reporting unusual paint metrics (for example excessive repaints)
- Check against known anti-practises 
- Advise on more performant approaches 

**How is this beneficial to Lighthouse?**
Make the very difficult category of render performance visible and accessible to developers. I am aware that paint performance can be checked in devtools yet I still find it quite hard to understand.

**Comment by paulirish** [comment]
This is a tricky area, mostly as there aren't widely accepted metrics around paint/rendering perf that are representative of user perception. I know there's work around "frame throughput" that some Chromium folks have worked on. 

But most of the investigations I know in this area isn't specific to paint specifically, but rather some portion of the rendering pipeline that excludes JS. Even doing that is hard, since one of the biggest challenges is layout thrashing, which is entirely due to JS.

Overpainting is a thing, but typically not very actionable by the web developer, and more typically it's the browser's responsibility to avoid rendering costs for pixels that are occluded.

I've seen cases where rendering a complex SVG is quite expensive and it's possible to invalidate those paints regularly, thus making paint a heavy cost for the lifetime of page. Though I think these situations are fairly rare.


Right now we're going to focus on summarizing runtime costs effectively. the "Minimizes main-thread work" audit captures much of this. If there are cases where "Paint" is > 20% of costs, then it certainly requires a more in-depth look, but I suspect that's an edge case.

**Comment by fchristant** [comment]
Forgot I even filed it :) Understandable it's not very actionable as an audit right now, thanks.
