### ISSUE TITLE
Make settings/context immutable

### ISSUE THREAD

**Issue by khempenius** [GoogleChrome/lighthouse#9897]
Add a centralized mechanism (e.g deep Object.freeze or readonly type system checks or whatever) to ensure settings immutability.

This issue came up when discussing https://github.com/GoogleChrome/lighthouse/pull/9895.

**Comment by brendankenny** [comment]
Would love this!

For audits,

https://github.com/GoogleChrome/lighthouse/blob/7fab7e2b9a34bd69bb7fb78326ab3d6a77ed9f8c/types/audit.d.ts#L11-L23

- `LighthouseRunWarnings` can move off of the context and audits can just return warnings as part of the `LH.Audit.Product` (audits that throw won't be able to push warnings, but any audit that would *need* both is probably a smell anyways)
- `computedCache` should be untouchable by audits anyways (though computed artifacts called by audits will need to be able to write to it, obvs)
- the rest should be easy (making audit options readonly should be fine)

gatherers are harder:
https://github.com/GoogleChrome/lighthouse/blob/7fab7e2b9a34bd69bb7fb78326ab3d6a77ed9f8c/types/gatherer.d.ts#L14-L25

a lot of it could be switched to `readonly` pretty easily, but we might need to do some type trickery with `LighthouseRunWarnings` (a custom `WriteOnlyArray`), etc

**Comment by patrickhulce** [comment]
Serious question: what is this trying to protect us from? 

AFAIK this originally came up in the context of the budgets parsing where before review we had some code that used an array mutation to do a lookup on the array. Freezing the config after it's been parsed sounds like a reasonable step and concern to address but I'm aware of a situation when we've come close to being bitten elsewhere. The complexity of doing this elsewhere is also much higher :)

>  audits can just return warnings as part of the LH.Audit.Product

Are you referring to the creation of a new audit product property that would do this? not reusing per-audit warnings?

**Comment by brendankenny** [comment]
> Serious question: what is this trying to protect us from?

I may have gotten carried away with the gatherer `PassContext` speculation :)

The reason I've been (non-urgently) thinking about this for a while is mostly because the audit context is passed into plugins. If we move to `postMessage` for plugins, it'll be more or less read-only/pass-by-value anyways; if not, it would be nice to have an interface that was self-evidently read-only...and mayyyyybe enforce that in some way beyond types.

I would *not* like to see major refactoring work for this, though :) I think we're already well aligned, so it would hopefully be at most:
- move the explicitly-mutable `LH.Audit.Context.LighthouseRunWarnings` off the context and onto the returned `LH.Audit.Product`.
- sprinkle some typescript `readonly`s around `Audit.audit()` and the `LH.Audit.Context` type in ways that are demonstrably effective (unfortunately there are still some readonly `tsc` loopholes)
- fix any type errors that come up from doing the above (I think/hope there would be none and everything is already behaving this way)

At that point, I'd probably be happy. This is javascript and plugins can do far worse on accident or on purpose [whether or not one object is read-only](https://user-images.githubusercontent.com/316891/67825548-0c532e00-faa0-11e9-9b11-b0ec1e3e1c36.jpg), but we could consider freezing if it felt good.

> > audits can just return warnings as part of the LH.Audit.Product
> 
> Are you referring to the creation of a new audit product property that would do this? not reusing per-audit warnings?

I had forgotten about that distinction :)

I think I would want to keep them separate, though both of them are kind of vaguely defined. The per-audit warnings [don't even get a jsdoc comment](https://github.com/GoogleChrome/lighthouse/blob/3f74f33d89eae459ac0eac81b451e65ae24941c2/types/audit.d.ts#L78) and I think we still only use `LighthouseRunWarnings` in [a single audit](https://github.com/GoogleChrome/lighthouse/blob/3f74f33d89eae459ac0eac81b451e65ae24941c2/lighthouse-core/audits/bootup-time.js#L167), though we've discussed moving other per-audit warnings up to that top level.

We could alternatively make lighthouse-level warnings through a method on the context, but if we do move to a `postMessage`-able future, making it part of the return object seems like the simplest choice.
