### ISSUE TITLE
Invalid error "Does not provide a valid apple-touch-icon" when rel="apple-touch-icon icon"

### ISSUE THREAD

**Issue by laukstein** [GoogleChrome/lighthouse#9915]
Remember `<meta rel="shortcut icon" ...` where **icon** is a fallback when **shortcut** not supported.
I guess same can say for `<meta rel="apple-touch-icon icon" ...` and it should display this error:

![grabilla em9116](https://user-images.githubusercontent.com/183966/68158871-3ce00f80-ff59-11e9-9e0e-bc90ba263e31.png)

meaning for iOS would capture as **apple-touch-icon** and for other devices as **icon**.

I haven't tested it in iOS, but I think it should work so.

**Comment by patrickhulce** [comment]
I believe you mean `<link rel="shortcut icon">` ;) but yes, point taken!

> I haven't tested it in iOS, but I think it should work so.

We should verify this before changing anything. Anyone have an iOS device they can validate? :)


For those curious about

>  iOS would capture as apple-touch-icon and for other devices as icon.

specifying multiple `rel` values for a link [creates multiple links](https://html.spec.whatwg.org/multipage/semantics.html#the-link-element) 

> Each link created for a link element is handled separately [...] if a single link element has a rel attribute with the value `next stylesheet`, it creates both a hyperlink (for the next keyword) and an external resource link (for the stylesheet keyword), and they are affected by other attributes (such as media or title) differently

If a link has an unrecognized rel, it will effectively be a noop.

**Comment by paulirish** [comment]
We need to test this out. 

Does a `shortcut icon` act as fallback for `apple-touch-icon`?

**Comment by laukstein** [comment]
@paulirish @patrickhulce 
The issue actually was with `<meta rel="apple-touch-icon icon" ...`, not related to **shortcut**.
I separated question might be addressed if iOS supports now `<meta rel="icon" ...` so that could recommend to drop **apple-touch-icon**.

**Comment by adrianaixba** [comment]
Hey @laukstein, thank you for the follow up! Unfortunately, it looks like `apple-touch-icon` and `icon` only work separately. This is a [link to MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types) that covers the icon/apple-touch-icon LinkType differences well. But, I did go ahead and run an example web app to test on iOS to see it play out a little better. 

`<link rel=”apple-touch-icon”...>` doesn’t trigger the favicon (since the “icon” rel isn’t present). But, the iOS icon shows fine as expected.
![apple-touch-icon](https://user-images.githubusercontent.com/23006279/96654782-accdde00-1301-11eb-8771-edff35458170.png)

`<link rel=”apple-touch-icon icon” ….>` Here, it looks like the favicon works fine, but iOS doesn’t correctly take in the icon, since “icon” is in the rel. So, it opts for an image of the actual page.
![apple-touch-icon-icon](https://user-images.githubusercontent.com/23006279/96654850-d129ba80-1301-11eb-9a32-93c820adfebb.png)

So, unfortunately it looks like iOS would require its own <link rel=""...> declaration without `icon` in it. Your best bet would be to have both `<link rel="icon"...>` and `<link rel="apple-touch-icon"...>"` to ensure you cover all your PWA bases :)

**Comment by laukstein** [comment]
@adrianaixba do you know if Safari has any open bug task for it?

**Comment by adrianaixba** [comment]
@laukstein I'm actually not sure! Although, if you end up opening a bug with them (or if you find one), feel free to comment here with a link. Would be an interesting thing to follow 🙂
